import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Seed={slug:string;model:string;type:string;url:string;machines:string[];note:string};
const CATALOG='https://tym.world/en-us/products/attachments';
const items:Seed[]=[
 {slug:'tym-bl200',model:'BL200',type:'front-loader',url:'https://tym.world/en-us/products/attachments/front-end-loader/bl200',machines:['3620r','3620h','4820r','4820h','5520r','5520h'],note:'Current US catalog lists BL200 for base models 3620, 4820 and 5520; expanded to their separately published R/H configurations.'},
 {slug:'tym-bl200c',model:'BL200C',type:'front-loader',url:'https://tym.world/en-us/products/attachments/front-end-loader/bl200c',machines:['4820c','4820ch','5520c','5520ch'],note:'Current US catalog lists BL200C for 4820C and 5520C base cab groups; expanded to separately published C/CH transmission configurations.'},
 {slug:'tym-bl350',model:'BL350',type:'front-loader',url:'https://tym.world/en-us/products/attachments/front-end-loader/bl350',machines:['5835'],note:'Current US catalog explicitly lists BL350 for 5835.'},
 {slug:'tym-bh200',model:'BH200',type:'backhoe',url:'https://tym.world/en-us/products/attachments/backhoe/bh200',machines:['3620r','3620h','4820r','4820h','5520r','5520h','5520c','5520ch'],note:'Current US catalog lists BH200 for 3620, 4820, 5520 and 5520C. It does not list 4820C, so no 4820C/CH backhoe fitment is inferred.'},
 {slug:'tym-bh350',model:'BH350',type:'backhoe',url:'https://tym.world/en-us/products/attachments/backhoe/bh350',machines:['5835'],note:'Current US catalog explicitly lists BH350 for 5835.'},
 {slug:'tym-by85',model:'BY85',type:'backhoe',url:'https://tym.world/en-us/products/attachments/backhoe/by85',machines:['t454','t454c','t494','t494c','t574'],note:'Current US catalog explicitly lists BY85 for T454, T454C, T494, T494C and T574. T574C is not added because it is not present in the current US compatibility string.'},
 {slug:'tym-tx57',model:'TX57',type:'front-loader',url:'https://tym.world/en-us/products/attachments/front-end-loader/tx57',machines:['t494','t494c','t574','t574c'],note:'Current US catalog explicitly lists TX57 for T494, T494C, T574 and T574C.'},
 {slug:'tym-bh86',model:'BH86',type:'backhoe',url:'https://tym.world/en-us/products/attachments/backhoe/bh86',machines:['t4058p','t4058pc'],note:'Current US catalog explicitly lists BH86 for T4058P and T4058PC.'},
 {slug:'tym-l4058p',model:'L4058P',type:'front-loader',url:'https://tym.world/en-us/products/attachments/front-end-loader/l4058p',machines:['t4058p'],note:'Current US catalog explicitly lists L4058P for T4058P.'},
 {slug:'tym-l4058pc',model:'L4058PC',type:'front-loader',url:'https://tym.world/en-us/products/attachments/front-end-loader/l4058pc',machines:['t4058pc'],note:'Current US catalog explicitly lists L4058PC for T4058PC.'},
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('TYM Series 4 attachment dependency missing');return Number(r[0].id)}
async function source(c:Parameters<DbMigration['apply']>[0],sid:number,eid:string,url:string,title:string,raw:unknown){const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[eid]);if(r[0])return Number(r[0].id);const[i]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,url,eid,title,JSON.stringify(raw)]);return Number(i.insertId)}
export const tymSeries4AttachmentsMigration:DbMigration={id:'20260830_408_tym_series4_attachments',description:'Add conservative verified current US TYM Series 4 loader and backhoe fitment',async apply(c){const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='tym' LIMIT 1`),sid=await id(c,`SELECT id FROM sources WHERE name='TYM' AND domain='tym.world' LIMIT 1`);const catalogSr=await source(c,sid,'tym-series4-attachments-current-us-2026-08',CATALOG,'TYM USA current Series 4 attachment fitment catalog',{market:'United States',captured:'2026-08-30',fitment:items.map(x=>({attachment:x.model,machines:x.machines})),policy:'Fitment only is added where the current US central attachment catalog explicitly identifies the model/base-model. Performance fields are deliberately not inferred from generic horsepower tables when a clean current product-detail record is unavailable.',omissions:['No current US attachment fitment is inferred for T554/T554C because the central catalog does not explicitly list them in the relevant attachment compatibility strings.','T574C is not extended to BY85 because current US BY85 compatibility lists T574 but not T574C.']});for(const a of items){const sr=await source(c,sid,`tym-series4-${a.model.toLowerCase()}-fitment-current-us-2026-08`,a.url,`TYM ${a.model} current US attachment fitment`,{market:'United States',captured:'2026-08-30',attachment:a.model,type:a.type,machineSlugs:a.machines,note:a.note,catalog:CATALOG});await c.query(`INSERT INTO attachments(manufacturer_id,attachment_type,model_name,slug,lift_capacity_text,lift_height_text,configuration_text,data_status) VALUES(?,?,?,?,NULL,NULL,?,'verified') ON DUPLICATE KEY UPDATE model_name=VALUES(model_name),attachment_type=VALUES(attachment_type),configuration_text=VALUES(configuration_text),data_status='verified'`,[mf,a.type,a.model,a.slug,a.note]);const aid=await id(c,`SELECT id FROM attachments WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,a.slug]);for(const ms of a.machines){const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,ms]);await c.query(`INSERT INTO machine_attachments(machine_id,attachment_id,compatibility_note,source_record_id,confidence) VALUES(?,?,?,?, 'official') ON DUPLICATE KEY UPDATE compatibility_note=VALUES(compatibility_note),source_record_id=VALUES(source_record_id),confidence='official'`,[mid,aid,a.note,sr||catalogSr])}}}}
