import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow = RowDataPacket & { id: number };
const LOADER_URL = 'https://www.claas.com/en-us/agricultural-machinery/tractors/front-loaders';
const LIFT_ARMS_URL = 'https://www.claas.com/en-us/agricultural-machinery/tractors/front-loader-lift-arms';
const ARION_BROCHURE = 'https://www.claas.com/caas/claas/media/188734/data/1d1bd5b74c99489339722998decb286a';
const machines = ['arion-630-cmatic','arion-650-cmatic','arion-660-cmatic'];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('CLAAS FL150 migration dependency missing');return Number(r[0].id)}
async function source(c:Parameters<DbMigration['apply']>[0],sid:number,eid:string,url:string,title:string,raw:unknown){const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[eid]);if(r[0])return Number(r[0].id);const[i]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,url,eid,title,JSON.stringify(raw)]);return Number(i.insertId)}
export const claasArion600Fl150LoaderMigration:DbMigration={
 id:'20260830_431_claas_arion_600_fl150_loader',description:'Add current CLAAS FL 150 EVO front-loader fitment for the US ARION 600 lineup',
 async apply(c){const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='claas' LIMIT 1`),sid=await id(c,`SELECT id FROM sources WHERE name='CLAAS North America' AND domain='claas.com' LIMIT 1`);const sr=await source(c,sid,'claas-fl150-evo-arion600-current-us-2026-08',LOADER_URL,'CLAAS FL 150 EVO current US loader specifications and ARION 600 fitment',{market:'United States',captured:'2026-08-30',currentFrontLoaderPage:LOADER_URL,currentLiftArmsPage:LIFT_ARMS_URL,arionBrochure:ARION_BROCHURE,currentUsLoader:{name:'FL 150 EVO',tractorPowerRangeHp:'165-205',liftCapacityOverEntireHeightLb:6724,maxAttachmentPivotHeightIn:181},arionBrochureLoader:{name:'FL 150',description:'hydraulic self-leveling',publishedLiftCapacityLb:7500,publishedReach:'up to 15 ft'},measurementPolicy:'Current US front-loader specification labels 6,724 lb as lift capacity over the entire lifting height and 181 in as max attachment-pivot height. The current ARION 600 North America brochure separately markets 7,500 lb lift capacity and up to 15 ft reach. Both official descriptions are preserved rather than conflated into one measurement.'});await c.query(`INSERT INTO attachments(manufacturer_id,attachment_type,model_name,slug,lift_capacity_text,lift_height_text,configuration_text,data_status) VALUES(?,'front-loader','FL 150 EVO','fl-150-evo',?,?,?,'verified') ON DUPLICATE KEY UPDATE model_name=VALUES(model_name),lift_capacity_text=VALUES(lift_capacity_text),lift_height_text=VALUES(lift_height_text),configuration_text=VALUES(configuration_text),data_status='verified'`,[mf,'6,724 lb over entire lifting height (current US FL 150 EVO specification); ARION 600 brochure separately publishes 7,500 lb hydraulic self-leveling lift capacity','181 in max attachment-pivot height (current US specification); ARION 600 brochure describes reach as up to 15 ft','Current CLAAS North America FL 150 EVO / FL 150 front-loader platform for 165-205 hp tractors. FITLOCK and MACH coupling systems; ARION 600 factory ELECTROPILOT control. Official US sources use two differently worded capacity descriptions, both retained explicitly.']);const aid=await id(c,`SELECT id FROM attachments WHERE manufacturer_id=? AND slug='fl-150-evo' LIMIT 1`,[mf]);for(const slug of machines){const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,slug]);await c.query(`INSERT INTO machine_attachments(machine_id,attachment_id,compatibility_note,source_record_id,confidence) VALUES(?,?,?,?, 'official') ON DUPLICATE KEY UPDATE compatibility_note=VALUES(compatibility_note),source_record_id=VALUES(source_record_id),confidence='official'`,[mid,aid,'CLAAS North America identifies FL 150 EVO for the 165-205 hp tractor range and the current ARION 600 brochure specifically describes the FL 150 loader for ARION 630/650/660.',sr])}}
};
