import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Seed={slug:string;name:string;rated:number;max:number;dp:number};
const VERSION='united-states-current-2026-08';
const TECH_URL='https://api.fendt.com/techdata/US/en/1519888';
const LINEUP_URL='https://www.fendt.com/us/products/tractors';
const models:Seed[]=[
{slug:'826-vario-gen5',name:'826 Vario Gen5',rated:260,max:260,dp:283},
{slug:'829-vario-gen5',name:'829 Vario Gen5',rated:290,max:290,dp:313},
{slug:'832-vario-gen5',name:'832 Vario Gen5',rated:320,max:320,dp:343},
];
async function id(c:Parameters<DbMigration['apply']>[0],q:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(q,p);if(!r[0])throw Error('Fendt 800 Gen5 dependency missing');return Number(r[0].id)}
async function source(c:Parameters<DbMigration['apply']>[0],sid:number,ext:string,url:string,title:string,raw:unknown){const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[ext]);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,url,ext,title,JSON.stringify(raw)]);return Number(x.insertId)}
async function put(c:Parameters<DbMigration['apply']>[0],mi:number,vi:number,di:number,sr:number,v:string|number,u:string|null){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mi,vi,di,typeof v==='string'?v:null,typeof v==='number'?v:null,u,sr])}
export const fendt800VarioGen5CurrentUsMigration:DbMigration={id:'20260829_314_fendt_800_vario_gen5_current_us',description:'Add three current US Fendt 800 Vario Gen5 models from official Fendt US sources',async apply(c){
const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='fendt' LIMIT 1`);const et=await id(c,`SELECT id FROM equipment_types WHERE slug='tractor' LIMIT 1`);const sid=await id(c,`SELECT id FROM sources WHERE name='Fendt' AND domain='fendt.com' LIMIT 1`);await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'Fendt 800 Vario Gen5','fendt-800-vario-gen5') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const si=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND slug='fendt-800-vario-gen5' LIMIT 1`,[mf]);const lineup=await source(c,sid,'fendt-800-vario-gen5-current-us-lineup-2026-08',LINEUP_URL,'Fendt US current tractor lineup',{market:'United States',captured:'2026-08-29',series:'Fendt 800 Vario Gen5',models:models.map(m=>m.name)});const tech=await source(c,sid,'fendt-800-vario-gen5-tech-current-us-2026-08',TECH_URL,'Fendt US 800 Vario Gen5 official technical data',{market:'United States',captured:'2026-08-29',models,displacementL:7.926,transmission:'TA250',pto:'540/540E/1000/1000E',hydraulicPumpLMin:[165,220,385],rearLiftKg:11600});
const defs=[['Engine','engine.displacement','Engine displacement','decimal','L',2],['Engine','engine.rated_power','Rated engine power','decimal','hp',4],['Engine','engine.maximum_power','Maximum engine power','decimal','hp',5],['Engine','engine.dynamic_performance_power','Maximum power with DynamicPerformance','decimal','hp',6],['Transmission','transmission.options','Transmission / drivetrain','text',null,10],['PTO','pto.speeds','PTO speeds','text',null,10],['Hydraulics','hydraulics.main_pump_max_flow','Maximum hydraulic flow','decimal','US gal/min',10],['Hydraulics','hitch.rear_max_lift_capacity','Maximum rear hitch lift capacity','decimal','lb',20]] as const;const d=new Map<string,number>();for(const x of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,[...x]);d.set(x[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[x[1]]))}
for(const m of models){await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current US Fendt 800 Vario Gen5 tractor','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[mf,et,si,m.name,m.slug]);const mi=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mi,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States','Current Fendt 800 Vario Gen5',TRUE,?,'Current US Fendt 800 Vario Gen5 record. Series availability is confirmed by the current US lineup and technical values come from the official US technical-data endpoint.') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mi,VERSION,lineup]);const vi=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mi,VERSION]);const vals:Array<[string,string|number,string|null]>=[['engine.displacement',7.926,'L'],['engine.rated_power',m.rated,'hp'],['engine.maximum_power',m.max,'hp'],['engine.dynamic_performance_power',m.dp,'hp'],['transmission.options','TA250',null],['pto.speeds','540 / 540E / 1000 / 1000E rpm',null],['hydraulics.main_pump_max_flow',101.7,'US gal/min'],['hitch.rear_max_lift_capacity',25574,'lb']];for(const[k,v,u]of vals)await put(c,mi,vi,d.get(k)!,tech,v,u)}
}};
