import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Seed={slug:string;model:string;url:string;hp:number;rocLb:number;weightLb:number;forwardMph:number;reverseMph:number;auxGpm:number;fuelGal:number;widthIn:number;hingeIn:number;reachIn:number;lengthIn:number;groundStdPsi:number;groundWidePsi:number};
const VERSION='united-states-current-2026-08';
const FAMILY_URL='https://www.bobcat.com/na/en/equipment/loaders/mini-track-loaders';
const models:Seed[]=[
 {slug:'mt100',model:'MT100',url:`${FAMILY_URL}/mt100`,hp:24.8,rocLb:1000,weightLb:3390,forwardMph:4.1,reverseMph:2.9,auxGpm:11,fuelGal:7,widthIn:35.6,hingeIn:80.9,reachIn:18.6,lengthIn:84.5,groundStdPsi:5.3,groundWidePsi:4},
 {slug:'mt120',model:'MT120',url:`${FAMILY_URL}/mt120`,hp:24.5,rocLb:1200,weightLb:3720,forwardMph:4.7,reverseMph:4.7,auxGpm:11.8,fuelGal:8.1,widthIn:35.6,hingeIn:88.2,reachIn:22.2,lengthIn:86.8,groundStdPsi:4.3,groundWidePsi:3.9},
];
const defs:Array<[string,string,string,string,string|null,number]>=[
 ['Machine Configuration','configuration.type','Machine configuration','text',null,1],['Machine Configuration','configuration.market_scope','Official market scope','text',null,2],
 ['Engine','mini_track_loader.engine_power','Published horsepower','decimal','hp',10],
 ['Loader Performance','mini_track_loader.rated_operating_capacity','Rated operating capacity','decimal','lb',10],['Loader Performance','mini_track_loader.ground_pressure_standard','Ground pressure, standard tracks','decimal','psi',20],['Loader Performance','mini_track_loader.ground_pressure_wide','Ground pressure, optional wide tracks','decimal','psi',30],
 ['Travel','mini_track_loader.forward_speed','Forward travel speed','decimal','mph',10],['Travel','mini_track_loader.reverse_speed','Reverse travel speed','decimal','mph',20],
 ['Hydraulics','mini_track_loader.auxiliary_flow','Auxiliary standard flow','decimal','gpm',10],
 ['Capacities','mini_track_loader.fuel_tank','Fuel tank','decimal','gal',10],
 ['Dimensions & Weight','mini_track_loader.operating_weight','Operating weight','decimal','lb',10],['Dimensions & Weight','mini_track_loader.width','Overall width','decimal','in',20],['Dimensions & Weight','mini_track_loader.hinge_pin_height','Height to bucket hinge pin','decimal','in',30],['Dimensions & Weight','mini_track_loader.reach_max_height','Reach at maximum height','decimal','in',40],['Dimensions & Weight','mini_track_loader.length_no_attachment','Length without attachment','decimal','in',50],
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('Bobcat mini track loader migration dependency missing');return Number(r[0].id);}
async function source(c:Parameters<DbMigration['apply']>[0]){const[r]=await c.query<IdRow[]>(`SELECT id FROM sources WHERE name='Bobcat' AND domain='bobcat.com' ORDER BY id LIMIT 1`);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO sources(name,domain,source_type,authority_level) VALUES('Bobcat','bobcat.com','manufacturer','official')`);return Number(x.insertId);}
async function record(c:Parameters<DbMigration['apply']>[0],sid:number,m:Seed){const externalId=`bobcat-${m.slug}-mini-track-loader-us-current-2026-08`;const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,m.url,externalId,`Bobcat ${m.model} current US mini track loader specifications`,JSON.stringify({captured:'2026-08-31',market:'United States / North America',equipmentType:'Mini Track Loader',model:m})]);return Number(x.insertId);}
async function put(c:Parameters<DbMigration['apply']>[0],mid:number,vid:number,did:number,rid:number,value:string|number,unit:string|null=null){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mid,vid,did,typeof value==='string'?value:null,typeof value==='number'?value:null,unit,rid]);}
export const bobcatMiniTrackLoadersCurrentMigration:DbMigration={id:'20260831_553_bobcat_mini_track_loaders_current',description:'Add current Bobcat United States MT100 and MT120 mini track loaders',async apply(c){
 await c.query(`INSERT INTO equipment_types(name,slug) VALUES('Mini Track Loader','mini-track-loader') ON DUPLICATE KEY UPDATE name=VALUES(name)`);await c.query(`INSERT INTO manufacturers(name,slug) VALUES('Bobcat','bobcat') ON DUPLICATE KEY UPDATE name=VALUES(name)`);const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='bobcat' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='mini-track-loader' LIMIT 1`),sid=await source(c);
 await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'Bobcat MT Mini Track Loaders','bobcat-mt-mini-track-loaders') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='bobcat-mt-mini-track-loaders' LIMIT 1`,[mf,et]);const ids=new Map<string,number>();for(const d of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,d);ids.set(d[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[d[1]]));}const def=(k:string)=>{const v=ids.get(k);if(!v)throw new Error(`Missing Bobcat mini track loader definition ${k}`);return v;};
 for(const m of models){const rid=await record(c,sid,m);await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current Bobcat North America mini track loader; MT85 is excluded because Bobcat lists it under non-current models','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[mf,et,series,m.model,m.slug]);const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND equipment_type_id=? AND slug=? LIMIT 1`,[mf,et,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mid,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States','Current Bobcat North America direct model-page specification',TRUE,?,'Current Bobcat direct product page captured 2026-08-31. All listed values remain model-specific; the old MT85 is not included because the official non-current catalog lists it as discontinued.') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mid,VERSION,rid]);const vid=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mid,VERSION]);await put(c,mid,vid,def('configuration.type'),rid,'Mini track loader');await put(c,mid,vid,def('configuration.market_scope'),rid,'United States / North America current catalog');await put(c,mid,vid,def('mini_track_loader.engine_power'),rid,m.hp,'hp');await put(c,mid,vid,def('mini_track_loader.rated_operating_capacity'),rid,m.rocLb,'lb');await put(c,mid,vid,def('mini_track_loader.ground_pressure_standard'),rid,m.groundStdPsi,'psi');await put(c,mid,vid,def('mini_track_loader.ground_pressure_wide'),rid,m.groundWidePsi,'psi');await put(c,mid,vid,def('mini_track_loader.forward_speed'),rid,m.forwardMph,'mph');await put(c,mid,vid,def('mini_track_loader.reverse_speed'),rid,m.reverseMph,'mph');await put(c,mid,vid,def('mini_track_loader.auxiliary_flow'),rid,m.auxGpm,'gpm');await put(c,mid,vid,def('mini_track_loader.fuel_tank'),rid,m.fuelGal,'gal');await put(c,mid,vid,def('mini_track_loader.operating_weight'),rid,m.weightLb,'lb');await put(c,mid,vid,def('mini_track_loader.width'),rid,m.widthIn,'in');await put(c,mid,vid,def('mini_track_loader.hinge_pin_height'),rid,m.hingeIn,'in');await put(c,mid,vid,def('mini_track_loader.reach_max_height'),rid,m.reachIn,'in');await put(c,mid,vid,def('mini_track_loader.length_no_attachment'),rid,m.lengthIn,'in');}
}};
