import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow = RowDataPacket & { id: number };
type Seed = { slug:string; name:string; grossHp:number; ptoHp:number; transmission:string; weightLb:number; url:string; note:string };

const VERSION='united-states-current-2026-08';
const CATALOG_URL='https://lstractorusa.com/class/compact/';
const BROCHURE_URL='https://lstractorusa.com/wp-content/uploads/2025/10/LS-Tractor-Brochure_MT3E_Update_v7.pdf';
const models:Seed[]=[
  {slug:'mt345e',name:'MT345E',grossHp:45,ptoHp:38.2,transmission:'Synchro Shuttle / Constant Mesh; F8 x R8',weightLb:3724,url:'https://lstractorusa.com/tractor/mt345e-he/',note:'Current grouped MT345E/HE web page plus current-linked MT3E brochure resolve the E variant as the gear configuration.'},
  {slug:'mt345he',name:'MT345HE',grossHp:45,ptoHp:36.0,transmission:'HST; 3 ranges',weightLb:3750,url:'https://lstractorusa.com/tractor/mt345e-he/',note:'Current grouped MT345E/HE web page plus current-linked MT3E brochure resolve the HE variant as HST.'},
  {slug:'mt355e',name:'MT355E',grossHp:55,ptoHp:46.7,transmission:'Synchro Shuttle / Constant Mesh; F8 x R8',weightLb:3750,url:'https://lstractorusa.com/tractor/mt355e-he/',note:'The current grouped MT355E/HE web technical table explicitly publishes Synchro Shuttle/Constant Mesh F8xR8. The current brochure has a compact transmission row that is internally difficult to map; the detailed current web table is used for MT355E transmission, while brochure model columns resolve PTO power.'},
  {slug:'mt355he',name:'MT355HE',grossHp:55,ptoHp:44.0,transmission:'HST; 3 ranges',weightLb:3750,url:'https://lstractorusa.com/tractor/mt355e-he/',note:'The grouped current web page publishes an E/HE PTO range; the current MT3E brochure supplies model-specific 44.0 PTO hp and HST for MT355HE.'},
];

const definitions:Array<[string,string,string,string,string|null,number]>=[
 ['Machine Configuration','configuration.station','Operator station','text',null,1],['Engine','engine.model','Engine model','text',null,2],['Engine','engine.type','Engine type','text',null,3],['Engine','engine.cylinders','Cylinders','integer',null,4],['Engine','engine.displacement','Engine displacement','decimal','L',6],['Engine','engine.gross_power','Gross engine power','decimal','hp',8],['Engine','engine.rated_speed','Rated engine speed','integer','rpm',9],['Transmission','transmission.standard','Transmission','text',null,10],['PTO','pto.rated_power','PTO power','decimal','hp',10],['PTO','pto.type','PTO type','text',null,15],['PTO','pto.rear_description','Rear PTO','text',null,20],['Hydraulics','hydraulics.main_pump_capacity','Implement hydraulic pump capacity','decimal','gpm',10],['Hydraulics','hydraulics.power_steering_pump_capacity','Power-steering pump capacity','decimal','gpm',20],['Hydraulics','hydraulics.total_flow','Total hydraulic flow','decimal','gpm',30],['Hydraulics','hitch.lift_capacity','3-point hitch lift capacity at hitch end','decimal','lb',50],['Capacities','capacities.fuel_tank','Fuel tank capacity','decimal','L',10],['Dimensions & Weight','dimensions.overall_length','Overall length','decimal','in',10],['Dimensions & Weight','dimensions.overall_width','Overall width','decimal','in',20],['Dimensions & Weight','dimensions.overall_height','Overall height','decimal','in',30],['Dimensions & Weight','dimensions.wheelbase','Wheelbase','decimal','in',40],['Dimensions & Weight','dimensions.unladen_weight','Tractor weight without ballast','decimal','lb',70],
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,params:unknown[]=[]){const [r]=await c.query<IdRow[]>(sql,params);if(!r[0])throw new Error('LS Tractor MT3E migration dependency missing');return Number(r[0].id);}
async function src(c:Parameters<DbMigration['apply']>[0],sourceId:number,externalId:string,url:string,title:string,raw:unknown){const [r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(r[0])return Number(r[0].id);const [x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sourceId,url,externalId,title,JSON.stringify(raw)]);return Number(x.insertId);}
async function put(c:Parameters<DbMigration['apply']>[0],mid:number,vid:number,did:number,srid:number,value:string|number,unit:string|null){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mid,vid,did,typeof value==='string'?value:null,typeof value==='number'?value:null,unit,srid]);}

export const lsTractorMt3eCurrentUsMigration:DbMigration={id:'20260830_376_ls_tractor_mt3e_current_us',description:'Add four current US LS Tractor MT3E configurations',async apply(c){
 const manufacturerId=await id(c,`SELECT id FROM manufacturers WHERE slug='ls-tractor' LIMIT 1`);const equipmentTypeId=await id(c,`SELECT id FROM equipment_types WHERE slug='tractor' LIMIT 1`);const sourceId=await id(c,`SELECT id FROM sources WHERE name='LS Tractor' AND domain='lstractorusa.com' LIMIT 1`);
 await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'LS MT3E Series','ls-mt3e-series') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[manufacturerId,equipmentTypeId]);const seriesId=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND slug='ls-mt3e-series' LIMIT 1`,[manufacturerId]);
 await src(c,sourceId,'ls-tractor-mt3e-current-us-lineup-2026-08',CATALOG_URL,'LS Tractor USA current compact lineup - MT3E',{market:'United States',captured:'2026-08-30',models:models.map(m=>m.name),brochure:BROCHURE_URL,sourcePolicy:'Current compact catalog and grouped MT3E model pages establish the active four-model lineup. Current-linked MT3E brochure is used only to resolve model-specific PTO/transmission/weight columns where the grouped web page publishes ranges. Hitch category is intentionally omitted because current first-party web and brochure sources conflict (CAT II vs CAT I); the agreed 2,910-lb hitch lift is retained.'});
 const defs=new Map<string,number>();for(const row of definitions){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,row);defs.set(row[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[row[1]]));}
 for(const m of models){const sr=await src(c,sourceId,`ls-tractor-${m.slug}-current-us-2026-08`,m.url,`LS Tractor ${m.name} current US specifications`,{market:'United States',captured:'2026-08-30',brochure:BROCHURE_URL,notes:m.note,hitchCategoryConflict:'Current web table says CAT 2 while current brochure says CAT I; category omitted.'});await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current US LS Tractor MT3E compact tractor','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[manufacturerId,equipmentTypeId,seriesId,m.name,m.slug]);const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=? LIMIT 1`,[manufacturerId,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mid,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States',?,TRUE,?,?) ON DUPLICATE KEY UPDATE configuration=VALUES(configuration),is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mid,VERSION,`ROPS; ${m.transmission}`,sr,m.note]);const vid=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mid,VERSION]);const values:Array<[string,string|number,string|null]>=[['configuration.station','ROPS',null],['engine.model','L3C19-T',null],['engine.type','Vertical water-cooled 4-cycle diesel',null],['engine.cylinders',3,null],['engine.displacement',1.88,'L'],['engine.gross_power',m.grossHp,'hp'],['engine.rated_speed',2600,'rpm'],['transmission.standard',m.transmission,null],['pto.rated_power',m.ptoHp,'hp'],['pto.type','Independent',null],['pto.rear_description','540 rpm',null],['hydraulics.main_pump_capacity',8.2,'gpm'],['hydraulics.power_steering_pump_capacity',4.8,'gpm'],['hydraulics.total_flow',13.0,'gpm'],['hitch.lift_capacity',2910,'lb'],['capacities.fuel_tank',51.9,'L'],['dimensions.overall_length',125,'in'],['dimensions.overall_width',68,'in'],['dimensions.overall_height',100,'in'],['dimensions.wheelbase',74.8,'in'],['dimensions.unladen_weight',m.weightLb,'lb']];for(const [key,v,u] of values){const did=defs.get(key);if(!did)throw new Error(`Missing LS Tractor MT3E spec definition ${key}`);await put(c,mid,vid,did,sr,v,u);}}
}};
