import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type ModelSeed={slug:string;model:string;ratedHp:number;maxHp:number;ptoHp:number;displacementL:number;url:string;externalId:string};
const FAMILY_URL='https://www.caseih.com/en-us/unitedstates/products/tractors/maxxum-series';
const FAMILY_EXTERNAL_ID='case-ih-maxxum-current-us-115-150-2026-08';
const VERSION_SLUG='united-states-current-2026-08';
const models:ModelSeed[]=[
  {slug:'maxxum-115',model:'Maxxum 115',ratedHp:116,maxHp:145,ptoHp:95,displacementL:4.5,url:'https://www.caseih.com/en-us/unitedstates/products/tractors/maxxum-series/maxxum-115',externalId:'case-ih-maxxum-115-current-us'},
  {slug:'maxxum-125',model:'Maxxum 125',ratedHp:125,maxHp:155,ptoHp:105,displacementL:4.5,url:'https://www.caseih.com/en-us/unitedstates/products/tractors/maxxum-series/maxxum-125',externalId:'case-ih-maxxum-125-current-us'},
  {slug:'maxxum-135',model:'Maxxum 135',ratedHp:135,maxHp:169,ptoHp:110,displacementL:4.5,url:'https://www.caseih.com/en-us/unitedstates/products/tractors/maxxum-series/maxxum-135',externalId:'case-ih-maxxum-135-current-us'},
  {slug:'maxxum-145',model:'Maxxum 145',ratedHp:145,maxHp:175,ptoHp:120,displacementL:4.5,url:'https://www.caseih.com/en-us/unitedstates/products/tractors/maxxum-series/maxxum-145',externalId:'case-ih-maxxum-145-current-us'},
  {slug:'maxxum-150',model:'Maxxum 150',ratedHp:150,maxHp:175,ptoHp:125,displacementL:6.7,url:'https://www.caseih.com/en-us/unitedstates/products/tractors/maxxum-series/maxxum-150',externalId:'case-ih-maxxum-150-current-us'},
];
const definitions=[
  ['Machine Configuration','configuration.station','Operator station','text',null,1],['Machine Configuration','configuration.drive','Drive configuration','text',null,2],
  ['Engine','engine.make','Engine manufacturer','text',null,1],['Engine','engine.displacement','Engine displacement','decimal','L',2],['Engine','engine.rated_power','Rated engine power','decimal','hp',3],['Engine','engine.maximum_power','Maximum engine power','decimal','hp',4],
  ['PTO','pto.rated_power','PTO power','decimal','hp',10],['Transmission','transmission.options','Transmission options','text',null,10],['Hydraulics','hydraulics.main_pump_max_flow','Maximum implement hydraulic flow','decimal','US gal/min',10],['Hydraulics','hitch.rear_max_lift_capacity','Maximum rear hitch lift capacity','decimal','lb',20],
] as const;
async function selectId(connection:Parameters<DbMigration['apply']>[0],sql:string,params:unknown[]=[]){const [rows]=await connection.query<IdRow[]>(sql,params);if(!rows[0])throw new Error('Missing Case IH Maxxum migration dependency.');return Number(rows[0].id);}
async function ensureSource(connection:Parameters<DbMigration['apply']>[0],sourceId:number,externalId:string,url:string,title:string){const [rows]=await connection.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(rows[0])return Number(rows[0].id);const [result]=await connection.query<ResultSetHeader>(`INSERT INTO source_records (source_id,url,external_id,title) VALUES (?,?,?,?)`,[sourceId,url,externalId,title]);return Number(result.insertId);}
async function upsertSpec(connection:Parameters<DbMigration['apply']>[0],machineId:number,versionId:number,definitionId:number,sourceRecordId:number,value:string|number,unit:string|null=null){await connection.query(`INSERT INTO machine_specs (machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES (?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[machineId,versionId,definitionId,typeof value==='string'?value:null,typeof value==='number'?value:null,unit,sourceRecordId]);}

export const caseIHMaxxumCurrentSpecsMigration:DbMigration={
  id:'20260828_233_case_ih_maxxum_current_specs',
  description:'Add current US Case IH Maxxum 115/125/135/145/150 official engine, PTO, transmission, hydraulic and hitch data',
  async apply(connection){
    await connection.query(`INSERT INTO equipment_types (name,slug) VALUES ('Tractor','tractor') ON DUPLICATE KEY UPDATE name=VALUES(name)`);
    await connection.query(`INSERT INTO manufacturers (name,slug) VALUES ('Case IH','case-ih') ON DUPLICATE KEY UPDATE name=VALUES(name)`);
    const manufacturerId=await selectId(connection,`SELECT id FROM manufacturers WHERE slug='case-ih' LIMIT 1`);const equipmentTypeId=await selectId(connection,`SELECT id FROM equipment_types WHERE slug='tractor' LIMIT 1`);
    await connection.query(`INSERT INTO machine_series (manufacturer_id,equipment_type_id,name,slug) VALUES (?,?,'Maxxum Series','maxxum-series') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[manufacturerId,equipmentTypeId]);const seriesId=await selectId(connection,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='maxxum-series' LIMIT 1`,[manufacturerId,equipmentTypeId]);
    let [sourceRows]=await connection.query<IdRow[]>(`SELECT id FROM sources WHERE name='Case IH' AND domain='caseih.com' ORDER BY id LIMIT 1`);let sourceId=sourceRows[0]?.id?Number(sourceRows[0].id):0;if(!sourceId){const [result]=await connection.query<ResultSetHeader>(`INSERT INTO sources (name,domain,source_type,authority_level) VALUES ('Case IH','caseih.com','manufacturer','official')`);sourceId=Number(result.insertId);}
    const familyId=await ensureSource(connection,sourceId,FAMILY_EXTERNAL_ID,FAMILY_URL,'Case IH US current Maxxum Series 115-150 lineup and family specifications');
    const definitionIds=new Map<string,number>();for(const [section,key,label,valueType,canonicalUnit,displayOrder] of definitions){await connection.query(`INSERT INTO spec_definitions (section,spec_key,label,value_type,canonical_unit,display_order) VALUES (?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,[section,key,label,valueType,canonicalUnit,displayOrder]);definitionIds.set(key,await selectId(connection,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[key]));}const def=(key:string)=>{const id=definitionIds.get(key);if(!id)throw new Error(`Missing Maxxum spec ${key}`);return id;};
    for(const model of models){const modelSourceId=await ensureSource(connection,sourceId,model.externalId,model.url,`Case IH US ${model.model} official current product specifications`);await connection.query(`INSERT INTO machines (manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES (?,?,?,?,?,'Current US Case IH Maxxum all-purpose tractor','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[manufacturerId,equipmentTypeId,seriesId,model.model,model.slug]);const machineId=await selectId(connection,`SELECT id FROM machines WHERE manufacturer_id=? AND equipment_type_id=? AND slug=? LIMIT 1`,[manufacturerId,equipmentTypeId,model.slug]);await connection.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[machineId,VERSION_SLUG]);await connection.query(`INSERT INTO machine_versions (machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES (?,?,'US','United States','Current Maxxum - wheeled tractor',TRUE,?,'Current Case IH US Maxxum lineup. Individual engine and PTO values come from the model page; family-level transmission, hydraulic and hitch values come from the Maxxum series page.') ON DUPLICATE KEY UPDATE market_code='US',market_name='United States',configuration=VALUES(configuration),is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[machineId,VERSION_SLUG,familyId]);const versionId=await selectId(connection,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[machineId,VERSION_SLUG]);const values:Array<[string,string|number,string|null,number]>=[['configuration.station','Cab',null,familyId],['configuration.drive','2WD or MFD depending on transmission/configuration',null,familyId],['engine.make','FPT / Case IH',null,familyId],['engine.displacement',model.displacementL,'L',modelSourceId],['engine.rated_power',model.ratedHp,'hp',modelSourceId],['engine.maximum_power',model.maxHp,'hp',modelSourceId],['pto.rated_power',model.ptoHp,'hp',modelSourceId],['transmission.options','ActiveDrive 4 semi-powershift, ActiveDrive 8 dual-clutch, or CVXDrive continuously variable transmission',null,familyId],['hydraulics.main_pump_max_flow',39.6,'US gal/min',familyId],['hitch.rear_max_lift_capacity',8945,'lb',familyId]];for(const [key,value,unit,recordId] of values)await upsertSpec(connection,machineId,versionId,def(key),recordId,value,unit);}
  }
};
