import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type PartSeed={number:string;name:string;category:string;url:string;externalId:string;note:string};
const VERSION_SLUG='united-states-current-2026-08';
const models=['9rt-490','9rt-540','9rt-590'] as const;
const parts:PartSeed[]=[
  {number:'TA17973',name:'Primary Air Filter Element',category:'air-filters',url:'https://shop.deere.com/ca/en/product/TA17973%3A-Primary-Air-Filter/p/TA17973',externalId:'john-deere-shop-ta17973-9rt-current-fitment',note:'John Deere primary engine air filter; Shop.Deere compatible-equipment list includes 9RT 490, 9RT 540 and 9RT 590.'},
  {number:'RE230985',name:'Secondary Air Filter Element',category:'air-filters',url:'https://shop.deere.com/us/product/RE230985%3A-Secondary-Air-Filter/p/RE230985',externalId:'john-deere-shop-re230985-9rt-current-fitment',note:'John Deere secondary engine air filter; Shop.Deere compatible-equipment list includes 9RT 490, 9RT 540 and 9RT 590.'},
  {number:'RE572785',name:'Engine Oil Filter',category:'engine-oil-filters',url:'https://shop.deere.com/us/product/RE572785%3A-Engine-Oil-Filter/p/RE572785',externalId:'john-deere-shop-re572785-9rt-current-fitment',note:'John Deere engine oil filter; Shop.Deere compatible-equipment data includes current 9RT 490/540/590 generation.'},
  {number:'DZ124761',name:'Primary Fuel Filter',category:'fuel-filters',url:'https://shop.deere.com/us/product/DZ124761%3A-Primary-Fuel-Filter/p/DZ124761',externalId:'john-deere-shop-dz124761-9rt-current-fitment',note:'John Deere primary fuel filter; Shop.Deere compatible-equipment list includes 9RT 490, 9RT 540 and 9RT 590.'},
  {number:'DZ124786',name:'Secondary Fuel Filter',category:'fuel-filters',url:'https://shop.deere.com/us/product/DZ124786%3A-Secondary-Fuel-Filter/p/DZ124786',externalId:'john-deere-shop-dz124786-9rt-current-fitment',note:'John Deere secondary fuel filter; Shop.Deere compatible-equipment list includes 9RT 490, 9RT 540 and 9RT 590.'},
  {number:'RE577612',name:'Hydraulic Oil Filter',category:'hydraulic-filters',url:'https://shop.deere.com/us/product/RE577612%3A-Hydraulic-Oil-Filter-Element/p/RE577612',externalId:'john-deere-shop-re577612-9rt-current-fitment',note:'John Deere hydraulic oil filter; Shop.Deere compatible-equipment list includes 9RT 490, 9RT 540 and 9RT 590.'},
  {number:'RE577250',name:'Steering Hydraulic Oil Filter',category:'hydraulic-filters',url:'https://shop.deere.com/us/us/product/RE577250%3A-Steering-Motor-Oil-Filter/p/RE577250',externalId:'john-deere-shop-re577250-9rt-current-fitment',note:'John Deere steering-system hydraulic oil filter; Shop.Deere compatible-equipment list includes 9RT 490, 9RT 540 and 9RT 590.'},
  {number:'RE593819',name:'Cab Recirculation Air Filter',category:'cabin-air-filters',url:'https://shop.deere.com/us/product/RE593819%3A-Tractor-Cab-Air-Filter/p/RE593819',externalId:'john-deere-shop-re593819-9rt-current-fitment',note:'John Deere Original cab recirculation-air filter; Shop.Deere compatible-equipment list includes 9RT 490, 9RT 540 and 9RT 590.'},
];
async function selectId(connection:Parameters<DbMigration['apply']>[0],sql:string,params:unknown[]=[]){const [rows]=await connection.query<IdRow[]>(sql,params);if(!rows[0])throw new Error('Missing John Deere 9RT service dependency.');return Number(rows[0].id);}
async function ensureCategory(connection:Parameters<DbMigration['apply']>[0],filtersId:number,name:string,slug:string){await connection.query(`INSERT INTO part_categories (parent_id,name,slug) VALUES (?,?,?) ON DUPLICATE KEY UPDATE parent_id=VALUES(parent_id),name=VALUES(name)`,[filtersId,name,slug]);return selectId(connection,`SELECT id FROM part_categories WHERE slug=? LIMIT 1`,[slug]);}
async function ensureSourceRecord(connection:Parameters<DbMigration['apply']>[0],sourceId:number,part:PartSeed){const [rows]=await connection.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[part.externalId]);if(rows[0])return Number(rows[0].id);const [result]=await connection.query<ResultSetHeader>(`INSERT INTO source_records (source_id,url,external_id,title) VALUES (?,?,?,?)`,[sourceId,part.url,part.externalId,`Shop.Deere ${part.number} - John Deere part fitment for current 9RT 490/540/590`]);return Number(result.insertId);}
async function upsertFitment(connection:Parameters<DbMigration['apply']>[0],machineId:number,versionId:number,partId:number,sourceRecordId:number,note:string){const [rows]=await connection.query<IdRow[]>(`SELECT id FROM machine_parts WHERE machine_id=? AND machine_version_id=? AND part_id=? AND serial_prefix IS NULL AND serial_from IS NULL AND serial_to IS NULL ORDER BY id DESC LIMIT 1`,[machineId,versionId,partId]);const configurationNote='Current 9RT 490/540/590 fitment confirmed by John Deere Shop.Deere compatible-equipment data; verify tractor serial/options before ordering.';if(rows[0])await connection.query(`UPDATE machine_parts SET fitment_note=?,configuration_note=?,source_record_id=?,fitment_confidence='official' WHERE id=?`,[note,configurationNote,sourceRecordId,Number(rows[0].id)]);else await connection.query(`INSERT INTO machine_parts (machine_id,machine_version_id,part_id,fitment_note,configuration_note,source_record_id,fitment_confidence) VALUES (?,?,?,?,?,?,'official')`,[machineId,versionId,partId,note,configurationNote,sourceRecordId]);}

export const johnDeere9RTServiceFiltersMigration:DbMigration={id:'20260828_222_john_deere_9rt_service_filters',description:'Add direct John Deere Shop.Deere service-filter fitments for current 9RT 490, 540 and 590 tractors',async apply(connection){
  const manufacturerId=await selectId(connection,`SELECT id FROM manufacturers WHERE slug='john-deere' LIMIT 1`);await connection.query(`INSERT INTO part_categories (name,slug) VALUES ('Filters','filters') ON DUPLICATE KEY UPDATE name=VALUES(name)`);const filtersId=await selectId(connection,`SELECT id FROM part_categories WHERE slug='filters' LIMIT 1`);const defs=[['Air Filters','air-filters'],['Engine Oil Filters','engine-oil-filters'],['Fuel Filters','fuel-filters'],['Hydraulic Filters','hydraulic-filters'],['Cabin Air Filters','cabin-air-filters']] as const;const categoryIds=new Map<string,number>();for(const [name,slug] of defs)categoryIds.set(slug,await ensureCategory(connection,filtersId,name,slug));
  let [sourceRows]=await connection.query<IdRow[]>(`SELECT id FROM sources WHERE name='John Deere Parts' AND domain='shop.deere.com' ORDER BY id LIMIT 1`);let sourceId=sourceRows[0]?.id?Number(sourceRows[0].id):0;if(!sourceId){const [result]=await connection.query<ResultSetHeader>(`INSERT INTO sources (name,domain,source_type,authority_level) VALUES ('John Deere Parts','shop.deere.com','manufacturer','official')`);sourceId=Number(result.insertId);}
  const partData=new Map<string,{partId:number;sourceRecordId:number;note:string}>();for(const part of parts){const categoryId=categoryIds.get(part.category);if(!categoryId)throw new Error(`Missing 9RT category ${part.category}`);const sourceRecordId=await ensureSourceRecord(connection,sourceId,part);await connection.query(`INSERT INTO parts (manufacturer_id,category_id,part_number,normalized_part_number,name,description,data_status) VALUES (?,?,?,?,?,?,'verified') ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),part_number=VALUES(part_number),name=VALUES(name),description=VALUES(description),data_status='verified'`,[manufacturerId,categoryId,part.number,part.number.toUpperCase(),part.name,part.note]);const partId=await selectId(connection,`SELECT id FROM parts WHERE manufacturer_id=? AND normalized_part_number=? LIMIT 1`,[manufacturerId,part.number.toUpperCase()]);partData.set(part.number,{partId,sourceRecordId,note:part.note});}
  for(const slug of models){const machineId=await selectId(connection,`SELECT m.id FROM machines m JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='john-deere' AND m.slug=? LIMIT 1`,[slug]);const versionId=await selectId(connection,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? AND is_current=1 LIMIT 1`,[machineId,VERSION_SLUG]);for(const part of parts){const data=partData.get(part.number);if(!data)throw new Error(`Missing 9RT part ${part.number}`);await upsertFitment(connection,machineId,versionId,data.partId,data.sourceRecordId,data.note);}}
}};