import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
const VERSION='united-states-current-2026-08';
const FAMILY_URL='https://www.deere.com/en/tillage/field-cultivators/';
const defs:Array<[string,string,string,string,string|null,number]>=[
 ['Machine Configuration','configuration.type','Machine configuration','text',null,1],['Machine Configuration','configuration.market_scope','Official market scope','text',null,2],
 ['Tillage System','combination_ripper.max_depth','Maximum working depth','text',null,10],['Tillage System','combination_ripper.working_speed','Working speed','text',null,20],['Tillage System','combination_ripper.residue_conditions','Residue conditions','text',null,30],['Tillage System','combination_ripper.depth_control','Depth control','text',null,40],['Tractor Requirements','combination_ripper.required_hp','Required horsepower','text',null,10],['Precision Technology','combination_ripper.autonomy_ready','Precision and autonomy preparation','text',null,10],
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('John Deere 2730 migration dependency missing');return Number(r[0].id);}
async function src(c:Parameters<DbMigration['apply']>[0]){const[r]=await c.query<IdRow[]>(`SELECT id FROM sources WHERE name='John Deere' AND domain='deere.com' ORDER BY id LIMIT 1`);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO sources(name,domain,source_type,authority_level) VALUES('John Deere','deere.com','manufacturer','official')`);return Number(x.insertId);}
async function rec(c:Parameters<DbMigration['apply']>[0],sid:number){const externalId='john-deere-2730-combination-ripper-us-current-2026-08';const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,FAMILY_URL,externalId,'John Deere 2730 current US combination ripper specifications',JSON.stringify({captured:'2026-08-31',market:'United States',equipmentType:'Combination Ripper',model:'2730 Combination Ripper',source:FAMILY_URL})]);return Number(x.insertId);}
async function put(c:Parameters<DbMigration['apply']>[0],mid:number,vid:number,did:number,rid:number,v:string){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,NULL,NULL,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=NULL,unit=NULL,source_record_id=VALUES(source_record_id),confidence='official'`,[mid,vid,did,v,rid]);}
export const johnDeere2730CombinationRipperCurrentMigration:DbMigration={id:'20260831_522_john_deere_2730_combination_ripper_current',description:'Add current John Deere US 2730 Combination Ripper',async apply(c){
 await c.query(`INSERT INTO equipment_types(name,slug) VALUES('Combination Ripper','combination-ripper') ON DUPLICATE KEY UPDATE name=VALUES(name)`);await c.query(`INSERT INTO manufacturers(name,slug) VALUES('John Deere','john-deere') ON DUPLICATE KEY UPDATE name=VALUES(name)`);const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='john-deere' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='combination-ripper' LIMIT 1`),sid=await src(c),rid=await rec(c,sid);await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'2730 Combination Ripper','2730-combination-ripper') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='2730-combination-ripper' LIMIT 1`,[mf,et]);const ids=new Map<string,number>();for(const d of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,d);ids.set(d[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[d[1]]));}const def=(k:string)=>{const v=ids.get(k);if(!v)throw new Error(`Missing 2730 definition ${k}`);return v;};
 await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current John Deere United States combination ripper lineup','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes)`,[mf,et,series,'2730 Combination Ripper','2730-combination-ripper']);const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND equipment_type_id=? AND slug='2730-combination-ripper' LIMIT 1`,[mf,et]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mid,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States','Current 2730 family specification',TRUE,?,'Current John Deere US tillage comparison data captured 2026-08-31; older price-book dimensions are intentionally not promoted into this current record.') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mid,VERSION,rid]);const vid=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mid,VERSION]);await put(c,mid,vid,def('configuration.type'),rid,'Combination ripper');await put(c,mid,vid,def('configuration.market_scope'),rid,'United States current catalog');await put(c,mid,vid,def('combination_ripper.max_depth'),rid,'Up to 16 in (40.6 cm)');await put(c,mid,vid,def('combination_ripper.working_speed'),rid,'5 mph (8 km/h)');await put(c,mid,vid,def('combination_ripper.residue_conditions'),rid,'Heavy');await put(c,mid,vid,def('combination_ripper.depth_control'),rid,'TruSet / Single-Point');await put(c,mid,vid,def('combination_ripper.required_hp'),rid,'335 - 620 hp (250 - 462.5 kW)');await put(c,mid,vid,def('combination_ripper.autonomy_ready'),rid,'2730 Combination Ripper is listed by John Deere among tillage tools that come Autonomy Ready');
 }};
