import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
const modelSlugs=['farmall-110a-pro','farmall-120a-pro','farmall-130a-pro','farmall-140a-pro'] as const;
const loaders=[
  {model:'L113',slug:'l113-farmall-100a-pro',url:'https://www.caseih.com/en-us/unitedstates/products/loaders-attachments/l11-series-loaders/l113-farmall-100a',externalId:'case-ih-farmall-100a-pro-l113-loader-current',lift:'2,094 lb max lift capacity',height:'133 in max height',breakout:'3,020 lb boom breakout force',raw:{maxLiftLb:2094,maxHeightIn:133,boomBreakoutLb:3020,sourceUnitNote:"The current L113 page renders the imperial boom-breakout unit as 'in.'; the metric 1,370 kg force equivalent and Case IH L11 family context support 3,020 lb as the force value."}},
  {model:'L114',slug:'l114-farmall-100a-pro',url:'https://www.caseih.com/en-us/unitedstates/products/loaders-attachments/l11-series-loaders/l114',externalId:'case-ih-farmall-100a-pro-l114-loader-current',lift:'3,814 lb max lift capacity',height:'139 in max height',breakout:'3,968 lb boom breakout force',raw:{maxLiftLb:3814,maxHeightIn:139,boomBreakoutLb:3968}},
] as const;
async function selectId(connection:Parameters<DbMigration['apply']>[0],sql:string,params:unknown[]=[]){const [rows]=await connection.query<IdRow[]>(sql,params);if(!rows[0])throw new Error('Missing Case IH Farmall 100A Pro loader migration dependency.');return Number(rows[0].id);}
async function ensureSource(connection:Parameters<DbMigration['apply']>[0],sourceId:number,loader:typeof loaders[number]){const [rows]=await connection.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[loader.externalId]);if(rows[0])return Number(rows[0].id);const [result]=await connection.query<ResultSetHeader>(`INSERT INTO source_records (source_id,url,external_id,title,raw_reference) VALUES (?,?,?,?,?)`,[sourceId,loader.url,loader.externalId,`Case IH US ${loader.model} for Farmall 100A Pro official loader specifications`,JSON.stringify({loader:loader.model,series:'Farmall Large Utility 100A Pro',...loader.raw})]);return Number(result.insertId);}

export const caseIHFarmall100AProLoadersMigration:DbMigration={
  id:'20260828_238_case_ih_farmall_100a_pro_loaders',
  description:'Add official Case IH L113 and L114 loader fitments for current Farmall Large Utility 100A Pro 110A/120A/130A/140A tractors',
  async apply(connection){
    const manufacturerId=await selectId(connection,`SELECT id FROM manufacturers WHERE slug='case-ih' LIMIT 1`);
    let [sourceRows]=await connection.query<IdRow[]>(`SELECT id FROM sources WHERE name='Case IH' AND domain='caseih.com' ORDER BY id LIMIT 1`);let sourceId=sourceRows[0]?.id?Number(sourceRows[0].id):0;if(!sourceId){const [result]=await connection.query<ResultSetHeader>(`INSERT INTO sources (name,domain,source_type,authority_level) VALUES ('Case IH','caseih.com','manufacturer','official')`);sourceId=Number(result.insertId);}
    for(const loader of loaders){const loaderSourceId=await ensureSource(connection,sourceId,loader);await connection.query(`INSERT INTO attachments (manufacturer_id,attachment_type,model_name,slug,lift_capacity_text,lift_height_text,configuration_text,data_status) VALUES (?,'front-loader',?,?,?,?,?,'verified') ON DUPLICATE KEY UPDATE model_name=VALUES(model_name),lift_capacity_text=VALUES(lift_capacity_text),lift_height_text=VALUES(lift_height_text),configuration_text=VALUES(configuration_text),data_status='verified'`,[manufacturerId,loader.model,loader.slug,loader.lift,loader.height,`Case IH ${loader.model} for Farmall Large Utility 100A Pro Series; ${loader.breakout}`]);const attachmentId=await selectId(connection,`SELECT id FROM attachments WHERE manufacturer_id=? AND attachment_type='front-loader' AND slug=? LIMIT 1`,[manufacturerId,loader.slug]);for(const modelSlug of modelSlugs){const machineId=await selectId(connection,`SELECT m.id FROM machines m JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='case-ih' AND m.slug=? LIMIT 1`,[modelSlug]);await connection.query(`INSERT INTO machine_attachments (machine_id,attachment_id,compatibility_note,source_record_id,confidence) VALUES (?,?,'Official Case IH loader and Farmall 100A Pro product pages identify this loader for Farmall Large Utility 100A Pro 110A, 120A, 130A and 140A tractors.',?,'official') ON DUPLICATE KEY UPDATE compatibility_note=VALUES(compatibility_note),source_record_id=VALUES(source_record_id),confidence='official'`,[machineId,attachmentId,loaderSourceId]);}}
  }
};
