import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type ModelSeed={slug:string;model:string;displacementL:number;ratedHp?:number;maxHp:number;ptoHp?:number;rearHitchLb:number;url:string;externalId:string;notes:string};
const FAMILY_URL='https://www.caseih.com/en-us/unitedstates/products/tractors/optum-series';
const FAMILY_EXTERNAL_ID='case-ih-optum-current-us-270-440-2026-08';
const VERSION_SLUG='united-states-current-2026-08';
const models:ModelSeed[]=[
  {slug:'optum-270',model:'Optum 270',displacementL:6.7,ratedHp:271,maxHp:290,ptoHp:240,rearHitchLb:22705,url:'https://www.caseih.com/en-us/unitedstates/products/tractors/optum-series/optum-270',externalId:'case-ih-optum-270-current-us',notes:'Current US product page spec panel lists 271 rated hp, 290 maximum engine hp and 240 PTO hp. The marketing sentence on the same page says 288 maximum hp; the structured specification panel is used here and the discrepancy is retained in this note.'},
  {slug:'optum-300',model:'Optum 300',displacementL:6.7,ratedHp:300,maxHp:313,ptoHp:267,rearHitchLb:22705,url:'https://www.caseih.com/en-us/unitedstates/products/tractors/optum-series/optum-300',externalId:'case-ih-optum-300-current-us',notes:'Current US individual product page values.'},
  {slug:'optum-340',model:'Optum 340',displacementL:6.7,maxHp:340,ptoHp:282,rearHitchLb:22705,url:'https://www.caseih.com/en-us/unitedstates/products/tractors/optum-series/optum-340',externalId:'case-ih-optum-340-current-us',notes:'Current US product page exposes 340 maximum engine hp and 282 PTO hp. Rated engine hp is intentionally omitted because the accessible page does not label a separate rated value.'},
  {slug:'optum-360',model:'Optum 360',displacementL:8.7,ratedHp:360,maxHp:360,rearHitchLb:25926,url:'https://www.caseih.com/en-us/unitedstates/products/tractors/optum-series/optum-360-440',externalId:'case-ih-optum-360-current-us',notes:'Current US Optum 360-440 family page and Case IH launch material identify the new Cursor 9 family at 360, 390 and 435 hp; PTO horsepower is not published in the accessible US product-page summary and is intentionally omitted.'},
  {slug:'optum-390',model:'Optum 390',displacementL:8.7,ratedHp:390,maxHp:390,rearHitchLb:25926,url:'https://www.caseih.com/en-us/unitedstates/products/tractors/optum-series/optum-360-440',externalId:'case-ih-optum-390-current-us',notes:'Current US Optum 360-440 family page and Case IH launch material identify the new Cursor 9 family at 360, 390 and 435 hp; PTO horsepower is not published in the accessible US product-page summary and is intentionally omitted.'},
  {slug:'optum-440',model:'Optum 440',displacementL:8.7,ratedHp:435,maxHp:435,rearHitchLb:25926,url:'https://www.caseih.com/en-us/unitedstates/products/tractors/optum-series/optum-360-440',externalId:'case-ih-optum-440-current-us',notes:'Optum 440 is the model designation; Case IH publishes 435 hp permanent/rated power for this model family. The 435 hp value is stored rather than inferring 440 hp from the model name. PTO horsepower is intentionally omitted.'},
];
const definitions=[
  ['Machine Configuration','configuration.station','Operator station','text',null,1],['Machine Configuration','configuration.drive','Drive configuration','text',null,2],
  ['Engine','engine.make','Engine manufacturer','text',null,1],['Engine','engine.displacement','Engine displacement','decimal','L',2],['Engine','engine.rated_power','Rated engine power','decimal','hp',3],['Engine','engine.maximum_power','Maximum engine power','decimal','hp',4],
  ['PTO','pto.rated_power','PTO power','decimal','hp',10],['Transmission','transmission.standard','Transmission','text',null,10],['Hydraulics','hitch.rear_max_lift_capacity','Maximum rear hitch lift capacity','decimal','lb',20],['Maintenance','maintenance.engine_oil_interval','Engine oil service interval','integer','hours',10],
] as const;
async function selectId(connection:Parameters<DbMigration['apply']>[0],sql:string,params:unknown[]=[]){const [rows]=await connection.query<IdRow[]>(sql,params);if(!rows[0])throw new Error('Missing Case IH Optum migration dependency.');return Number(rows[0].id);}
async function ensureSource(connection:Parameters<DbMigration['apply']>[0],sourceId:number,externalId:string,url:string,title:string){const [rows]=await connection.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(rows[0])return Number(rows[0].id);const [result]=await connection.query<ResultSetHeader>(`INSERT INTO source_records (source_id,url,external_id,title) VALUES (?,?,?,?)`,[sourceId,url,externalId,title]);return Number(result.insertId);}
async function upsertSpec(connection:Parameters<DbMigration['apply']>[0],machineId:number,versionId:number,definitionId:number,sourceRecordId:number,value:string|number,unit:string|null=null){await connection.query(`INSERT INTO machine_specs (machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES (?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[machineId,versionId,definitionId,typeof value==='string'?value:null,typeof value==='number'?value:null,unit,sourceRecordId]);}

export const caseIHOptumCurrentSpecsMigration:DbMigration={
  id:'20260828_232_case_ih_optum_current_specs',
  description:'Add current US Case IH Optum 270/300/340/360/390/440 official engine, PTO, transmission, hitch and maintenance data',
  async apply(connection){
    await connection.query(`INSERT INTO equipment_types (name,slug) VALUES ('Tractor','tractor') ON DUPLICATE KEY UPDATE name=VALUES(name)`);
    await connection.query(`INSERT INTO manufacturers (name,slug) VALUES ('Case IH','case-ih') ON DUPLICATE KEY UPDATE name=VALUES(name)`);
    const manufacturerId=await selectId(connection,`SELECT id FROM manufacturers WHERE slug='case-ih' LIMIT 1`);const equipmentTypeId=await selectId(connection,`SELECT id FROM equipment_types WHERE slug='tractor' LIMIT 1`);
    await connection.query(`INSERT INTO machine_series (manufacturer_id,equipment_type_id,name,slug) VALUES (?,?,'Optum Series','optum-series') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[manufacturerId,equipmentTypeId]);const seriesId=await selectId(connection,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='optum-series' LIMIT 1`,[manufacturerId,equipmentTypeId]);
    let [sourceRows]=await connection.query<IdRow[]>(`SELECT id FROM sources WHERE name='Case IH' AND domain='caseih.com' ORDER BY id LIMIT 1`);let sourceId=sourceRows[0]?.id?Number(sourceRows[0].id):0;if(!sourceId){const [result]=await connection.query<ResultSetHeader>(`INSERT INTO sources (name,domain,source_type,authority_level) VALUES ('Case IH','caseih.com','manufacturer','official')`);sourceId=Number(result.insertId);}
    const familyId=await ensureSource(connection,sourceId,FAMILY_EXTERNAL_ID,FAMILY_URL,'Case IH US current Optum Series 270-440 lineup');
    const definitionIds=new Map<string,number>();for(const [section,key,label,valueType,canonicalUnit,displayOrder] of definitions){await connection.query(`INSERT INTO spec_definitions (section,spec_key,label,value_type,canonical_unit,display_order) VALUES (?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,[section,key,label,valueType,canonicalUnit,displayOrder]);definitionIds.set(key,await selectId(connection,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[key]));}const def=(key:string)=>{const id=definitionIds.get(key);if(!id)throw new Error(`Missing Optum spec ${key}`);return id;};
    for(const model of models){const modelSourceId=await ensureSource(connection,sourceId,model.externalId,model.url,`Case IH US ${model.model} official current product specifications`);await connection.query(`INSERT INTO machines (manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES (?,?,?,?,?,'Current US Case IH Optum multipurpose tractor','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[manufacturerId,equipmentTypeId,seriesId,model.model,model.slug]);const machineId=await selectId(connection,`SELECT id FROM machines WHERE manufacturer_id=? AND equipment_type_id=? AND slug=? LIMIT 1`,[manufacturerId,equipmentTypeId,model.slug]);await connection.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[machineId,VERSION_SLUG]);await connection.query(`INSERT INTO machine_versions (machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES (?,?,'US','United States','Current Optum - wheeled cab tractor',TRUE,?,?) ON DUPLICATE KEY UPDATE market_code='US',market_name='United States',configuration=VALUES(configuration),is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[machineId,VERSION_SLUG,familyId,model.notes]);const versionId=await selectId(connection,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[machineId,VERSION_SLUG]);const values:Array<[string,string|number,string|null,number]>=[['configuration.station','Cab',null,familyId],['configuration.drive','Wheeled tractor',null,familyId],['engine.make','FPT / Case IH',null,familyId],['engine.displacement',model.displacementL,'L',modelSourceId],['engine.maximum_power',model.maxHp,'hp',modelSourceId],['transmission.standard','CVXDrive continuously variable transmission',null,familyId],['hitch.rear_max_lift_capacity',model.rearHitchLb,'lb',familyId],['maintenance.engine_oil_interval',750,'hours',familyId]];if(model.ratedHp!==undefined)values.push(['engine.rated_power',model.ratedHp,'hp',modelSourceId]);if(model.ptoHp!==undefined)values.push(['pto.rated_power',model.ptoHp,'hp',modelSourceId]);for(const [key,value,unit,recordId] of values)await upsertSpec(connection,machineId,versionId,def(key),recordId,value,unit);}
  }
};
