import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Seed={slug:string;model:string;hp:number;pto:number;url:string;externalId:string};
const VERSION='united-states-current-2026-08';
const FAMILY='https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-utility-series/farmall-large-utility-m-series';
const models:Seed[]=[
 {slug:'farmall-110m',model:'Farmall 110M',hp:110,pto:93,url:FAMILY+'/farmall-110m',externalId:'case-ih-farmall-110m-current-us'},
 {slug:'farmall-120-super-m',model:'Farmall 120 Super M',hp:120,pto:99,url:FAMILY+'/farmall-120-super-m',externalId:'case-ih-farmall-120-super-m-current-us'}
];
async function id(c:Parameters<DbMigration['apply']>[0],q:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(q,p);if(!r[0])throw Error('Farmall Large Utility M dependency missing');return Number(r[0].id)}
async function source(c:Parameters<DbMigration['apply']>[0],sid:number,externalId:string,url:string,title:string,raw:unknown){const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,url,externalId,title,JSON.stringify(raw)]);return Number(x.insertId)}
export const caseIHFarmallLargeUtilityMCurrentMigration:DbMigration={id:'20260828_253_case_ih_farmall_large_utility_m_current',description:'Add current US Case IH Farmall Large Utility M 110M and 120 Super M specs plus L113 loader fitments',async apply(c){
 await c.query(`INSERT INTO equipment_types(name,slug) VALUES('Tractor','tractor') ON DUPLICATE KEY UPDATE name=VALUES(name)`);await c.query(`INSERT INTO manufacturers(name,slug) VALUES('Case IH','case-ih') ON DUPLICATE KEY UPDATE name=VALUES(name)`);const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='case-ih'`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='tractor'`);await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'Farmall Large Utility M Series','farmall-large-utility-m-series') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND slug='farmall-large-utility-m-series'`,[mf]);let[s]=await c.query<IdRow[]>(`SELECT id FROM sources WHERE name='Case IH' AND domain='caseih.com' LIMIT 1`);let sid=s[0]?.id?Number(s[0].id):0;if(!sid){const[x]=await c.query<ResultSetHeader>(`INSERT INTO sources(name,domain,source_type,authority_level) VALUES('Case IH','caseih.com','manufacturer','official')`);sid=Number(x.insertId)}
 const defs:(string|number|null)[][]=[['Machine Configuration','configuration.station','Operator station','text',null,1],['Machine Configuration','configuration.drive','Drive configuration','text',null,2],['Engine','engine.displacement','Engine displacement','decimal','L',2],['Engine','engine.rated_power','Engine horsepower','decimal','hp',3],['PTO','pto.rated_power','PTO power','decimal','hp',10],['Transmission','transmission.options','Transmission options','text',null,10],['Emissions','emissions.compliance','Emissions compliance','text',null,10]];for(const d of defs)await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit)`,d);
 for(const m of models){const sr=await source(c,sid,m.externalId,m.url,`Case IH US ${m.model} official current specifications`,{horsepower:m.hp,ptoHorsepower:m.pto,operatorArea:'Cab',traction:'4WD',engineDisplacementL:3.6,transmission:'ActiveDrive 4 16x16 Semi-Powershift, Creeper Ready',emissions:'Stage V'});await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current US Case IH Farmall Large Utility M tractor','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes)`,[mf,et,series,m.model,m.slug]);const mi=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=?`,[mf,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mi,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States','Current Farmall Large Utility M tractor',TRUE,?,'Official Case IH US current product data') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mi,VERSION,sr]);const vi=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=?`,[mi,VERSION]);const vals:[string,string|number,string|null][]=[['configuration.station','Cab',null],['configuration.drive','4WD',null],['engine.displacement',3.6,'L'],['engine.rated_power',m.hp,'hp'],['pto.rated_power',m.pto,'hp'],['transmission.options','ActiveDrive 4 16x16 Semi-Powershift, Creeper Ready',null],['emissions.compliance','Stage V',null]];for(const[k,v,u]of vals){const di=await id(c,`SELECT id FROM spec_definitions WHERE spec_key=?`,[k]);await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mi,vi,di,typeof v==='string'?v:null,typeof v==='number'?v:null,u,sr])}}
 const lurl='https://www.caseih.com/en-us/unitedstates/products/loaders-attachments/l11-series-loaders';const lsr=await source(c,sid,'case-ih-farmall-large-utility-m-l113-current',lurl,'Case IH L113 loader official Farmall Large Utility M specifications',{compatible:['Farmall 110M','Farmall 120M'],liftLb:2205,heightIn:129,breakoutLb:3175});await c.query(`INSERT INTO attachments(manufacturer_id,attachment_type,model_name,slug,lift_capacity_text,lift_height_text,configuration_text,data_status) VALUES(?,'front-loader','L113','l113-farmall-large-utility-m','2,205 lb max lift capacity','129 in max height','Farmall Large Utility M configuration; 3,175 lb boom breakout force','verified') ON DUPLICATE KEY UPDATE data_status='verified',lift_capacity_text=VALUES(lift_capacity_text),lift_height_text=VALUES(lift_height_text),configuration_text=VALUES(configuration_text)`,[mf]);const ai=await id(c,`SELECT id FROM attachments WHERE manufacturer_id=? AND slug='l113-farmall-large-utility-m'`,[mf]);for(const slug of ['farmall-110m','farmall-120-super-m']){const mi=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=?`,[mf,slug]);await c.query(`INSERT INTO machine_attachments(machine_id,attachment_id,compatibility_note,source_record_id,confidence) VALUES(?,?,'Official Case IH L113 compatibility for Farmall Large Utility M series.',?,'official') ON DUPLICATE KEY UPDATE source_record_id=VALUES(source_record_id),confidence='official',compatibility_note=VALUES(compatibility_note)`,[mi,ai,lsr])}
}};
