import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Seed={slug:string;name:string;max:number;dp:number};
const VERSION='united-states-current-2026-08';
const URL='https://www.fendt.com/us/products/tractors/fendt-1000-vario-gen4';
const models:Seed[]=[
{slug:'1040-vario-gen4',name:'1040 Vario Gen4',max:400,dp:426},
{slug:'1044-vario-gen4',name:'1044 Vario Gen4',max:440,dp:466},
{slug:'1048-vario-gen4',name:'1048 Vario Gen4',max:480,dp:507},
{slug:'1052-vario-gen4',name:'1052 Vario Gen4',max:520,dp:550},
];
async function id(c:Parameters<DbMigration['apply']>[0],q:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(q,p);if(!r[0])throw Error('Fendt 1000 Gen4 dependency missing');return Number(r[0].id)}
async function put(c:Parameters<DbMigration['apply']>[0],mi:number,vi:number,di:number,sr:number,v:string|number,u:string|null){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mi,vi,di,typeof v==='string'?v:null,typeof v==='number'?v:null,u,sr])}
export const fendt1000VarioGen4CurrentUsMigration:DbMigration={id:'20260829_312_fendt_1000_vario_gen4_current_us',description:'Add four current US Fendt 1000 Vario Gen4 models from the official Fendt US page',async apply(c){
const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='fendt' LIMIT 1`);const et=await id(c,`SELECT id FROM equipment_types WHERE slug='tractor' LIMIT 1`);const sid=await id(c,`SELECT id FROM sources WHERE name='Fendt' AND domain='fendt.com' LIMIT 1`);await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'Fendt 1000 Vario Gen4','fendt-1000-vario-gen4') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const si=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND slug='fendt-1000-vario-gen4' LIMIT 1`,[mf]);const ext='fendt-1000-vario-gen4-current-us-2026-08';let[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[ext]);let sr=r[0]?.id?Number(r[0].id):0;if(!sr){const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,URL,ext,'Fendt US 1000 Vario Gen4 current product specifications',JSON.stringify({market:'United States',captured:'2026-08-29',models,engine:'MAN D26',displacementL:12.4,cylinders:6,drivetrain:'VarioDrive'})]);sr=Number(x.insertId)}
const defs=[['Engine','engine.make','Engine manufacturer','text',null,1],['Engine','engine.displacement','Engine displacement','decimal','L',2],['Engine','engine.cylinders','Engine cylinders','integer',null,3],['Engine','engine.maximum_power','Maximum engine power','decimal','hp',5],['Engine','engine.dynamic_performance_power','Maximum power with DynamicPerformance','decimal','hp',6],['Transmission','transmission.options','Transmission / drivetrain','text',null,10]] as const;const d=new Map<string,number>();for(const x of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,[...x]);d.set(x[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[x[1]]))}
for(const m of models){await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current US Fendt 1000 Vario Gen4 tractor','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[mf,et,si,m.name,m.slug]);const mi=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mi,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States','Current Fendt 1000 Vario Gen4',TRUE,?,'Current US Fendt Gen4 record. Older 1000 Vario generations are not inherited into this record.') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mi,VERSION,sr]);const vi=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mi,VERSION]);const vals:Array<[string,string|number,string|null]>=[['engine.make','MAN D26',null],['engine.displacement',12.4,'L'],['engine.cylinders',6,null],['engine.maximum_power',m.max,'hp'],['engine.dynamic_performance_power',m.dp,'hp'],['transmission.options','Fendt VarioDrive continuously variable drivetrain',null]];for(const [k,v,u] of vals)await put(c,mi,vi,d.get(k)!,sr,v,u)}
}};
