import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow = RowDataPacket & { id: number };
type Model = {
  slug: string; model: string; ratedHp: number; maxHp: number; ptoHp: number;
  displacementL?: number; engineModel?: string; transmission: string;
  pumpStandard: number; pumpOptional?: number; drive: string; url: string; externalId: string;
};

const VERSION='united-states-current-2026-08';
const models: Model[] = [
  {slug:'6m-180',model:'6M 180',ratedHp:180,maxHp:198,ptoHp:140,displacementL:6.8,engineModel:'John Deere PowerTech PVS',transmission:'20-speed PowrQuad Plus standard; optional 16-speed PowrQuad Plus, 20-speed AutoQuad Plus, e19 PowerShift, or AutoPowr/IVT',pumpStandard:114,pumpOptional:155,drive:'MFWD',url:'https://www.deere.com/en-us/products-solutions/tractors/utility-tractors/6m-180-tractor-njexmuw',externalId:'john-deere-6m-180-current-us-2026-08'},
  {slug:'6m-185',model:'6M 185',ratedHp:185,maxHp:204,ptoHp:146,displacementL:6.8,engineModel:'John Deere PowerTech PVS',transmission:'AutoPowr/IVT 40 km/h standard; optional AutoPowr/IVT 50 km/h',pumpStandard:114,pumpOptional:155,drive:'MFWD',url:'https://www.deere.com/en-us/products-solutions/tractors/utility-tractors/6m-185-tractor-njixmuw',externalId:'john-deere-6m-185-current-us-2026-08'},
  {slug:'6m-200',model:'6M 200',ratedHp:200,maxHp:220,ptoHp:159,transmission:'20-speed PowrQuad Plus standard; optional 16-speed PowrQuad Plus, 20-speed AutoQuad Plus, e19 PowerShift, or AutoPowr/IVT',pumpStandard:114,pumpOptional:155,drive:'MFWD',url:'https://www.deere.com/en/tractors/utility-tractors/6-family-utility-tractors/',externalId:'john-deere-6m-200-current-us-2026-08'},
  {slug:'6m-220',model:'6M 220',ratedHp:220,maxHp:242,ptoHp:177,displacementL:6.8,engineModel:'John Deere PowerTech PVS',transmission:'20-speed PowrQuad Plus standard; optional 16-speed PowrQuad Plus, 20-speed AutoQuad Plus, e19 PowerShift, or AutoPowr/IVT',pumpStandard:114,pumpOptional:155,drive:'MFWD',url:'https://www.deere.com/en-us/products-solutions/tractors/utility-tractors/6m-220-tractor-nje0muw',externalId:'john-deere-6m-220-current-us-2026-08'},
  {slug:'6m-230',model:'6M 230',ratedHp:230,maxHp:253,ptoHp:184,displacementL:6.8,engineModel:'John Deere PowerTech PSS 6068HL550',transmission:'AutoPowr/IVT 40 km/h standard; optional IVT 50 km/h or e19 PowerShift',pumpStandard:155,pumpOptional:195,drive:'4WD',url:'https://www.deere.com/en-us/products-solutions/tractors/utility-tractors/6m-230-tractor-nje1muw',externalId:'john-deere-6m-230-current-us-2026-08'},
  {slug:'6m-240',model:'6M 240',ratedHp:240,maxHp:264,ptoHp:194,displacementL:6.8,engineModel:'John Deere PowerTech PSS',transmission:'AutoPowr/IVT 40 km/h standard; optional AutoPowr/IVT 50 km/h',pumpStandard:114,pumpOptional:155,drive:'MFWD',url:'https://www.deere.com/en-us/products-solutions/tractors/utility-tractors/6m-240-tractor-nje2muw',externalId:'john-deere-6m-240-current-us-2026-08'},
];

async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('John Deere 6M 180-240 dependency missing');return Number(r[0].id)}
async function sourceRecord(c:Parameters<DbMigration['apply']>[0],sourceId:number,m:Model){const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[m.externalId]);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sourceId,m.url,m.externalId,`John Deere US ${m.model} official current specifications`,JSON.stringify(m)]);return Number(x.insertId)}

export const johnDeere6M180240CurrentSpecsMigration:DbMigration={id:'20260828_264_john_deere_6m_180_240_current_specs',description:'Add official current US John Deere 6M 180/185/200/220/230/240 specs',async apply(c){
 const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='john-deere' LIMIT 1`), et=await id(c,`SELECT id FROM equipment_types WHERE slug='tractor' LIMIT 1`), sid=await id(c,`SELECT id FROM sources WHERE name='John Deere' AND domain='deere.com' LIMIT 1`);
 await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'6M Series','6m-series') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='6m-series' LIMIT 1`,[mf,et]);
 const defs:Array<[string,string,string,string,string|null,number]>=[['Engine','engine.model','Engine model','text',null,5],['Engine','engine.displacement','Engine displacement','decimal','L',20],['Engine','engine.rated_power','Rated engine power','decimal','hp',10],['Engine','engine.maximum_power','Maximum engine power','decimal','hp',15],['Engine','engine.emissions','Emissions','text',null,50],['Transmission','transmission.options','Transmission options','text',null,20],['PTO','pto.rated_power','PTO power','decimal','hp',10],['Hydraulics','hydraulics.pump_rated_output','Standard pump rated output','decimal','L/min',10],['Hydraulics','hydraulics.pump_optional_output','Optional pump rated output','decimal','L/min',20],['Machine Configuration','configuration.drive','Drive configuration','text',null,2]];for(const d of defs)await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,d);
 for(const m of models){const sr=await sourceRecord(c,sid,m);await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current US John Deere 6M utility tractor','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes)`,[mf,et,series,m.model,m.slug]);const mi=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mi,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States','Current 6M utility tractor',TRUE,?,'Official John Deere US current product data captured August 2026.') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mi,VERSION,sr]);const vi=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mi,VERSION]);const vals:Array<[string,string|number,string|null]>=[['engine.rated_power',m.ratedHp,'hp'],['engine.maximum_power',m.maxHp,'hp'],['engine.emissions','Final Tier 4',null],['transmission.options',m.transmission,null],['pto.rated_power',m.ptoHp,'hp'],['hydraulics.pump_rated_output',m.pumpStandard,'L/min'],['configuration.drive',m.drive,null]];if(m.engineModel)vals.push(['engine.model',m.engineModel,null]);if(m.displacementL!==undefined)vals.push(['engine.displacement',m.displacementL,'L']);if(m.pumpOptional!==undefined)vals.push(['hydraulics.pump_optional_output',m.pumpOptional,'L/min']);for(const[k,v,u]of vals){const di=await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[k]);await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mi,vi,di,typeof v==='string'?v:null,typeof v==='number'?v:null,u,sr])}}
}};
