import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Seed={slug:string;name:string;station:'ROPS'|'Cab';ptoHp:number;transmission:string;weightLb:number;heightIn:number};
const VERSION='united-states-current-2026-08';
const PAGE='https://www.zetorna.com/compact-utility-class';
const PRODUCTS='https://www.zetorna.com/products';
const PDF='https://www.zetorna.com/file/1630/major-compactutilityclass.pdf';
const models:Seed[]=[
 {slug:'m60ss',name:'M60SS',station:'ROPS',ptoHp:47.5,transmission:'16F x 16R synchronized shuttle; 4 ranges x 4 speeds; 4 factory creeper speeds',weightLb:5400,heightIn:102.1},
 {slug:'m60htc',name:'M60HTC',station:'Cab',ptoHp:45,transmission:'3-range HST; Auto Throttle, Electronic Cruise and Load Sense; dual side-by-side pedals',weightLb:5845,heightIn:99.6},
];
const defs:Array<[string,string,string,string,string|null,number]>=[
 ['Machine Configuration','configuration.station','Operator station','text',null,1],
 ['Engine','engine.make','Engine manufacturer','text',null,1],['Engine','engine.type','Engine type','text',null,2],['Engine','engine.cylinders','Cylinders','integer',null,4],['Engine','emissions.standard','Emissions standard','text',null,5],['Engine','engine.gross_power','Maximum engine power','decimal','hp',8],['Engine','engine.rated_speed','Rated engine speed','integer','rpm',9],
 ['Transmission','transmission.standard','Transmission','text',null,10],['PTO','pto.rated_power','PTO power','decimal','hp',10],['PTO','pto.rear_description','Rear PTO','text',null,20],
 ['Hydraulics','hydraulics.system_type','Hydraulic system','text',null,5],['Hydraulics','hydraulics.total_flow','Total hydraulic flow','decimal','gpm',30],['Hydraulics','hydraulics.main_pump_capacity','Flow to 3-point hitch and loader','decimal','gpm',20],['Hydraulics','hydraulics.power_steering_pump_capacity','Power steering flow','decimal','gpm',25],['Hydraulics','hydraulics.remote_valves','Remote/mid valves','text',null,60],['Hydraulics','hitch.category','3-point hitch category','text',null,40],['Hydraulics','hitch.lift_capacity','3-point hitch lift capacity','decimal','lb',50],
 ['Dimensions & Weight','dimensions.overall_height','Maximum height','decimal','in',30],['Dimensions & Weight','dimensions.package_weight','Published complete package weight','decimal','lb',70],['Tires','tires.industrial','Industrial tires front / rear','text',null,20],
 ['Loader','loader.published_lift_height','Published QA loader max lift height','decimal','in',10],['Loader','loader.published_lift_capacity','Published QA loader max lift capacity','decimal','lb',20]
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('Zetor M60 migration dependency missing');return Number(r[0].id)}
async function source(c:Parameters<DbMigration['apply']>[0],sid:number,eid:string,url:string,title:string,raw:unknown){const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[eid]);if(r[0])return Number(r[0].id);const[i]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,url,eid,title,JSON.stringify(raw)]);return Number(i.insertId)}
async function put(c:Parameters<DbMigration['apply']>[0],mid:number,vid:number,did:number,srid:number,v:string|number,u:string|null){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mid,vid,did,typeof v==='string'?v:null,typeof v==='number'?v:null,u,srid])}

export const zetorM60CompactUtilityCurrentUsMigration:DbMigration={
 id:'20260831_447_zetor_m60_compact_utility_current_us',description:'Add current US Zetor M60SS and M60HTC compact utility configurations',
 async apply(c){
  const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='zetor' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='tractor' LIMIT 1`),sid=await id(c,`SELECT id FROM sources WHERE name='Zetor North America' AND domain='zetorna.com' LIMIT 1`);
  await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'Zetor M60 Compact Utility','zetor-m60-compact-utility') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND slug='zetor-m60-compact-utility' LIMIT 1`,[mf]);
  const seriesSr=await source(c,sid,'zetor-m60-compact-utility-current-us-2026-08',PAGE,'Zetor North America current M60 Compact Utility lineup',{market:'United States',captured:'2026-08-31',productPage:PAGE,productsIndex:PRODUCTS,officialPdf:PDF,currentCards:['M60SS – 59HP, 16/16 Shuttle ROPS Tractor','M60HTC – 59HP, HST CAB Tractor'],rangeConflict:'The current Products index labels Compact Utility as 49–59 HP, but the current Compact Utility page explicitly lists only M60SS and M60HTC, both 59 HP. No 49-hp current model is identified, so none is inferred.',pdfDate:'01/2020',sourceFreshnessPolicy:'Current 2026 HTML page is authoritative for current-model presence. Official M60 PDF supplies detailed specs and is retained as technical source; revision date is preserved.',shared:{engine:'Yanmar Tier 4 Final, 4-cylinder common-rail water-cooled turbo diesel',grossHp:59,hitchLb:3314,totalHydraulicGpm:14.5,implementLoaderGpm:9.5,steeringGpm:5,rearValves:'2 standard; 3 optional',midValves:'2 standard / 4 couplers / factory joystick / 3rd-function control',pto:'540 rear hydraulic independent',loader:'QA 72-in bucket, skid-steer style carrier; 109.1-in lift height; 2,478-lb max lift capacity',industrialTires:'12-16.5 / 16.9-24'}});
  const d=new Map<string,number>();for(const row of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,row);d.set(row[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[row[1]]))}
  for(const m of models){const sr=await source(c,sid,`zetor-${m.slug}-current-us-2026-08`,PDF,`Zetor North America ${m.name} current specifications`,{market:'United States',captured:'2026-08-31',model:m.name,productPage:PAGE,station:m.station,ptoHp:m.ptoHp,transmission:m.transmission,publishedPackageWeightLb:m.weightLb,technicalPdfRevision:'01/2020'});await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current US Zetor M60 compact utility tractor','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[mf,et,series,m.name,m.slug]);const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mid,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States',?,TRUE,?,'Current Zetor North America M60 configuration. Published weight is labeled complete package weight by Zetor and is not normalized as bare tractor weight.') ON DUPLICATE KEY UPDATE configuration=VALUES(configuration),is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mid,VERSION,`${m.station}; ${m.transmission}`,sr||seriesSr]);const vid=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mid,VERSION]);const vals:Array<[string,string|number,string|null]>=[['configuration.station',m.station,null],['engine.make','Yanmar',null],['engine.type','Common-rail, water-cooled, turbocharged diesel',null],['engine.cylinders',4,null],['emissions.standard','US EPA Tier 4 Final',null],['engine.gross_power',59,'hp'],['engine.rated_speed',3000,'rpm'],['transmission.standard',m.transmission,null],['pto.rated_power',m.ptoHp,'hp'],['pto.rear_description','540 rear, hydraulic independent; manual/off/auto control',null],['hydraulics.system_type','Open center',null],['hydraulics.total_flow',14.5,'gpm'],['hydraulics.main_pump_capacity',9.5,'gpm'],['hydraulics.power_steering_pump_capacity',5,'gpm'],['hydraulics.remote_valves','2 rear standard / 3 optional; 2 mid valves standard with 4 couplers and factory joystick; optional 3rd function',null],['hitch.category','Category I',null],['hitch.lift_capacity',3314,'lb'],['dimensions.overall_height',m.heightIn,'in'],['dimensions.package_weight',m.weightLb,'lb'],['tires.industrial','12-16.5 / 16.9-24',null],['loader.published_lift_height',109.1,'in'],['loader.published_lift_capacity',2478,'lb']];for(const[k,v,u]of vals){const did=d.get(k);if(!did)throw new Error(`Missing Zetor M60 spec ${k}`);await put(c,mid,vid,did,sr||seriesSr,v,u)}}
 }
};
