import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Model={slug:string;model:string;ratedHp:number;ptoHp:number;transmission:string;station:string};
const SOURCE_URL='https://agriculture.newholland.com/en-us/nar/products/tractors-telehandlers/t5-series';
const EXTERNAL_ID='new-holland-t5-current-us-2026-08';
const VERSION='united-states-current-2026-08';
const models:Model[]=[
 {slug:'t5-110',model:'T5.110',ratedHp:107,ptoHp:93,transmission:'Dual Command 24x24 Hi-Lo or Electro Command 16x16 semi-powershift',station:'VisionView cab; ROPS also available on Dual Command'},
 {slug:'t5-120',model:'T5.120',ratedHp:117,ptoHp:100,transmission:'Dual Command 24x24 Hi-Lo or Electro Command 16x16 semi-powershift',station:'VisionView cab; ROPS also available on Dual Command'},
 {slug:'t5-130',model:'T5.130',ratedHp:120,ptoHp:102,transmission:'Dynamic Command 24x24 8-step semi-powershift or Auto Command CVT',station:'Horizon cab'},
 {slug:'t5-140',model:'T5.140',ratedHp:130,ptoHp:111,transmission:'Dynamic Command 24x24 8-step semi-powershift or Auto Command CVT',station:'Horizon cab'},
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('New Holland T5 dependency missing');return Number(r[0].id)}
export const newHollandT5CurrentSpecsMigration:DbMigration={id:'20260829_280_new_holland_t5_current_specs',description:'Add current official US New Holland T5 Series tractors',async apply(c){
 const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='new-holland' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='tractor' LIMIT 1`),sid=await id(c,`SELECT id FROM sources WHERE name='New Holland' AND domain='agriculture.newholland.com' LIMIT 1`);
 const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[EXTERNAL_ID]);let sr=r[0]?.id?Number(r[0].id):0;if(!sr){const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title) VALUES(?,?,?,'New Holland US T5 Series current specifications')`,[sid,SOURCE_URL,EXTERNAL_ID]);sr=Number(x.insertId)}
 await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'T5 Series','t5-series') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='t5-series' LIMIT 1`,[mf,et]);
 const defs:Array<[string,string,string,string,string|null,number]>=[['Machine Configuration','configuration.station','Operator station','text',null,1],['Engine','engine.make','Engine manufacturer','text',null,1],['Engine','engine.cylinders','Cylinders','integer',null,4],['Engine','engine.rated_power','Rated engine power','decimal','hp',10],['Maintenance','maintenance.engine_service_interval','Engine service interval','integer','hours',10],['Transmission','transmission.options','Transmission options','text',null,20],['PTO','pto.rated_power','PTO power','decimal','hp',10]];for(const d of defs)await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,d);
 for(const m of models){await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current US New Holland T5 utility tractor','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes)`,[mf,et,series,m.model,m.slug]);const mi=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mi,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States','T5 Series current US configuration',TRUE,?,'Official New Holland North America current data captured August 2026.') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mi,VERSION,sr]);const vi=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mi,VERSION]);const vals:Array<[string,string|number,string|null]>=[['configuration.station',m.station,null],['engine.make','FPT Industrial',null],['engine.cylinders',4,null],['engine.rated_power',m.ratedHp,'hp'],['maintenance.engine_service_interval',600,'hours'],['transmission.options',m.transmission,null],['pto.rated_power',m.ptoHp,'hp']];for(const[k,v,u]of vals){const di=await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[k]);await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mi,vi,di,typeof v==='string'?v:null,typeof v==='number'?v:null,u,sr])}}
}};