import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type ModelSeed={slug:string;model:string;ratedHp:number;ptoHp:number;maxHp?:number;maxBoostedHp?:number;displacementL:number;transmission?:string;rowtrac:boolean;url:string;externalId:string};
const FAMILY_URL='https://www.caseih.com/en-us/unitedstates/products/tractors/magnum-series';
const FAMILY_EXTERNAL_ID='case-ih-magnum-current-us-200-405-2026-08';
const VERSION_SLUG='united-states-current-2026-08';
const models:ModelSeed[]=[
  {slug:'magnum-200',model:'Magnum 200',ratedHp:200,ptoHp:170,maxHp:220,displacementL:6.7,transmission:'PowerDrive or CVXDrive',rowtrac:false,url:'https://www.caseih.com/en-us/unitedstates/products/tractors/magnum-series/magnum-200',externalId:'case-ih-magnum-200-current-us'},
  {slug:'magnum-220',model:'Magnum 220',ratedHp:220,ptoHp:185,maxHp:240,displacementL:6.7,transmission:'PowerDrive or CVXDrive',rowtrac:false,url:'https://www.caseih.com/en-us/unitedstates/products/tractors/magnum-series/magnum-220',externalId:'case-ih-magnum-220-current-us'},
  {slug:'magnum-240',model:'Magnum 240',ratedHp:240,ptoHp:205,displacementL:6.7,transmission:'CVXDrive standard; PowerDrive not available on the current US product page',rowtrac:false,url:'https://www.caseih.com/en-us/unitedstates/products/tractors/magnum-series/magnum-240',externalId:'case-ih-magnum-240-current-us'},
  {slug:'magnum-265',model:'Magnum 265',ratedHp:265,ptoHp:218,maxHp:290,displacementL:8.7,transmission:'PowerDrive or CVXDrive',rowtrac:false,url:'https://www.caseih.com/en-us/unitedstates/products/tractors/magnum-series/magnum-265',externalId:'case-ih-magnum-265-current-us'},
  {slug:'magnum-295',model:'Magnum 295',ratedHp:295,ptoHp:248,maxHp:325,displacementL:8.7,transmission:'PowerDrive or CVXDrive',rowtrac:false,url:'https://www.caseih.com/en-us/unitedstates/products/tractors/magnum-series/magnum-295',externalId:'case-ih-magnum-295-current-us'},
  {slug:'magnum-325',model:'Magnum 325',ratedHp:325,ptoHp:277,maxHp:356,displacementL:8.7,transmission:'PowerDrive or CVXDrive',rowtrac:false,url:'https://www.caseih.com/en-us/unitedstates/products/tractors/magnum-series/magnum-325',externalId:'case-ih-magnum-325-current-us'},
  {slug:'magnum-355',model:'Magnum 355',ratedHp:355,ptoHp:303,maxHp:390,maxBoostedHp:410,displacementL:8.7,transmission:'PowerDrive or CVXDrive',rowtrac:true,url:'https://www.caseih.com/en-us/unitedstates/products/tractors/magnum-series/magnum-355',externalId:'case-ih-magnum-355-current-us'},
  {slug:'magnum-385',model:'Magnum 385',ratedHp:385,ptoHp:320,maxHp:417,displacementL:8.7,transmission:'CVXDrive standard',rowtrac:true,url:'https://www.caseih.com/en-us/unitedstates/products/tractors/magnum-series/magnum-385',externalId:'case-ih-magnum-385-current-us'},
  {slug:'magnum-405',model:'Magnum 405',ratedHp:405,ptoHp:352,maxHp:435,displacementL:8.7,rowtrac:true,url:'https://www.caseih.com/en-us/unitedstates/products/tractors/magnum-series/magnum-405',externalId:'case-ih-magnum-405-current-us'},
];
const definitions=[
  ['Machine Configuration','configuration.station','Operator station','text',null,1],['Machine Configuration','configuration.drive','Drive configuration','text',null,2],
  ['Engine','engine.make','Engine manufacturer','text',null,1],['Engine','engine.displacement','Engine displacement','decimal','L',2],['Engine','engine.rated_power','Rated engine power','decimal','hp',3],['Engine','engine.maximum_power','Maximum engine power','decimal','hp',4],['Engine','engine.maximum_boosted_power','Maximum boosted engine power','decimal','hp',5],
  ['PTO','pto.rated_power','PTO power','decimal','hp',10],['Transmission','transmission.standard','Transmission','text',null,10],
] as const;
async function selectId(connection:Parameters<DbMigration['apply']>[0],sql:string,params:unknown[]=[]){const [rows]=await connection.query<IdRow[]>(sql,params);if(!rows[0])throw new Error('Missing Case IH Magnum migration dependency.');return Number(rows[0].id);}
async function ensureSource(connection:Parameters<DbMigration['apply']>[0],sourceId:number,externalId:string,url:string,title:string){const [rows]=await connection.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(rows[0])return Number(rows[0].id);const [result]=await connection.query<ResultSetHeader>(`INSERT INTO source_records (source_id,url,external_id,title) VALUES (?,?,?,?)`,[sourceId,url,externalId,title]);return Number(result.insertId);}
async function upsertSpec(connection:Parameters<DbMigration['apply']>[0],machineId:number,versionId:number,definitionId:number,sourceRecordId:number,value:string|number,unit:string|null=null){await connection.query(`INSERT INTO machine_specs (machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES (?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[machineId,versionId,definitionId,typeof value==='string'?value:null,typeof value==='number'?value:null,unit,sourceRecordId]);}

export const caseIHMagnumCurrentSpecsMigration:DbMigration={
  id:'20260828_229_case_ih_magnum_current_specs',
  description:'Add current US Case IH Magnum 200-405 engine, PTO, transmission and wheel/Rowtrac configuration specifications',
  async apply(connection){
    const manufacturerId=await selectId(connection,`SELECT id FROM manufacturers WHERE slug='case-ih' LIMIT 1`);const equipmentTypeId=await selectId(connection,`SELECT id FROM equipment_types WHERE slug='tractor' LIMIT 1`);
    await connection.query(`INSERT INTO machine_series (manufacturer_id,equipment_type_id,name,slug) VALUES (?,?,'Magnum Series','magnum-series') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[manufacturerId,equipmentTypeId]);const seriesId=await selectId(connection,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='magnum-series' LIMIT 1`,[manufacturerId,equipmentTypeId]);
    let [sourceRows]=await connection.query<IdRow[]>(`SELECT id FROM sources WHERE name='Case IH' AND domain='caseih.com' ORDER BY id LIMIT 1`);let sourceId=sourceRows[0]?.id?Number(sourceRows[0].id):0;if(!sourceId){const [result]=await connection.query<ResultSetHeader>(`INSERT INTO sources (name,domain,source_type,authority_level) VALUES ('Case IH','caseih.com','manufacturer','official')`);sourceId=Number(result.insertId);}
    const familyId=await ensureSource(connection,sourceId,FAMILY_EXTERNAL_ID,FAMILY_URL,'Case IH US current Magnum Series 200-405 lineup');
    const definitionIds=new Map<string,number>();for(const [section,key,label,valueType,canonicalUnit,displayOrder] of definitions){await connection.query(`INSERT INTO spec_definitions (section,spec_key,label,value_type,canonical_unit,display_order) VALUES (?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,[section,key,label,valueType,canonicalUnit,displayOrder]);definitionIds.set(key,await selectId(connection,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[key]));}const def=(key:string)=>{const id=definitionIds.get(key);if(!id)throw new Error(`Missing Magnum spec ${key}`);return id;};
    for(const model of models){const modelSourceId=await ensureSource(connection,sourceId,model.externalId,model.url,`Case IH US ${model.model} official current product specifications`);await connection.query(`INSERT INTO machines (manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES (?,?,?,?,?,'Current US Case IH Magnum row-crop tractor','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[manufacturerId,equipmentTypeId,seriesId,model.model,model.slug]);const machineId=await selectId(connection,`SELECT id FROM machines WHERE manufacturer_id=? AND equipment_type_id=? AND slug=? LIMIT 1`,[manufacturerId,equipmentTypeId,model.slug]);await connection.query(`INSERT INTO machine_versions (machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES (?,?,'US','United States',?,TRUE,?,?) ON DUPLICATE KEY UPDATE market_code='US',market_name='United States',configuration=VALUES(configuration),is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[machineId,VERSION_SLUG,model.rowtrac?'Current Magnum - wheeled or Rowtrac configuration':'Current Magnum - wheeled configuration',familyId,model.model==='Magnum 240'?'Current US Magnum 240 page publishes rated HP, PTO HP, 6.7 L engine and CVXDrive standard, but does not expose a current Maximum Engine Horsepower value in accessible product-page data; that field is intentionally omitted.':model.model==='Magnum 355'?'Current US product page separately publishes Maximum Engine Horsepower 390 and marketing max-boosted power 410; both are stored as distinct fields.':'Current values are from the individual Case IH US product page.']);const versionId=await selectId(connection,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[machineId,VERSION_SLUG]);const values:Array<[string,string|number,string|null]>=[['configuration.station','Cab',null],['configuration.drive',model.rowtrac?'Wheeled or Rowtrac':'Wheeled',null],['engine.make','FPT / Case IH',null],['engine.displacement',model.displacementL,'L'],['engine.rated_power',model.ratedHp,'hp'],['pto.rated_power',model.ptoHp,'hp']];if(model.maxHp!==undefined)values.push(['engine.maximum_power',model.maxHp,'hp']);if(model.maxBoostedHp!==undefined)values.push(['engine.maximum_boosted_power',model.maxBoostedHp,'hp']);if(model.transmission)values.push(['transmission.standard',model.transmission,null]);for(const [key,value,unit] of values)await upsertSpec(connection,machineId,versionId,def(key),modelSourceId,value,unit);}
  }
};