import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Model={slug:string;name:string;hp:number;powerKey:'engine.maximum_power'|'engine.rated_power';dpHp?:number};
type Series={slug:string;name:string;url:string;externalId:string;note:string;models:Model[];shared:Array<[string,string|number,string|null]>};
const VERSION='united-states-current-2026-08';
const BROCHURE_URL='https://www.fendt.com/us/geneva-assets/article/151317/971328-ft22b006agv03-fendt-700-vario-series-brochure-lr.pdf';
const series:Series[]=[
{slug:'fendt-700-vario-gen7-1',name:'Fendt 700 Vario Gen7.1',url:'https://www.fendt.com/us/products/tractors/fendt-700-vario-gen7',externalId:'fendt-700-vario-gen7-1-current-us-2026-08',note:'Current US Fendt 700 Vario Gen7.1 wheeled tractor',models:[
{slug:'720-vario-gen7-1',name:'720 Vario Gen7.1',hp:203,powerKey:'engine.maximum_power'},
{slug:'722-vario-gen7-1',name:'722 Vario Gen7.1',hp:223,powerKey:'engine.maximum_power'},
{slug:'724-vario-gen7-1',name:'724 Vario Gen7.1',hp:243,powerKey:'engine.maximum_power'},
{slug:'726-vario-gen7-1',name:'726 Vario Gen7.1',hp:262,powerKey:'engine.maximum_power'},
{slug:'728-vario-gen7-1',name:'728 Vario Gen7.1',hp:283,powerKey:'engine.maximum_power',dpHp:303},
],shared:[['engine.make','AGCO Power CORE75',null],['engine.displacement',7.5,'L'],['transmission.options','Fendt VarioDrive continuously variable drivetrain',null],['hydraulics.main_pump_max_flow',58,'US gal/min']]},
{slug:'fendt-900-vario-mt',name:'Fendt 900 Vario MT',url:'https://www.fendt.com/us/products/tractors/fendt-900-vario-mt',externalId:'fendt-900-vario-mt-current-us-2026-08',note:'Current US Fendt 900 Vario MT tracked tractor',models:[
{slug:'938-vario-mt',name:'938 Vario MT',hp:380,powerKey:'engine.rated_power'},
{slug:'940-vario-mt',name:'940 Vario MT',hp:405,powerKey:'engine.rated_power'},
{slug:'943-vario-mt',name:'943 Vario MT',hp:431,powerKey:'engine.rated_power'},
],shared:[['configuration.drive','Mobil-Trac System tracked undercarriage',null],['engine.make','AGCO Power',null],['engine.displacement',9.8,'L'],['engine.cylinders',7,null],['transmission.options','Fendt VarioDrive continuously variable drivetrain',null],['hydraulics.main_pump_max_flow',116,'US gal/min'],['hitch.rear_max_lift_capacity',19000,'lb'],['pto.speeds','1000 / 1000E rpm',null]]}
];
const defs=[
['Machine Configuration','configuration.drive','Drive configuration','text',null,2],
['Engine','engine.make','Engine manufacturer','text',null,1],['Engine','engine.displacement','Engine displacement','decimal','L',2],['Engine','engine.cylinders','Engine cylinders','integer',null,3],['Engine','engine.rated_power','Rated engine power','decimal','hp',4],['Engine','engine.maximum_power','Maximum engine power','decimal','hp',5],['Engine','engine.dynamic_performance_power','Maximum power with DynamicPerformance','decimal','hp',6],
['Transmission','transmission.options','Transmission / drivetrain','text',null,10],['Hydraulics','hydraulics.main_pump_max_flow','Maximum hydraulic flow','decimal','US gal/min',10],['Hydraulics','hitch.rear_max_lift_capacity','Maximum rear hitch lift capacity','decimal','lb',20],['PTO','pto.speeds','PTO speeds','text',null,10]
] as const;
async function id(c:Parameters<DbMigration['apply']>[0],q:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(q,p);if(!r[0])throw Error('Fendt migration dependency missing');return Number(r[0].id)}
async function spec(c:Parameters<DbMigration['apply']>[0],mi:number,vi:number,di:number,sr:number,v:string|number,u:string|null){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mi,vi,di,typeof v==='string'?v:null,typeof v==='number'?v:null,u,sr])}
export const fendtCurrentUsCoreMigration:DbMigration={id:'20260829_310_fendt_current_us_core',description:'Add 8 current US Fendt 700 Vario Gen7.1 and 900 Vario MT tractors from official Fendt US pages',async apply(c){
await c.query(`INSERT INTO equipment_types(name,slug) VALUES('Tractor','tractor') ON DUPLICATE KEY UPDATE name=VALUES(name)`);await c.query(`INSERT INTO manufacturers(name,slug) VALUES('Fendt','fendt') ON DUPLICATE KEY UPDATE name=VALUES(name)`);const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='fendt' LIMIT 1`);const et=await id(c,`SELECT id FROM equipment_types WHERE slug='tractor' LIMIT 1`);let[s]=await c.query<IdRow[]>(`SELECT id FROM sources WHERE name='Fendt' AND domain='fendt.com' LIMIT 1`);let sid=s[0]?.id?Number(s[0].id):0;if(!sid){const[x]=await c.query<ResultSetHeader>(`INSERT INTO sources(name,domain,source_type,authority_level) VALUES('Fendt','fendt.com','manufacturer','official')`);sid=Number(x.insertId)}let[b]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id='fendt-700-vario-gen7-us-brochure-power-2026-08' LIMIT 1`);let brochureSr=b[0]?.id?Number(b[0].id):0;if(!brochureSr){const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,BROCHURE_URL,'fendt-700-vario-gen7-us-brochure-power-2026-08','Fendt US 700 Vario Series brochure power table',JSON.stringify({model:'728 Vario',maximumPowerHp:283,maximumPowerWithDynamicPerformanceHp:303})]);brochureSr=Number(x.insertId)}
const d=new Map<string,number>();for(const [section,key,label,type,unit,order] of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,[section,key,label,type,unit,order]);d.set(key,await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[key]))}
for(const se of series){await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et,se.name,se.slug]);const si=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug=? LIMIT 1`,[mf,et,se.slug]);let[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[se.externalId]);let sr=r[0]?.id?Number(r[0].id):0;if(!sr){const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,se.url,se.externalId,`Fendt US ${se.name} current specifications`,JSON.stringify({market:'United States',captured:'2026-08-29',models:se.models,shared:se.shared})]);sr=Number(x.insertId)}for(const m of se.models){await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,?,'partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[mf,et,si,m.name,m.slug,se.note]);const mi=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mi,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States',?,TRUE,?,'Current US Fendt record. Only values explicitly published by linked official US sources are included; older-generation data is not inherited.') ON DUPLICATE KEY UPDATE market_code='US',market_name='United States',configuration=VALUES(configuration),is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mi,VERSION,se.note,sr]);const vi=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mi,VERSION]);const powerSr=m.slug==='728-vario-gen7-1'?brochureSr:sr;await spec(c,mi,vi,d.get(m.powerKey)!,powerSr,m.hp,'hp');if(m.dpHp!==undefined)await spec(c,mi,vi,d.get('engine.dynamic_performance_power')!,brochureSr,m.dpHp,'hp');for(const [key,v,u] of se.shared)await spec(c,mi,vi,d.get(key)!,sr,v,u)}}
}};
