import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
const VERSION='united-states-current-2026-08';
const URL='https://www.caseih.com/en-us/unitedstates/products/tillage/disk-rippers/ecolo-tiger-875';
const FAMILY_URL='https://www.caseih.com/en-us/unitedstates/products/tillage/disk-rippers';
const defs:Array<[string,string,string,string,string|null,number]>=[
 ['Machine Configuration','configuration.type','Machine configuration','text',null,1],['Machine Configuration','configuration.market_scope','Official market scope','text',null,2],
 ['Tillage System','ripper.working_width','Working width','text',null,10],['Tillage System','ripper.shank_count','Number of shanks','text',null,20],['Tillage System','ripper.shank_spacing','Shank spacing','text',null,30],['Tillage System','ripper.disk_system','Disk system','text',null,40],['Tillage System','ripper.disk_spacing','Gang disk spacing','text',null,50],['Tillage System','ripper.blade_size','Blade diameter','text',null,60],['Tillage System','ripper.point_system','Point system','text',null,70],['Tillage System','ripper.seedbed_conditioning','Seedbed conditioning options','text',null,80],
 ['Tractor Requirements','ripper.required_hp','Required horsepower','text',null,10],['Precision Technology','ripper.precision_control','Precision tillage control','text',null,10],
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('Case IH Ecolo-Tiger migration dependency missing');return Number(r[0].id);}
async function src(c:Parameters<DbMigration['apply']>[0]){const[r]=await c.query<IdRow[]>(`SELECT id FROM sources WHERE name='Case IH' AND domain='caseih.com' ORDER BY id LIMIT 1`);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO sources(name,domain,source_type,authority_level) VALUES('Case IH','caseih.com','manufacturer','official')`);return Number(x.insertId);}
async function rec(c:Parameters<DbMigration['apply']>[0],sid:number){const externalId='case-ih-ecolo-tiger-875-disk-ripper-us-current-2026-08';const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,URL,externalId,'Case IH Ecolo-Tiger 875 current US disk ripper specifications',JSON.stringify({captured:'2026-08-31',market:'United States',equipmentType:'Disk Ripper',model:'Ecolo-Tiger 875',familySource:FAMILY_URL})]);return Number(x.insertId);}
async function put(c:Parameters<DbMigration['apply']>[0],mid:number,vid:number,did:number,rid:number,v:string){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,NULL,NULL,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=NULL,unit=NULL,source_record_id=VALUES(source_record_id),confidence='official'`,[mid,vid,did,v,rid]);}
export const caseIhEcoloTiger875DiskRipperCurrentMigration:DbMigration={id:'20260831_521_case_ih_ecolo_tiger_875_disk_ripper_current',description:'Add current Case IH US Ecolo-Tiger 875 disk ripper',async apply(c){
 await c.query(`INSERT INTO equipment_types(name,slug) VALUES('Disk Ripper','disk-ripper') ON DUPLICATE KEY UPDATE name=VALUES(name)`);await c.query(`INSERT INTO manufacturers(name,slug) VALUES('Case IH','case-ih') ON DUPLICATE KEY UPDATE name=VALUES(name)`);const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='case-ih' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='disk-ripper' LIMIT 1`),sid=await src(c),rid=await rec(c,sid);await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'Ecolo-Tiger','ecolo-tiger') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='ecolo-tiger' LIMIT 1`,[mf,et]);const ids=new Map<string,number>();for(const d of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,d);ids.set(d[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[d[1]]));}const def=(k:string)=>{const v=ids.get(k);if(!v)throw new Error(`Missing disk ripper definition ${k}`);return v;};
 await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current Case IH United States disk ripper lineup','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes)`,[mf,et,series,'Ecolo-Tiger 875','ecolo-tiger-875']);const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND equipment_type_id=? AND slug='ecolo-tiger-875' LIMIT 1`,[mf,et]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mid,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States','Current Ecolo-Tiger 875 specification',TRUE,?,'Current Case IH US product and family pages captured 2026-08-31.') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mid,VERSION,rid]);const vid=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mid,VERSION]);await put(c,mid,vid,def('configuration.type'),rid,'Disk ripper');await put(c,mid,vid,def('configuration.market_scope'),rid,'United States current catalog');await put(c,mid,vid,def('ripper.working_width'),rid,'14, 18, 22, or 26 ft (4.3, 5.5, 6.7, or 7.9 m)');await put(c,mid,vid,def('ripper.shank_count'),rid,'7, 9, 11, or 13');await put(c,mid,vid,def('ripper.shank_spacing'),rid,'24 in (61 cm)');await put(c,mid,vid,def('ripper.disk_system'),rid,'24-in individual disks or optional 26-in Cushion Gang disks; split-the-middle front-to-rear gang position');await put(c,mid,vid,def('ripper.disk_spacing'),rid,'12 in (304 mm) between gang disks');await put(c,mid,vid,def('ripper.blade_size'),rid,'24 or 26 in Earth Metal blades');await put(c,mid,vid,def('ripper.point_system'),rid,'High-density Tiger Points with lift-twist-roll action');await put(c,mid,vid,def('ripper.seedbed_conditioning'),rid,'Double-Edge Tigerpaw Crumbler or Disk Leveler attachment');await put(c,mid,vid,def('ripper.required_hp'),rid,'280 - 600 hp (209 - 447 kW)');await put(c,mid,vid,def('ripper.precision_control'),rid,'Soil Command supports tillage prescriptions and coordinated component control');
 }};
