import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Seed={slug:string;model:string;url:string;machine:string;lift?:string;height?:string;text:string};
const CATALOG='https://tym.world/en-us/products/attachments';
const items:Seed[]=[
 {slug:'tym-tx65sl',model:'TX65SL',url:'https://tym.world/en-us/products/attachments/front-end-loader/tx65sl',machine:'t654',lift:'3,122 lb at pivot point at maximum height',height:'124.8 in maximum lift height',text:'Current TYM TX65SL front-end loader for T654; 15.2 cu ft bucket capacity.'},
 {slug:'tym-l5068sl',model:'L5068SL',url:'https://tym.world/en-us/products/attachments/front-end-loader/l5068sl',machine:'t5068',text:'Current TYM US central attachment catalog explicitly maps L5068SL to T5068. Performance fields are intentionally omitted because a clean current product-detail technical record was not available during this capture.'},
 {slug:'tym-tx75sl',model:'TX75SL',url:'https://tym.world/en-us/products/attachments/front-end-loader/tx75sl',machine:'t754',lift:'3,325 lb at pivot point at maximum height',height:'133.8 in maximum lift height',text:'Current TYM TX75SL front-end loader for T754; 16.2 cu ft bucket capacity.'},
 {slug:'tym-l5075sl',model:'L5075SL',url:'https://tym.world/en-us/products/attachments/front-end-loader/l5075sl',machine:'t5075',lift:'3,325 lb at pivot point at maximum height',height:'133.8 in maximum lift height',text:'Current TYM L5075SL front-end loader for T5075; 16.2 cu ft bucket capacity.'},
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('TYM Series 5 attachment dependency missing');return Number(r[0].id)}
async function source(c:Parameters<DbMigration['apply']>[0],sid:number,eid:string,url:string,title:string,raw:unknown){const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[eid]);if(r[0])return Number(r[0].id);const[i]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,url,eid,title,JSON.stringify(raw)]);return Number(i.insertId)}
export const tymSeries5AttachmentsMigration:DbMigration={id:'20260830_410_tym_series5_attachments',description:'Add conservative verified current US TYM Series 5 front-loader fitment and available performance specs',async apply(c){const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='tym' LIMIT 1`),sid=await id(c,`SELECT id FROM sources WHERE name='TYM' AND domain='tym.world' LIMIT 1`);const csr=await source(c,sid,'tym-series5-attachments-current-us-2026-08',CATALOG,'TYM USA current Series 5 attachment fitment catalog',{market:'United States',captured:'2026-08-30',fitment:{T654:'TX65SL',T5068:'L5068SL',T754:'TX75SL',T5075:'L5075SL'},deferred:['T5074 has no explicit current loader mapping in the current US central attachment catalog, so no verified loader relationship is added.'],sourcePolicy:'Central US catalog controls fitment; individual current loader pages provide performance fields when cleanly available.'});for(const a of items){const sr=await source(c,sid,`tym-${a.model.toLowerCase()}-current-us-2026-08`,a.url,`TYM ${a.model} current US loader specifications`,{market:'United States',captured:'2026-08-30',machineSlug:a.machine,catalog:CATALOG,performanceAvailable:Boolean(a.lift)});await c.query(`INSERT INTO attachments(manufacturer_id,attachment_type,model_name,slug,lift_capacity_text,lift_height_text,configuration_text,data_status) VALUES(?,'front-loader',?,?,?,?,?,'verified') ON DUPLICATE KEY UPDATE model_name=VALUES(model_name),lift_capacity_text=VALUES(lift_capacity_text),lift_height_text=VALUES(lift_height_text),configuration_text=VALUES(configuration_text),data_status='verified'`,[mf,a.model,a.slug,a.lift??null,a.height??null,a.text]);const aid=await id(c,`SELECT id FROM attachments WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,a.slug]);const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,a.machine]);await c.query(`INSERT INTO machine_attachments(machine_id,attachment_id,compatibility_note,source_record_id,confidence) VALUES(?,?,?,?, 'official') ON DUPLICATE KEY UPDATE compatibility_note=VALUES(compatibility_note),source_record_id=VALUES(source_record_id),confidence='official'`,[mid,aid,`${a.model} current US fitment is explicitly listed by TYM for ${a.machine.toUpperCase()}.`,sr||csr]);}}};
