import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow = RowDataPacket & { id: number };
type Seed = {
  slug: string; name: string; hp: number; rpm: number; displacementL: number; cylinders: number; fuelL: number;
  transmission: string; maxSpeedMph: number; ptoType: string; ptoPowerHp: number; totalFlowGpm: number; mainFlowGpm: number;
  battery: string; alternator: string; lengthIn: number; wheelbaseIn: number; widthIn: number; heightIn: number; clearanceIn: number; weightLb: number; loaderSlug: string;
};

const VERSION = 'united-states-current-2026-08';
const URL = 'https://www.mahindrausa.com/series/1600/';
const shuttle = 'Constant mesh gearshift; synchromesh F-R shuttle; 8F / 8R';
const hst = 'HST - 3 ranges; infinite speeds';
const models: Seed[] = [
  { slug:'1626-hst', name:'1626 HST', hp:24.8, rpm:2500, displacementL:1.318, cylinders:3, fuelL:27, transmission:hst, maxSpeedMph:13.3, ptoType:'Live', ptoPowerHp:19, totalFlowGpm:10.8, mainFlowGpm:7.5, battery:'12 V, 540 CCA', alternator:'12 V, 50 A', lengthIn:121.3, wheelbaseIn:67.3, widthIn:63, heightIn:81.5, clearanceIn:11.4, weightLb:2459, loaderSlug:'mahindra-1626l' },
  { slug:'1626-shuttle', name:'1626 Shuttle', hp:24.8, rpm:2500, displacementL:1.318, cylinders:3, fuelL:27, transmission:shuttle, maxSpeedMph:11.4, ptoType:'Independent', ptoPowerHp:21.5, totalFlowGpm:10.8, mainFlowGpm:7.5, battery:'12 V, 540 CCA', alternator:'12 V, 50 A', lengthIn:121.3, wheelbaseIn:67.3, widthIn:63, heightIn:81.5, clearanceIn:11.4, weightLb:2437, loaderSlug:'mahindra-1626l' },
  { slug:'1635-hst', name:'1635 HST', hp:36.2, rpm:2500, displacementL:2.048, cylinders:3, fuelL:29, transmission:hst, maxSpeedMph:13.3, ptoType:'Live with overrunning clutch', ptoPowerHp:26, totalFlowGpm:10.8, mainFlowGpm:7.5, battery:'12 V, 925 CCA', alternator:'12 V, 90 A', lengthIn:123.8, wheelbaseIn:73, widthIn:64, heightIn:90.2, clearanceIn:12.2, weightLb:3086, loaderSlug:'mahindra-1635l' },
  { slug:'1635-hst-cab', name:'1635 HST Cab', hp:36.2, rpm:2500, displacementL:2.048, cylinders:3, fuelL:29, transmission:hst, maxSpeedMph:13.3, ptoType:'Live with overrunning clutch', ptoPowerHp:26, totalFlowGpm:10.8, mainFlowGpm:7.5, battery:'12 V, 925 CCA', alternator:'12 V, 90 A', lengthIn:123.8, wheelbaseIn:73, widthIn:64, heightIn:88, clearanceIn:12.2, weightLb:3527, loaderSlug:'mahindra-1635l' },
  { slug:'1635-shuttle', name:'1635 Shuttle', hp:36.2, rpm:2500, displacementL:2.048, cylinders:3, fuelL:29, transmission:shuttle, maxSpeedMph:12.2, ptoType:'Independent', ptoPowerHp:27.6, totalFlowGpm:10.8, mainFlowGpm:7.5, battery:'12 V, 925 CCA', alternator:'12 V, 90 A', lengthIn:123.8, wheelbaseIn:73, widthIn:64, heightIn:90.2, clearanceIn:12.2, weightLb:3075, loaderSlug:'mahindra-1635l' },
  { slug:'1640-hst', name:'1640 HST', hp:38.7, rpm:2400, displacementL:2.732, cylinders:4, fuelL:29, transmission:hst, maxSpeedMph:14.8, ptoType:'Live with overrunning clutch', ptoPowerHp:27.7, totalFlowGpm:11.4, mainFlowGpm:7.7, battery:'12 V, 925 CCA', alternator:'12 V, 90 A', lengthIn:127.8, wheelbaseIn:76.9, widthIn:62, heightIn:91.5, clearanceIn:12.8, weightLb:3175, loaderSlug:'mahindra-1640l' },
  { slug:'1640-hst-cab', name:'1640 HST Cab', hp:38.7, rpm:2400, displacementL:2.732, cylinders:4, fuelL:29, transmission:hst, maxSpeedMph:14.8, ptoType:'Live with overrunning clutch', ptoPowerHp:27.7, totalFlowGpm:11.4, mainFlowGpm:7.7, battery:'12 V, 925 CCA', alternator:'12 V, 90 A', lengthIn:127.8, wheelbaseIn:76.9, widthIn:62, heightIn:89.4, clearanceIn:12.8, weightLb:3627, loaderSlug:'mahindra-1640l' },
  { slug:'1640-shuttle', name:'1640 Shuttle', hp:38.7, rpm:2400, displacementL:2.732, cylinders:4, fuelL:29, transmission:shuttle, maxSpeedMph:13.6, ptoType:'Independent', ptoPowerHp:29.9, totalFlowGpm:11.4, mainFlowGpm:7.7, battery:'12 V, 925 CCA', alternator:'12 V, 90 A', lengthIn:127.8, wheelbaseIn:76.9, widthIn:62, heightIn:91.5, clearanceIn:12.8, weightLb:3186, loaderSlug:'mahindra-1640l' },
];
const loaders = [
  { slug:'mahindra-1626l', model:'1626L', height:'84 in on 1626 HST; 86 in on 1626 Shuttle', capacity:1653, fit:['1626-hst','1626-shuttle'] },
  { slug:'mahindra-1635l', model:'1635L', height:'92 in', capacity:1830, fit:['1635-hst','1635-hst-cab','1635-shuttle'] },
  { slug:'mahindra-1640l', model:'1640L', height:'92 in', capacity:1830, fit:['1640-hst','1640-hst-cab','1640-shuttle'] },
];

async function id(c: Parameters<DbMigration['apply']>[0], sql: string, params: unknown[] = []) { const [r] = await c.query<IdRow[]>(sql, params); if (!r[0]) throw new Error('Mahindra 1600 migration dependency missing'); return Number(r[0].id); }
async function put(c: Parameters<DbMigration['apply']>[0], mi:number, vi:number, di:number, sr:number, value:string|number, unit:string|null) { await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`, [mi,vi,di,typeof value==='string'?value:null,typeof value==='number'?value:null,unit,sr]); }

export const mahindra1600CurrentUsMigration: DbMigration = {
  id:'20260830_321_mahindra_1600_current_us',
  description:'Add eight current US Mahindra 1600 Series tractors, no-DPF emissions details and official loader fitment',
  async apply(c) {
    const mf = await id(c, `SELECT id FROM manufacturers WHERE slug='mahindra' LIMIT 1`); const et = await id(c, `SELECT id FROM equipment_types WHERE slug='tractor' LIMIT 1`); const sid = await id(c, `SELECT id FROM sources WHERE name='Mahindra' AND domain='mahindrausa.com' LIMIT 1`);
    await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'Mahindra 1600 Series','mahindra-1600') ON DUPLICATE KEY UPDATE name=VALUES(name)`, [mf,et]); const seriesId = await id(c, `SELECT id FROM machine_series WHERE manufacturer_id=? AND slug='mahindra-1600' LIMIT 1`, [mf]);
    const ext='mahindra-1600-current-us-2026-08'; let [rr]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[ext]); let sr=rr[0]?.id?Number(rr[0].id):0; if(!sr){const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,URL,ext,'Mahindra 1600 Series current US specifications',JSON.stringify({market:'United States',captured:'2026-08-30',models,loaders,sourcePolicy:'Detailed current specification table used when summary cards differ.',discrepancies:['1626 summary card says 25.9 HP while detailed current table says 24.8 HP.','Summary loader capacities differ from detailed loader table; detailed table values are stored.','Summary 3-point capacity is not substituted for the detailed @24 in aft value.'],emissions:'mCRD engine; no DPF and no regeneration downtime'})]);sr=Number(x.insertId)}
    const defs:Array<[string,string,string,string,string|null,number]>=[['Engine','emissions.dpf','Diesel particulate filter (DPF)','text',null,30],['Engine','emissions.regeneration','DPF regeneration','text',null,31]]; for(const row of defs) await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,row);
    const keys=['engine.power','engine.power_speed','engine.displacement','engine.cylinders','transmission.options','transmission.max_forward_speed','pto.type','pto.speeds','pto.power','hydraulics.total_flow','hydraulics.main_pump_flow','hitch.rear_max_lift_capacity','capacities.fuel_tank','electrical.battery_system','electrical.alternator','dimensions.overall_length','dimensions.wheelbase','dimensions.overall_width','dimensions.overall_height','dimensions.ground_clearance','dimensions.unladen_weight','emissions.dpf','emissions.regeneration']; const d=new Map<string,number>(); for(const key of keys)d.set(key,await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[key]));
    for(const m of models){await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current US Mahindra 1600 Series tractor','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[mf,et,seriesId,m.name,m.slug]);const mi=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mi,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States',?,TRUE,?,'Current Mahindra USA detailed specification-table record. Summary-card conflicts are not used to overwrite detailed-table values.') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mi,VERSION,m.name,sr]);const vi=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mi,VERSION]);const vals:Array<[string,string|number,string|null]>=[['engine.power',m.hp,'hp'],['engine.power_speed',m.rpm,'rpm'],['engine.displacement',m.displacementL,'L'],['engine.cylinders',m.cylinders,null],['transmission.options',m.transmission,null],['transmission.max_forward_speed',m.maxSpeedMph,'mph'],['pto.type',m.ptoType,null],['pto.speeds','Rear 540 @ 2376 rpm; Mid 2000 optional @ 2526 rpm',null],['pto.power',m.ptoPowerHp,'hp'],['hydraulics.total_flow',m.totalFlowGpm,'US gal/min'],['hydraulics.main_pump_flow',m.mainFlowGpm,'US gal/min'],['hitch.rear_max_lift_capacity',1720,'lb'],['capacities.fuel_tank',m.fuelL,'L'],['electrical.battery_system',m.battery,null],['electrical.alternator',m.alternator,null],['dimensions.overall_length',m.lengthIn,'in'],['dimensions.wheelbase',m.wheelbaseIn,'in'],['dimensions.overall_width',m.widthIn,'in'],['dimensions.overall_height',m.heightIn,'in'],['dimensions.ground_clearance',m.clearanceIn,'in'],['dimensions.unladen_weight',m.weightLb,'lb'],['emissions.dpf','No DPF',null],['emissions.regeneration','No regeneration required',null]];for(const[k,v,u]of vals)await put(c,mi,vi,d.get(k)!,sr,v,u)}
    for(const l of loaders){await c.query(`INSERT INTO attachments(manufacturer_id,attachment_type,model_name,slug,lift_capacity_text,lift_height_text,configuration_text,data_status) VALUES(?,'front-loader',?,?,?,?,?,'verified') ON DUPLICATE KEY UPDATE model_name=VALUES(model_name),lift_capacity_text=VALUES(lift_capacity_text),lift_height_text=VALUES(lift_height_text),configuration_text=VALUES(configuration_text),data_status='verified'`,[mf,l.model,l.slug,`${l.capacity} lb at pivot pin`,l.height,'Official Mahindra 1600 Series loader; digging depth 3 in']);const ai=await id(c,`SELECT id FROM attachments WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,l.slug]);for(const slug of l.fit){const mi=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,slug]);await c.query(`INSERT INTO machine_attachments(machine_id,attachment_id,compatibility_note,source_record_id,confidence) VALUES(?,?,?,?, 'official') ON DUPLICATE KEY UPDATE compatibility_note=VALUES(compatibility_note),source_record_id=VALUES(source_record_id),confidence='official'`,[mi,ai,`Official ${l.model} loader listed for ${slug} in the current Mahindra USA specification table.`,sr])}}
  },
};
