import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Seed={slug:string;model:string;hp:number;weightLb:number;liftLb:number;reach:string};
const VERSION='north-america-current-2026-09';
const URL='https://construction.newholland.com/en-us/northamerica/products/light-construction-equipment/loader-backhoes';
const models:Seed[]=[
 {slug:'b75d',model:'B75D',hp:74,weightLb:17487,liftLb:8157,reach:'22 ft 1 in (6731 mm)'},
 {slug:'b95d',model:'B95D',hp:97,weightLb:17560,liftLb:7996,reach:'20 ft 4 in (6198 mm)'},
 {slug:'b95d-tool-carrier',model:'B95D Tool Carrier',hp:97,weightLb:17703,liftLb:7606,reach:'20 ft 8 in (6286 mm)'},
 {slug:'b95d-long-reach',model:'B95D Long Reach',hp:97,weightLb:18805,liftLb:7996,reach:'22 ft 4 in (6814 mm)'},
 {slug:'b110d',model:'B110D',hp:110,weightLb:18805,liftLb:7833,reach:'22 ft 11 in (6985 mm)'},
];
const defs:Array<[string,string,string,string,string|null,number]>=[
 ['Machine Configuration','configuration.type','Machine configuration','text',null,1],['Machine Configuration','configuration.market_scope','Official market scope','text',null,2],
 ['Engine','loader_backhoe.engine_power','Gross engine power','decimal','hp',10],['Engine','loader_backhoe.engine_family','Engine family','text',null,20],['Engine','loader_backhoe.emissions','Emissions standard','text',null,30],
 ['Loader Performance','loader_backhoe.loader_lift_capacity','Loader lift capacity','decimal','lb',10],
 ['Backhoe Performance','loader_backhoe.max_backhoe_reach','Maximum backhoe reach','text',null,10],
 ['Transmission','loader_backhoe.drive','Drive configuration','text',null,10],['Transmission','loader_backhoe.transmission_options','Transmission options','text',null,20],
 ['Hydraulics','loader_backhoe.twin_gear_flow','Twin gear pump maximum flow','text',null,10],['Hydraulics','loader_backhoe.variable_flow','Variable displacement pump flow range','text',null,20],['Hydraulics','loader_backhoe.max_pressure','Maximum operating pressure','decimal','psi',30],
 ['Dimensions & Weight','loader_backhoe.operating_weight','Operating weight','decimal','lb',10],
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('New Holland loader backhoe migration dependency missing');return Number(r[0].id);}
async function source(c:Parameters<DbMigration['apply']>[0]){const[r]=await c.query<IdRow[]>(`SELECT id FROM sources WHERE name='New Holland Construction' AND domain='construction.newholland.com' ORDER BY id LIMIT 1`);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO sources(name,domain,source_type,authority_level) VALUES('New Holland Construction','construction.newholland.com','manufacturer','official')`);return Number(x.insertId);}
async function record(c:Parameters<DbMigration['apply']>[0],sid:number){const externalId='new-holland-d-series-loader-backhoes-na-current-2026-09';const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(r[0])return Number(r[0].id);const raw={captured:'2026-09-01',market:'North America / United States site',equipmentType:'Loader Backhoe',models,family:{engine:'FPT Industrial F5 3.4-liter four-cylinder',emissions:'Tier 4 Final',drive:'Switchable 2WD / 4WD',transmissions:'Mechanical PowerShuttle or automatic PowerShift',twinGearPump:'39.8 GPM (150.7 LPM) @ 2200 RPM',variableDisplacementPump:'1.5 to 41.2 GPM (5.7 to 156 LPM)',maxPressurePsi:2973}};const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,URL,externalId,'New Holland D Series loader backhoes current North America specifications',JSON.stringify(raw)]);return Number(x.insertId);}
async function put(c:Parameters<DbMigration['apply']>[0],mid:number,vid:number,did:number,rid:number,value:string|number,unit:string|null=null){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mid,vid,did,typeof value==='string'?value:null,typeof value==='number'?value:null,unit,rid]);}
export const newHollandDSeriesLoaderBackhoesCurrentMigration:DbMigration={id:'20260901_561_new_holland_d_series_loader_backhoes_current',description:'Add current New Holland North America D Series loader backhoes',async apply(c){
 await c.query(`INSERT INTO equipment_types(name,slug) VALUES('Loader Backhoe','loader-backhoe') ON DUPLICATE KEY UPDATE name=VALUES(name)`);await c.query(`INSERT INTO manufacturers(name,slug) VALUES('New Holland','new-holland') ON DUPLICATE KEY UPDATE name=VALUES(name)`);const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='new-holland' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='loader-backhoe' LIMIT 1`),sid=await source(c),rid=await record(c,sid);
 await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'D Series Loader Backhoes','d-series-loader-backhoes') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='d-series-loader-backhoes' LIMIT 1`,[mf,et]);const ids=new Map<string,number>();for(const d of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,d);ids.set(d[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[d[1]]));}const def=(k:string)=>{const v=ids.get(k);if(!v)throw new Error(`Missing New Holland loader backhoe definition ${k}`);return v;};
 for(const m of models){await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current New Holland Construction North America D Series loader backhoe; B75D product page explicitly cites agriculture and landscaping work','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[mf,et,series,m.model,m.slug]);const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND equipment_type_id=? AND slug=? LIMIT 1`,[mf,et,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mid,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'NA','North America','Current New Holland D Series family/model-table specification',TRUE,?,'Current North America D Series page captured 2026-09-01. Model-table horsepower, operating weight, loader lift capacity and max backhoe reach remain model-specific; engine, transmission and hydraulic choices are family-level D Series specifications.') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),configuration=VALUES(configuration),notes=VALUES(notes)`,[mid,VERSION,rid]);const vid=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mid,VERSION]);await put(c,mid,vid,def('configuration.type'),rid,'Loader backhoe');await put(c,mid,vid,def('configuration.market_scope'),rid,'North America / United States current catalog');await put(c,mid,vid,def('loader_backhoe.engine_power'),rid,m.hp,'hp');await put(c,mid,vid,def('loader_backhoe.engine_family'),rid,'FPT Industrial F5 3.4-liter four-cylinder');await put(c,mid,vid,def('loader_backhoe.emissions'),rid,'Tier 4 Final');await put(c,mid,vid,def('loader_backhoe.loader_lift_capacity'),rid,m.liftLb,'lb');await put(c,mid,vid,def('loader_backhoe.max_backhoe_reach'),rid,m.reach);await put(c,mid,vid,def('loader_backhoe.drive'),rid,'Switchable 2WD / 4WD');await put(c,mid,vid,def('loader_backhoe.transmission_options'),rid,'Mechanical PowerShuttle or automatic PowerShift');await put(c,mid,vid,def('loader_backhoe.twin_gear_flow'),rid,'39.8 GPM (150.7 LPM) @ 2200 RPM');await put(c,mid,vid,def('loader_backhoe.variable_flow'),rid,'1.5 to 41.2 GPM (5.7 to 156 LPM)');await put(c,mid,vid,def('loader_backhoe.max_pressure'),rid,2973,'psi');await put(c,mid,vid,def('loader_backhoe.operating_weight'),rid,m.weightLb,'lb');}
}};
