import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow = RowDataPacket & { id: number };
type Seed={slug:string;model:string;detailUrl?:string;workingWidth?:string;transportWidth?:string;standards?:number;mount?:string;wheels?:string;spacing?:string};
const VERSION='united-states-current-2026-08';
const FAMILY_URL='https://www.deere.com/en/tillage/field-cultivators/';
const models:Seed[]=[
 {slug:'mt5-minimum-till-ripper',model:'MT5'},
 {slug:'mt7-minimum-till-ripper',model:'MT7'},
 {slug:'mt9-minimum-till-ripper',model:'MT9',detailUrl:'https://www-cm-ue.deere.com/en-us/products-and-solutions/tillage-equipment/rippers/mt9-minimum-till-ripper-mzk1qug',workingWidth:'22.5 ft',transportWidth:'16.0 ft',standards:9,mount:'Integral or drawn options',wheels:'Four stabilizer wheels',spacing:'30 in'},
 {slug:'mt11-minimum-till-ripper',model:'MT11'},
];
const defs:Array<[string,string,string,string,string|null,number]>=[
 ['Machine Configuration','configuration.type','Machine configuration','text',null,1],['Machine Configuration','configuration.market_scope','Official market scope','text',null,2],
 ['Tillage System','in_line_ripper.max_depth','Maximum operating depth','text',null,10],['Tillage System','in_line_ripper.working_speed','Working speed','text',null,20],['Tillage System','in_line_ripper.residue_conditions','Residue conditions','text',null,30],['Tillage System','in_line_ripper.depth_control','Depth control','text',null,40],['Tillage System','in_line_ripper.standard_count','Number of standards','integer',null,50],['Tillage System','in_line_ripper.standard_spacing','Spacing between standards','text',null,60],['Tillage System','in_line_ripper.mount_type','Mounting configuration','text',null,70],['Tillage System','in_line_ripper.stabilizer_wheels','Stabilizer wheels','text',null,80],['Tillage System','in_line_ripper.working_width','Working width','text',null,90],
 ['Dimensions & Transport','in_line_ripper.transport_width','Transport width','text',null,10],['Tractor Requirements','in_line_ripper.hp_per_standard','Horsepower required per standard','text',null,10],['Precision Technology','in_line_ripper.precision_control','Precision tillage control','text',null,10],
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('John Deere MT migration dependency missing');return Number(r[0].id);}
async function src(c:Parameters<DbMigration['apply']>[0]){const[r]=await c.query<IdRow[]>(`SELECT id FROM sources WHERE name='John Deere' AND domain='deere.com' ORDER BY id LIMIT 1`);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO sources(name,domain,source_type,authority_level) VALUES('John Deere','deere.com','manufacturer','official')`);return Number(x.insertId);}
async function sourceRecord(c:Parameters<DbMigration['apply']>[0],sid:number,externalId:string,url:string,title:string,raw:unknown){const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,url,externalId,title,JSON.stringify(raw)]);return Number(x.insertId);}
async function familyRec(c:Parameters<DbMigration['apply']>[0],sid:number,m:Seed){return sourceRecord(c,sid,`john-deere-${m.slug}-family-us-current-2026-08`,FAMILY_URL,`John Deere ${m.model} current US minimum-till ripper comparison data`,{captured:'2026-08-31',market:'United States',equipmentType:'In-Line Ripper',manufacturerCategory:'Minimum-Till Ripper',model:m.model,source:FAMILY_URL});}
async function detailRec(c:Parameters<DbMigration['apply']>[0],sid:number,m:Seed){if(!m.detailUrl)return null;return sourceRecord(c,sid,`john-deere-${m.slug}-detail-us-current-2026-08`,m.detailUrl,`John Deere ${m.model} current US minimum-till ripper model specifications`,{captured:'2026-08-31',market:'United States',equipmentType:'In-Line Ripper',manufacturerCategory:'Minimum-Till Ripper',model:m.model,source:m.detailUrl});}
async function putText(c:Parameters<DbMigration['apply']>[0],mid:number,vid:number,did:number,rid:number,v:string){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,NULL,NULL,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=NULL,unit=NULL,source_record_id=VALUES(source_record_id),confidence='official'`,[mid,vid,did,v,rid]);}
async function putNum(c:Parameters<DbMigration['apply']>[0],mid:number,vid:number,did:number,rid:number,v:number){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,NULL,?,NULL,?,'official') ON DUPLICATE KEY UPDATE value_text=NULL,value_number=VALUES(value_number),unit=NULL,source_record_id=VALUES(source_record_id),confidence='official'`,[mid,vid,did,v,rid]);}
export const johnDeereMtMinimumTillRippersCurrentMigration:DbMigration={id:'20260831_527_john_deere_mt_minimum_till_rippers_current',description:'Add current John Deere US MT5, MT7, MT9 and MT11 minimum-till rippers',async apply(c){
 await c.query(`INSERT INTO equipment_types(name,slug) VALUES('In-Line Ripper','in-line-ripper') ON DUPLICATE KEY UPDATE name=VALUES(name)`);await c.query(`INSERT INTO manufacturers(name,slug) VALUES('John Deere','john-deere') ON DUPLICATE KEY UPDATE name=VALUES(name)`);const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='john-deere' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='in-line-ripper' LIMIT 1`),sid=await src(c);await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'MT Series Minimum-Till Rippers','mt-series-minimum-till-rippers') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='mt-series-minimum-till-rippers' LIMIT 1`,[mf,et]);const ids=new Map<string,number>();for(const d of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,d);ids.set(d[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[d[1]]));}const def=(k:string)=>{const v=ids.get(k);if(!v)throw new Error(`Missing MT definition ${k}`);return v;};
 for(const m of models){const familyRid=await familyRec(c,sid,m),detailRid=await detailRec(c,sid,m);await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current John Deere United States minimum-till ripper lineup','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes)`,[mf,et,series,m.model,m.slug]);const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND equipment_type_id=? AND slug=? LIMIT 1`,[mf,et,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mid,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States','Current MT Series minimum-till ripper specification',TRUE,?,'Current John Deere US comparison data captured 2026-08-31. MT9 includes extra model-page details from a separate current John Deere US product record. Family and individual source values are not silently merged when they differ.') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mid,VERSION,familyRid]);const vid=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mid,VERSION]);await putText(c,mid,vid,def('configuration.type'),familyRid,'Minimum-till in-line ripper');await putText(c,mid,vid,def('configuration.market_scope'),familyRid,'United States current catalog');await putText(c,mid,vid,def('in_line_ripper.max_depth'),familyRid,'Up to 16 in (40.6 cm)');await putText(c,mid,vid,def('in_line_ripper.working_speed'),familyRid,'5 - 7 mph (current US comparison table)');await putText(c,mid,vid,def('in_line_ripper.residue_conditions'),familyRid,'Medium / Heavy');await putText(c,mid,vid,def('in_line_ripper.depth_control'),familyRid,'TruSet / 3-Point Hitch');await putText(c,mid,vid,def('in_line_ripper.hp_per_standard'),familyRid,'50 - 60 hp (37 - 44 kW) per standard');await putText(c,mid,vid,def('in_line_ripper.precision_control'),familyRid,'TruSet on applicable MT configurations');if(detailRid&&m.standards)await putNum(c,mid,vid,def('in_line_ripper.standard_count'),detailRid,m.standards);if(detailRid&&m.spacing)await putText(c,mid,vid,def('in_line_ripper.standard_spacing'),detailRid,m.spacing);if(detailRid&&m.mount)await putText(c,mid,vid,def('in_line_ripper.mount_type'),detailRid,m.mount);if(detailRid&&m.wheels)await putText(c,mid,vid,def('in_line_ripper.stabilizer_wheels'),detailRid,m.wheels);if(detailRid&&m.workingWidth)await putText(c,mid,vid,def('in_line_ripper.working_width'),detailRid,m.workingWidth);if(detailRid&&m.transportWidth)await putText(c,mid,vid,def('in_line_ripper.transport_width'),detailRid,m.transportWidth);}
 }};
