import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow = RowDataPacket & { id: number };
type Seed = {
  slug:string; model:string; hp?:number; batteryKwh?:number; powertrain:'Diesel'|'Electric';
  operatingWeight:string; digDepth:string; dumpHeight:string; sourceNote?:string;
};

const VERSION='north-america-current-2026-09';
const URL='https://construction.newholland.com/en-us/northamerica/products/light-construction-equipment/mini-excavators';
const models:Seed[]=[
  {slug:'e12d',model:'E12D',hp:11.8,powertrain:'Diesel',operatingWeight:'Cab / Canopy: - / 2,932 lb (1,330 kg)',digDepth:'Std / Long Arm: 6 ft 1 in (1860 mm) / 6 ft 6 in (1980 mm)',dumpHeight:'Std / Long Arm: 7 ft (2130 mm) / 7 ft 3 in (2215 mm)',sourceNote:'Family card labels the 11.8 hp field Gross Capacity; stored neutrally as published engine power.'},
  {slug:'e15x',model:'E15X',batteryKwh:21.5,powertrain:'Electric',operatingWeight:'Cab / Canopy: - / 3,194 lb (1,449 kg)',digDepth:'Std / Long Arm: 6 ft 7 in (2045 mm) / 7 ft 1 in (2175 mm)',dumpHeight:'Std / Long Arm: 7 ft 5 in (2290 mm) / 7 ft 8 in (2380 mm)',sourceNote:'Technical card publishes 21.5 kWh gross capacity; product prose elsewhere says 21.4 gross capacity. The structured card value is retained.'},
  {slug:'e17c',model:'E17C',hp:16.8,powertrain:'Diesel',operatingWeight:'Cab / Canopy: - / 3,910 lb (1,775 kg)',digDepth:'Std / Long Arm: 7 ft 3 in (2200 mm) / 7 ft 9 in (2350 mm)',dumpHeight:'Std / Long Arm: 8 ft 5 in (2570 mm) / 8 ft 10 in (2670 mm)'},
  {slug:'e19d',model:'E19D',hp:18.4,powertrain:'Diesel',operatingWeight:'Cab / Canopy: - / 4,145 lb (1,880 kg)',digDepth:'Std / Long Arm: 7 ft 6 in (2280 mm) / 8 ft 2 in (2480 mm)',dumpHeight:'Std / Long Arm: 8 ft 6 in (2580 mm) / 8 ft 10 in (2700 mm)'},
  {slug:'e25x',model:'E25X',batteryKwh:32.3,powertrain:'Electric',operatingWeight:'Cab / Canopy: 5,445 lb (2,470 kg) / 5,159 lb (2,340 kg)',digDepth:'Std / Long Arm: 8 ft 5 in (2560 mm) / 9 ft 1 in (2760 mm)',dumpHeight:'Std / Long Arm: 8 ft 8 in (2650 mm) / 9 ft 1 in (2760 mm)',sourceNote:'Technical card publishes 32.3 kWh gross capacity; product prose also references a 25 kWh battery. The structured gross-capacity value is retained.'},
  {slug:'e26c',model:'E26C',hp:24.8,powertrain:'Diesel',operatingWeight:'Cab / Canopy: 5,850 lb (2,655 kg) / 5,520 lb (2,505 kg)',digDepth:'Std / Long Arm: 7 ft 11 in (2420 mm) / 8 ft 8 in (2645 mm)',dumpHeight:'Std / Long Arm: 9 ft 7 in (2930 mm) / 9 ft 11 in (3030 mm)'},
  {slug:'e30c',model:'E30C',hp:24.8,powertrain:'Diesel',operatingWeight:'Cab / Canopy: 6,922 lb (3,140 kg) / 6,592 lb (2,990 kg)',digDepth:'Std / Long Arm: 8 ft 2 in (2489 mm) / not published',dumpHeight:'Std / Long Arm: 9 ft 7 in (2930 mm) / not published'},
  {slug:'e30d',model:'E30D',hp:24.4,powertrain:'Diesel',operatingWeight:'Cab / Canopy: 7,143 lb (3,240 kg) / 6,658 lb (3,020 kg)',digDepth:'Std / Long Arm: 8 ft 8 in (2640 mm) / 9 ft 3 in (2830 mm)',dumpHeight:'Std / Long Arm: 10 ft 2 in (3110 mm) / 10 ft 8 in (3240 mm)'},
  {slug:'e37c',model:'E37C',hp:24.4,powertrain:'Diesel',operatingWeight:'Cab / Canopy: 8,300 lb (3,765 kg) / 7,990 lb (3,625 kg)',digDepth:'Std / Long Arm: 10 ft 3 in (3135 mm) / 11 ft 3 in (3440 mm)',dumpHeight:'Std / Long Arm: 11 ft 3 in (3425 mm) / 11 ft 10 in (3615 mm)'},
  {slug:'e38d',model:'E38D',hp:24.4,powertrain:'Diesel',operatingWeight:'Cab / Canopy: 8,620 lb (3,910 kg) / 8,333 lb (3,780 kg)',digDepth:'Std / Long Arm: 10 ft 1 in (3070 mm) / 10 ft 11 in (3320 mm)',dumpHeight:'Std / Long Arm: 10 ft 7 in (3230 mm) / 11 ft 1 in (3380 mm)'},
  {slug:'e42d',model:'E42D',hp:43.3,powertrain:'Diesel',operatingWeight:'Cab / Canopy: 9,590 lb (4,350 kg) / 9,259 lb (4,200 kg)',digDepth:'Std / Long Arm: 10 ft 1 in (3085 mm) / 10 ft 11 in (3335 mm)',dumpHeight:'Std / Long Arm: 12 ft (3660 mm) / 12 ft 6 in (3820 mm)'},
  {slug:'e50d',model:'E50D',hp:58.7,powertrain:'Diesel',operatingWeight:'Cab / Canopy: 10,912 lb (4,950 kg) / -',digDepth:'Std / Long Arm: 10 ft 11 in (3330 mm) / 11 ft 9 in (3580 mm)',dumpHeight:'Std / Long Arm: 12 ft 10 in (3920 mm) / 13 ft 5 in (4080 mm)'},
  {slug:'e57c',model:'E57C',hp:66.9,powertrain:'Diesel',operatingWeight:'Cab / Canopy: 12,050 lb (5,465 kg) / -',digDepth:'Std / Long Arm: 12 ft 6 in (3820 mm) / 13 ft 4 in (4060 mm)',dumpHeight:'Std / Long Arm: 13 ft 3 in (4050 mm) / 13 ft 9 in (4180 mm)'},
  {slug:'e60c',model:'E60C',hp:64.7,powertrain:'Diesel',operatingWeight:'Cab / Canopy: 12,940 lb (5,870 kg) / -',digDepth:'Std / Long Arm: 11 ft 9 in (3570 mm) / 13 ft 1 in (3990 mm)',dumpHeight:'Std / Long Arm: 12 ft 11 in (3930 mm) / 13 ft 5 in (4100 mm)'},
  {slug:'e60d',model:'E60D',hp:59.4,powertrain:'Diesel',operatingWeight:'Cab / Canopy: 13,162 lb (5,970 kg) / -',digDepth:'Std / Long Arm: 12 ft 8 in (3850 mm) / 13 ft 5 in (4100 mm)',dumpHeight:'Std / Long Arm: 13 ft 5 in (4090 mm) / 13 ft 11 in (4240 mm)'},
];

const defs:Array<[string,string,string,string,string|null,number]>=[
  ['Machine Configuration','configuration.type','Machine configuration','text',null,1],
  ['Machine Configuration','configuration.market_scope','Official market scope','text',null,2],
  ['Machine Configuration','mini_excavator.powertrain','Powertrain','text',null,3],
  ['Engine','mini_excavator.engine_power','Published horsepower','decimal','hp',10],
  ['Electrical','mini_excavator.battery_capacity','Battery capacity','decimal','kWh',10],
  ['Excavator Performance','mini_excavator.dig_depth_configurations','Maximum digging depth configurations','text',null,10],
  ['Excavator Performance','mini_excavator.dump_height_configurations','Maximum dump height configurations','text',null,20],
  ['Excavator Performance','mini_excavator.source_note','Source interpretation note','text',null,30],
  ['Dimensions & Weight','mini_excavator.operating_weight_configurations','Operating weight configurations','text',null,10],
];

async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('New Holland mini excavator migration dependency missing');return Number(r[0].id);}
async function source(c:Parameters<DbMigration['apply']>[0]){const[r]=await c.query<IdRow[]>(`SELECT id FROM sources WHERE name='New Holland Construction' AND domain='construction.newholland.com' ORDER BY id LIMIT 1`);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO sources(name,domain,source_type,authority_level) VALUES('New Holland Construction','construction.newholland.com','manufacturer','official')`);return Number(x.insertId);}
async function record(c:Parameters<DbMigration['apply']>[0],sid:number){const externalId='new-holland-mini-excavators-na-current-2026-09';const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,URL,externalId,'New Holland mini excavators current North America model table',JSON.stringify({captured:'2026-09-01',market:'North America / United States site',equipmentType:'Mini Excavator',models,notes:'Current family technical cards publish power or gross battery capacity, cab/canopy operating weight pairs, and standard/long-arm digging and dump-height pairs. Structured card values are retained where individual marketing prose differs.'})]);return Number(x.insertId);}
async function put(c:Parameters<DbMigration['apply']>[0],mid:number,vid:number,did:number,rid:number,value:string|number,unit:string|null=null){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mid,vid,did,typeof value==='string'?value:null,typeof value==='number'?value:null,unit,rid]);}

export const newHollandMiniExcavatorsCurrentMigration:DbMigration={
  id:'20260901_559_new_holland_mini_excavators_current',
  description:'Add current New Holland North America mini excavators with configuration-pair specs',
  async apply(c){
    await c.query(`INSERT INTO equipment_types(name,slug) VALUES('Mini Excavator','mini-excavator') ON DUPLICATE KEY UPDATE name=VALUES(name)`);
    await c.query(`INSERT INTO manufacturers(name,slug) VALUES('New Holland','new-holland') ON DUPLICATE KEY UPDATE name=VALUES(name)`);
    const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='new-holland' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='mini-excavator' LIMIT 1`),sid=await source(c),rid=await record(c,sid);
    await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'New Holland Mini Excavators','new-holland-mini-excavators') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);
    const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='new-holland-mini-excavators' LIMIT 1`,[mf,et]);
    const ids=new Map<string,number>();for(const d of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,d);ids.set(d[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[d[1]]));}const def=(k:string)=>{const v=ids.get(k);if(!v)throw new Error(`Missing New Holland mini excavator definition ${k}`);return v;};
    for(const m of models){await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current New Holland Construction North America mini excavator; family technical-card configuration pairs preserved','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[mf,et,series,m.model,m.slug]);const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND equipment_type_id=? AND slug=? LIMIT 1`,[mf,et,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mid,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'NA','North America','Current New Holland family technical-card model with published cab/canopy and arm-option pairs',TRUE,?,'Current North America family table captured 2026-09-01. Cab/canopy and standard/long-arm values stay paired in source form rather than being blended into one false configuration.') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),configuration=VALUES(configuration),notes=VALUES(notes)`,[mid,VERSION,rid]);const vid=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mid,VERSION]);await put(c,mid,vid,def('configuration.type'),rid,'Mini excavator');await put(c,mid,vid,def('configuration.market_scope'),rid,'North America / United States current catalog');await put(c,mid,vid,def('mini_excavator.powertrain'),rid,m.powertrain);if(m.hp!==undefined)await put(c,mid,vid,def('mini_excavator.engine_power'),rid,m.hp,'hp');if(m.batteryKwh!==undefined)await put(c,mid,vid,def('mini_excavator.battery_capacity'),rid,m.batteryKwh,'kWh');await put(c,mid,vid,def('mini_excavator.operating_weight_configurations'),rid,m.operatingWeight);await put(c,mid,vid,def('mini_excavator.dig_depth_configurations'),rid,m.digDepth);await put(c,mid,vid,def('mini_excavator.dump_height_configurations'),rid,m.dumpHeight);if(m.sourceNote)await put(c,mid,vid,def('mini_excavator.source_note'),rid,m.sourceNote);}
  },
};
