import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Seed={slug:string;name:string;rated:number;dp:number};
const VERSION='united-states-current-2026-08';
const TECH_URL='https://api.fendt.com/techdata/US/en/1465241/Fendt%20600%20Vario';
const PRODUCT_URL='https://www.fendt.com/us/products/tractors/fendt-600-vario';
const models:Seed[]=[
{slug:'614-vario',name:'614 Vario',rated:149,dp:164},
{slug:'616-vario',name:'616 Vario',rated:169,dp:184},
{slug:'618-vario',name:'618 Vario',rated:189,dp:204},
{slug:'620-vario',name:'620 Vario',rated:209,dp:224},
];
async function id(c:Parameters<DbMigration['apply']>[0],q:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(q,p);if(!r[0])throw Error('Fendt 600 dependency missing');return Number(r[0].id)}
async function source(c:Parameters<DbMigration['apply']>[0],sid:number,ext:string,url:string,title:string,raw:unknown){const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[ext]);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,url,ext,title,JSON.stringify(raw)]);return Number(x.insertId)}
async function put(c:Parameters<DbMigration['apply']>[0],mi:number,vi:number,di:number,sr:number,v:string|number,u:string|null){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mi,vi,di,typeof v==='string'?v:null,typeof v==='number'?v:null,u,sr])}
export const fendt600VarioCurrentUsMigration:DbMigration={id:'20260829_311_fendt_600_vario_current_us',description:'Add four current US Fendt 600 Vario models with official US technical data',async apply(c){
const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='fendt' LIMIT 1`);const et=await id(c,`SELECT id FROM equipment_types WHERE slug='tractor' LIMIT 1`);const sid=await id(c,`SELECT id FROM sources WHERE name='Fendt' AND domain='fendt.com' LIMIT 1`);await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'Fendt 600 Vario','fendt-600-vario') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const si=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND slug='fendt-600-vario' LIMIT 1`,[mf]);const tech=await source(c,sid,'fendt-600-vario-tech-current-us-2026-08',TECH_URL,'Fendt US 600 Vario official technical data',{market:'US',captured:'2026-08-29',models,displacementL:5.017,emissions:'SCR + DPF',transmission:'TA 150'});const product=await source(c,sid,'fendt-600-vario-product-current-us-2026-08',PRODUCT_URL,'Fendt US 600 Vario current product page',{hydraulicFlowGpm:[40.2,54.2],engine:'AGCO Power CORE50',drivetrain:'VarioDrive'});
const defs=[['Engine','engine.make','Engine manufacturer','text',null,1],['Engine','engine.displacement','Engine displacement','decimal','L',2],['Engine','engine.rated_power','Rated engine power','decimal','hp',4],['Engine','engine.maximum_power','Maximum engine power','decimal','hp',5],['Engine','engine.dynamic_performance_power','Maximum power with DynamicPerformance','decimal','hp',6],['Engine','emissions.aftertreatment','Exhaust aftertreatment','text',null,20],['Transmission','transmission.options','Transmission / drivetrain','text',null,10],['Hydraulics','hydraulics.main_pump_max_flow','Maximum hydraulic flow','decimal','US gal/min',10]] as const;const d=new Map<string,number>();for(const x of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,x);d.set(x[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[x[1]]))}
for(const m of models){await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current US Fendt 600 Vario tractor','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[mf,et,si,m.name,m.slug]);const mi=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mi,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States','Current Fendt 600 Vario',TRUE,?,'Current US Fendt record using the official US technical-data endpoint and current product page.') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mi,VERSION,tech]);const vi=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mi,VERSION]);const vals:Array<[string,string|number,string|null,number]>=[['engine.make','AGCO Power CORE50',null,product],['engine.displacement',5.017,'L',tech],['engine.rated_power',m.rated,'hp',tech],['engine.maximum_power',m.rated,'hp',tech],['engine.dynamic_performance_power',m.dp,'hp',tech],['emissions.aftertreatment','SCR + DPF',null,tech],['transmission.options','Fendt VarioDrive / TA 150',null,tech],['hydraulics.main_pump_max_flow',54.2,'US gal/min',product]];for(const [k,v,u,sr] of vals)await put(c,mi,vi,d.get(k)!,sr,v,u)}
}};
