import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';
type IdRow=RowDataPacket&{id:number};
type Model={slug:string;name:string;hp:number;pto?:number;transmission:string;url:string;externalId:string};
const models:Model[]=[
 {slug:'farmall-90c',name:'Farmall Utility 90C',hp:90,transmission:'12x12 Power or 24x24 Hi-Lo',url:'https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-utility-series/farmall-medium-utility-c-series/farmall-medium-utility-90c',externalId:'case-ih-farmall-90c-current-us'},
 {slug:'farmall-100c',name:'Farmall Utility 100C',hp:101,pto:85,transmission:'12x12 Power or 24x24 Hi-Lo',url:'https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-utility-series/farmall-medium-utility-c-series/farmall-medium-utility-100c',externalId:'case-ih-farmall-100c-current-us'},
 {slug:'farmall-110c',name:'Farmall Utility 110C',hp:110,pto:93,transmission:'12x12 Power or 24x24 Hi-Lo',url:'https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-medium-utility-c-series/farmall-medium-utility-110c',externalId:'case-ih-farmall-110c-current-us'},
 {slug:'farmall-120c',name:'Farmall Utility 120C',hp:117,pto:100,transmission:'12x12 Power or 24x24 Hi-Lo',url:'https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-utility-series/farmall-medium-utility-c-series/farmall-medium-utility-120c',externalId:'case-ih-farmall-120c-current-us'}];
const defs=[['Engine','engine.rated_power','Engine horsepower','decimal','hp',3],['PTO','pto.rated_power','PTO power','decimal','hp',10],['Machine Configuration','configuration.station','Operator station','text',null,1],['Machine Configuration','configuration.drive','Drive configuration','text',null,2],['Transmission','transmission.options','Transmission options','text',null,10]] as const;
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const [r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw Error('Missing Farmall Medium Utility C dependency');return Number(r[0].id)}
async function source(c:Parameters<DbMigration['apply']>[0],sid:number,m:Model){const [r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[m.externalId]);if(r[0])return Number(r[0].id);const [x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title) VALUES(?,?,?,?)`,[sid,m.url,m.externalId,`Case IH US ${m.name} official current specifications`]);return Number(x.insertId)}
export const caseIHFarmallMediumUtilityCCurrentSpecsMigration:DbMigration={id:'20260828_243_case_ih_farmall_medium_utility_c_current_specs',description:'Add current US Case IH Farmall Medium Utility C 90C/100C/110C/120C specs',async apply(c){await c.query(`INSERT INTO equipment_types(name,slug) VALUES('Tractor','tractor') ON DUPLICATE KEY UPDATE name=VALUES(name)`);await c.query(`INSERT INTO manufacturers(name,slug) VALUES('Case IH','case-ih') ON DUPLICATE KEY UPDATE name=VALUES(name)`);const mid=await id(c,`SELECT id FROM manufacturers WHERE slug='case-ih' LIMIT 1`),tid=await id(c,`SELECT id FROM equipment_types WHERE slug='tractor' LIMIT 1`);await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'Farmall Medium Utility C Series','farmall-medium-utility-c-series') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mid,tid]);const sidSeries=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='farmall-medium-utility-c-series' LIMIT 1`,[mid,tid]);let [sr]=await c.query<IdRow[]>(`SELECT id FROM sources WHERE name='Case IH' AND domain='caseih.com' LIMIT 1`);let sourceId=sr[0]?.id?Number(sr[0].id):0;if(!sourceId){const [x]=await c.query<ResultSetHeader>(`INSERT INTO sources(name,domain,source_type,authority_level) VALUES('Case IH','caseih.com','manufacturer','official')`);sourceId=Number(x.insertId)}
 const did=new Map<string,number>();for(const [section,key,label,type,unit,ord] of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,[section,key,label,type,unit,ord]);did.set(key,await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[key]))}
 for(const m of models){const srid=await source(c,sourceId,m);await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current US Case IH Farmall Medium Utility C tractor','partial') ON DUPLICATE KEY UPDATE model_name=VALUES(model_name),series_id=VALUES(series_id),data_status=IF(data_status='verified','verified','partial')`,[mid,tid,sidSeries,m.name,m.slug]);const machineId=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND equipment_type_id=? AND slug=? LIMIT 1`,[mid,tid,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>'united-states-current-2026-08'`,[machineId]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,'united-states-current-2026-08','US','United States','Current Farmall Medium Utility C - utility tractor',TRUE,?,'Current Case IH US product page data.') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[machineId,srid]);const vid=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug='united-states-current-2026-08' LIMIT 1`,[machineId]);const vals:[string,string|number,null|string][]=[['engine.rated_power',m.hp,'hp'],['configuration.station','Cab',null],['configuration.drive','MFD',null],['transmission.options',m.transmission,null]];if(m.pto!==undefined)vals.push(['pto.rated_power',m.pto,'hp']);for(const [key,v,u] of vals)await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[machineId,vid,did.get(key),typeof v==='string'?v:null,typeof v==='number'?v:null,u,srid])}
 }};
