import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Model={slug:string;model:string;grossHp:number;ptoHp:number};
const SOURCE_URL='https://agriculture.newholland.com/en-us/nar/products/tractors-telehandlers/workmaster-utility-50-70-series';
const EXTERNAL_ID='new-holland-workmaster-50-70-current-us-2026-08';
const VERSION='united-states-current-2026-08';
const models:Model[]=[
 {slug:'workmaster-50',model:'WORKMASTER 50',grossHp:53,ptoHp:45},
 {slug:'workmaster-60',model:'WORKMASTER 60',grossHp:60,ptoHp:51},
 {slug:'workmaster-70',model:'WORKMASTER 70',grossHp:70,ptoHp:62},
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('New Holland WORKMASTER 50-70 dependency missing');return Number(r[0].id)}
export const newHollandWorkmaster5070CurrentSpecsMigration:DbMigration={id:'20260828_273_new_holland_workmaster_50_70_current_specs',description:'Add current official US New Holland WORKMASTER 50/60/70 utility tractors',async apply(c){
 const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='new-holland' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='tractor' LIMIT 1`),sid=await id(c,`SELECT id FROM sources WHERE name='New Holland' AND domain='agriculture.newholland.com' LIMIT 1`);
 const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[EXTERNAL_ID]);let sr=r[0]?.id?Number(r[0].id):0;if(!sr){const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title) VALUES(?,?,?,'New Holland US WORKMASTER Utility 50-70 current specifications')`,[sid,SOURCE_URL,EXTERNAL_ID]);sr=Number(x.insertId)}
 await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'WORKMASTER Utility 50-70 Series','workmaster-utility-50-70-series') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='workmaster-utility-50-70-series' LIMIT 1`,[mf,et]);
 const defs:Array<[string,string,string,string,string|null,number]>=[['Machine Configuration','configuration.drive','Drive configuration','text',null,2],['Engine','engine.gross_power','Gross engine power','decimal','hp',10],['Engine','engine.aspiration','Aspiration / fuel system','text',null,40],['Engine','engine.emissions','Emissions','text',null,50],['Transmission','transmission.standard','Standard transmission','text',null,10],['PTO','pto.rated_power','PTO power','decimal','hp',10]];for(const d of defs)await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,d);
 for(const m of models){await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current US New Holland WORKMASTER utility tractor','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes)`,[mf,et,series,m.model,m.slug]);const mi=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mi,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States','WORKMASTER Utility 50-70',TRUE,?,'Official New Holland North America current data captured August 2026.') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mi,VERSION,sr]);const vi=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mi,VERSION]);const vals:Array<[string,string|number,string|null]>=[['configuration.drive','2WD or 4WD',null],['engine.gross_power',m.grossHp,'hp'],['engine.aspiration','Turbocharged, direct-injected common-rail diesel',null],['engine.emissions','Tier 4B Final',null],['transmission.standard','8x8 synchronized shuttle',null],['pto.rated_power',m.ptoHp,'hp']];for(const[k,v,u]of vals){const di=await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[k]);await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mi,vi,di,typeof v==='string'?v:null,typeof v==='number'?v:null,u,sr])}}
}};