import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type ModelSeed={slug:string;model:string;ratedHp:number;ptoHp:number;station:string;drive:string;url:string;externalId:string;notes?:string};
const FAMILY_URL='https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-100a-series';
const FAMILY_EXTERNAL_ID='case-ih-farmall-large-utility-100a-pro-current-us-110-140-2026-08';
const VERSION_SLUG='united-states-current-2026-08';
const models:ModelSeed[]=[
  {slug:'farmall-110a-pro',model:'Farmall 110A Pro',ratedHp:110,ptoHp:92,station:'Cab',drive:'MFD',url:'https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-100a-series/farmall-110a',externalId:'case-ih-farmall-110a-pro-current-us',notes:'The current US product page marketing sentence says 90 PTO HP, while its structured PTO specification tile publishes 92 PTO HP. This record retains the structured specification value of 92 PTO HP and documents the conflict.'},
  {slug:'farmall-120a-pro',model:'Farmall 120A Pro',ratedHp:120,ptoHp:102,station:'Non-cab or Cab',drive:'MFD',url:'https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-100a-series/farmall-120a',externalId:'case-ih-farmall-120a-pro-current-us'},
  {slug:'farmall-130a-pro',model:'Farmall 130A Pro',ratedHp:130,ptoHp:112,station:'Cab',drive:'2WD or MFD',url:'https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-100a-series/farmall-130a',externalId:'case-ih-farmall-130a-pro-current-us'},
  {slug:'farmall-140a-pro',model:'Farmall 140A Pro',ratedHp:140,ptoHp:118,station:'Cab or Non-cab',drive:'2WD (Cab Only) or MFD',url:'https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-100a-series/farmall-140a',externalId:'case-ih-farmall-140a-pro-current-us'},
];
const definitions=[
  ['Machine Configuration','configuration.station','Operator station','text',null,1],['Machine Configuration','configuration.drive','Drive configuration','text',null,2],
  ['Engine','engine.make','Engine manufacturer','text',null,1],['Engine','engine.displacement','Engine displacement','decimal','L',2],['Engine','engine.rated_power','Engine horsepower','decimal','hp',3],
  ['PTO','pto.rated_power','PTO power','decimal','hp',10],['Transmission','transmission.options','Transmission options','text',null,10],['Hydraulics','hydraulics.main_pump_max_flow','Hydraulic flow capacity','decimal','US gal/min',10],['Hydraulics','hitch.rear_max_lift_capacity','Rear 3-point hitch lift capacity','decimal','lb',20],
] as const;
async function selectId(connection:Parameters<DbMigration['apply']>[0],sql:string,params:unknown[]=[]){const [rows]=await connection.query<IdRow[]>(sql,params);if(!rows[0])throw new Error('Missing Case IH Farmall 100A Pro migration dependency.');return Number(rows[0].id);}
async function ensureSource(connection:Parameters<DbMigration['apply']>[0],sourceId:number,externalId:string,url:string,title:string){const [rows]=await connection.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(rows[0])return Number(rows[0].id);const [result]=await connection.query<ResultSetHeader>(`INSERT INTO source_records (source_id,url,external_id,title) VALUES (?,?,?,?)`,[sourceId,url,externalId,title]);return Number(result.insertId);}
async function upsertSpec(connection:Parameters<DbMigration['apply']>[0],machineId:number,versionId:number,definitionId:number,sourceRecordId:number,value:string|number,unit:string|null=null){await connection.query(`INSERT INTO machine_specs (machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES (?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[machineId,versionId,definitionId,typeof value==='string'?value:null,typeof value==='number'?value:null,unit,sourceRecordId]);}

export const caseIHFarmall100AProCurrentSpecsMigration:DbMigration={
  id:'20260828_237_case_ih_farmall_100a_pro_current_specs',
  description:'Add current US Case IH Farmall Large Utility 100A Pro 110A/120A/130A/140A official engine, PTO, transmission, hydraulic and hitch data',
  async apply(connection){
    await connection.query(`INSERT INTO equipment_types (name,slug) VALUES ('Tractor','tractor') ON DUPLICATE KEY UPDATE name=VALUES(name)`);
    await connection.query(`INSERT INTO manufacturers (name,slug) VALUES ('Case IH','case-ih') ON DUPLICATE KEY UPDATE name=VALUES(name)`);
    const manufacturerId=await selectId(connection,`SELECT id FROM manufacturers WHERE slug='case-ih' LIMIT 1`);const equipmentTypeId=await selectId(connection,`SELECT id FROM equipment_types WHERE slug='tractor' LIMIT 1`);
    await connection.query(`INSERT INTO machine_series (manufacturer_id,equipment_type_id,name,slug) VALUES (?,?,'Farmall Large Utility 100A Pro Series','farmall-large-utility-100a-pro-series') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[manufacturerId,equipmentTypeId]);const seriesId=await selectId(connection,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='farmall-large-utility-100a-pro-series' LIMIT 1`,[manufacturerId,equipmentTypeId]);
    let [sourceRows]=await connection.query<IdRow[]>(`SELECT id FROM sources WHERE name='Case IH' AND domain='caseih.com' ORDER BY id LIMIT 1`);let sourceId=sourceRows[0]?.id?Number(sourceRows[0].id):0;if(!sourceId){const [result]=await connection.query<ResultSetHeader>(`INSERT INTO sources (name,domain,source_type,authority_level) VALUES ('Case IH','caseih.com','manufacturer','official')`);sourceId=Number(result.insertId);}
    const familyId=await ensureSource(connection,sourceId,FAMILY_EXTERNAL_ID,FAMILY_URL,'Case IH US current Farmall Large Utility 100A Pro Series family specifications');
    const definitionIds=new Map<string,number>();for(const [section,key,label,valueType,canonicalUnit,displayOrder] of definitions){await connection.query(`INSERT INTO spec_definitions (section,spec_key,label,value_type,canonical_unit,display_order) VALUES (?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,[section,key,label,valueType,canonicalUnit,displayOrder]);definitionIds.set(key,await selectId(connection,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[key]));}const def=(key:string)=>{const id=definitionIds.get(key);if(!id)throw new Error(`Missing Farmall 100A Pro spec ${key}`);return id;};
    for(const model of models){const modelSourceId=await ensureSource(connection,sourceId,model.externalId,model.url,`Case IH US ${model.model} official current product specifications`);await connection.query(`INSERT INTO machines (manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES (?,?,?,?,?,'Current US Case IH Farmall Large Utility 100A Pro tractor','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[manufacturerId,equipmentTypeId,seriesId,model.model,model.slug]);const machineId=await selectId(connection,`SELECT id FROM machines WHERE manufacturer_id=? AND equipment_type_id=? AND slug=? LIMIT 1`,[manufacturerId,equipmentTypeId,model.slug]);await connection.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[machineId,VERSION_SLUG]);const notes=model.notes||'Current engine and PTO power, operator station, traction and transmission values are from the individual Case IH US product page. Family-level engine displacement, hydraulic flow and rear hitch capacity are from the current US Farmall Large Utility 100A Pro family page.';await connection.query(`INSERT INTO machine_versions (machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES (?,?,'US','United States',?,TRUE,?,?) ON DUPLICATE KEY UPDATE market_code='US',market_name='United States',configuration=VALUES(configuration),is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[machineId,VERSION_SLUG,`${model.station}; ${model.drive}`,modelSourceId,notes]);const versionId=await selectId(connection,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[machineId,VERSION_SLUG]);const values:Array<[string,string|number,string|null,number]>=[['configuration.station',model.station,null,modelSourceId],['configuration.drive',model.drive,null,modelSourceId],['engine.make','FPT Industrial',null,familyId],['engine.displacement',4.5,'L',familyId],['engine.rated_power',model.ratedHp,'hp',modelSourceId],['pto.rated_power',model.ptoHp,'hp',modelSourceId],['transmission.options','8x8 or 16x8 Power Shuttle',null,modelSourceId],['hydraulics.main_pump_max_flow',22,'US gal/min',familyId],['hitch.rear_max_lift_capacity',7200,'lb',familyId]];for(const [key,value,unit,recordId] of values)await upsertSpec(connection,machineId,versionId,def(key),recordId,value,unit);}
  }
};
