import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Seed={slug:string;model:string;hp?:number;batteryKwh?:number;weightLb:number;boom:'Standard'|'Telescopic Reach';powertrain:'Diesel'|'Electric'};
const VERSION='north-america-current-2026-08';
const URL='https://www.casece.com/en-us/northamerica/products/small-articulated-loaders';
const models:Seed[]=[
 {slug:'sl12',model:'SL12',hp:25,weightLb:2425,boom:'Standard',powertrain:'Diesel'},
 {slug:'sl12-tr',model:'SL12 TR',hp:25,weightLb:2646,boom:'Telescopic Reach',powertrain:'Diesel'},
 {slug:'sl15',model:'SL15',hp:26,weightLb:3362,boom:'Standard',powertrain:'Diesel'},
 {slug:'sl22ev',model:'SL22EV',batteryKwh:24.9,weightLb:4850,boom:'Standard',powertrain:'Electric'},
 {slug:'sl23',model:'SL23',hp:26,weightLb:5181,boom:'Standard',powertrain:'Diesel'},
 {slug:'sl27',model:'SL27',hp:50,weightLb:5732,boom:'Standard',powertrain:'Diesel'},
 {slug:'sl27-tr',model:'SL27 TR',hp:50,weightLb:5940,boom:'Telescopic Reach',powertrain:'Diesel'},
 {slug:'sl35-tr',model:'SL35 TR',hp:65,weightLb:8818,boom:'Telescopic Reach',powertrain:'Diesel'},
 {slug:'sl50-tr',model:'SL50 TR',hp:74,weightLb:11464,boom:'Telescopic Reach',powertrain:'Diesel'},
];
const defs:Array<[string,string,string,string,string|null,number]>=[
 ['Machine Configuration','configuration.type','Machine configuration','text',null,1],['Machine Configuration','configuration.market_scope','Official market scope','text',null,2],['Machine Configuration','case.brand_context','Brand context','text',null,3],
 ['Engine','small_articulated_loader.engine_power','Published horsepower','decimal','hp',10],['Electrical','small_articulated_loader.battery_capacity','Battery capacity','decimal','kWh',10],
 ['Loader Performance','small_articulated_loader.boom_configuration','Boom configuration','text',null,10],['Loader Performance','small_articulated_loader.powertrain','Powertrain','text',null,20],['Dimensions & Weight','small_articulated_loader.operating_weight','Operating weight','decimal','lb',10],
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('CASE small articulated loader migration dependency missing');return Number(r[0].id);}
async function source(c:Parameters<DbMigration['apply']>[0]){const[r]=await c.query<IdRow[]>(`SELECT id FROM sources WHERE name='CASE Construction Equipment' AND domain='casece.com' ORDER BY id LIMIT 1`);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO sources(name,domain,source_type,authority_level) VALUES('CASE Construction Equipment','casece.com','manufacturer','official')`);return Number(x.insertId);}
async function record(c:Parameters<DbMigration['apply']>[0],sid:number){const externalId='case-small-articulated-loaders-na-current-2026-08';const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,URL,externalId,'CASE small articulated loaders current North America model table',JSON.stringify({captured:'2026-08-31',market:'North America',equipmentType:'Small Articulated Loader',models})]);return Number(x.insertId);}
async function put(c:Parameters<DbMigration['apply']>[0],mid:number,vid:number,did:number,rid:number,value:string|number,unit:string|null=null){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mid,vid,did,typeof value==='string'?value:null,typeof value==='number'?value:null,unit,rid]);}
export const caseSmallArticulatedLoadersCurrentMigration:DbMigration={id:'20260831_540_case_small_articulated_loaders_current',description:'Add current CASE North America small articulated loaders',async apply(c){
 await c.query(`INSERT INTO equipment_types(name,slug) VALUES('Small Articulated Loader','small-articulated-loader') ON DUPLICATE KEY UPDATE name=VALUES(name)`);await c.query(`INSERT INTO manufacturers(name,slug) VALUES('CASE','case') ON DUPLICATE KEY UPDATE name=VALUES(name)`);const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='case' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='small-articulated-loader' LIMIT 1`),sid=await source(c),rid=await record(c,sid);
 await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'CASE Small Articulated Loaders','case-small-articulated-loaders') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='case-small-articulated-loaders' LIMIT 1`,[mf,et]);const ids=new Map<string,number>();for(const d of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,d);ids.set(d[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[d[1]]));}const def=(k:string)=>{const v=ids.get(k);if(!v)throw new Error(`Missing CASE SAL definition ${k}`);return v;};
 for(const m of models){await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current CASE North America small articulated loader lineup; CASE agriculture positioning supports farm and ranch material-handling use','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[mf,et,series,m.model,m.slug]);const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND equipment_type_id=? AND slug=? LIMIT 1`,[mf,et,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mid,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'NA','North America','Current CASE small articulated loader family-table specification',TRUE,?,'Current CASE North America model table captured 2026-08-31. TR variants remain separate telescopic-reach models; SL22EV uses battery capacity without invented horsepower.') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mid,VERSION,rid]);const vid=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mid,VERSION]);await put(c,mid,vid,def('configuration.type'),rid,'Small articulated loader');await put(c,mid,vid,def('configuration.market_scope'),rid,'North America current catalog');await put(c,mid,vid,def('case.brand_context'),rid,'CASE Construction Equipment');await put(c,mid,vid,def('small_articulated_loader.boom_configuration'),rid,m.boom);await put(c,mid,vid,def('small_articulated_loader.powertrain'),rid,m.powertrain);await put(c,mid,vid,def('small_articulated_loader.operating_weight'),rid,m.weightLb,'lb');if(m.hp)await put(c,mid,vid,def('small_articulated_loader.engine_power'),rid,m.hp,'hp');if(m.batteryKwh)await put(c,mid,vid,def('small_articulated_loader.battery_capacity'),rid,m.batteryKwh,'kWh');}
}};
