import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Seed={slug:string;name:string;hp:number;engine:string;transmission:string;configuration:string;weight:string;capacity:string;bed:string;conflict:string|null};
const VERSION='north-america-current-2026-08';
const PAGE='https://www.antoniocarraro.it/na/catalogue/tigrecar-5800';
const models:Seed[]=[
 {slug:'tigrecar-5800-pc',name:'Tigrecar 5800 PC',hp:51.5,engine:'Yanmar Stage 5 common-rail direct-injection diesel; 4 cylinders; 16 valves; 2,091 cc',transmission:'8 forward + 8 reverse mechanical gearbox with reversing shuttle',configuration:'Steering transporter; PC loading-bed configuration; 4-wheel drive; synchronized 540 PTO',weight:'2,190 kg published machine weight; 4,500 kg published full-loaded value',capacity:'4,500 kg published capacity',bed:'PC loading bed',conflict:null},
 {slug:'tigrecar-5800-pl',name:'Tigrecar 5800 PL',hp:51.5,engine:'Yanmar Stage 5 common-rail direct-injection diesel; 4 cylinders; 16 valves; 2,091 cc',transmission:'16-speed mechanical gearbox; 8 forward + 8 reverse',configuration:'Steering transporter; PL loading-bed configuration; 4-wheel drive; synchronized 540 PTO',weight:'1,970 kg published base/loading-bed value; page states up to 4,500 kg with PL loading bed',capacity:'4,500 kg published capacity',bed:'PL loading bed',conflict:null},
 {slug:'tigrecar-6800-pc',name:'Tigrecar 6800 PC',hp:66,engine:'Yanmar common-rail direct-injection turbo/intercooled diesel; 4 cylinders; 16 valves; Stage 5',transmission:'8 forward + 8 reverse mechanical gearbox with reversing shuttle',configuration:'Steering transporter; PC loading-bed configuration; 4-wheel drive; synchronized 540 PTO',weight:'1,970 kg published base/loading-bed value; page states up to 4,500 kg with PC loading bed',capacity:'4,500 kg published capacity',bed:'PC loading bed',conflict:'The general Tigrecar narrative describes the family as using a 4-cylinder 50 hp Yanmar engine, but the explicit current technical selector lists 6800 PC at 66 HP. The model-specific technical selector is primary.'},
 {slug:'tigrecar-6800-pl',name:'Tigrecar 6800 PL',hp:66,engine:'Yanmar common-rail direct-injection turbo/intercooled diesel; 4 cylinders; 16 valves; Stage 5',transmission:'8 forward + 8 reverse mechanical gearbox with reversing shuttle',configuration:'Steering transporter; PL loading-bed configuration; 4-wheel drive; synchronized 540 PTO',weight:'1,970 kg published base/loading-bed value; page states up to 4,500 kg with PL loading bed',capacity:'4,500 kg published capacity',bed:'PL loading bed',conflict:'The general Tigrecar narrative describes the family as using a 4-cylinder 50 hp Yanmar engine, but the explicit current technical selector lists 6800 PL at 66 HP. The model-specific technical selector is primary.'},
];
const defs:Array<[string,string,string,string,string|null,number]>=[
 ['Machine Configuration','configuration.type','Machine configuration','text',null,1],
 ['Machine Configuration','configuration.market_scope','Official market scope','text',null,2],
 ['Machine Configuration','configuration.loading_bed','Loading bed','text',null,3],
 ['Engine','engine.description','Engine description','text',null,2],
 ['Engine','engine.gross_power','Engine power','decimal','hp',8],
 ['Transmission','transmission.standard','Transmission','text',null,10],
 ['PTO','pto.rear_description','PTO configuration','text',null,20],
 ['Dimensions & Weight','dimensions.published_weight','Published weight','text',null,70],
 ['Capacities','capacities.payload_published','Published payload / capacity','text',null,80]
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('Antonio Carraro Tigrecar migration dependency missing');return Number(r[0].id)}
async function source(c:Parameters<DbMigration['apply']>[0],sid:number,m:Seed){const eid=`antonio-carraro-${m.slug}-na-current-2026-08`;const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[eid]);if(r[0])return Number(r[0].id);const raw={market:'North America',captured:'2026-08-31',equipmentType:'Transporter',model:m.name,hp:m.hp,engine:m.engine,transmission:m.transmission,configuration:m.configuration,publishedWeight:m.weight,publishedCapacity:m.capacity,loadingBed:m.bed,conflict:m.conflict,classificationPolicy:'Antonio Carraro explicitly calls Tigrecar a steering transporter. It is stored as equipment type Transporter, not Tractor. Model-specific technical selector values outrank generic family narrative.'};const[i]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,PAGE,eid,`Antonio Carraro ${m.name} current North America transporter specifications`,JSON.stringify(raw)]);return Number(i.insertId)}
async function put(c:Parameters<DbMigration['apply']>[0],mid:number,vid:number,did:number,srid:number,v:string|number,u:string|null){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mid,vid,did,typeof v==='string'?v:null,typeof v==='number'?v:null,u,srid])}
export const antonioCarraroTigrecarNaCurrentMigration:DbMigration={id:'20260831_479_antonio_carraro_tigrecar_na_current',description:'Add four current Antonio Carraro North America Tigrecar steering transporter variants as Transporter equipment',async apply(c){
 await c.query(`INSERT INTO equipment_types(name,slug) VALUES('Transporter','transporter') ON DUPLICATE KEY UPDATE name=VALUES(name)`);
 const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='antonio-carraro' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='transporter' LIMIT 1`),sid=await id(c,`SELECT id FROM sources WHERE name='Antonio Carraro' AND domain='antoniocarraro.it' LIMIT 1`);
 await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'Tigrecar','tigrecar') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);
 const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='tigrecar' LIMIT 1`,[mf,et]);
 const d=new Map<string,number>();for(const row of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,row);d.set(row[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[row[1]]))}
 for(const m of models){const sr=await source(c,sid,m);await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current Antonio Carraro North America Tigrecar steering transporter','partial') ON DUPLICATE KEY UPDATE equipment_type_id=VALUES(equipment_type_id),series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[mf,et,series,m.name,m.slug]);const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND equipment_type_id=? AND slug=? LIMIT 1`,[mf,et,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mid,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'NA','North America',?,TRUE,?,'Current Antonio Carraro North America Tigrecar transporter listing captured 2026-08-31.') ON DUPLICATE KEY UPDATE configuration=VALUES(configuration),is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mid,VERSION,m.configuration,sr]);const vid=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mid,VERSION]);const vals:Array<[string,string|number,string|null]>=[['configuration.type',m.configuration,null],['configuration.market_scope','North America',null],['configuration.loading_bed',m.bed,null],['engine.description',m.engine,null],['engine.gross_power',m.hp,'hp'],['transmission.standard',m.transmission,null],['pto.rear_description','Synchronized 540 PTO',null],['dimensions.published_weight',m.weight,null],['capacities.payload_published',m.capacity,null]];for(const[k,v,u]of vals){const did=d.get(k);if(!did)throw new Error(`Missing Antonio Carraro Tigrecar spec ${k}`);await put(c,mid,vid,did,sr,v,u)}}
}};
