import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow = RowDataPacket & { id: number };
type Seed = {
  slug: string; name: string; url: string; station: 'ROPS' | 'Cab'; engineModel: string; powerHp: number; displacementL: number;
  rpm?: number; aspiration?: string; fuelL: number; transmission: string; ptoPowerHp: number; ptoSpeeds?: string; pumpGpm: number;
  hydraulicLiftLb: number; hitchLiftLb?: number; lengthIn: number; widthIn: number; heightIn: number; wheelbaseIn?: number;
  clearanceIn: number; turningRadiusFt: number; weightLb: number; note?: string;
};

const VERSION = 'united-states-current-2026-08';
const LINEUP_URL = 'https://www.kioti.com/products/tractors/cs';
const models: Seed[] = [
  { slug:'cs2210h',name:'CS2210H',url:'https://www.kioti.com/products/tractors/cs/cs2210',station:'ROPS',engineModel:'3C100LWH-U3',powerHp:21,displacementL:1.007,fuelL:25.5,transmission:'Hydrostatic',ptoPowerHp:16.3,ptoSpeeds:'Rear 540 rpm; mid 2,200 rpm',pumpGpm:6.5,hydraulicLiftLb:700,hitchLiftLb:700,lengthIn:99.3,widthIn:46.7,heightIn:88,clearanceIn:6.4,turningRadiusFt:8.2,weightLb:1485 },
  { slug:'cs2510h',name:'CS2510H',url:'https://www.kioti.com/products/tractors/cs/cs2510',station:'ROPS',engineModel:'3C100LFH-U2',powerHp:24.5,displacementL:1.007,rpm:3000,fuelL:25.5,transmission:'Hydrostatic',ptoPowerHp:18.5,ptoSpeeds:'Rear 540 rpm; mid 2,200 rpm',pumpGpm:6.5,hydraulicLiftLb:700,lengthIn:99.3,widthIn:46.7,heightIn:88,wheelbaseIn:55.1,clearanceIn:6.4,turningRadiusFt:8.2,weightLb:1485,note:'The current US page has a malformed Hitch Lift Capacity cell (318 lb / 700 kg). That hitch value is omitted; the separately labeled hydraulic lift capacity of 700 lb / 318 kg is retained.' },
  { slug:'cs2220h',name:'CS2220H',url:'https://www.kioti.com/products/tractors/cs/cs2220',station:'ROPS',engineModel:'3C100LWH-U3',powerHp:21,displacementL:1.007,fuelL:25.5,transmission:'Hydrostatic',ptoPowerHp:16.3,ptoSpeeds:'Rear 540 rpm; mid 2,200 rpm',pumpGpm:7,hydraulicLiftLb:700,hitchLiftLb:700,lengthIn:99.3,widthIn:45.9,heightIn:88,wheelbaseIn:55.1,clearanceIn:6.4,turningRadiusFt:8.2,weightLb:1554 },
  { slug:'cs2520h',name:'CS2520H',url:'https://www.kioti.com/products/tractors/cs/cs2520',station:'ROPS',engineModel:'3C100LFH-U2',powerHp:24.5,displacementL:1.007,rpm:3000,fuelL:25.5,transmission:'Hydrostatic',ptoPowerHp:18.5,ptoSpeeds:'Rear 540 rpm; mid 2,200 rpm',pumpGpm:7,hydraulicLiftLb:700,hitchLiftLb:700,lengthIn:99.3,widthIn:45.9,heightIn:88,wheelbaseIn:55.1,clearanceIn:6.4,turningRadiusFt:8.2,weightLb:1554 },
  { slug:'cs2230h',name:'CS2230H',url:'https://www.kioti.com/products/tractors/cs/cs2230h',station:'ROPS',engineModel:'3L123',powerHp:21,displacementL:1.233,aspiration:'Intercooler',fuelL:25.5,transmission:'Hydrostatic; 2-range',ptoPowerHp:16.7,pumpGpm:7,hydraulicLiftLb:700,hitchLiftLb:700,lengthIn:88.6,widthIn:48.8,heightIn:87.6,wheelbaseIn:55.1,clearanceIn:6.4,turningRadiusFt:8.333,weightLb:1735 },
  { slug:'cs2530h',name:'CS2530H',url:'https://www.kioti.com/products/tractors/cs/cs2530h',station:'ROPS',engineModel:'3L123',powerHp:24.5,displacementL:1.233,aspiration:'Intercooler',fuelL:25.5,transmission:'Hydrostatic; 2-range',ptoPowerHp:19.3,pumpGpm:7,hydraulicLiftLb:700,hitchLiftLb:700,lengthIn:88.6,widthIn:48.8,heightIn:87.6,wheelbaseIn:55.1,clearanceIn:6.4,turningRadiusFt:8.333,weightLb:1735 },
  { slug:'cs2530h-cab',name:'CS2530H Cab',url:'https://www.kioti.com/products/tractors/cs/cs2530c',station:'Cab',engineModel:'3L123',powerHp:24.5,displacementL:1.233,aspiration:'Intercooler',fuelL:25.5,transmission:'Hydrostatic; 2-range',ptoPowerHp:19.3,ptoSpeeds:'Rear 540 rpm; mid 2,200 rpm',pumpGpm:7,hydraulicLiftLb:700,hitchLiftLb:700,lengthIn:102.9,widthIn:48.3,heightIn:82.6,clearanceIn:6.4,turningRadiusFt:8.2,weightLb:2233.3 },
];

const defs: Array<[string,string,string,string,string|null,number]> = [
 ['Machine Configuration','configuration.station','Operator station','text',null,1],['Engine','engine.model','Engine model','text',null,1],['Engine','engine.make','Engine manufacturer','text',null,2],['Engine','engine.power','Engine power','decimal','hp',4],['Engine','engine.displacement','Engine displacement','decimal','L',6],['Engine','engine.power_speed','Engine speed at published power','integer','rpm',8],['Engine','engine.aspiration','Aspiration','text',null,10],['Transmission','transmission.options','Transmission','text',null,10],['PTO','pto.type','PTO type','text',null,5],['PTO','pto.power','PTO power','decimal','hp',10],['PTO','pto.speeds','PTO speeds','text',null,20],['Hydraulics','hydraulics.main_pump_flow','Hydraulic pump capacity','decimal','US gal/min',10],['Hydraulics','hydraulics.lift_capacity','Hydraulics lift capacity','decimal','lb',20],['Hydraulics','hitch.rear_max_lift_capacity','Hitch lift capacity','decimal','lb',25],['Capacities','capacities.fuel_tank','Fuel tank capacity','decimal','L',10],['Dimensions & Weight','dimensions.overall_length','Length with hitch','decimal','in',10],['Dimensions & Weight','dimensions.overall_width','Overall width','decimal','in',20],['Dimensions & Weight','dimensions.overall_height','Overall height','decimal','in',30],['Dimensions & Weight','dimensions.wheelbase','Wheelbase','decimal','in',40],['Dimensions & Weight','dimensions.ground_clearance','Ground clearance','decimal','in',50],['Dimensions & Weight','dimensions.turning_radius','Turning radius','decimal','ft',60],['Dimensions & Weight','dimensions.unladen_weight','Tractor weight','decimal','lb',70]
];
async function id(c:Parameters<DbMigration['apply']>[0],q:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(q,p);if(!r[0])throw Error('KIOTI CS migration dependency missing');return Number(r[0].id)}
async function source(c:Parameters<DbMigration['apply']>[0],sid:number,ext:string,url:string,title:string,raw:unknown){const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[ext]);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,url,ext,title,JSON.stringify(raw)]);return Number(x.insertId)}
async function put(c:Parameters<DbMigration['apply']>[0],mi:number,vi:number,di:number,sr:number,v:string|number,u:string|null){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mi,vi,di,typeof v==='string'?v:null,typeof v==='number'?v:null,u,sr])}

export const kiotiCsCurrentUsMigration:DbMigration={id:'20260830_332_kioti_cs_current_us',description:'Add seven current US KIOTI CS Series sub-compact tractor configurations from official US model pages',async apply(c){
 const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='kioti' LIMIT 1`);const et=await id(c,`SELECT id FROM equipment_types WHERE slug='tractor' LIMIT 1`);const sid=await id(c,`SELECT id FROM sources WHERE name='KIOTI' AND domain='kioti.com' LIMIT 1`);
 await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'KIOTI CS Series','kioti-cs') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND slug='kioti-cs' LIMIT 1`,[mf]);
 await source(c,sid,'kioti-cs-current-us-lineup-2026-08',LINEUP_URL,'KIOTI US current CS Series lineup',{market:'United States',captured:'2026-08-30',models:models.map(m=>m.name)});
 const d=new Map<string,number>();for(const row of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),display_order=VALUES(display_order)`,row);d.set(row[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[row[1]]))}
 for(const m of models){const sr=await source(c,sid,`kioti-${m.slug}-current-us-2026-08`,m.url,`KIOTI US ${m.name} current specifications`,{market:'United States',captured:'2026-08-30',model:m,note:m.note||null});await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current US KIOTI CS sub-compact tractor','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[mf,et,series,m.name,m.slug]);const mi=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mi,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States',?,TRUE,?,?) ON DUPLICATE KEY UPDATE configuration=VALUES(configuration),is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mi,VERSION,`${m.station}; ${m.transmission}`,sr,m.note||'Current KIOTI US model-specific specification record.']);const vi=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mi,VERSION]);const vals:Array<[string,string|number|undefined,string|null]>=[['configuration.station',m.station,null],['engine.model',m.engineModel,null],['engine.make','KIOTI',null],['engine.power',m.powerHp,'hp'],['engine.displacement',m.displacementL,'L'],['engine.power_speed',m.rpm,'rpm'],['engine.aspiration',m.aspiration,null],['transmission.options',m.transmission,null],['pto.type','Independent',null],['pto.power',m.ptoPowerHp,'hp'],['pto.speeds',m.ptoSpeeds,null],['hydraulics.main_pump_flow',m.pumpGpm,'US gal/min'],['hydraulics.lift_capacity',m.hydraulicLiftLb,'lb'],['hitch.rear_max_lift_capacity',m.hitchLiftLb,'lb'],['capacities.fuel_tank',m.fuelL,'L'],['dimensions.overall_length',m.lengthIn,'in'],['dimensions.overall_width',m.widthIn,'in'],['dimensions.overall_height',m.heightIn,'in'],['dimensions.wheelbase',m.wheelbaseIn,'in'],['dimensions.ground_clearance',m.clearanceIn,'in'],['dimensions.turning_radius',m.turningRadiusFt,'ft'],['dimensions.unladen_weight',m.weightLb,'lb']];for(const[k,v,u]of vals){if(v===undefined)continue;await put(c,mi,vi,d.get(k)!,sr,v,u)}}
}};
