import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Seed={slug:string;model:string;url:string;series:string;frame:string;rows:string;width:string;transport?:string;rowUnit:string;conditioning:string;precision:string};
const VERSION='united-states-current-2026-08';
const models:Seed[]=[
 {slug:'nutri-tiller-955',model:'Nutri-Tiller 955',series:'Nutri-Tiller 955',url:'https://www.caseih.com/en-us/unitedstates/products/tillage/strip-till/nutri-tiller-955',frame:'Pull-Type',rows:'8, 12, 16, or 24 rows',width:'20 - 60 ft (6 - 18.3 m)',rowUnit:'24-in front coulter with High-clearance Shank for Strip-Till (HCS ST)',conditioning:'Berm Build’r with Berm Condition’r basket options',precision:'AccuGuide guidance and variable-rate application support; Pro 700 integration described for blockage monitoring'},
 {slug:'nutri-tiller-1010',model:'Nutri-Tiller 1010',series:'Nutri-Tiller 1000',url:'https://www.caseih.com/en-us/unitedstates/products/tillage/nutri-tiller-1000/nutri-tiller-1010',frame:'Rigid Mount',rows:'6 rows',width:'15 ft',transport:'14 ft 3 in',rowUnit:'Shank or coulter strip-till row-unit options; 12 in total vertical row-unit travel on 1000 Series',conditioning:'Basket or Spider Berm Condition’r options',precision:'ISOBUS compatible with in-cab residue-manager, down-pressure and berm-conditioner control; FieldOps guidance-line workflow'},
 {slug:'nutri-tiller-1030',model:'Nutri-Tiller 1030',series:'Nutri-Tiller 1000',url:'https://www.caseih.com/en-us/unitedstates/products/tillage/nutri-tiller-1000/nutri-tiller-1030',frame:'Folding-mounted toolbar',rows:'8, 12, or 16 rows',width:'20 - 40 ft',transport:'12 ft 4 in - 20 ft 2 in',rowUnit:'Shank, coulter, or knife-coulter strip-till options; 12 in total vertical row-unit travel on 1000 Series',conditioning:'Basket or Spider Berm Condition’r options',precision:'ISOBUS compatible with in-cab residue-manager, down-pressure and berm-conditioner control; FieldOps guidance-line workflow'},
];
const defs:Array<[string,string,string,string,string|null,number]>=[
 ['Machine Configuration','configuration.type','Machine configuration','text',null,1],['Machine Configuration','configuration.market_scope','Official market scope','text',null,2],
 ['Strip-Till System','strip_till.frame_style','Frame style','text',null,10],['Strip-Till System','strip_till.rows','Row configurations','text',null,20],['Strip-Till System','strip_till.operating_width','Operating width','text',null,30],['Strip-Till System','strip_till.row_unit','Row unit and tillage system','text',null,40],['Strip-Till System','strip_till.berm_conditioning','Berm conditioning','text',null,50],
 ['Dimensions & Transport','strip_till.transport_width','Transport width','text',null,10],['Precision Technology','strip_till.precision_control','Precision and implement control','text',null,10],
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('Case IH Nutri-Tiller migration dependency missing');return Number(r[0].id);}
async function src(c:Parameters<DbMigration['apply']>[0]){const[r]=await c.query<IdRow[]>(`SELECT id FROM sources WHERE name='Case IH' AND domain='caseih.com' ORDER BY id LIMIT 1`);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO sources(name,domain,source_type,authority_level) VALUES('Case IH','caseih.com','manufacturer','official')`);return Number(x.insertId);}
async function rec(c:Parameters<DbMigration['apply']>[0],sid:number,m:Seed){const externalId=`case-ih-${m.slug}-strip-till-us-current-2026-08`;const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,m.url,externalId,`Case IH ${m.model} current US strip-till specifications`,JSON.stringify({captured:'2026-08-31',market:'United States',equipmentType:'Strip-Till',...m})]);return Number(x.insertId);}
async function put(c:Parameters<DbMigration['apply']>[0],mid:number,vid:number,did:number,rid:number,v:string){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,NULL,NULL,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=NULL,unit=NULL,source_record_id=VALUES(source_record_id),confidence='official'`,[mid,vid,did,v,rid]);}
export const caseIhNutriTillerStripTillCurrentMigration:DbMigration={id:'20260831_525_case_ih_nutri_tiller_strip_till_current',description:'Add current Case IH US Nutri-Tiller strip-till models',async apply(c){
 await c.query(`INSERT INTO equipment_types(name,slug) VALUES('Strip-Till','strip-till') ON DUPLICATE KEY UPDATE name=VALUES(name)`);await c.query(`INSERT INTO manufacturers(name,slug) VALUES('Case IH','case-ih') ON DUPLICATE KEY UPDATE name=VALUES(name)`);const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='case-ih' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='strip-till' LIMIT 1`),sid=await src(c);const ids=new Map<string,number>();for(const d of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,d);ids.set(d[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[d[1]]));}const def=(k:string)=>{const v=ids.get(k);if(!v)throw new Error(`Missing strip-till definition ${k}`);return v;};
 for(const m of models){const seriesSlug=m.series.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et,m.series,seriesSlug]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug=? LIMIT 1`,[mf,et,seriesSlug]);const rid=await rec(c,sid,m);await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current Case IH United States strip-till lineup','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes)`,[mf,et,series,m.model,m.slug]);const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND equipment_type_id=? AND slug=? LIMIT 1`,[mf,et,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mid,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States','Current Nutri-Tiller strip-till specification',TRUE,?,'Current Case IH US product and family-page data captured 2026-08-31. The 955 manufacturer page contains an inconsistent metric annotation for its 24-in coulter; this record preserves the unambiguous inch value only.') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mid,VERSION,rid]);const vid=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mid,VERSION]);await put(c,mid,vid,def('configuration.type'),rid,'Strip-till implement');await put(c,mid,vid,def('configuration.market_scope'),rid,'United States current catalog');await put(c,mid,vid,def('strip_till.frame_style'),rid,m.frame);await put(c,mid,vid,def('strip_till.rows'),rid,m.rows);await put(c,mid,vid,def('strip_till.operating_width'),rid,m.width);await put(c,mid,vid,def('strip_till.row_unit'),rid,m.rowUnit);await put(c,mid,vid,def('strip_till.berm_conditioning'),rid,m.conditioning);if(m.transport)await put(c,mid,vid,def('strip_till.transport_width'),rid,m.transport);await put(c,mid,vid,def('strip_till.precision_control'),rid,m.precision);}
 }};
