import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Seed={slug:string;name:string;rated:number;max:number;dp?:number};
const VERSION='united-states-current-2026-08';
const PRODUCT_URL='https://www.fendt.com/us/products/tractors/fendt-300-vario';
const TECH_URL='https://api.fendt.com/techdata/US/en/1153013';
const BROCHURE_URL='https://www.fendt.com/us/geneva-assets/widget/14292/734954-734954-fendt-300-vario-brochure-v2.pdf';
const models:Seed[]=[
{slug:'311-vario-gen4',name:'311 Vario Gen4',rated:100,max:113},
{slug:'312-vario-gen4',name:'312 Vario Gen4',rated:113,max:123},
{slug:'313-vario-gen4',name:'313 Vario Gen4',rated:123,max:133},
{slug:'314-vario-gen4',name:'314 Vario Gen4',rated:132,max:142,dp:152},
];
async function id(c:Parameters<DbMigration['apply']>[0],q:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(q,p);if(!r[0])throw Error('Fendt 300 Gen4 dependency missing');return Number(r[0].id)}
async function source(c:Parameters<DbMigration['apply']>[0],sid:number,ext:string,url:string,title:string,raw:unknown){const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[ext]);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,url,ext,title,JSON.stringify(raw)]);return Number(x.insertId)}
async function put(c:Parameters<DbMigration['apply']>[0],mi:number,vi:number,di:number,sr:number,v:string|number,u:string|null){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mi,vi,di,typeof v==='string'?v:null,typeof v==='number'?v:null,u,sr])}
export const fendt300VarioGen4CurrentUsMigration:DbMigration={id:'20260829_313_fendt_300_vario_gen4_current_us',description:'Add four current US Fendt 300 Vario Gen4 models with official product, technical and emissions data',async apply(c){
const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='fendt' LIMIT 1`);const et=await id(c,`SELECT id FROM equipment_types WHERE slug='tractor' LIMIT 1`);const sid=await id(c,`SELECT id FROM sources WHERE name='Fendt' AND domain='fendt.com' LIMIT 1`);await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'Fendt 300 Vario Gen4','fendt-300-vario-gen4') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const si=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND slug='fendt-300-vario-gen4' LIMIT 1`,[mf]);const product=await source(c,sid,'fendt-300-vario-gen4-product-current-us-2026-08',PRODUCT_URL,'Fendt US 300 Vario current product page',{market:'United States',captured:'2026-08-29',models,transmission:'Vario CVT'});const tech=await source(c,sid,'fendt-300-vario-gen4-tech-current-us-2026-08',TECH_URL,'Fendt US 300 Vario Gen4 official technical data',{market:'United States',captured:'2026-08-29',displacementL:4.4,transmission:'ML 75',pto:'540/540E/1000',hydraulicFlowLMin:110});const brochure=await source(c,sid,'fendt-300-vario-gen4-us-brochure-emissions-2026-08',BROCHURE_URL,'Fendt US 300 Vario Series brochure emissions and specifications',{market:'United States',emissions:'Tier 4 Final',aftertreatment:'SCR + DOC + passive DPF',activeRegeneration:false,cylinders:4});
const defs=[['Engine','engine.make','Engine manufacturer','text',null,1],['Engine','engine.displacement','Engine displacement','decimal','L',2],['Engine','engine.cylinders','Engine cylinders','integer',null,3],['Engine','engine.rated_power','Rated engine power','decimal','hp',4],['Engine','engine.maximum_power','Maximum engine power','decimal','hp',5],['Engine','engine.dynamic_performance_power','Maximum power with DynamicPerformance','decimal','hp',6],['Engine','engine.emissions','Emissions standard','text',null,20],['Engine','emissions.aftertreatment','Aftertreatment system','text',null,21],['Engine','emissions.dpf','Diesel particulate filter (DPF)','text',null,22],['Engine','emissions.regeneration','DPF regeneration','text',null,23],['Transmission','transmission.options','Transmission / drivetrain','text',null,10],['PTO','pto.speeds','PTO speeds','text',null,10],['Hydraulics','hydraulics.main_pump_max_flow','Maximum hydraulic flow','decimal','US gal/min',10]] as const;const d=new Map<string,number>();for(const x of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,[...x]);d.set(x[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[x[1]]))}
for(const m of models){await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current US Fendt 300 Vario Gen4 tractor','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[mf,et,si,m.name,m.slug]);const mi=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mi,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States','Current Fendt 300 Vario Gen4',TRUE,?,'Current US Fendt 300 Vario Gen4 record using official US product, technical-data and brochure sources. No data is inherited from later Gen5 records.') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mi,VERSION,tech]);const vi=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mi,VERSION]);const vals:Array<[string,string|number,string|null,number]>=[['engine.make','AGCO Power',null,brochure],['engine.displacement',4.4,'L',tech],['engine.cylinders',4,null,brochure],['engine.rated_power',m.rated,'hp',tech],['engine.maximum_power',m.max,'hp',tech],['engine.emissions','Tier 4 Final',null,brochure],['emissions.aftertreatment','SCR + DOC + passive DPF',null,brochure],['emissions.dpf','Passive DPF installed',null,brochure],['emissions.regeneration','No active DPF regeneration',null,brochure],['transmission.options','Fendt Vario CVT / ML 75',null,product],['pto.speeds','540 / 540E / 1000 rpm',null,tech],['hydraulics.main_pump_max_flow',29.1,'US gal/min',tech]];if(m.dp!==undefined)vals.push(['engine.dynamic_performance_power',m.dp,'hp',product]);for(const[k,v,u,sr]of vals)await put(c,mi,vi,d.get(k)!,sr,v,u)}
}};
