import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Seed={
  slug:string; model:string; engineModel:string; grossHp:number;
  weightCanopyLb:number; weightCabLb:number; bucketBreakoutLbf:number; bucketCapacityYd3:number;
  tippingStraightBucketCanopy:number; tippingStraightBucketCab:number;
  tippingStraightForksCanopy:number; tippingStraightForksCab:number;
  tippingFullBucketCanopy:number; tippingFullBucketCab:number;
  tippingFullForksCanopy:number; tippingFullForksCab:number;
  rocBucketCanopy:number; rocBucketCab:number; rocForksCanopy:number; rocForksCab:number;
  dumpClearance:string; hingePinHeight:string; reachRaised:string; auxFlowGpm:number; tractionForceLb:number;
};

const VERSION='united-states-current-2026-09';
const URL='https://www.kubotausa.com/docs/default-source/brochure-sheets/full-product-line-brochure-2026.pdf';
const CURRENT_URL='https://www.kubotausa.com/construction';
const models:Seed[]=[
 {slug:'r430',model:'R430',engineModel:'D1803-CR-TIE4-WL5',grossHp:47.6,weightCanopyLb:7749,weightCabLb:8223,bucketBreakoutLbf:5215,bucketCapacityYd3:0.5,tippingStraightBucketCanopy:5335,tippingStraightBucketCab:5743,tippingStraightForksCanopy:3494,tippingStraightForksCab:3770,tippingFullBucketCanopy:4596,tippingFullBucketCab:4949,tippingFullForksCanopy:3009,tippingFullForksCab:3251,rocBucketCanopy:1504,rocBucketCab:1625,rocForksCanopy:2298,rocForksCab:2474,dumpClearance:`7' 2"`,hingePinHeight:`9' 2"`,reachRaised:`2' 10"`,auxFlowGpm:11.2,tractionForceLb:5485},
 {slug:'r540',model:'R540',engineModel:'V2607-CR-E5-WL',grossHp:50.9,weightCanopyLb:9888,weightCabLb:10285,bucketBreakoutLbf:8183,bucketCapacityYd3:0.85,tippingStraightBucketCanopy:6437,tippingStraightBucketCab:6768,tippingStraightForksCanopy:4960,tippingStraightForksCab:5202,tippingFullBucketCanopy:5644,tippingFullBucketCab:5930,tippingFullForksCanopy:4365,tippingFullForksCab:4586,rocBucketCanopy:2822,rocBucketCab:2965,rocForksCanopy:2183,rocForksCab:2293,dumpClearance:`8' 0"`,hingePinHeight:`10' 7"`,reachRaised:`2' 7"`,auxFlowGpm:14.2,tractionForceLb:6541},
 {slug:'r640',model:'R640',engineModel:'V2607-CR-TE5-WL',grossHp:64.3,weightCanopyLb:11177,weightCabLb:11563,bucketBreakoutLbf:9869,bucketCapacityYd3:1.0,tippingStraightBucketCanopy:7542,tippingStraightBucketCab:7760,tippingStraightForksCanopy:5820,tippingStraightForksCab:6063,tippingFullBucketCanopy:6526,tippingFullBucketCab:6812,tippingFullForksCanopy:5115,tippingFullForksCab:5313,rocBucketCanopy:3263,rocBucketCab:3345,rocForksCanopy:2558,rocForksCab:2657,dumpClearance:`7' 9"`,hingePinHeight:`10' 8"`,reachRaised:`2' 9"`,auxFlowGpm:17.8,tractionForceLb:8588},
];

const defs:Array<[string,string,string,string,string|null,number]>=[
 ['Machine Configuration','configuration.type','Machine configuration','text',null,1],['Machine Configuration','configuration.market_scope','Official market scope','text',null,2],
 ['Engine','kubota.wheel_loader.engine_model','Engine model','text',null,10],['Engine','kubota.wheel_loader.gross_power','Gross engine power','decimal','hp',20],
 ['Loader Performance','kubota.wheel_loader.bucket_breakout','Bucket breakout force','decimal','lbf',10],['Loader Performance','kubota.wheel_loader.boom_linkage','Loader boom linkage','text',null,20],['Loader Performance','kubota.wheel_loader.bucket_capacity','Standard bucket capacity','decimal','cu yd',30],
 ['Loader Performance','kubota.wheel_loader.tipping_straight_bucket_canopy','Tipping load straight with bucket, canopy','decimal','lb',40],['Loader Performance','kubota.wheel_loader.tipping_straight_bucket_cab','Tipping load straight with bucket, cab','decimal','lb',41],['Loader Performance','kubota.wheel_loader.tipping_straight_forks_canopy','Tipping load straight with pallet forks, canopy','decimal','lb',42],['Loader Performance','kubota.wheel_loader.tipping_straight_forks_cab','Tipping load straight with pallet forks, cab','decimal','lb',43],
 ['Loader Performance','kubota.wheel_loader.tipping_full_bucket_canopy','Tipping load full turn with bucket, canopy','decimal','lb',44],['Loader Performance','kubota.wheel_loader.tipping_full_bucket_cab','Tipping load full turn with bucket, cab','decimal','lb',45],['Loader Performance','kubota.wheel_loader.tipping_full_forks_canopy','Tipping load full turn with pallet forks, canopy','decimal','lb',46],['Loader Performance','kubota.wheel_loader.tipping_full_forks_cab','Tipping load full turn with pallet forks, cab','decimal','lb',47],
 ['Loader Performance','kubota.wheel_loader.roc_bucket_canopy','Rated operating capacity with bucket, canopy (SAE 50%)','decimal','lb',50],['Loader Performance','kubota.wheel_loader.roc_bucket_cab','Rated operating capacity with bucket, cab (SAE 50%)','decimal','lb',51],['Loader Performance','kubota.wheel_loader.roc_forks_canopy','Rated operating capacity with pallet forks, canopy','decimal','lb',52],['Loader Performance','kubota.wheel_loader.roc_forks_cab','Rated operating capacity with pallet forks, cab','decimal','lb',53],
 ['Loader Performance','kubota.wheel_loader.articulation','Angle of articulation','decimal','deg',60],['Loader Performance','kubota.wheel_loader.frame_oscillation','Frame oscillation','decimal','deg',61],['Loader Performance','kubota.wheel_loader.dump_clearance','Dump clearance','text',null,62],['Loader Performance','kubota.wheel_loader.hinge_pin_height','Hinge pin height','text',null,63],['Loader Performance','kubota.wheel_loader.reach_raised','Reach fully raised','text',null,64],
 ['Hydraulics','kubota.wheel_loader.aux_flow','Auxiliary hydraulic flow','decimal','gpm',10],
 ['Travel','kubota.wheel_loader.transmission','Transmission type','text',null,10],['Travel','kubota.wheel_loader.traction_force','Traction force','decimal','lb',20],['Travel','kubota.wheel_loader.travel_speed','Travel speed','text',null,30],
 ['Dimensions & Weight','kubota.wheel_loader.operating_weight_canopy','Operating weight, canopy','decimal','lb',10],['Dimensions & Weight','kubota.wheel_loader.operating_weight_cab','Operating weight, cab','decimal','lb',20],
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('Kubota wheel loader migration dependency missing');return Number(r[0].id);}
async function source(c:Parameters<DbMigration['apply']>[0]){const[r]=await c.query<IdRow[]>(`SELECT id FROM sources WHERE name='Kubota' AND domain='kubotausa.com' ORDER BY id LIMIT 1`);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO sources(name,domain,source_type,authority_level) VALUES('Kubota','kubotausa.com','manufacturer','official')`);return Number(x.insertId);}
async function record(c:Parameters<DbMigration['apply']>[0],sid:number,m:Seed){const externalId=`kubota-${m.slug}-wheel-loader-us-current-2026-09`;const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,URL,externalId,`Kubota ${m.model} 2026 U.S. wheel loader specifications`,JSON.stringify({captured:'2026-09-01',market:'United States',equipmentType:'Wheel Loader',currentKubotaConstructionUrl:CURRENT_URL,model:m,notes:'Kubota USA 2026 Full Product Line identifies R430, R540 and R640 as Wheel Loaders. Canopy/cab slash-pairs are expanded into explicit configuration-specific fields only where the catalog header makes that pairing unambiguous.'})]);return Number(x.insertId);}
async function put(c:Parameters<DbMigration['apply']>[0],mid:number,vid:number,did:number,rid:number,value:string|number,unit:string|null=null){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mid,vid,did,typeof value==='string'?value:null,typeof value==='number'?value:null,unit,rid]);}

export const kubotaRSeriesWheelLoadersCurrentMigration:DbMigration={id:'20260901_567_kubota_r_series_wheel_loaders_current',description:'Add current Kubota R430 R540 and R640 U.S. wheel loaders',async apply(c){
 await c.query(`INSERT INTO equipment_types(name,slug) VALUES('Wheel Loader','wheel-loader') ON DUPLICATE KEY UPDATE name=VALUES(name)`);await c.query(`INSERT INTO manufacturers(name,slug) VALUES('Kubota','kubota') ON DUPLICATE KEY UPDATE name=VALUES(name)`);const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='kubota' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='wheel-loader' LIMIT 1`),sid=await source(c);
 await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'Kubota R Series Wheel Loaders','kubota-r-series-wheel-loaders') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='kubota-r-series-wheel-loaders' LIMIT 1`,[mf,et]);const ids=new Map<string,number>();for(const d of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,d);ids.set(d[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[d[1]]));}const def=(k:string)=>{const v=ids.get(k);if(!v)throw new Error(`Missing Kubota wheel loader definition ${k}`);return v;};
 for(const m of models){const rid=await record(c,sid,m);await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current Kubota USA R Series wheel loader from the 2026 full-line construction catalog','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[mf,et,series,m.model,m.slug]);const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND equipment_type_id=? AND slug=? LIMIT 1`,[mf,et,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mid,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States','Kubota USA 2026 R Series wheel loader specification',TRUE,?,'Kubota manufacturer category retained as Wheel Loader. Canopy and cab weights/performance values remain separate rather than averaged.') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),configuration=VALUES(configuration),notes=VALUES(notes)`,[mid,VERSION,rid]);const vid=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mid,VERSION]);
 await put(c,mid,vid,def('configuration.type'),rid,'Wheel loader');await put(c,mid,vid,def('configuration.market_scope'),rid,'United States current catalog');await put(c,mid,vid,def('kubota.wheel_loader.engine_model'),rid,m.engineModel);await put(c,mid,vid,def('kubota.wheel_loader.gross_power'),rid,m.grossHp,'hp');await put(c,mid,vid,def('kubota.wheel_loader.bucket_breakout'),rid,m.bucketBreakoutLbf,'lbf');await put(c,mid,vid,def('kubota.wheel_loader.boom_linkage'),rid,'Hybrid');await put(c,mid,vid,def('kubota.wheel_loader.bucket_capacity'),rid,m.bucketCapacityYd3,'cu yd');
 await put(c,mid,vid,def('kubota.wheel_loader.tipping_straight_bucket_canopy'),rid,m.tippingStraightBucketCanopy,'lb');await put(c,mid,vid,def('kubota.wheel_loader.tipping_straight_bucket_cab'),rid,m.tippingStraightBucketCab,'lb');await put(c,mid,vid,def('kubota.wheel_loader.tipping_straight_forks_canopy'),rid,m.tippingStraightForksCanopy,'lb');await put(c,mid,vid,def('kubota.wheel_loader.tipping_straight_forks_cab'),rid,m.tippingStraightForksCab,'lb');await put(c,mid,vid,def('kubota.wheel_loader.tipping_full_bucket_canopy'),rid,m.tippingFullBucketCanopy,'lb');await put(c,mid,vid,def('kubota.wheel_loader.tipping_full_bucket_cab'),rid,m.tippingFullBucketCab,'lb');await put(c,mid,vid,def('kubota.wheel_loader.tipping_full_forks_canopy'),rid,m.tippingFullForksCanopy,'lb');await put(c,mid,vid,def('kubota.wheel_loader.tipping_full_forks_cab'),rid,m.tippingFullForksCab,'lb');
 await put(c,mid,vid,def('kubota.wheel_loader.roc_bucket_canopy'),rid,m.rocBucketCanopy,'lb');await put(c,mid,vid,def('kubota.wheel_loader.roc_bucket_cab'),rid,m.rocBucketCab,'lb');await put(c,mid,vid,def('kubota.wheel_loader.roc_forks_canopy'),rid,m.rocForksCanopy,'lb');await put(c,mid,vid,def('kubota.wheel_loader.roc_forks_cab'),rid,m.rocForksCab,'lb');await put(c,mid,vid,def('kubota.wheel_loader.articulation'),rid,40,'deg');await put(c,mid,vid,def('kubota.wheel_loader.frame_oscillation'),rid,8,'deg');await put(c,mid,vid,def('kubota.wheel_loader.dump_clearance'),rid,m.dumpClearance);await put(c,mid,vid,def('kubota.wheel_loader.hinge_pin_height'),rid,m.hingePinHeight);await put(c,mid,vid,def('kubota.wheel_loader.reach_raised'),rid,m.reachRaised);
 await put(c,mid,vid,def('kubota.wheel_loader.aux_flow'),rid,m.auxFlowGpm,'gpm');await put(c,mid,vid,def('kubota.wheel_loader.transmission'),rid,'HST, 2-speed');await put(c,mid,vid,def('kubota.wheel_loader.traction_force'),rid,m.tractionForceLb,'lb');await put(c,mid,vid,def('kubota.wheel_loader.travel_speed'),rid,'0–12.4 mph');await put(c,mid,vid,def('kubota.wheel_loader.operating_weight_canopy'),rid,m.weightCanopyLb,'lb');await put(c,mid,vid,def('kubota.wheel_loader.operating_weight_cab'),rid,m.weightCabLb,'lb');}
}};
