import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow = RowDataPacket & { id: number };
type Seed = {
  slug:string; name:string; url:string; station:'ROPS'|'Cab'; engineModel:string; powerHp:number;
  transmission:string; ptoPowerHp?:number; midPto:boolean; pumpGpm:number; hydraulicLiftLb:number;
  hitchCategory:string; hitchLiftLb:number; lengthIn:number; widthIn:number; heightIn:number;
  wheelbaseIn:number; clearanceIn:number; turningRadiusFt:number; weightLb:number; note?:string;
};

const VERSION='united-states-current-2026-08';
const LINEUP_URL='https://www.kioti.com/products/tractors/ns';
const MANUAL='Manual: Synchro Shuttle';
const HST='Hydrostatic';
const models:Seed[]=[
  {slug:'ns4710',name:'NS4710',url:'https://www.kioti.com/products/tractors/ns/ns4710',station:'ROPS',engineModel:'3HT-S4TM45A',powerHp:44.9,transmission:MANUAL,ptoPowerHp:36.6,midPto:false,pumpGpm:16.5,hydraulicLiftLb:2493,hitchCategory:'Category 1',hitchLiftLb:2493,lengthIn:136.4,widthIn:67.1,heightIn:98.4,wheelbaseIn:75.5,clearanceIn:13.4,turningRadiusFt:11.04,weightLb:4027},
  {slug:'ns4710h',name:'NS4710H',url:'https://www.kioti.com/products/tractors/ns/ns4710h',station:'ROPS',engineModel:'3HT-S4TM45A',powerHp:44.9,transmission:HST,ptoPowerHp:36.6,midPto:true,pumpGpm:16.5,hydraulicLiftLb:2493,hitchCategory:'Category 1',hitchLiftLb:2493,lengthIn:136.4,widthIn:67.1,heightIn:98.4,wheelbaseIn:75.5,clearanceIn:13.4,turningRadiusFt:11.04,weightLb:4027,note:'The current US page publishes identical minimum/maximum travel-speed rows for HST. Detailed travel-speed values are intentionally omitted.'},
  {slug:'ns4710-cab',name:'NS4710 CAB',url:'https://www.kioti.com/products/tractors/ns/ns4710c',station:'Cab',engineModel:'3HT-S4TH45A',powerHp:44.9,transmission:MANUAL,ptoPowerHp:36.6,midPto:false,pumpGpm:16.5,hydraulicLiftLb:2940,hitchCategory:'Category 2',hitchLiftLb:2940,lengthIn:136.4,widthIn:70.4,heightIn:93.7,wheelbaseIn:75.5,clearanceIn:11.8,turningRadiusFt:11.2,weightLb:4614,note:'The marketing prose on the current page mixes HST wording into this model, but the model-specific Full Specs table explicitly identifies Manual: Synchro Shuttle. The detailed table is used.'},
  {slug:'ns4710h-cab',name:'NS4710H CAB',url:'https://www.kioti.com/products/tractors/ns/ns4710c-hst',station:'Cab',engineModel:'3HT-S4TH45A',powerHp:45,transmission:HST,ptoPowerHp:36.3,midPto:true,pumpGpm:16.5,hydraulicLiftLb:2940,hitchCategory:'Category 2',hitchLiftLb:2940,lengthIn:136.4,widthIn:70.4,heightIn:93.7,wheelbaseIn:75.5,clearanceIn:11.8,turningRadiusFt:11.16,weightLb:4422},
  {slug:'ns5310h',name:'NS5310H',url:'https://www.kioti.com/products/tractors/ns/ns5310h',station:'ROPS',engineModel:'3HT-S4TH50A',powerHp:50.3,transmission:HST,ptoPowerHp:36.6,midPto:true,pumpGpm:16.5,hydraulicLiftLb:2940,hitchCategory:'Category 1',hitchLiftLb:2940,lengthIn:136.4,widthIn:67.1,heightIn:98.4,wheelbaseIn:75.5,clearanceIn:13.4,turningRadiusFt:11.04,weightLb:4027},
  {slug:'ns6010',name:'NS6010',url:'https://www.kioti.com/products/tractors/ns/ns6010',station:'ROPS',engineModel:'3HT-S4TM58A',powerHp:57.7,transmission:MANUAL,ptoPowerHp:48.3,midPto:false,pumpGpm:16.5,hydraulicLiftLb:2940,hitchCategory:'Category 2',hitchLiftLb:2940,lengthIn:136.4,widthIn:67.1,heightIn:98.4,wheelbaseIn:75.5,clearanceIn:13.4,turningRadiusFt:11.04,weightLb:4027},
  {slug:'ns6010h',name:'NS6010H',url:'https://www.kioti.com/products/tractors/ns/ns6010h',station:'ROPS',engineModel:'3HT-S4TM58A',powerHp:57.7,transmission:HST,ptoPowerHp:47.8,midPto:true,pumpGpm:16.5,hydraulicLiftLb:2940,hitchCategory:'Category 2',hitchLiftLb:2940,lengthIn:136.4,widthIn:67.1,heightIn:98.4,wheelbaseIn:75.5,clearanceIn:13.4,turningRadiusFt:11.04,weightLb:4027},
  {slug:'ns6010-cab',name:'NS6010 CAB',url:'https://www.kioti.com/products/tractors/ns/ns6010c',station:'Cab',engineModel:'3HT-S4TM58A',powerHp:57.7,transmission:HST,midPto:false,pumpGpm:16.5,hydraulicLiftLb:2932,hitchCategory:'Category 2',hitchLiftLb:2932,lengthIn:136.4,widthIn:70.4,heightIn:93.7,wheelbaseIn:75.5,clearanceIn:11.8,turningRadiusFt:11.16,weightLb:4614,note:'Both the current US lineup and Full Specs identify Hydrostatic transmission, but the same Full Specs table contains contradictory shuttle/main-gear/travel-speed rows and an implausible PTO-power value equal to engine power. Those conflicting detailed fields and PTO power are omitted.'},
  {slug:'ns6010h-cab',name:'NS6010H CAB',url:'https://www.kioti.com/products/tractors/ns/ns6010c-hst',station:'Cab',engineModel:'3HT-S4TM58A',powerHp:57.7,transmission:HST,ptoPowerHp:48.3,midPto:true,pumpGpm:16.5,hydraulicLiftLb:2932,hitchCategory:'Category 2',hitchLiftLb:2940,lengthIn:136.4,widthIn:70.4,heightIn:93.7,wheelbaseIn:75.5,clearanceIn:11.8,turningRadiusFt:11.2,weightLb:4479,note:'The current US table publishes hydraulics lift as 2,932 lb and hitch lift as 2,940 lb; both labeled values are preserved separately.'},
];

const definitions:Array<[string,string,string,string,string|null,number]>=[
  ['Machine Configuration','configuration.station','Operator station','text',null,1],
  ['Engine','engine.model','Engine model','text',null,1],['Engine','engine.make','Engine manufacturer','text',null,2],['Engine','engine.power','Engine power','decimal','hp',4],['Engine','engine.displacement','Engine displacement','decimal','L',6],['Engine','engine.power_speed','Engine speed at published power','integer','rpm',8],['Engine','engine.aspiration','Aspiration','text',null,10],['Engine','engine.emissions','Emissions','text',null,12],
  ['Transmission','transmission.options','Transmission','text',null,10],
  ['PTO','pto.type','PTO type','text',null,5],['PTO','pto.power','PTO power','decimal','hp',10],['PTO','pto.speeds','PTO speeds','text',null,20],
  ['Hydraulics','hydraulics.main_pump_flow','Hydraulic pump capacity','decimal','US gal/min',10],['Hydraulics','hydraulics.lift_capacity','Hydraulics lift capacity','decimal','lb',20],['Hydraulics','hitch.category','3-point hitch category','text',null,22],['Hydraulics','hitch.rear_max_lift_capacity','Hitch lift capacity','decimal','lb',25],
  ['Capacities','capacities.fuel_tank','Fuel tank capacity','decimal','L',10],
  ['Dimensions & Weight','dimensions.overall_length','Length with hitch','decimal','in',10],['Dimensions & Weight','dimensions.overall_width','Overall width','decimal','in',20],['Dimensions & Weight','dimensions.overall_height','Overall height','decimal','in',30],['Dimensions & Weight','dimensions.wheelbase','Wheelbase','decimal','in',40],['Dimensions & Weight','dimensions.ground_clearance','Ground clearance','decimal','in',50],['Dimensions & Weight','dimensions.turning_radius','Turning radius','decimal','ft',60],['Dimensions & Weight','dimensions.unladen_weight','Tractor weight','decimal','lb',70],
];

async function id(c:Parameters<DbMigration['apply']>[0],q:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(q,p);if(!r[0])throw new Error('KIOTI NS migration dependency missing');return Number(r[0].id)}
async function source(c:Parameters<DbMigration['apply']>[0],sid:number,externalId:string,url:string,title:string,raw:unknown){const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,url,externalId,title,JSON.stringify(raw)]);return Number(x.insertId)}
async function put(c:Parameters<DbMigration['apply']>[0],mi:number,vi:number,di:number,sr:number,v:string|number,u:string|null){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mi,vi,di,typeof v==='string'?v:null,typeof v==='number'?v:null,u,sr])}

export const kiotiNsCurrentUsMigration:DbMigration={
  id:'20260830_338_kioti_ns_current_us',description:'Add nine current US KIOTI NS Series compact utility tractor configurations from official model-specific pages',async apply(c){
    const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='kioti' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='tractor' LIMIT 1`),sid=await id(c,`SELECT id FROM sources WHERE name='KIOTI' AND domain='kioti.com' LIMIT 1`);
    await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'KIOTI NS Series','kioti-ns') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const seriesId=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND slug='kioti-ns' LIMIT 1`,[mf]);
    await source(c,sid,'kioti-ns-current-us-lineup-2026-08',LINEUP_URL,'KIOTI US current NS Series lineup',{market:'United States',captured:'2026-08-30',models:models.map(m=>m.name)});
    const defs=new Map<string,number>();for(const row of definitions){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,row);defs.set(row[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[row[1]]))}
    for(const m of models){const sr=await source(c,sid,`kioti-${m.slug}-current-us-2026-08`,m.url,`KIOTI US ${m.name} current specifications`,{market:'United States',captured:'2026-08-30',model:m,sourcePolicy:'Current model-specific US Full Specs are used. Internally conflicting fields are omitted rather than reconciled by inference.',note:m.note||null});await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current US KIOTI NS compact utility tractor','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[mf,et,seriesId,m.name,m.slug]);const mi=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mi,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States',?,TRUE,?,?) ON DUPLICATE KEY UPDATE configuration=VALUES(configuration),is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mi,VERSION,`${m.station}; ${m.transmission}`,sr,m.note||'Current KIOTI US model-specific specification record.']);const vi=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mi,VERSION]);const vals:Array<[string,string|number|undefined,string|null]>=[['configuration.station',m.station,null],['engine.model',m.engineModel,null],['engine.make','KIOTI',null],['engine.power',m.powerHp,'hp'],['engine.displacement',1.826,'L'],['engine.power_speed',2600,'rpm'],['engine.aspiration','Turbo Charged',null],['engine.emissions','Tier 4 CRDI',null],['transmission.options',m.transmission,null],['pto.type','Independent',null],['pto.power',m.ptoPowerHp,'hp'],['pto.speeds',m.midPto?'Rear 540 rpm; mid 2,000 rpm optional':'Rear 540 rpm',null],['hydraulics.main_pump_flow',m.pumpGpm,'US gal/min'],['hydraulics.lift_capacity',m.hydraulicLiftLb,'lb'],['hitch.category',m.hitchCategory,null],['hitch.rear_max_lift_capacity',m.hitchLiftLb,'lb'],['capacities.fuel_tank',50,'L'],['dimensions.overall_length',m.lengthIn,'in'],['dimensions.overall_width',m.widthIn,'in'],['dimensions.overall_height',m.heightIn,'in'],['dimensions.wheelbase',m.wheelbaseIn,'in'],['dimensions.ground_clearance',m.clearanceIn,'in'],['dimensions.turning_radius',m.turningRadiusFt,'ft'],['dimensions.unladen_weight',m.weightLb,'lb']];for(const[k,v,u]of vals){if(v===undefined)continue;const di=defs.get(k);if(!di)throw new Error(`Missing KIOTI NS spec definition ${k}`);await put(c,mi,vi,di,sr,v,u)}}
  }
};
