import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow = RowDataPacket & { id: number };
type Seed={slugs:string[];hours:number;url:string;externalId:string;title:string;notes:string};
const VERSION='united-states-current-2026-08';
const S:Seed[]=[
{slugs:['mf-7s-155','mf-7s-165','mf-7s-180','mf-7s-190','mf-7s-210'],hours:600,url:'https://www.masseyferguson.com/en_us/products/tractors/high-horse-power/mf-7s/',externalId:'massey-ferguson-mf-7s-service-interval-current-us-2026-08',title:'Massey Ferguson US MF 7S current service interval',notes:'Current US MF 7S product page explicitly states 600-hour engine service intervals.'},
{slugs:['mf-8s-205','mf-8s-225','mf-8s-245','mf-8s-265','mf-8s-285','mf-8s-305'],hours:600,url:'https://www.masseyferguson.com/content/dam/public/masseyfergusonglobal/markets/en_us/assets/product-brochures/tractors/mf-8s/MF-8S-Series-Brochure.pdf',externalId:'massey-ferguson-mf-8s-service-interval-us-brochure',title:'Massey Ferguson US MF 8S Series brochure service interval',notes:'US MF 8S Series technical specifications publish a 600-hour service interval.'},
{slugs:['mf-9s-310','mf-9s-340','mf-9s-370','mf-9s-400','mf-9s-425'],hours:500,url:'https://www.masseyferguson.com/content/dam/public/masseyfergusonglobal/markets/en_us/assets/product-brochures/tractors/mf-9s/MF24B002FC-MF-9S-Series-Brochure-LR.pdf',externalId:'massey-ferguson-mf-9s-service-interval-us-brochure',title:'Massey Ferguson US MF 9S Series brochure service interval',notes:'Current US MF 9S Series technical specifications publish a 500-hour service interval; this product-specific value is used instead of the generic high-horsepower landing-page statement.'},
];
async function id(c:Parameters<DbMigration['apply']>[0],q:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(q,p);if(!r[0])throw Error('MF service interval dependency missing');return Number(r[0].id)}
export const masseyFergusonServiceIntervalsMigration:DbMigration={id:'20260829_304_massey_ferguson_service_intervals',description:'Add official current US service intervals for MF 7S, 8S and 9S tractors',async apply(c){const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='massey-ferguson' LIMIT 1`);const sid=await id(c,`SELECT id FROM sources WHERE name='Massey Ferguson' AND domain='masseyferguson.com' ORDER BY id LIMIT 1`);await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES('Maintenance','maintenance.service_interval','Service interval','integer','hours',10) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`);const di=await id(c,`SELECT id FROM spec_definitions WHERE spec_key='maintenance.service_interval' LIMIT 1`);
for(const s of S){let[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[s.externalId]);let sr=r[0]?.id?Number(r[0].id):0;if(!sr){const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,s.url,s.externalId,s.title,JSON.stringify({market:'United States',captured:'2026-08-29',intervalHours:s.hours,notes:s.notes})]);sr=Number(x.insertId)}for(const slug of s.slugs){const mi=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,slug]);const vi=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mi,VERSION]);await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mi,vi,di,s.hours,'hours',sr]);await c.query(`INSERT INTO maintenance_tasks(machine_id,machine_version_id,task_key,section,action,title,interval_hours,interval_text,notes,source_record_id,confidence) VALUES(?,?,'scheduled-service','Maintenance','Service','Scheduled service interval',?, ?, ?, ?,'official') ON DUPLICATE KEY UPDATE machine_version_id=VALUES(machine_version_id),interval_hours=VALUES(interval_hours),interval_text=VALUES(interval_text),notes=VALUES(notes),confidence='official'`,[mi,vi,s.hours,`Every ${s.hours} hours`,s.notes,sr])}}
}};
