import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Seed={slug:string;model:string;url:string;purpose:string;depth:string;speed:string;hp:string;weight:string;residue:string;blade:string;spacing:string;width:string};
const VERSION='united-states-current-2026-08';
const FAMILY_URL='https://www.deere.com/en/tillage/field-cultivators/';
const models:Seed[]=[
 {slug:'2630-tandem-disk',model:'2630',url:'https://www.deere.com/en/tillage/disks/2630-three-and-five-section-tandem-disks/',purpose:'Secondary tillage / light duty',depth:'Up to 5 in (12.7 cm)',speed:'5 - 7 mph (8 - 11.3 km/h)',hp:'7 - 11 engine hp/ft (17.15 - 26.95 kW/m)',weight:'179 - 209 lb per blade (81.2 - 94.8 kg), configuration dependent',residue:'Light / Medium',blade:'22 or 24 in (560 or 610 mm)',spacing:'7.25 or 9 in (185 or 230 mm)',width:'20.75 - 49.25 ft (6.3 - 15.0 m)'},
 {slug:'2633-tandem-disk',model:'2633',url:'https://www.deere.com/en/tillage/disks/2633-three-and-five-section-tandem-disks/',purpose:'Primary or secondary tillage / medium duty',depth:'Up to 6 in (15.2 cm) on current US comparison table',speed:'5 - 7 mph (8 - 11.3 km/h)',hp:'7 - 11 engine hp/ft (17.15 - 26.95 kW/m)',weight:'201 - 243 lb per blade (91.2 - 110.2 kg), configuration dependent',residue:'Light / Medium / Heavy',blade:'24 or 26 in (610 or 660 mm)',spacing:'9 in (230 mm)',width:'20.75 - 49.25 ft (6.3 - 15.0 m)'},
 {slug:'2635-tandem-disk',model:'2635',url:'https://www.deere.com/en/tillage/disks/2635-three-and-five-section-tandem-disks/',purpose:'Primary tillage / heavy duty',depth:'Up to 8 in (20.3 cm)',speed:'5 - 7 mph (8 - 11.3 km/h)',hp:'9 - 12 engine hp/ft (22.05 - 29.4 kW/m)',weight:'280 - 286 lb per blade (127 - 129.7 kg), configuration dependent',residue:'Light / Medium',blade:'24 or 26 in (610 or 660 mm)',spacing:'9 in front with 11 in rear, or 11 in spacing configuration',width:'23.58 - 40.66 ft (7.2 - 12.4 m)'},
];
const defs:Array<[string,string,string,string,string|null,number]>=[
 ['Machine Configuration','configuration.type','Machine configuration','text',null,1],['Machine Configuration','configuration.market_scope','Official market scope','text',null,2],
 ['Tillage System','tandem_disk.purpose','Tillage purpose','text',null,10],['Tillage System','tandem_disk.working_depth','Working depth','text',null,20],['Tillage System','tandem_disk.working_speed','Working speed','text',null,30],['Tillage System','tandem_disk.weight_per_blade','Weight per blade','text',null,40],['Tillage System','tandem_disk.residue_conditions','Residue conditions','text',null,50],['Tillage System','tandem_disk.blade_size','Blade size','text',null,60],['Tillage System','tandem_disk.blade_spacing','Blade spacing','text',null,70],['Tillage System','tandem_disk.working_width','Working width','text',null,80],['Tillage System','tandem_disk.depth_control','Depth control','text',null,90],
 ['Tractor Requirements','tandem_disk.hp_per_ft','Required engine power per foot','text',null,10],['Precision Technology','tandem_disk.precision_control','Precision tillage control','text',null,10],
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('John Deere 2630 Series tandem disk migration dependency missing');return Number(r[0].id);}
async function src(c:Parameters<DbMigration['apply']>[0]){const[r]=await c.query<IdRow[]>(`SELECT id FROM sources WHERE name='John Deere' AND domain='deere.com' ORDER BY id LIMIT 1`);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO sources(name,domain,source_type,authority_level) VALUES('John Deere','deere.com','manufacturer','official')`);return Number(x.insertId);}
async function rec(c:Parameters<DbMigration['apply']>[0],sid:number,m:Seed){const externalId=`john-deere-${m.slug}-us-current-2026-08`;const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,m.url,externalId,`John Deere ${m.model} current US tandem disk specifications`,JSON.stringify({captured:'2026-08-31',market:'United States',equipmentType:'Tandem Disk',familySource:FAMILY_URL,...m})]);return Number(x.insertId);}
async function put(c:Parameters<DbMigration['apply']>[0],mid:number,vid:number,did:number,rid:number,v:string){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,NULL,NULL,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=NULL,unit=NULL,source_record_id=VALUES(source_record_id),confidence='official'`,[mid,vid,did,v,rid]);}
export const johnDeere2630SeriesTandemDisksCurrentMigration:DbMigration={id:'20260831_524_john_deere_2630_series_tandem_disks_current',description:'Add current John Deere US 2630, 2633 and 2635 tandem disks',async apply(c){
 await c.query(`INSERT INTO equipment_types(name,slug) VALUES('Tandem Disk','tandem-disk') ON DUPLICATE KEY UPDATE name=VALUES(name)`);await c.query(`INSERT INTO manufacturers(name,slug) VALUES('John Deere','john-deere') ON DUPLICATE KEY UPDATE name=VALUES(name)`);const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='john-deere' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='tandem-disk' LIMIT 1`),sid=await src(c);await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'2630 Series Tandem Disks','2630-series-tandem-disks') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='2630-series-tandem-disks' LIMIT 1`,[mf,et]);const ids=new Map<string,number>();for(const d of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,d);ids.set(d[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[d[1]]));}const def=(k:string)=>{const v=ids.get(k);if(!v)throw new Error(`Missing Deere tandem disk definition ${k}`);return v;};
 for(const m of models){const rid=await rec(c,sid,m);await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current John Deere United States 2630 Series tandem disk lineup','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes)`,[mf,et,series,m.model,m.slug]);const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND equipment_type_id=? AND slug=? LIMIT 1`,[mf,et,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mid,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States','Current 2630 Series family specification',TRUE,?,'Current John Deere US product and comparison data captured 2026-08-31. Configuration-dependent values are preserved as ranges instead of expanded into invented machines.') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mid,VERSION,rid]);const vid=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mid,VERSION]);await put(c,mid,vid,def('configuration.type'),rid,'Tandem disk');await put(c,mid,vid,def('configuration.market_scope'),rid,'United States current catalog');await put(c,mid,vid,def('tandem_disk.purpose'),rid,m.purpose);await put(c,mid,vid,def('tandem_disk.working_depth'),rid,m.depth);await put(c,mid,vid,def('tandem_disk.working_speed'),rid,m.speed);await put(c,mid,vid,def('tandem_disk.weight_per_blade'),rid,m.weight);await put(c,mid,vid,def('tandem_disk.residue_conditions'),rid,m.residue);await put(c,mid,vid,def('tandem_disk.blade_size'),rid,m.blade);await put(c,mid,vid,def('tandem_disk.blade_spacing'),rid,m.spacing);await put(c,mid,vid,def('tandem_disk.working_width'),rid,m.width);await put(c,mid,vid,def('tandem_disk.depth_control'),rid,'TruSet / Single-Point');await put(c,mid,vid,def('tandem_disk.hp_per_ft'),rid,m.hp);await put(c,mid,vid,def('tandem_disk.precision_control'),rid,'John Deere TruSet Tillage Technology');}
 }};
