import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Seed={slug:string;model:string;type:string;note:string};
const PAGE='https://www.antoniocarraro.it/na/catalogue/TTR_4800_HST';
const attachments:Seed[]=[
 {slug:'ac-rt-1500-hds',model:'RT 1500 HDS',type:'mower',note:'Professional turbine rotary mower with 150 cm cutting width; optional on TTR 4800 HST current North America product page'},
 {slug:'ac-ct-1000',model:'CT 1000',type:'collector',note:'Patented grass collector with capacity up to 1000 liters; optional on TTR 4800 HST current North America product page'},
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('Antonio Carraro TTR attachment dependency missing');return Number(r[0].id)}
async function source(c:Parameters<DbMigration['apply']>[0],sid:number,a:Seed){const eid=`antonio-carraro-${a.slug}-ttr4800-fitment-na-2026-08`;const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[eid]);if(r[0])return Number(r[0].id);const[i]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,PAGE,eid,`Antonio Carraro ${a.model} TTR 4800 HST North America fitment`,JSON.stringify({market:'North America',captured:'2026-08-31',model:a.model,type:a.type,machine:'TTR 4800 HST',note:a.note,sourcePolicy:'Only attachment model names explicitly identified as optional on the current North America TTR 4800 HST product page are added.'})]);return Number(i.insertId)}
export const antonioCarraroTtr4800AttachmentsMigration:DbMigration={id:'20260831_472_antonio_carraro_ttr_4800_attachments',description:'Add official RT 1500 HDS mower and CT 1000 collector fitment for Antonio Carraro TTR 4800 HST',async apply(c){const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='antonio-carraro' LIMIT 1`),sid=await id(c,`SELECT id FROM sources WHERE name='Antonio Carraro' AND domain='antoniocarraro.it' LIMIT 1`),mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug='ttr-4800-hst' LIMIT 1`,[mf]);for(const a of attachments){const sr=await source(c,sid,a);await c.query(`INSERT INTO attachments(manufacturer_id,attachment_type,model_name,slug,configuration_text,data_status) VALUES(?,?,?,?,?,'verified') ON DUPLICATE KEY UPDATE attachment_type=VALUES(attachment_type),model_name=VALUES(model_name),configuration_text=VALUES(configuration_text),data_status='verified'`,[mf,a.type,a.model,a.slug,a.note]);const aid=await id(c,`SELECT id FROM attachments WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,a.slug]);await c.query(`INSERT INTO machine_attachments(machine_id,attachment_id,compatibility_note,source_record_id,confidence) VALUES(?,?,?,?, 'official') ON DUPLICATE KEY UPDATE compatibility_note=VALUES(compatibility_note),source_record_id=VALUES(source_record_id),confidence='official'`,[mid,aid,a.note,sr])}}};
