import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type ModelSeed={slug:string;model:string;ratedHp:number;maxHp:number};
const CURRENT_URL='https://www.deere.com/en-us/products-solutions/tractors/row-crop-4wd-tractors/9rx-710-tractor-otkwmfjx';
const CURRENT_EXTERNAL_ID='john-deere-9rx-490-640-current-related-products-2026-08';
const SPEC_URL='https://www.deere.com/assets/pdfs/common/products/tractors/4wd-track-tractors/9-series-au-nz-CP8264_LR.pdf';
const SPEC_EXTERNAL_ID='john-deere-9rx-490-640-jd14-official-specifications';
const ENGINE_URL='https://shop.deere.com/us/product/SZ10293%3A-Diesel-Engine%2C-13-6-Liter/p/SZ10293';
const ENGINE_EXTERNAL_ID='john-deere-shop-sz10293-13-6l-9rx-490-640-fitment';
const VERSION_SLUG='united-states-current-2026-08';
const models:ModelSeed[]=[
  {slug:'9rx-490',model:'9RX 490',ratedHp:490,maxHp:539},
  {slug:'9rx-540',model:'9RX 540',ratedHp:540,maxHp:594},
  {slug:'9rx-590',model:'9RX 590',ratedHp:590,maxHp:649},
  {slug:'9rx-640',model:'9RX 640',ratedHp:640,maxHp:691},
];
const definitions=[
  ['Machine Configuration','configuration.station','Operator station','text',null,1],['Machine Configuration','configuration.track','Wheel or track configuration','text',null,2],['Machine Configuration','drivetrain.type','Drive type','text',null,3],
  ['Engine','engine.make','Engine manufacturer','text',null,1],['Engine','engine.model','Engine model','text',null,2],['Engine','engine.displacement','Engine displacement','decimal','L',3],['Engine','engine.cylinders','Cylinders','integer',null,4],['Engine','engine.rated_power','Rated engine power (ISO)','decimal','hp',5],['Engine','engine.maximum_power','Maximum engine power (ISO)','decimal','hp',6],['Engine','engine.rated_speed','Rated engine speed','integer','rpm',7],['Engine','engine.emissions','Emissions certification','text',null,8],
  ['PTO','pto.rated_power','Rated PTO power','decimal','hp',10],['Transmission','transmission.standard','Standard transmission','text',null,10],['Hydraulics','hydraulics.pump_rated_output','Standard hydraulic pump output','decimal','gpm',10],['Hydraulics','hydraulics.pump_optional_output','Optional hydraulic pump output','decimal','gpm',20],['Capacities','capacities.fuel_tank_variants','Fuel tank capacity','decimal','US gal',10],
] as const;
async function selectId(connection:Parameters<DbMigration['apply']>[0],sql:string,params:unknown[]=[]){const [rows]=await connection.query<IdRow[]>(sql,params);if(!rows[0])throw new Error('Missing John Deere 9RX 490-640 current migration dependency.');return Number(rows[0].id);}
async function ensureSource(connection:Parameters<DbMigration['apply']>[0],sourceId:number,externalId:string,url:string,title:string,publishedDate:string|null=null){const [rows]=await connection.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(rows[0])return Number(rows[0].id);const [result]=await connection.query<ResultSetHeader>(`INSERT INTO source_records (source_id,url,external_id,title,published_date) VALUES (?,?,?,?,?)`,[sourceId,url,externalId,title,publishedDate]);return Number(result.insertId);}
async function upsertSpec(connection:Parameters<DbMigration['apply']>[0],machineId:number,versionId:number,definitionId:number,sourceRecordId:number,value:string|number,unit:string|null=null){await connection.query(`INSERT INTO machine_specs (machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES (?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[machineId,versionId,definitionId,typeof value==='string'?value:null,typeof value==='number'?value:null,unit,sourceRecordId]);}

export const johnDeere9RX490640CurrentSpecsMigration:DbMigration={
  id:'20260828_225_john_deere_9rx_490_640_current_specs',
  description:'Add current US John Deere 9RX 490, 540, 590 and 640 four-track specifications using the current JD14 13.6 L revision',
  async apply(connection){
    const manufacturerId=await selectId(connection,`SELECT id FROM manufacturers WHERE slug='john-deere' LIMIT 1`);const equipmentTypeId=await selectId(connection,`SELECT id FROM equipment_types WHERE slug='tractor' LIMIT 1`);
    await connection.query(`INSERT INTO machine_series (manufacturer_id,equipment_type_id,name,slug) VALUES (?,?,'9RX Series','9rx-series') ON DUPLICATE KEY UPDATE name='9RX Series'`,[manufacturerId,equipmentTypeId]);const seriesId=await selectId(connection,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='9rx-series' LIMIT 1`,[manufacturerId,equipmentTypeId]);
    let [sourceRows]=await connection.query<IdRow[]>(`SELECT id FROM sources WHERE name='John Deere' AND domain='deere.com' ORDER BY id LIMIT 1`);let sourceId=sourceRows[0]?.id?Number(sourceRows[0].id):0;if(!sourceId){const [result]=await connection.query<ResultSetHeader>(`INSERT INTO sources (name,domain,source_type,authority_level) VALUES ('John Deere','deere.com','manufacturer','official')`);sourceId=Number(result.insertId);}
    let [shopSourceRows]=await connection.query<IdRow[]>(`SELECT id FROM sources WHERE name='John Deere Parts' AND domain='shop.deere.com' ORDER BY id LIMIT 1`);let shopSourceId=shopSourceRows[0]?.id?Number(shopSourceRows[0].id):0;if(!shopSourceId){const [result]=await connection.query<ResultSetHeader>(`INSERT INTO sources (name,domain,source_type,authority_level) VALUES ('John Deere Parts','shop.deere.com','manufacturer','official')`);shopSourceId=Number(result.insertId);}
    const currentSourceId=await ensureSource(connection,sourceId,CURRENT_EXTERNAL_ID,CURRENT_URL,'John Deere US current 9RX family page - related 9RX 490/540/590/640 products');
    const specSourceId=await ensureSource(connection,sourceId,SPEC_EXTERNAL_ID,SPEC_URL,'John Deere official 9 Series specifications - 9RX 490/540/590/640 JD14 configuration');
    const engineSourceId=await ensureSource(connection,shopSourceId,ENGINE_EXTERNAL_ID,ENGINE_URL,'Shop.Deere SZ10293 13.6 L engine - compatible equipment includes 9RX 490/540/590/640');
    const definitionIds=new Map<string,number>();for(const [section,key,label,valueType,canonicalUnit,displayOrder] of definitions){await connection.query(`INSERT INTO spec_definitions (section,spec_key,label,value_type,canonical_unit,display_order) VALUES (?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,[section,key,label,valueType,canonicalUnit,displayOrder]);definitionIds.set(key,await selectId(connection,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[key]));}const def=(key:string)=>{const id=definitionIds.get(key);if(!id)throw new Error(`Missing 9RX 490-640 spec ${key}`);return id;};
    for(const model of models){await connection.query(`INSERT INTO machines (manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES (?,?,?,?,?,'Current US John Deere 9RX four-track JD14 generation. Older service literature also documents a 15 L path for some 9RX 640 serials; current Shop.Deere 13.6 L engine compatibility is used for the current catalog version.','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[manufacturerId,equipmentTypeId,seriesId,model.model,model.slug]);const machineId=await selectId(connection,`SELECT id FROM machines WHERE manufacturer_id=? AND equipment_type_id=? AND slug=? LIMIT 1`,[manufacturerId,equipmentTypeId,model.slug]);await connection.query(`INSERT INTO machine_versions (machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES (?,?,'US','United States','Current 9RX four-track agricultural tractor - JD14 13.6 L',TRUE,?,?) ON DUPLICATE KEY UPDATE market_code='US',market_name='United States',configuration=VALUES(configuration),is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[machineId,VERSION_SLUG,currentSourceId,'Current Deere US product relationships still list 9RX 490/540/590/640. Current Shop.Deere engine records identify the 13.6 L JD14 as compatible with all four, including 9RX 640. Historical 15 L 9RX 640 service records should be treated as serial/revision-specific, not current default.']);const versionId=await selectId(connection,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[machineId,VERSION_SLUG]);const values:Array<[string,string|number,string|null,number]>=[['configuration.station','Cab',null,currentSourceId],['configuration.track','4-Track',null,currentSourceId],['drivetrain.type','4WD articulated tracked',null,currentSourceId],['engine.make','John Deere',null,engineSourceId],['engine.model','JD14',null,engineSourceId],['engine.displacement',13.6,'L',engineSourceId],['engine.cylinders',6,null,specSourceId],['engine.rated_power',model.ratedHp,'hp',specSourceId],['engine.maximum_power',model.maxHp,'hp',specSourceId],['engine.rated_speed',2100,'rpm',specSourceId],['engine.emissions','Final Tier 4',null,specSourceId],['pto.rated_power',335,'hp',specSourceId],['transmission.standard','John Deere e18 18-speed PowerShift with Efficiency Manager; 18F/6R',null,specSourceId],['hydraulics.pump_rated_output',55,'gpm',specSourceId],['hydraulics.pump_optional_output',110,'gpm',specSourceId],['capacities.fuel_tank_variants',400,'US gal',specSourceId]];for(const [key,value,unit,recordId] of values)await upsertSpec(connection,machineId,versionId,def(key),recordId,value,unit);}
  }
};