import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type ModelSeed={slug:string;model:string;ratedHp:number;maxHp:number};
const FAMILY_URL='https://www.deere.com/en-us/products-solutions/tractors/row-crop-4wd-tractors/9rx-710-tractor-otkwmfjx';
const FAMILY_EXTERNAL_ID='john-deere-9rx-hhp-current-2026-08';
const SPEC_URL='https://www.deere.com/assets/pdfs/region-4/products/4-wd-and-track-tractors/4843464-9rx-tractors.pdf';
const SPEC_EXTERNAL_ID='john-deere-9rx-710-770-830-official-specifications';
const VERSION_SLUG='united-states-current-2026-08';
const models:ModelSeed[]=[
  {slug:'9rx-710',model:'9RX 710',ratedHp:710,maxHp:781},
  {slug:'9rx-770',model:'9RX 770',ratedHp:770,maxHp:847},
  {slug:'9rx-830',model:'9RX 830',ratedHp:830,maxHp:913},
];
const definitions=[
  ['Machine Configuration','configuration.station','Operator station','text',null,1],['Machine Configuration','configuration.track','Wheel or track configuration','text',null,2],['Machine Configuration','drivetrain.type','Drive type','text',null,3],
  ['Engine','engine.make','Engine manufacturer','text',null,1],['Engine','engine.model','Engine model','text',null,2],['Engine','engine.displacement','Engine displacement','decimal','L',3],['Engine','engine.cylinders','Cylinders','integer',null,4],['Engine','engine.aspiration','Aspiration','text',null,5],['Engine','engine.rated_power','Rated engine power (ISO)','decimal','hp',6],['Engine','engine.maximum_power','Maximum engine power (ISO)','decimal','hp',7],['Engine','engine.ipm_boost','Seeding Hydraulic Intelligent Power Management boost','decimal','hp',8],['Engine','engine.rated_speed','Rated engine speed','integer','rpm',9],['Engine','engine.emissions','Emissions certification','text',null,10],
  ['PTO','pto.rated_power','Rated PTO power','decimal','hp',10],['Transmission','transmission.standard','Standard transmission','text',null,10],['Hydraulics','hydraulics.pump_rated_output','Single hydraulic pump output','decimal','gpm',10],['Hydraulics','hydraulics.pump_optional_output','Maximum optional hydraulic pump output','decimal','gpm',20],
] as const;
async function selectId(connection:Parameters<DbMigration['apply']>[0],sql:string,params:unknown[]=[]){const [rows]=await connection.query<IdRow[]>(sql,params);if(!rows[0])throw new Error('Missing John Deere 9RX HHP migration dependency.');return Number(rows[0].id);}
async function ensureSource(connection:Parameters<DbMigration['apply']>[0],sourceId:number,externalId:string,url:string,title:string){const [rows]=await connection.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(rows[0])return Number(rows[0].id);const [result]=await connection.query<ResultSetHeader>(`INSERT INTO source_records (source_id,url,external_id,title) VALUES (?,?,?,?)`,[sourceId,url,externalId,title]);return Number(result.insertId);}
async function upsertSpec(connection:Parameters<DbMigration['apply']>[0],machineId:number,versionId:number,definitionId:number,sourceId:number,value:string|number,unit:string|null=null){await connection.query(`INSERT INTO machine_specs (machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES (?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[machineId,versionId,definitionId,typeof value==='string'?value:null,typeof value==='number'?value:null,unit,sourceId]);}
export const johnDeere9RXHHPCurrentSpecsMigration:DbMigration={id:'20260828_219_john_deere_9rx_hhp_current_specs',description:'Add current John Deere 9RX 710, 770 and 830 high-horsepower four-track specifications with JD18 engine and e21 transmission',async apply(connection){
  const manufacturerId=await selectId(connection,`SELECT id FROM manufacturers WHERE slug='john-deere' LIMIT 1`);const equipmentTypeId=await selectId(connection,`SELECT id FROM equipment_types WHERE slug='tractor' LIMIT 1`);
  await connection.query(`INSERT INTO machine_series (manufacturer_id,equipment_type_id,name,slug) VALUES (?,?,'9RX High Horsepower Series','9rx-high-horsepower') ON DUPLICATE KEY UPDATE name='9RX High Horsepower Series'`,[manufacturerId,equipmentTypeId]);const seriesId=await selectId(connection,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='9rx-high-horsepower' LIMIT 1`,[manufacturerId,equipmentTypeId]);
  let [sourceRows]=await connection.query<IdRow[]>(`SELECT id FROM sources WHERE name='John Deere' AND domain='deere.com' ORDER BY id LIMIT 1`);let sourceId=sourceRows[0]?.id?Number(sourceRows[0].id):0;if(!sourceId){const [result]=await connection.query<ResultSetHeader>(`INSERT INTO sources (name,domain,source_type,authority_level) VALUES ('John Deere','deere.com','manufacturer','official')`);sourceId=Number(result.insertId);}const familyId=await ensureSource(connection,sourceId,FAMILY_EXTERNAL_ID,FAMILY_URL,'John Deere US 9RX high-horsepower current product page');const specId=await ensureSource(connection,sourceId,SPEC_EXTERNAL_ID,SPEC_URL,'John Deere official 9RX 710, 770 and 830 specifications');
  const definitionIds=new Map<string,number>();for(const [section,key,label,valueType,canonicalUnit,displayOrder] of definitions){await connection.query(`INSERT INTO spec_definitions (section,spec_key,label,value_type,canonical_unit,display_order) VALUES (?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,[section,key,label,valueType,canonicalUnit,displayOrder]);definitionIds.set(key,await selectId(connection,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[key]));}const def=(key:string)=>{const id=definitionIds.get(key);if(!id)throw new Error(`Missing 9RX HHP spec ${key}`);return id;};
  for(const model of models){await connection.query(`INSERT INTO machines (manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES (?,?,?,?,?,'Current John Deere US 9RX high-horsepower four-track tractor with JD18 engine','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[manufacturerId,equipmentTypeId,seriesId,model.model,model.slug]);const machineId=await selectId(connection,`SELECT id FROM machines WHERE manufacturer_id=? AND equipment_type_id=? AND slug=? LIMIT 1`,[manufacturerId,equipmentTypeId,model.slug]);await connection.query(`INSERT INTO machine_versions (machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES (?,?,'US','United States','Current 9RX high-horsepower fixed-frame four-track tractor - cab',TRUE,?,?) ON DUPLICATE KEY UPDATE market_code='US',market_name='United States',configuration=VALUES(configuration),is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[machineId,VERSION_SLUG,familyId,'Current high-horsepower 9RX generation uses the JD18 18 L engine and e21 transmission. Stored separately from the 9RX 490-640 generation.']);const versionId=await selectId(connection,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[machineId,VERSION_SLUG]);const values:Array<[string,string|number,string|null,number]>=[['configuration.station','Cab',null,familyId],['configuration.track','4-Track',null,familyId],['drivetrain.type','4WD tracked',null,familyId],['engine.make','John Deere',null,specId],['engine.model','JD18',null,specId],['engine.displacement',18,'L',specId],['engine.cylinders',6,null,specId],['engine.aspiration','Dual turbochargers in series; fixed-displacement primary and wastegated secondary, air-to-air aftercooling and cooled EGR',null,specId],['engine.rated_power',model.ratedHp,'hp',specId],['engine.maximum_power',model.maxHp,'hp',specId],['engine.ipm_boost',40,'hp',specId],['engine.rated_speed',1900,'rpm',specId],['engine.emissions','Final Tier 4 / Stage V; diesel-only aftertreatment with no DEF',null,familyId],['pto.rated_power',335,'hp',specId],['transmission.standard','John Deere e21 21-speed PowerShift; 21F/11R with Efficiency Manager',null,specId],['hydraulics.pump_rated_output',56,'gpm',specId],['hydraulics.pump_optional_output',168,'gpm',specId]];for(const [key,value,unit,recordId] of values)await upsertSpec(connection,machineId,versionId,def(key),recordId,value,unit);}
}};