import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow = RowDataPacket & { id: number };
type Seed = { slug:string; model:string; hp:number; ptoHp:number; displacementL:number; station?:string; drive?:string; url:string; externalId:string };
const VERSION='united-states-current-2026-08';
const FAMILY='https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-specialty-series/farmall-cl-series';
const models:Seed[]=[
 {slug:'farmall-80cl',model:'Farmall 80CL',hp:75,ptoHp:65,displacementL:3.4,url:FAMILY+'/farmall-80cl',externalId:'case-ih-farmall-80cl-current-us'},
 {slug:'farmall-90cl',model:'Farmall 90CL',hp:85,ptoHp:75,displacementL:3.6,station:'Cab or Non-Cab',drive:'MFD',url:FAMILY+'/farmall-90cl',externalId:'case-ih-farmall-90cl-current-us'},
 {slug:'farmall-100cl',model:'Farmall 100CL',hp:98,ptoHp:87,displacementL:3.6,station:'Cab or Non-Cab',drive:'MFD',url:FAMILY+'/farmall-100cl',externalId:'case-ih-farmall-100cl-current-us'},
 {slug:'farmall-110cl',model:'Farmall 110CL',hp:106,ptoHp:96,displacementL:3.6,station:'Cab or Non-Cab',drive:'MFD',url:FAMILY+'/farmall-110cl',externalId:'case-ih-farmall-110cl-current-us'},
 {slug:'farmall-120cl',model:'Farmall 120CL',hp:119,ptoHp:102,displacementL:3.6,station:'Cab or Non-Cab',drive:'MFD',url:FAMILY+'/farmall-120cl',externalId:'case-ih-farmall-120cl-current-us'},
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw Error('Farmall CL dependency missing');return Number(r[0].id)}
async function source(c:Parameters<DbMigration['apply']>[0],sid:number,m:Seed){const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[m.externalId]);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,m.url,m.externalId,`Case IH US ${m.model} official current specifications`,JSON.stringify({...m,application:'Orchard / specialty'})]);return Number(x.insertId)}
export const caseIHFarmallCLCurrentSpecsMigration:DbMigration={id:'20260828_256_case_ih_farmall_cl_current_specs',description:'Add current US Case IH Farmall CL 80CL-120CL official specs',async apply(c){
 await c.query(`INSERT INTO equipment_types(name,slug) VALUES('Tractor','tractor') ON DUPLICATE KEY UPDATE name=VALUES(name)`);await c.query(`INSERT INTO manufacturers(name,slug) VALUES('Case IH','case-ih') ON DUPLICATE KEY UPDATE name=VALUES(name)`);const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='case-ih'`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='tractor'`);await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'Farmall CL Series','farmall-cl-series') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND slug='farmall-cl-series'`,[mf]);let[s]=await c.query<IdRow[]>(`SELECT id FROM sources WHERE name='Case IH' AND domain='caseih.com' LIMIT 1`);let sid=s[0]?.id?Number(s[0].id):0;if(!sid){const[x]=await c.query<ResultSetHeader>(`INSERT INTO sources(name,domain,source_type,authority_level) VALUES('Case IH','caseih.com','manufacturer','official')`);sid=Number(x.insertId)}
 const defs:Array<[string,string,string,string,string|null,number]>=[['Application','application.type','Application','text',null,3],['Machine Configuration','configuration.station','Operator station','text',null,1],['Machine Configuration','configuration.drive','Drive configuration','text',null,2],['Engine','engine.displacement','Engine displacement','decimal','L',2],['Engine','engine.rated_power','Engine horsepower','decimal','hp',3],['PTO','pto.rated_power','PTO power','decimal','hp',10]];for(const d of defs)await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit)`,d);
 for(const m of models){const sr=await source(c,sid,m);await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current US Case IH Farmall CL orchard specialty tractor','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes)`,[mf,et,series,m.model,m.slug]);const mi=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=?`,[mf,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mi,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States','Current Farmall CL orchard specialty tractor',TRUE,?,'Official Case IH US current product data') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mi,VERSION,sr]);const vi=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=?`,[mi,VERSION]);const vals:Array<[string,string|number,string|null]>=[['application.type','Orchard / specialty',null],['engine.displacement',m.displacementL,'L'],['engine.rated_power',m.hp,'hp'],['pto.rated_power',m.ptoHp,'hp']];if(m.station)vals.push(['configuration.station',m.station,null]);if(m.drive)vals.push(['configuration.drive',m.drive,null]);for(const[k,v,u]of vals){const di=await id(c,`SELECT id FROM spec_definitions WHERE spec_key=?`,[k]);await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mi,vi,di,typeof v==='string'?v:null,typeof v==='number'?v:null,u,sr])}}
}};
