import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Seed={slug:string;model:string;seriesName:string;seriesSlug:string;sourceUrl:string;grossHp:number;maxHp?:number;displacementL?:number;ratedRpm?:number;fuelGal?:number;grainTank?:number;unloadRate?:number;separator:string;note:string};
const VERSION='united-states-current-2026-08';
const NEXT='https://agriculture.newholland.com/en-us/nar/products/combines-and-headers/next-gen-cr-series-twin-rotor-combines';
const LEGACY='https://agriculture.newholland.com/en-us/nar/products/combines-and-headers/cr-series-twin-rotor-combines';
const models:Seed[]=[
 {slug:'cr10',model:'CR10',seriesName:'Next Generation CR Series',seriesSlug:'next-gen-cr',sourceUrl:NEXT,grossHp:634,displacementL:12.9,ratedRpm:1900,fuelGal:343,grainTank:455,unloadRate:4.5,separator:'Twin Rotor',note:'Current New Holland North America CR10 product page captured 2026-08-31; 634 hp, 12.9 L Cursor 13, 455-bushel tank and 4.5 bu/sec headline unloading rate.'},
 {slug:'cr11',model:'CR11',seriesName:'Next Generation CR Series',seriesSlug:'next-gen-cr',sourceUrl:NEXT,grossHp:775,displacementL:15.9,ratedRpm:1900,fuelGal:396,grainTank:567,unloadRate:6,separator:'Twin Rotor',note:'Current New Holland North America CR11 product page captured 2026-08-31; 775 hp, 15.9 L Cursor 16, 567-bushel tank and 6 bu/sec unloading rate.'},
 {slug:'cr7-80',model:'CR7.80',seriesName:'CR Series Twin Rotor',seriesSlug:'cr-series',sourceUrl:LEGACY,grossHp:374,maxHp:415,separator:'Twin Rotor',note:'Current New Holland North America CR Series page captured 2026-08-31.'},
 {slug:'cr7-90',model:'CR7.90',seriesName:'CR Series Twin Rotor',seriesSlug:'cr-series',sourceUrl:LEGACY,grossHp:420,maxHp:460,separator:'Twin Rotor',note:'Current New Holland North America CR Series page captured 2026-08-31.'},
 {slug:'cr8-90',model:'CR8.90',seriesName:'CR Series Twin Rotor',seriesSlug:'cr-series',sourceUrl:LEGACY,grossHp:496,maxHp:571,separator:'Twin Rotor',note:'Current New Holland North America CR Series page captured 2026-08-31.'},
 {slug:'cr9-90-aggressive-shake',model:'CR9.90 Aggressive Shake',seriesName:'CR Series Twin Rotor',seriesSlug:'cr-series',sourceUrl:LEGACY,grossHp:544,maxHp:600,separator:'Twin Rotor',note:'Current New Holland North America CR Series page captured 2026-08-31.'},
 {slug:'cr8-90-opti-clean',model:'CR8.90 Opti-Clean',seriesName:'CR Series Twin Rotor',seriesSlug:'cr-series',sourceUrl:LEGACY,grossHp:496,maxHp:544,separator:'Twin Rotor',note:'Current New Holland North America CR Series page captured 2026-08-31.'},
 {slug:'cr9-90-opti-clean',model:'CR9.90 Opti-Clean',seriesName:'CR Series Twin Rotor',seriesSlug:'cr-series',sourceUrl:LEGACY,grossHp:544,maxHp:600,separator:'Twin Rotor',note:'Current New Holland North America CR Series page captured 2026-08-31.'},
 {slug:'cr10-90-opti-clean',model:'CR10.90 Opti-Clean',seriesName:'CR Series Twin Rotor',seriesSlug:'cr-series',sourceUrl:LEGACY,grossHp:639,maxHp:700,separator:'Twin Rotor',note:'Current New Holland North America CR Series page captured 2026-08-31.'},
];
const defs:Array<[string,string,string,string,string|null,number]>=[
 ['Machine Configuration','configuration.type','Machine configuration','text',null,1],
 ['Machine Configuration','configuration.market_scope','Official market scope','text',null,2],
 ['Engine','engine.gross_power','Gross engine power','decimal','hp',10],
 ['Engine','engine.maximum_power','Maximum engine power','decimal','hp',20],
 ['Engine','engine.displacement','Engine displacement','decimal','L',30],
 ['Engine','engine.rated_speed','Rated engine speed','integer','rpm',40],
 ['Threshing & Separating','threshing.separator_type','Separator type','text',null,10],
 ['Grain Handling','grain.grain_tank_capacity','Grain tank capacity','decimal','bu',10],
 ['Grain Handling','grain.peak_unloading_rate','Peak unloading rate','decimal','bu/sec',20],
 ['Capacities','capacities.fuel_tank','Fuel tank capacity','decimal','gal',10],
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('New Holland CR combine dependency missing');return Number(r[0].id)}
async function source(c:Parameters<DbMigration['apply']>[0],sid:number,m:Seed){const e=`new-holland-${m.slug}-us-current-2026-08`;const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[e]);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,m.sourceUrl,e,`New Holland ${m.model} combine specifications`,JSON.stringify({captured:'2026-08-31',market:'United States / North America',equipmentType:'Combine',model:m.model,note:m.note})]);return Number(x.insertId)}
async function put(c:Parameters<DbMigration['apply']>[0],mi:number,vi:number,di:number,sr:number,v:string|number,u:string|null){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mi,vi,di,typeof v==='string'?v:null,typeof v==='number'?v:null,u,sr])}
export const newHollandCRCombinesCurrentMigration:DbMigration={id:'20260831_483_new_holland_cr_combines_current',description:'Add current New Holland North America next-generation and legacy CR Twin Rotor combines',async apply(c){
 await c.query(`INSERT INTO equipment_types(name,slug) VALUES('Combine','combine') ON DUPLICATE KEY UPDATE name=VALUES(name)`);
 await c.query(`INSERT INTO manufacturers(name,slug) VALUES('New Holland','new-holland') ON DUPLICATE KEY UPDATE name=VALUES(name)`);
 const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='new-holland' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='combine' LIMIT 1`);
 let[r]=await c.query<IdRow[]>(`SELECT id FROM sources WHERE name='New Holland' AND domain='agriculture.newholland.com' LIMIT 1`);let sid=r[0]?.id?Number(r[0].id):0;if(!sid){const[x]=await c.query<ResultSetHeader>(`INSERT INTO sources(name,domain,source_type,authority_level) VALUES('New Holland','agriculture.newholland.com','manufacturer','official')`);sid=Number(x.insertId)}
 for(const s of Array.from(new Map(models.map(m=>[m.seriesSlug,{name:m.seriesName,slug:m.seriesSlug}])).values()))await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et,s.name,s.slug]);
 const d=new Map<string,number>();for(const x of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,x);d.set(x[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[x[1]]))}
 for(const m of models){const sr=await source(c,sid,m),series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug=? LIMIT 1`,[mf,et,m.seriesSlug]);await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current New Holland North America combine lineup','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[mf,et,series,m.model,m.slug]);const mi=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND equipment_type_id=? AND slug=? LIMIT 1`,[mf,et,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mi,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'NA','North America','Current North America combine specification',TRUE,?,?) ON DUPLICATE KEY UPDATE market_code=VALUES(market_code),market_name=VALUES(market_name),configuration=VALUES(configuration),is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mi,VERSION,sr,m.note]);const vi=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mi,VERSION]);const vals:Array<[string,string|number,string|null]>=[['configuration.type','Combine harvester',null],['configuration.market_scope','United States / North America',null],['engine.gross_power',m.grossHp,'hp'],['threshing.separator_type',m.separator,null]];if(m.maxHp!==undefined)vals.push(['engine.maximum_power',m.maxHp,'hp']);if(m.displacementL!==undefined)vals.push(['engine.displacement',m.displacementL,'L']);if(m.ratedRpm!==undefined)vals.push(['engine.rated_speed',m.ratedRpm,'rpm']);if(m.fuelGal!==undefined)vals.push(['capacities.fuel_tank',m.fuelGal,'gal']);if(m.grainTank!==undefined)vals.push(['grain.grain_tank_capacity',m.grainTank,'bu']);if(m.unloadRate!==undefined)vals.push(['grain.peak_unloading_rate',m.unloadRate,'bu/sec']);for(const[k,v,u]of vals){const di=d.get(k);if(!di)throw new Error(`Missing New Holland combine spec ${k}`);await put(c,mi,vi,di,sr,v,u)}}
}};
