import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow = RowDataPacket & { id: number };
const VERSION='united-states-current-2026-08';
const URL='https://www.deere.com/en-us/products-solutions/tillage/vertical-tillage/2660vt-14-ft-4-in-variable-intensity-tillage-mtax40q';
const defs:Array<[string,string,string,string,string|null,number]>=[
 ['Machine Configuration','configuration.type','Machine configuration','text',null,1],['Machine Configuration','configuration.market_scope','Official market scope','text',null,2],
 ['Tillage System','vertical_tillage.working_width_ft','Working width','decimal','ft',10],['Tillage System','vertical_tillage.available_widths','Available working widths','text',null,20],['Tillage System','vertical_tillage.gang_angle','Gang angle','text',null,30],['Tillage System','vertical_tillage.blade_type','Blade type','text',null,40],['Tillage System','vertical_tillage.blade_diameter_in','Blade diameter','decimal','in',50],['Tillage System','vertical_tillage.blade_spacing_in','Blade spacing','decimal','in',60],['Tillage System','vertical_tillage.max_depth_in','Maximum operating depth','decimal','in',70],['Tillage System','vertical_tillage.operating_speed','Operating speed','text',null,80],['Tillage System','vertical_tillage.rolling_basket','Rolling basket','text',null,90],
 ['Tractor Requirements','vertical_tillage.power_requirement','Power requirement','text',null,10],['Dimensions & Transport','vertical_tillage.transport_width_ft','Transport width','decimal','ft',10],['Dimensions & Transport','vertical_tillage.transport_height_ft','Transport height','decimal','ft',20],['Dimensions & Transport','vertical_tillage.transport_length','Transport length without rear hitch','text',null,30],['Precision Technology','vertical_tillage.depth_control','Depth control technology','text',null,10],
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('John Deere 2660VT migration dependency missing');return Number(r[0].id);}
async function src(c:Parameters<DbMigration['apply']>[0]){const[r]=await c.query<IdRow[]>(`SELECT id FROM sources WHERE name='John Deere' AND domain='deere.com' ORDER BY id LIMIT 1`);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO sources(name,domain,source_type,authority_level) VALUES('John Deere','deere.com','manufacturer','official')`);return Number(x.insertId);}
async function rec(c:Parameters<DbMigration['apply']>[0],sid:number){const externalId='john-deere-2660vt-14-ft-4-in-us-current-2026-08';const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,URL,externalId,'John Deere 2660VT 14 ft 4 in current US vertical tillage specifications',JSON.stringify({captured:'2026-08-31',market:'United States',equipmentType:'Vertical Tillage',model:'2660VT 14 ft 4 in',source:URL})]);return Number(x.insertId);}
async function putText(c:Parameters<DbMigration['apply']>[0],mid:number,vid:number,did:number,rid:number,v:string){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,NULL,NULL,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=NULL,unit=NULL,source_record_id=VALUES(source_record_id),confidence='official'`,[mid,vid,did,v,rid]);}
async function putNum(c:Parameters<DbMigration['apply']>[0],mid:number,vid:number,did:number,rid:number,v:number,u:string){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,NULL,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=NULL,value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mid,vid,did,v,u,rid]);}
export const johnDeere2660vtVerticalTillageCurrentMigration:DbMigration={id:'20260831_518_john_deere_2660vt_vertical_tillage_current',description:'Add current John Deere US 2660VT 14 ft 4 in vertical tillage configuration',async apply(c){
 await c.query(`INSERT INTO equipment_types(name,slug) VALUES('Vertical Tillage','vertical-tillage') ON DUPLICATE KEY UPDATE name=VALUES(name)`);await c.query(`INSERT INTO manufacturers(name,slug) VALUES('John Deere','john-deere') ON DUPLICATE KEY UPDATE name=VALUES(name)`);const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='john-deere' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='vertical-tillage' LIMIT 1`),sid=await src(c),rid=await rec(c,sid);
 await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'2660VT Variable Intensity Tillage','2660vt-variable-intensity') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='2660vt-variable-intensity' LIMIT 1`,[mf,et]);const ids=new Map<string,number>();for(const d of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,d);ids.set(d[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[d[1]]));}const def=(k:string)=>{const v=ids.get(k);if(!v)throw new Error(`Missing 2660VT definition ${k}`);return v;};
 await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current John Deere United States 2660VT configuration','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes)`,[mf,et,series,'2660VT 14 ft 4 in','2660vt-14-ft-4-in']);const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND equipment_type_id=? AND slug='2660vt-14-ft-4-in' LIMIT 1`,[mf,et]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mid,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States','2660VT one-section 14 ft 4 in',TRUE,?,'Current John Deere US product-page data captured 2026-08-31.') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mid,VERSION,rid]);const vid=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mid,VERSION]);
 await putText(c,mid,vid,def('configuration.type'),rid,'Variable intensity vertical tillage');await putText(c,mid,vid,def('configuration.market_scope'),rid,'United States current product page');await putNum(c,mid,vid,def('vertical_tillage.working_width_ft'),rid,14.33,'ft');await putText(c,mid,vid,def('vertical_tillage.available_widths'),rid,'14 ft 4 in; 20 ft 6 in; 25 ft 5 in; 30 ft 3 in; 33 ft 10 in; 43 ft 6 in; 49 ft 6 in');await putText(c,mid,vid,def('vertical_tillage.gang_angle'),rid,'0 - 12 degrees');await putText(c,mid,vid,def('vertical_tillage.blade_type'),rid,'Wavy-straight blade with double-cut edge');await putNum(c,mid,vid,def('vertical_tillage.blade_diameter_in'),rid,22,'in');await putNum(c,mid,vid,def('vertical_tillage.blade_spacing_in'),rid,7.25,'in');await putNum(c,mid,vid,def('vertical_tillage.max_depth_in'),rid,6,'in');await putText(c,mid,vid,def('vertical_tillage.operating_speed'),rid,'8 - 10 mph');await putText(c,mid,vid,def('vertical_tillage.rolling_basket'),rid,'ProFinish leveling system with dual hydraulic rolling baskets');await putText(c,mid,vid,def('vertical_tillage.power_requirement'),rid,'10 - 14 engine hp/ft (24.5 - 34.25 engine kW/m)');await putNum(c,mid,vid,def('vertical_tillage.transport_width_ft'),rid,15.92,'ft');await putNum(c,mid,vid,def('vertical_tillage.transport_height_ft'),rid,7.17,'ft');await putText(c,mid,vid,def('vertical_tillage.transport_length'),rid,'One-section: 30 ft 3 in; three-section: 33 ft; five-section: 40 ft');await putText(c,mid,vid,def('vertical_tillage.depth_control'),rid,'Single-point depth control and TruSet system');
 }};
