import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
const VERSION='united-states-current-2026-08';
const URL='https://www.masseyferguson.com/content/dam/public/masseyfergusonglobal/markets/en_us/assets/product-brochures/tractors/global-series/MF19B007AG-massey-ferguson-global-series-brochure-lr.pdf';
const slugs=['mf-4707','mf-4709','mf-4710','mf-5710','mf-5710-d','mf-5711','mf-6712','mf-6713'];
async function id(c:Parameters<DbMigration['apply']>[0],q:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(q,p);if(!r[0])throw Error('MF Global emissions dependency missing');return Number(r[0].id)}
export const masseyFergusonGlobalEmissionsMigration:DbMigration={id:'20260829_305_massey_ferguson_global_emissions',description:'Add official US Tier 4 Final SCR, no-DPF and no-regeneration details for MF 4700/5700/6700 Global tractors',async apply(c){
const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='massey-ferguson' LIMIT 1`);const sid=await id(c,`SELECT id FROM sources WHERE name='Massey Ferguson' AND domain='masseyferguson.com' ORDER BY id LIMIT 1`);const ext='massey-ferguson-global-series-emissions-us-brochure-2026-08';let[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[ext]);let sr=r[0]?.id?Number(r[0].id):0;if(!sr){const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,URL,ext,'Massey Ferguson US Global Series emissions and aftertreatment brochure',JSON.stringify({market:'United States',captured:'2026-08-29',emissions:'Tier 4 Final',aftertreatment:'All-in-one SCR',dpf:'No DPF',regeneration:'No DPF regeneration'})]);sr=Number(x.insertId)}
const defs=[['Engine','engine.emissions','Emissions standard'],['Emissions','emissions.aftertreatment','Aftertreatment system'],['Emissions','emissions.dpf','Diesel particulate filter (DPF)'],['Emissions','emissions.regeneration','DPF regeneration']] as const;const d=new Map<string,number>();for(const [section,key,label] of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,'text',NULL,20) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type='text'`,[section,key,label]);d.set(key,await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[key]))}
const vals=[['engine.emissions','Tier 4 Final'],['emissions.aftertreatment','All-in-one SCR'],['emissions.dpf','No DPF'],['emissions.regeneration','No DPF regeneration required']] as const;for(const slug of slugs){const mi=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,slug]);const vi=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mi,VERSION]);for(const [key,value] of vals){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,source_record_id,confidence) VALUES(?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),source_record_id=VALUES(source_record_id),confidence='official'`,[mi,vi,d.get(key),value,sr])}}
}};
