import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Seed={slug:string;model:string;hp?:number;weightLb:number;digDepth:string;powertrain:'Diesel'|'Electric';arm:string;batteryKwh?:number;voltage?:number};
const VERSION='united-states-current-2026-08';
const FAMILY_URL='https://www.bobcat.com/na/en/equipment/excavators/compact-excavators';
const E10E_URL=`${FAMILY_URL}/e10e`;
const E19E_URL=`${FAMILY_URL}/e19e`;
const models:Seed[]=[
 {slug:'e10',model:'E10',hp:10.2,weightLb:2593,digDepth:'6 ft',powertrain:'Diesel',arm:'Standard'},
 {slug:'e10e',model:'E10e',weightLb:2648,digDepth:'76.9 in',powertrain:'Electric',arm:'Standard',batteryKwh:11.5,voltage:51.8},
 {slug:'e17',model:'E17',hp:15,weightLb:3774,digDepth:'87.8 in',powertrain:'Diesel',arm:'Standard'},
 {slug:'e20',model:'E20',hp:15,weightLb:4167,digDepth:'100.2 in',powertrain:'Diesel',arm:'Standard'},
 {slug:'e19e',model:'E19e',weightLb:4212,digDepth:'101 in',powertrain:'Electric',arm:'Standard long arm',batteryKwh:17.3,voltage:51.8},
 {slug:'e26',model:'E26',hp:24.8,weightLb:6489,digDepth:'114.4 in',powertrain:'Diesel',arm:'Long arm current configuration'},
 {slug:'e32',model:'E32',hp:24.8,weightLb:7403,digDepth:'10.1 ft',powertrain:'Diesel',arm:'Standard'},
 {slug:'e32-long-arm',model:'E32 (Long-Arm)',hp:24.8,weightLb:7403,digDepth:'10.1 ft',powertrain:'Diesel',arm:'Long arm'},
 {slug:'e32-extendable-arm',model:'E32 (Extendable Arm)',hp:24.8,weightLb:7403,digDepth:'10.1 ft',powertrain:'Diesel',arm:'Extendable arm'},
 {slug:'e35-25-hp',model:'E35 (25 HP)',hp:24.8,weightLb:7659,digDepth:'121.2 in',powertrain:'Diesel',arm:'Standard'},
 {slug:'e35-25-hp-long-arm',model:'E35 (25 HP, Long-Arm)',hp:24.8,weightLb:8362,digDepth:'133 in',powertrain:'Diesel',arm:'Long arm'},
 {slug:'e35-25-hp-extendable-arm',model:'E35 (25 HP, Extendable Arm)',hp:24.8,weightLb:8590,digDepth:'153.2 in',powertrain:'Diesel',arm:'Extendable arm'},
 {slug:'e38',model:'E38',hp:33.2,weightLb:7893,digDepth:'121 in',powertrain:'Diesel',arm:'Standard'},
 {slug:'e38-long-arm',model:'E38 (Long-Arm)',hp:33.2,weightLb:8596,digDepth:'133 in',powertrain:'Diesel',arm:'Long arm'},
 {slug:'e38-extendable-arm',model:'E38 (Extendable Arm)',hp:33.2,weightLb:8824,digDepth:'153 in',powertrain:'Diesel',arm:'Extendable arm'},
 {slug:'e40',model:'E40',hp:40.4,weightLb:9180,digDepth:'130.4 in',powertrain:'Diesel',arm:'Standard'},
 {slug:'e48',model:'E48',hp:42.6,weightLb:9830,digDepth:'10.4 ft',powertrain:'Diesel',arm:'Standard; optional long or extendable arm offered'},
 {slug:'e55',model:'E55',hp:49.7,weightLb:11357,digDepth:'11.4 ft',powertrain:'Diesel',arm:'Standard'},
 {slug:'e60',model:'E60',hp:55.7,weightLb:12315,digDepth:'13.1 ft',powertrain:'Diesel',arm:'Standard'},
 {slug:'e60-long-arm',model:'E60 (Long-Arm)',hp:55.7,weightLb:12315,digDepth:'13.1 ft',powertrain:'Diesel',arm:'Long arm'},
 {slug:'e60-extendable-arm',model:'E60 (Extendable Arm)',hp:55.7,weightLb:12315,digDepth:'13.1 ft',powertrain:'Diesel',arm:'Extendable arm'},
 {slug:'e88-long-arm',model:'E88 (Long-Arm)',hp:65.4,weightLb:19600,digDepth:'182 in',powertrain:'Diesel',arm:'Long arm'},
];
const defs:Array<[string,string,string,string,string|null,number]>=[
 ['Machine Configuration','configuration.type','Machine configuration','text',null,1],['Machine Configuration','configuration.market_scope','Official market scope','text',null,2],['Machine Configuration','mini_excavator.arm_configuration','Arm configuration','text',null,10],['Machine Configuration','mini_excavator.powertrain','Powertrain','text',null,20],
 ['Engine','mini_excavator.engine_power','Published horsepower','decimal','hp',10],
 ['Loader Performance','mini_excavator.maximum_dig_depth','Maximum dig depth','text',null,10],
 ['Dimensions & Weight','mini_excavator.operating_weight','Operating weight','decimal','lb',10],
 ['Electrical','mini_excavator.battery_capacity','Gross battery capacity','decimal','kWh',10],['Electrical','mini_excavator.system_voltage','System voltage','decimal','V',20],
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('Bobcat mini excavator migration dependency missing');return Number(r[0].id);}
async function source(c:Parameters<DbMigration['apply']>[0]){const[r]=await c.query<IdRow[]>(`SELECT id FROM sources WHERE name='Bobcat' AND domain='bobcat.com' ORDER BY id LIMIT 1`);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO sources(name,domain,source_type,authority_level) VALUES('Bobcat','bobcat.com','manufacturer','official')`);return Number(x.insertId);}
async function record(c:Parameters<DbMigration['apply']>[0],sid:number,externalId:string,url:string,title:string,raw:unknown){const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,url,externalId,title,JSON.stringify(raw)]);return Number(x.insertId);}
async function put(c:Parameters<DbMigration['apply']>[0],mid:number,vid:number,did:number,rid:number,value:string|number,unit:string|null=null){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mid,vid,did,typeof value==='string'?value:null,typeof value==='number'?value:null,unit,rid]);}
export const bobcatMiniExcavatorsCurrentMigration:DbMigration={id:'20260831_551_bobcat_mini_excavators_current',description:'Add current Bobcat North America compact mini excavator configurations',async apply(c){
 await c.query(`INSERT INTO equipment_types(name,slug) VALUES('Mini Excavator','mini-excavator') ON DUPLICATE KEY UPDATE name=VALUES(name)`);await c.query(`INSERT INTO manufacturers(name,slug) VALUES('Bobcat','bobcat') ON DUPLICATE KEY UPDATE name=VALUES(name)`);const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='bobcat' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='mini-excavator' LIMIT 1`),sid=await source(c);
 const familyRid=await record(c,sid,'bobcat-mini-excavators-us-current-2026-08',FAMILY_URL,'Bobcat current North America compact excavator model and configuration listings',{captured:'2026-08-31',market:'United States / North America',equipmentType:'Mini Excavator',models:models.map(({batteryKwh,voltage,...m})=>m),notes:'Arm variants remain separate when Bobcat exposes them as distinct current configurations. E32e is intentionally not inserted because it was not present in the current family result set used for this migration.'});
 const e10eRid=await record(c,sid,'bobcat-e10e-us-current-2026-08',E10E_URL,'Bobcat E10e current North America specifications',{captured:'2026-08-31',model:'E10e',batteryKwh:11.5,voltage:51.8,operatingWeightLb:2648,digDepth:'76.9 in'});
 const e19eRid=await record(c,sid,'bobcat-e19e-us-current-2026-08',E19E_URL,'Bobcat E19e current North America specifications',{captured:'2026-08-31',model:'E19e',batteryKwh:17.3,voltage:51.8,operatingWeightLb:4212,digDepth:'101 in'});
 await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'Bobcat Current Compact Excavators','bobcat-current-compact-excavators') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='bobcat-current-compact-excavators' LIMIT 1`,[mf,et]);const ids=new Map<string,number>();for(const d of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,d);ids.set(d[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[d[1]]));}const def=(k:string)=>{const v=ids.get(k);if(!v)throw new Error(`Missing Bobcat mini excavator definition ${k}`);return v;};
 for(const m of models){const rid=m.model==='E10e'?e10eRid:m.model==='E19e'?e19eRid:familyRid;await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current Bobcat North America compact excavator configuration; arm variants remain separate when the manufacturer lists them separately','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[mf,et,series,m.model,m.slug]);const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND equipment_type_id=? AND slug=? LIMIT 1`,[mf,et,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mid,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States',?,TRUE,?,'Current Bobcat North America compact excavator data captured 2026-08-31. Maximum dig depth retains the manufacturer-published source unit instead of converting mixed ft/in values into a new derived figure.') ON DUPLICATE KEY UPDATE configuration=VALUES(configuration),is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mid,VERSION,m.arm,rid]);const vid=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mid,VERSION]);await put(c,mid,vid,def('configuration.type'),rid,'Mini excavator');await put(c,mid,vid,def('configuration.market_scope'),rid,'United States / North America current catalog');await put(c,mid,vid,def('mini_excavator.arm_configuration'),rid,m.arm);await put(c,mid,vid,def('mini_excavator.powertrain'),rid,m.powertrain);if(m.hp)await put(c,mid,vid,def('mini_excavator.engine_power'),rid,m.hp,'hp');await put(c,mid,vid,def('mini_excavator.maximum_dig_depth'),rid,m.digDepth);await put(c,mid,vid,def('mini_excavator.operating_weight'),rid,m.weightLb,'lb');if(m.batteryKwh)await put(c,mid,vid,def('mini_excavator.battery_capacity'),rid,m.batteryKwh,'kWh');if(m.voltage)await put(c,mid,vid,def('mini_excavator.system_voltage'),rid,m.voltage,'V');}
}};
