import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Model={slug:string;model:string;runningGear:string;ratedHp?:number;ratedText?:string;maxEpmHp:number;wheelbase?:number};
const SOURCE_URL='https://agriculture.newholland.com/en-us/nar/products/tractors-telehandlers/genesis-t8-series-with-plm-intelligence';
const EXTERNAL_ID='new-holland-genesis-t8-current-us-2026-08';
const VERSION='united-states-current-2026-08';
const models:Model[]=[
 {slug:'t8-320',model:'T8.320',runningGear:'Wheeled',ratedHp:250,maxEpmHp:320,wheelbase:136},
 {slug:'t8-350',model:'T8.350',runningGear:'Wheeled',ratedHp:280,maxEpmHp:351,wheelbase:136},
 {slug:'t8-380',model:'T8.380',runningGear:'Wheeled',ratedHp:311,maxEpmHp:381,wheelbase:136},
 {slug:'t8-410',model:'T8.410',runningGear:'Wheeled',ratedHp:340,maxEpmHp:409,wheelbase:136},
 {slug:'t8-435',model:'T8.435',runningGear:'Wheeled',ratedText:'380 hp Auto Command / 396 hp Ultra Command',maxEpmHp:435,wheelbase:140},
 {slug:'t8-410-smarttrax',model:'T8.410 SmartTrax',runningGear:'SmartTrax rear tracks',ratedHp:340,maxEpmHp:409},
 {slug:'t8-435-smarttrax',model:'T8.435 SmartTrax',runningGear:'SmartTrax rear tracks',ratedText:'380 hp Auto Command / 396 hp Ultra Command',maxEpmHp:435},
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('New Holland GENESIS T8 dependency missing');return Number(r[0].id)}
export const newHollandGenesisT8CurrentSpecsMigration:DbMigration={id:'20260829_285_new_holland_genesis_t8_current_specs',description:'Add current official US New Holland GENESIS T8 and SmartTrax tractor specifications',async apply(c){
 const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='new-holland' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='tractor' LIMIT 1`),sid=await id(c,`SELECT id FROM sources WHERE name='New Holland' AND domain='agriculture.newholland.com' LIMIT 1`);
 const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[EXTERNAL_ID]);let sr=r[0]?.id?Number(r[0].id):0;if(!sr){const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title) VALUES(?,?,?,'New Holland US GENESIS T8 current specifications')`,[sid,SOURCE_URL,EXTERNAL_ID]);sr=Number(x.insertId)}
 await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'GENESIS T8 Series','genesis-t8-series') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='genesis-t8-series' LIMIT 1`,[mf,et]);
 const defs:Array<[string,string,string,string,string|null,number]>=[['Machine Configuration','configuration.running_gear','Running gear','text',null,2],['Engine','engine.make','Engine manufacturer','text',null,1],['Engine','engine.model','Engine model','text',null,2],['Engine','engine.displacement','Engine displacement','decimal','L',20],['Engine','engine.rated_power','Rated engine power','decimal','hp',10],['Engine','engine.rated_power_configuration','Rated engine power by transmission','text',null,11],['Engine','engine.max_epm_power','Maximum EPM power','decimal','hp',12],['Maintenance','maintenance.engine_service_interval','Engine service interval','integer','hours',10],['Transmission','transmission.options','Transmission options','text',null,20],['Hydraulics','hydraulics.standard_flow','Standard hydraulic flow','decimal','L/min',10],['Hydraulics','hydraulics.optional_flow','Optional MegaFlow hydraulic flow','decimal','L/min',11],['Dimensions','dimensions.wheelbase','Wheelbase','decimal','in',10]];for(const d of defs)await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,d);
 for(const m of models){await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current US New Holland GENESIS T8 high-horsepower tractor','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes)`,[mf,et,series,m.model,m.slug]);const mi=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mi,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States','GENESIS T8 current US configuration',TRUE,?,'Official New Holland North America current GENESIS T8 data captured August 2026.') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mi,VERSION,sr]);const vi=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mi,VERSION]);const vals:Array<[string,string|number,string|null]>=[['configuration.running_gear',m.runningGear,null],['engine.make','FPT Industrial',null],['engine.model','Cursor 9',null],['engine.displacement',8.7,'L'],['engine.max_epm_power',m.maxEpmHp,'hp'],['maintenance.engine_service_interval',600,'hours'],['transmission.options','Ultra Command full powershift or Auto Command CVT depending on model/configuration',null],['hydraulics.standard_flow',223.3,'L/min'],['hydraulics.optional_flow',325.5,'L/min']];if(m.ratedHp!==undefined)vals.push(['engine.rated_power',m.ratedHp,'hp']);if(m.ratedText)vals.push(['engine.rated_power_configuration',m.ratedText,null]);if(m.wheelbase!==undefined)vals.push(['dimensions.wheelbase',m.wheelbase,'in']);for(const[k,v,u]of vals){const di=await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[k]);await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mi,vi,di,typeof v==='string'?v:null,typeof v==='number'?v:null,u,sr])}}
}};
