import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Model={slug:string;model:string;runningGear:string;ratedHp?:number;peakHp?:number;frame:string};
const SOURCE_URL='https://agriculture.newholland.com/en-us/nar/products/tractors-telehandlers/t9-with-plm-intelligence';
const EXTERNAL_ID='new-holland-t9-current-us-2026-08';
const VERSION='united-states-current-2026-08';
const models:Model[]=[
 {slug:'t9-470',model:'T9.470',runningGear:'Wheeled',ratedHp:425,peakHp:467,frame:'Row crop frame'},
 {slug:'t9-520',model:'T9.520',runningGear:'Wheeled',ratedHp:475,peakHp:522,frame:'Row crop frame'},
 {slug:'t9-520-smarttrax',model:'T9.520 SmartTrax',runningGear:'SmartTrax',ratedHp:475,peakHp:522,frame:'Row crop frame'},
 {slug:'t9-580',model:'T9.580',runningGear:'Wheeled',ratedHp:525,peakHp:578,frame:'Row crop frame'},
 {slug:'t9-580-smarttrax',model:'T9.580 SmartTrax',runningGear:'SmartTrax',ratedHp:525,peakHp:578,frame:'Row crop frame'},
 {slug:'t9-615',model:'T9.615',runningGear:'Wheeled',ratedHp:555,peakHp:614,frame:'High horsepower wide frame'},
 {slug:'t9-615-smarttrax',model:'T9.615 SmartTrax',runningGear:'SmartTrax',ratedHp:555,peakHp:614,frame:'High horsepower wide frame'},
 {slug:'t9-655',model:'T9.655',runningGear:'Wheeled',ratedHp:595,peakHp:656,frame:'High horsepower wide frame'},
 {slug:'t9-700',model:'T9.700',runningGear:'Wheeled',frame:'High horsepower wide frame'},
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('New Holland T9 dependency missing');return Number(r[0].id)}
export const newHollandT9CurrentSpecsMigration:DbMigration={id:'20260829_286_new_holland_t9_current_specs',description:'Add current official US New Holland T9 wheeled and visible SmartTrax tractor specifications',async apply(c){
 const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='new-holland' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='tractor' LIMIT 1`),sid=await id(c,`SELECT id FROM sources WHERE name='New Holland' AND domain='agriculture.newholland.com' LIMIT 1`);
 const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[EXTERNAL_ID]);let sr=r[0]?.id?Number(r[0].id):0;if(!sr){const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title) VALUES(?,?,?,'New Holland US T9 Series current specifications')`,[sid,SOURCE_URL,EXTERNAL_ID]);sr=Number(x.insertId)}
 await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'T9 Series','t9-series') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='t9-series' LIMIT 1`,[mf,et]);
 const defs:Array<[string,string,string,string,string|null,number]>=[['Machine Configuration','configuration.running_gear','Running gear','text',null,1],['Machine Configuration','configuration.frame_size','Frame size','text',null,2],['Engine','engine.make','Engine manufacturer','text',null,1],['Engine','engine.model','Engine model','text',null,2],['Engine','engine.displacement','Engine displacement','decimal','L',20],['Engine','engine.rated_power','Rated engine power','decimal','hp',10],['Engine','engine.peak_power','Peak engine power','decimal','hp',11],['Engine','engine.emissions','Emissions','text',null,50],['Maintenance','maintenance.engine_service_interval','Engine service interval','integer','hours',10],['Transmission','transmission.options','Transmission options','text',null,20],['Hydraulics','hydraulics.standard_flow','Standard hydraulic flow','decimal','L/min',10],['Hydraulics','hydraulics.high_flow','High-flow hydraulic capacity','decimal','L/min',11],['Hydraulics','hydraulics.max_total_flow','Maximum total hydraulic flow','decimal','L/min',12]];for(const d of defs)await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,d);
 for(const m of models){await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current US New Holland T9 high-horsepower 4WD tractor','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes)`,[mf,et,series,m.model,m.slug]);const mi=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mi,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States','T9 current US configuration',TRUE,?,'Official New Holland North America current T9 data captured August 2026. T9.700 is included as a current model but no numeric rated or peak power is stored because the visible US model row did not expose those values.') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mi,VERSION,sr]);const vi=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mi,VERSION]);const vals:Array<[string,string|number,string|null]>=[['configuration.running_gear',m.runningGear,null],['configuration.frame_size',m.frame,null],['engine.make','FPT Industrial',null],['engine.model','Cursor',null],['engine.displacement',13,'L'],['engine.emissions','Tier 4B / Final Stage V',null],['maintenance.engine_service_interval',1800,'hours'],['transmission.options','Ultra Command full powershift or Auto Command CVT depending on model/configuration',null],['hydraulics.standard_flow',159,'L/min'],['hydraulics.high_flow',216,'L/min'],['hydraulics.max_total_flow',427,'L/min']];if(m.ratedHp!==undefined)vals.push(['engine.rated_power',m.ratedHp,'hp']);if(m.peakHp!==undefined)vals.push(['engine.peak_power',m.peakHp,'hp']);for(const[k,v,u]of vals){const di=await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[k]);await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mi,vi,di,typeof v==='string'?v:null,typeof v==='number'?v:null,u,sr])}}
}};
