import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Seed={slug:string;model:string;wheels:number;weightLb:number;weightKg:number;maxWidth:string;plus:boolean};
const VERSION='north-america-current-2026-08';
const FAMILY_URL='https://agriculture.newholland.com/en-us/nar/products/haytools-spreaders/procart-and-procart-plus-deluxe-carted-wheel-rakes';
const models:Seed[]=[
 {slug:'procart-819-8-wheel',model:'ProCart 819 8-Wheel',wheels:8,weightLb:1675,weightKg:760,maxWidth:'18 ft (5.5 m)',plus:false},
 {slug:'procart-1022-10-wheel',model:'ProCart 1022 10-Wheel',wheels:10,weightLb:1875,weightKg:850,maxWidth:'21 ft (6.4 m)',plus:false},
 {slug:'procart-1225-12-wheel',model:'ProCart 1225 12-Wheel',wheels:12,weightLb:2115,weightKg:960,maxWidth:'24 ft 6 in (7.5 m)',plus:false},
 {slug:'procart-1225-plus-12-wheel',model:'ProCart 1225 PLUS 12-Wheel',wheels:12,weightLb:2736,weightKg:1241,maxWidth:'25 ft 1 in (7.65 m)',plus:true},
 {slug:'procart-1428-plus-14-wheel',model:'ProCart 1428 PLUS 14-Wheel',wheels:14,weightLb:3038,weightKg:1378,maxWidth:'28 ft (8.5 m)',plus:true},
];
const defs:Array<[string,string,string,string,string|null,number]>=[
 ['Machine Configuration','configuration.type','Machine configuration','text',null,1],['Machine Configuration','configuration.market_scope','Official market scope','text',null,2],
 ['Raking System','rake.number_of_wheels','Number of rake wheels','integer',null,10],['Raking System','rake.maximum_working_width','Maximum raking width','text',null,20],['Raking System','rake.wheel_flotiation','Rake wheel flotation','text',null,30],['Raking System','rake.operation','Raking modes','text',null,40],
 ['Dimensions & Weight','rake.weight','Machine weight','decimal','lb',10],['Machine Configuration','rake.plus_configuration','PLUS configuration','text',null,20],
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('New Holland ProCart migration dependency missing');return Number(r[0].id);}
async function src(c:Parameters<DbMigration['apply']>[0]){const[r]=await c.query<IdRow[]>(`SELECT id FROM sources WHERE name='New Holland' AND domain='agriculture.newholland.com' ORDER BY id LIMIT 1`);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO sources(name,domain,source_type,authority_level) VALUES('New Holland','agriculture.newholland.com','manufacturer','official')`);return Number(x.insertId);}
async function rec(c:Parameters<DbMigration['apply']>[0],sid:number,m:Seed){const externalId=`new-holland-${m.slug}-wheel-rake-na-current-2026-08`;const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,FAMILY_URL,externalId,`New Holland ${m.model} current North America wheel rake specifications`,JSON.stringify({captured:'2026-08-31',market:'North America',equipmentType:'Wheel Rake',...m})]);return Number(x.insertId);}
async function put(c:Parameters<DbMigration['apply']>[0],mid:number,vid:number,did:number,rid:number,v:string|number,u:string|null=null){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mid,vid,did,typeof v==='string'?v:null,typeof v==='number'?v:null,u,rid]);}
export const newHollandProCartWheelRakesCurrentMigration:DbMigration={id:'20260831_505_new_holland_procart_wheel_rakes_current',description:'Add current New Holland North America ProCart and ProCart PLUS wheel rakes',async apply(c){
 await c.query(`INSERT INTO equipment_types(name,slug) VALUES('Wheel Rake','wheel-rake') ON DUPLICATE KEY UPDATE name=VALUES(name)`);await c.query(`INSERT INTO manufacturers(name,slug) VALUES('New Holland','new-holland') ON DUPLICATE KEY UPDATE name=VALUES(name)`);const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='new-holland' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='wheel-rake' LIMIT 1`),sid=await src(c);await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'ProCart Wheel Rakes','procart-wheel-rakes') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='procart-wheel-rakes' LIMIT 1`,[mf,et]);const ids=new Map<string,number>();for(const d of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,d);ids.set(d[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[d[1]]));}const def=(k:string)=>{const v=ids.get(k);if(!v)throw new Error(`Missing rake definition ${k}`);return v;};
 for(const m of models){const rid=await rec(c,sid,m);await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current New Holland North America ProCart wheel rake lineup','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes)`,[mf,et,series,m.model,m.slug]);const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND equipment_type_id=? AND slug=? LIMIT 1`,[mf,et,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mid,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'NA','North America','Current ProCart wheel rake specification',TRUE,?,'Current New Holland North America product-page data captured 2026-08-31.') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mid,VERSION,rid]);const vid=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mid,VERSION]);await put(c,mid,vid,def('configuration.type'),rid,'Carted wheel rake');await put(c,mid,vid,def('configuration.market_scope'),rid,'New Holland North America current product line');await put(c,mid,vid,def('rake.number_of_wheels'),rid,m.wheels);await put(c,mid,vid,def('rake.maximum_working_width'),rid,m.maxWidth);await put(c,mid,vid,def('rake.wheel_flotiation'),rid,'Individual floating rake wheels with adjustable compression springs');await put(c,mid,vid,def('rake.operation'),rid,'Single-side raking, V-raking, or windrow turning using hydraulic lock valves');await put(c,mid,vid,def('rake.weight'),rid,m.weightLb,'lb');await put(c,mid,vid,def('rake.plus_configuration'),rid,m.plus?'ProCart PLUS heavy-duty configuration':'Standard ProCart configuration');}
 }};
