import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Seed={slug:string;model:string;url:string;frame:string;width:string;transport:string;precision?:string};
const VERSION='united-states-current-2026-08';
const FAMILY_URL='https://www.caseih.com/en-us/unitedstates/products/tillage/speed-tiller-high-speed-disk';
const models:Seed[]=[
 {slug:'speed-tiller-465',model:'Speed-Tiller 465',url:`${FAMILY_URL}/speed-tiller-465`,frame:'Rigid 3-point mount',width:'5.7 - 18 ft',transport:'6.9 - 19.4 ft'},
 {slug:'speed-tiller-475',model:'Speed-Tiller 475',url:`${FAMILY_URL}/speed-tiller-475`,frame:'Trailing and folding',width:'13 - 41 ft',transport:'9.6 - 15.7 ft',precision:'Soil Command standard on 21-ft through 41-ft Speed-Tiller 475 models'},
];
const defs:Array<[string,string,string,string,string|null,number]>=[
 ['Machine Configuration','configuration.type','Machine configuration','text',null,1],['Machine Configuration','configuration.market_scope','Official market scope','text',null,2],
 ['Tillage System','high_speed_disk.frame_type','Frame type','text',null,10],['Tillage System','high_speed_disk.working_width','Operating width','text',null,20],['Tillage System','high_speed_disk.operating_depth','Operating depth','text',null,30],['Tillage System','high_speed_disk.blade_system','Blade system','text',null,40],['Tillage System','high_speed_disk.leveling_system','Leveling and depth-control system','text',null,50],
 ['Dimensions & Transport','high_speed_disk.transport_width','Transport width','text',null,10],['Precision Technology','high_speed_disk.precision_control','Precision tillage control','text',null,10],
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('Case IH Speed-Tiller migration dependency missing');return Number(r[0].id);}
async function src(c:Parameters<DbMigration['apply']>[0]){const[r]=await c.query<IdRow[]>(`SELECT id FROM sources WHERE name='Case IH' AND domain='caseih.com' ORDER BY id LIMIT 1`);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO sources(name,domain,source_type,authority_level) VALUES('Case IH','caseih.com','manufacturer','official')`);return Number(x.insertId);}
async function rec(c:Parameters<DbMigration['apply']>[0],sid:number,m:Seed){const externalId=`case-ih-${m.slug}-high-speed-disk-us-current-2026-08`;const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,m.url,externalId,`Case IH ${m.model} current US high-speed disk specifications`,JSON.stringify({captured:'2026-08-31',market:'United States',equipmentType:'High-Speed Disk',familySource:FAMILY_URL,...m})]);return Number(x.insertId);}
async function put(c:Parameters<DbMigration['apply']>[0],mid:number,vid:number,did:number,rid:number,v:string){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,NULL,NULL,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=NULL,unit=NULL,source_record_id=VALUES(source_record_id),confidence='official'`,[mid,vid,did,v,rid]);}
export const caseIhSpeedTillerHighSpeedDisksCurrentMigration:DbMigration={id:'20260831_519_case_ih_speed_tiller_high_speed_disks_current',description:'Add current Case IH US Speed-Tiller 465 and 475 high-speed disks',async apply(c){
 await c.query(`INSERT INTO equipment_types(name,slug) VALUES('High-Speed Disk','high-speed-disk') ON DUPLICATE KEY UPDATE name=VALUES(name)`);await c.query(`INSERT INTO manufacturers(name,slug) VALUES('Case IH','case-ih') ON DUPLICATE KEY UPDATE name=VALUES(name)`);const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='case-ih' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='high-speed-disk' LIMIT 1`),sid=await src(c);await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'Speed-Tiller','speed-tiller') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='speed-tiller' LIMIT 1`,[mf,et]);const ids=new Map<string,number>();for(const d of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,d);ids.set(d[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[d[1]]));}const def=(k:string)=>{const v=ids.get(k);if(!v)throw new Error(`Missing high-speed disk definition ${k}`);return v;};
 for(const m of models){const rid=await rec(c,sid,m);await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current Case IH United States high-speed disk lineup','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes)`,[mf,et,series,m.model,m.slug]);const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND equipment_type_id=? AND slug=? LIMIT 1`,[mf,et,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mid,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States','Current Speed-Tiller specification',TRUE,?,'Current Case IH US product-page data captured 2026-08-31.') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mid,VERSION,rid]);const vid=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mid,VERSION]);await put(c,mid,vid,def('configuration.type'),rid,'High-speed disk');await put(c,mid,vid,def('configuration.market_scope'),rid,'United States current catalog');await put(c,mid,vid,def('high_speed_disk.frame_type'),rid,m.frame);await put(c,mid,vid,def('high_speed_disk.working_width'),rid,m.width);await put(c,mid,vid,def('high_speed_disk.operating_depth'),rid,'3 - 6 in in fall; shallower spring operation described by manufacturer');await put(c,mid,vid,def('high_speed_disk.blade_system'),rid,'Laterally adjustable, indexed, independently mounted blades with rubber-torsioned disk arms');await put(c,mid,vid,def('high_speed_disk.leveling_system'),rid,'Constant-level or floating hitch modes with hydraulically positioned conditioner roller');await put(c,mid,vid,def('high_speed_disk.transport_width'),rid,m.transport);if(m.precision)await put(c,mid,vid,def('high_speed_disk.precision_control'),rid,m.precision);}
 }};
