import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
const modelSlugs=['maxxum-115','maxxum-125','maxxum-135','maxxum-145','maxxum-150'] as const;
const loaders=[
  {slug:'l113-maxxum',model:'L113',url:'https://www.caseih.com/en-us/unitedstates/products/loaders-attachments/l11-series-loaders/l113-maxxum',externalId:'case-ih-maxxum-l113-loader-current',lift:'2,381 lb max lift capacity; 3,439 lb boom breakout force',height:'131 in max height',configuration:'Case IH L113 for Maxxum Series. Compatibility is restricted to Maxxum tractors equipped with 2WD front axles.',note:'Official Case IH L113 Maxxum page lists Maxxum 115, 125, 135, 145 and 150; loader requires a 2WD front axle.'},
  {slug:'l115-maxxum',model:'L115',url:'https://www.caseih.com/en-us/unitedstates/products/loaders-attachments/l11-series-loaders/l115',externalId:'case-ih-maxxum-l115-loader-current',lift:'5,203 lb max lift capacity; 5,975 lb boom breakout force',height:'150 in max height',configuration:'Case IH L115 for Maxxum Series.',note:'Official Case IH L115 page lists Maxxum 115, 125, 135, 145 and 150 as compatible tractors.'},
] as const;
async function selectId(connection:Parameters<DbMigration['apply']>[0],sql:string,params:unknown[]=[]){const [rows]=await connection.query<IdRow[]>(sql,params);if(!rows[0])throw new Error('Missing Case IH Maxxum loader migration dependency.');return Number(rows[0].id);}
async function ensureSource(connection:Parameters<DbMigration['apply']>[0],sourceId:number,externalId:string,url:string,title:string,rawReference:unknown){const [rows]=await connection.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(rows[0])return Number(rows[0].id);const [result]=await connection.query<ResultSetHeader>(`INSERT INTO source_records (source_id,url,external_id,title,raw_reference) VALUES (?,?,?,?,?)`,[sourceId,url,externalId,title,JSON.stringify(rawReference)]);return Number(result.insertId);}

export const caseIHMaxxumLoadersMigration:DbMigration={
  id:'20260828_234_case_ih_maxxum_loaders',
  description:'Add official Case IH L113 and L115 loader compatibility for current Maxxum 115-150 tractors',
  async apply(connection){
    const manufacturerId=await selectId(connection,`SELECT id FROM manufacturers WHERE slug='case-ih' LIMIT 1`);
    let [sourceRows]=await connection.query<IdRow[]>(`SELECT id FROM sources WHERE name='Case IH' AND domain='caseih.com' ORDER BY id LIMIT 1`);let sourceId=sourceRows[0]?.id?Number(sourceRows[0].id):0;if(!sourceId){const [result]=await connection.query<ResultSetHeader>(`INSERT INTO sources (name,domain,source_type,authority_level) VALUES ('Case IH','caseih.com','manufacturer','official')`);sourceId=Number(result.insertId);}
    for(const loader of loaders){const sourceRecordId=await ensureSource(connection,sourceId,loader.externalId,loader.url,`Case IH US ${loader.model} for Maxxum Series official compatibility`,{loader:loader.model,compatibleModels:['Maxxum 115','Maxxum 125','Maxxum 135','Maxxum 145','Maxxum 150'],configuration:loader.configuration});await connection.query(`INSERT INTO attachments (manufacturer_id,attachment_type,model_name,slug,lift_capacity_text,lift_height_text,configuration_text,data_status) VALUES (?,'front-loader',?,?,?,?,?,'verified') ON DUPLICATE KEY UPDATE model_name=VALUES(model_name),lift_capacity_text=VALUES(lift_capacity_text),lift_height_text=VALUES(lift_height_text),configuration_text=VALUES(configuration_text),data_status='verified'`,[manufacturerId,loader.model,loader.slug,loader.lift,loader.height,loader.configuration]);const attachmentId=await selectId(connection,`SELECT id FROM attachments WHERE manufacturer_id=? AND attachment_type='front-loader' AND slug=? LIMIT 1`,[manufacturerId,loader.slug]);for(const slug of modelSlugs){const machineId=await selectId(connection,`SELECT m.id FROM machines m JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='case-ih' AND m.slug=? LIMIT 1`,[slug]);await connection.query(`INSERT INTO machine_attachments (machine_id,attachment_id,compatibility_note,source_record_id,confidence) VALUES (?,?,?,?,'official') ON DUPLICATE KEY UPDATE compatibility_note=VALUES(compatibility_note),source_record_id=VALUES(source_record_id),confidence='official'`,[machineId,attachmentId,loader.note,sourceRecordId]);}}
  }
};
