import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow = RowDataPacket & { id:number };
const VERSION='united-states-current-2026-09';
const LIVE_URL='https://www.kubotausa.com/equipment-series/scl-series';
const defs:Array<[string,string,string,string,string|null,number]>=[
  ['Machine Configuration','configuration.type','Machine configuration','text',null,1],
  ['Machine Configuration','configuration.market_scope','Official market scope','text',null,2],
  ['Engine','kubota.scl.engine_type','Engine type','text',null,10],
  ['Engine','kubota.scl.displacement','Engine displacement','decimal','cu in',20],
  ['Engine','kubota.scl.gross_power','SAE J1995 gross engine power','decimal','hp',30],
  ['Engine','kubota.scl.rated_speed','Rated engine speed','decimal','rpm',40],
  ['Dimensions & Weight','kubota.scl.overall_width_bucket','Overall width with standard bucket','decimal','in',10],
  ['Dimensions & Weight','kubota.scl.overall_height','Overall height','decimal','in',20],
  ['Dimensions & Weight','kubota.scl.transport_length','Transport length with standard bucket','decimal','in',30],
  ['Dimensions & Weight','kubota.scl.track_width','Track width','decimal','in',40],
  ['Loader Performance','kubota.scl.rated_operating_capacity','Rated operating capacity at 35% tipping load','decimal','lb',10],
  ['Loader Performance','kubota.scl.tipping_load','Tipping load','decimal','lb',20],
  ['Hydraulics','kubota.scl.auxiliary_pressure','Auxiliary hydraulic pressure','decimal','psi',10],
  ['Attachment System','kubota.scl.coupler','Attachment coupler','text',null,10],
  ['Controls','kubota.scl.display','Operator display','text',null,10],
  ['Controls','kubota.scl.start_security','Start and security','text',null,20],
  ['Controls','kubota.scl.loader_controls','Loader and auxiliary controls','text',null,30],
  ['Safety','kubota.scl.operator_presence','Operator-presence safety','text',null,10],
  ['Service','kubota.scl.track_rollers','Track roller maintenance','text',null,10],
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('Kubota SCL1000 migration dependency missing');return Number(r[0].id);}
async function source(c:Parameters<DbMigration['apply']>[0]){const[r]=await c.query<IdRow[]>(`SELECT id FROM sources WHERE name='Kubota' AND domain='kubotausa.com' ORDER BY id LIMIT 1`);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO sources(name,domain,source_type,authority_level) VALUES('Kubota','kubotausa.com','manufacturer','official')`);return Number(x.insertId);}
async function record(c:Parameters<DbMigration['apply']>[0],sid:number){const externalId='kubota-scl1000-live-current-2026-09';const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(r[0])return Number(r[0].id);const raw={captured:'2026-09-01',model:'SCL1000',specs:{grossHp:23.7,displacementCuIn:54.8,widthIn:36,heightIn:55.7,transportLengthIn:107.7,roc35Lb:1000,tippingLoadLb:2857,auxPressurePsi:2800,trackWidthIn:9.8},features:['4.3 in color LCD','keyless start with password protection','standard heavy-duty CII coupler','optional welded 2-lever coupler','hydraulic pilot-operated loader and drive valves','right-hand loader joystick','continuous auxiliary flow button','operator presence sensor','permanently sealed and lubricated track rollers']};const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,LIVE_URL,externalId,'Kubota USA current SCL1000 live specifications and features',JSON.stringify(raw)]);return Number(x.insertId);}
async function put(c:Parameters<DbMigration['apply']>[0],mid:number,vid:number,did:number,rid:number,value:string|number,unit:string|null=null){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mid,vid,did,typeof value==='string'?value:null,typeof value==='number'?value:null,unit,rid]);}
export const kubotaCurrentScl1000Migration:DbMigration={
  id:'20260901_582_kubota_current_scl1000',description:'Add current Kubota USA SCL1000 Stand-On Compact Loader from the live SCL Series page',
  async apply(c){
    await c.query(`INSERT INTO equipment_types(name,slug) VALUES('Stand-On Compact Loader','stand-on-compact-loader') ON DUPLICATE KEY UPDATE name=VALUES(name)`);await c.query(`INSERT INTO manufacturers(name,slug) VALUES('Kubota','kubota') ON DUPLICATE KEY UPDATE name=VALUES(name)`);
    const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='kubota' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='stand-on-compact-loader' LIMIT 1`),sid=await source(c),rid=await record(c,sid);
    const seriesSlug='kubota-scl-series';await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'Kubota SCL Series',?) ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et,seriesSlug]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug=? LIMIT 1`,[mf,et,seriesSlug]);
    const ids=new Map<string,number>();for(const d of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,d);ids.set(d[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[d[1]]));}const def=(k:string)=>{const v=ids.get(k);if(!v)throw new Error(`Missing Kubota SCL1000 definition ${k}`);return v;};
    await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current Kubota USA Stand-On Compact Loader','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[mf,et,series,'SCL1000','scl1000']);const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND equipment_type_id=? AND slug='scl1000' LIMIT 1`,[mf,et]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mid,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States','SCL1000 Stand-On Compact Loader',TRUE,?,?) ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),configuration=VALUES(configuration),notes=VALUES(notes)`,[mid,VERSION,rid,'Current live Kubota USA SCL Series specifications captured 2026-09-01. This value set uses the live page, including the current 23.7 hp figure, rather than older brochure generations that have published a different horsepower value.']);const vid=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mid,VERSION]);const vals:Array<[string,string|number,string|null]>=[['configuration.type','Stand-On Compact Loader',null],['configuration.market_scope','United States current lineup',null],['kubota.scl.engine_type','Water-cooled 4-cycle 3-cylinder turbo diesel, EPA Tier 4',null],['kubota.scl.displacement',54.8,'cu in'],['kubota.scl.gross_power',23.7,'hp'],['kubota.scl.rated_speed',2800,'rpm'],['kubota.scl.overall_width_bucket',36,'in'],['kubota.scl.overall_height',55.7,'in'],['kubota.scl.transport_length',107.7,'in'],['kubota.scl.track_width',9.8,'in'],['kubota.scl.rated_operating_capacity',1000,'lb'],['kubota.scl.tipping_load',2857,'lb'],['kubota.scl.auxiliary_pressure',2800,'psi'],['kubota.scl.coupler','Heavy-duty CII coupler standard; welded 2-lever style coupler optional',null],['kubota.scl.display','4.3 in color LCD with diagnostics and service reminders',null],['kubota.scl.start_security','Keyless start with password protection',null],['kubota.scl.loader_controls','Hydraulic pilot-operated loader/drive valves; right-hand loader joystick; auxiliary controls and continuous flow from joystick',null],['kubota.scl.operator_presence','Platform operator-presence sensor automatically engages parking brake when operator steps off',null],['kubota.scl.track_rollers','Permanently sealed and lubricated track rollers',null]];for(const[k,v,u]of vals)await put(c,mid,vid,def(k),rid,v,u);
  }
};