import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Seed={slug:string;name:string;hp:number;pto:string;engine:string;cyl:number;fuelGal:number;variants:string;transmissions:string;station:string;wheelbaseIn:number;hitchLb:number;hydraulic:string};
const VERSION='united-states-current-2026-08';
const PAGE='https://mccormick-tractors.com/us/en/products/x1.html';
const BROCHURE='https://www.mccormick.it/wp-content/uploads/2023/05/X1-Brochure-2023.pdf';
const models:Seed[]=[
 {slug:'x1-25',name:'X1.25',hp:24,pto:'18 hp',engine:'1.2 L Kukje diesel',cyl:3,fuelGal:6.2,variants:'X1.25M / X1.25H',transmissions:'6F x 2R mechanical / 2-range HST',station:'ROPS',wheelbaseIn:60.0,hitchLb:1500,hydraulic:'4.8 gpm remote flow'},
 {slug:'x1-35',name:'X1.35',hp:35,pto:'29 hp',engine:'1.7 L Kukje diesel',cyl:3,fuelGal:9.3,variants:'X1.35 / X1.35H (current dealer naming also uses X1.35M for mechanical)',transmissions:'12F x 12R synchronized shuttle / 3-range HST',station:'ROPS',wheelbaseIn:70.9,hitchLb:3306,hydraulic:'open center; 2 rear remotes in family literature'},
 {slug:'x1-37',name:'X1.37',hp:37,pto:'33 hp mechanical / 32 hp hydrostatic',engine:'2.01 L Kukje diesel',cyl:4,fuelGal:12.0,variants:'X1.37C / X1.37HC',transmissions:'12F x 12R mechanical / 3-range HST',station:'Cab',wheelbaseIn:71.1,hitchLb:3306,hydraulic:'11.1 gpm main pump; 5.0 gpm steering pump'},
 {slug:'x1-45',name:'X1.45',hp:47,pto:'38 hp in current May-2023 North America brochure',engine:'2.3 L Kukje diesel',cyl:4,fuelGal:9.3,variants:'X1.45 / X1.45C',transmissions:'12F x 12R synchronized shuttle',station:'ROPS / Cab',wheelbaseIn:70.9,hitchLb:3306,hydraulic:'11.1 gpm remote flow'},
 {slug:'x1-55',name:'X1.55',hp:55,pto:'47 hp',engine:'2.3 L Kukje turbocharged diesel',cyl:4,fuelGal:9.3,variants:'X1.55M / X1.55H / X1.55C / X1.55HC in May-2023 brochure',transmissions:'12F x 12R synchronized shuttle / 3-range HST',station:'ROPS / Cab',wheelbaseIn:70.9,hitchLb:3306,hydraulic:'11.1 gpm remote flow'},
];
const defs:Array<[string,string,string,string,string|null,number]>=[
 ['Machine Configuration','configuration.station','Operator station','text',null,1],['Machine Configuration','configuration.official_variants','Official brochure variants','text',null,2],
 ['Engine','engine.make','Engine manufacturer','text',null,1],['Engine','engine.type','Engine type','text',null,2],['Engine','engine.cylinders','Cylinders','integer',null,4],['Engine','emissions.standard','Emissions standard','text',null,5],['Engine','engine.gross_power','Rated engine power','decimal','hp',8],['Engine','engine.rated_speed','Rated engine speed','integer','rpm',9],
 ['Transmission','transmission.standard','Available transmission families','text',null,10],['PTO','pto.rated_power_text','PTO power by configuration','text',null,10],['PTO','pto.rear_description','Rear PTO','text',null,20],
 ['Hydraulics','hydraulics.system_type','Hydraulic system','text',null,5],['Hydraulics','hydraulics.published_flow','Published hydraulic flow','text',null,20],['Hydraulics','hitch.category','3-point hitch category','text',null,40],['Hydraulics','hitch.lift_capacity','3-point hitch lift capacity at ball ends','decimal','lb',50],
 ['Capacities','capacities.fuel_tank','Fuel tank capacity','decimal','gal',10],['Dimensions & Weight','dimensions.wheelbase','Wheelbase','decimal','in',40]
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('McCormick X1 migration dependency missing');return Number(r[0].id)}
async function source(c:Parameters<DbMigration['apply']>[0],sid:number,eid:string,url:string,title:string,raw:unknown){const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[eid]);if(r[0])return Number(r[0].id);const[i]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,url,eid,title,JSON.stringify(raw)]);return Number(i.insertId)}
async function put(c:Parameters<DbMigration['apply']>[0],mid:number,vid:number,did:number,srid:number,v:string|number,u:string|null){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mid,vid,did,typeof v==='string'?v:null,typeof v==='number'?v:null,u,srid])}

export const mccormickX1CurrentUsMigration:DbMigration={
 id:'20260831_445_mccormick_x1_current_us',description:'Add five current McCormick North America X1 power families while preserving unresolved trim-count conflict',
 async apply(c){
  const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='mccormick' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='tractor' LIMIT 1`),sid=await id(c,`SELECT id FROM sources WHERE name='McCormick North America' AND domain='mccormick-tractors.com' LIMIT 1`);
  await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'McCormick X1','mccormick-x1') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND slug='mccormick-x1' LIMIT 1`,[mf]);
  const seriesSr=await source(c,sid,'mccormick-x1-current-us-2026-08',BROCHURE,'McCormick North America current X1 compact family',{market:'United States',captured:'2026-08-31',productPage:PAGE,brochure:BROCHURE,currentPageClaim:'All eight models, from 24 to 55 engine horsepower',brochureConflict:'The May-2023 North America brochure linked from the X1 family enumerates 12 named trim/configuration columns across five power families: X1.25M, X1.25H, X1.35, X1.35H, X1.37C, X1.37HC, X1.45, X1.45C, X1.55M, X1.55H, X1.55C, X1.55HC. The current web page does not identify which eight remain current. This migration therefore normalizes five power-family machine records and preserves trim names as official configuration options instead of guessing four discontinued trims.',currentMarketCrossCheck:'2025-2026 US dealer inventory continues to show X1.25H, X1.35/X1.35H/X1.35M, X1.37C/X1.37HC, X1.45 and X1.55C among new/current inventory, supporting the family-level current status while not resolving the exact eight-trim set.',brochureUpdated:'May 2023',shared:{drive:'4WD options throughout family',emissions:'EPA Tier 4 / Tier 4 Final wording in North America brochure',hitch:'Category I',useCases:'loader work, grading, tilling, snow removal, landscaping'},normalizationPolicy:'Machine records represent power families X1.25/35/37/45/55. Transmission/station suffixes remain in configuration metadata until McCormick North America publishes an unambiguous current eight-trim list.'});
  const d=new Map<string,number>();for(const row of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,row);d.set(row[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[row[1]]))}
  for(const m of models){const sr=await source(c,sid,`mccormick-${m.slug}-current-us-2026-08`,BROCHURE,`McCormick ${m.name} current North America family specifications`,{market:'United States',captured:'2026-08-31',modelFamily:m.name,ratedHp:m.hp,pto:m.pto,variants:m.variants,transmissions:m.transmissions,station:m.station,sourcePolicy:'Family-level record due unresolved current-page eight-model vs brochure twelve-trim conflict.'});await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current US McCormick X1 compact power family; exact active trim subset unresolved','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[mf,et,series,m.name,m.slug]);const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mid,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States',?,TRUE,?,'Current X1 power-family record; official trim options preserved without guessing which eight trims remain active.') ON DUPLICATE KEY UPDATE configuration=VALUES(configuration),is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mid,VERSION,`${m.station}; variants ${m.variants}; ${m.transmissions}`,sr||seriesSr]);const vid=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mid,VERSION]);const vals:Array<[string,string|number,string|null]>=[['configuration.station',m.station,null],['configuration.official_variants',m.variants,null],['engine.make','Kukje',null],['engine.type',m.engine,null],['engine.cylinders',m.cyl,null],['emissions.standard','EPA Tier 4 / Tier 4 Final (North America brochure wording)',null],['engine.gross_power',m.hp,'hp'],['engine.rated_speed',2600,'rpm'],['transmission.standard',m.transmissions,null],['pto.rated_power_text',m.pto,null],['pto.rear_description',m.hp<=24?'540 rpm; mid PTO available on X1.25 family':'Independent 540 / 540E',null],['hydraulics.system_type','Open center',null],['hydraulics.published_flow',m.hydraulic,null],['hitch.category','Category I',null],['hitch.lift_capacity',m.hitchLb,'lb'],['capacities.fuel_tank',m.fuelGal,'gal'],['dimensions.wheelbase',m.wheelbaseIn,'in']];for(const[k,v,u]of vals){const did=d.get(k);if(!did)throw new Error(`Missing McCormick X1 spec ${k}`);await put(c,mid,vid,did,sr||seriesSr,v,u)}}
 }
};
