import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Seed={slug:string;model:string;url:string;machine:string;lift:string;height?:string;text:string};
const CATALOG='https://tym.world/en-us/products/attachments';
const items:Seed[]=[
 {slug:'tym-tx110sl',model:'TX110SL',url:'https://tym.world/en-us/products/attachments/front-end-loader/tx110sl',machine:'t1104',lift:'4,129 lb at pivot point at maximum height',height:'144.4 in maximum lift height',text:'Current TYM TX110SL self-leveling front-end loader for T1104; 19.1 cu ft bucket capacity.'},
 {slug:'tym-tl115sl',model:'TL115SL',url:'https://tym.world/en-us/products/attachments/front-end-loader/tl115sl',machine:'t115',lift:'4,129 lb current T115 model-page loader lift capacity',text:'Current TYM TL115SL self-leveling front-end loader for T115. T115 current model page explicitly states 4,129 lb loader lift capacity; clean current loader-detail height row is not inferred.'},
 {slug:'tym-tl130sl',model:'TL130SL',url:'https://tym.world/en-us/products/attachments/front-end-loader/tl130sl',machine:'t130',lift:'5,414 lb current T130 model-page loader lift capacity',text:'Current TYM TL130SL self-leveling front-end loader for T130. T130 current model page explicitly states 5,414 lb loader lift capacity; clean current loader-detail height row is not inferred.'},
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('TYM Series 6 attachment dependency missing');return Number(r[0].id)}
async function source(c:Parameters<DbMigration['apply']>[0],sid:number,eid:string,url:string,title:string,raw:unknown){const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[eid]);if(r[0])return Number(r[0].id);const[i]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,url,eid,title,JSON.stringify(raw)]);return Number(i.insertId)}
export const tymSeries6AttachmentsMigration:DbMigration={id:'20260830_412_tym_series6_attachments',description:'Add verified current US TYM Series 6 self-leveling front-loader fitment',async apply(c){const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='tym' LIMIT 1`),sid=await id(c,`SELECT id FROM sources WHERE name='TYM' AND domain='tym.world' LIMIT 1`);const csr=await source(c,sid,'tym-series6-attachments-current-us-2026-08',CATALOG,'TYM USA current Series 6 attachment fitment catalog',{market:'United States',captured:'2026-08-30',fitment:{T1104:'TX110SL',T115:'TL115SL',T130:'TL130SL'},deferred:['T6115 has no explicit current US loader mapping in the central attachment catalog, so no T6115 loader relationship is inferred from T115 despite similar power/platform positioning.'],sourcePolicy:'Central US catalog controls fitment. Model-specific current pages can supplement lift values where individual loader pages are incomplete.'});for(const a of items){const sr=await source(c,sid,`tym-${a.model.toLowerCase()}-current-us-2026-08`,a.url,`TYM ${a.model} current US loader fitment/specification`,{market:'United States',captured:'2026-08-30',machineSlug:a.machine,catalog:CATALOG,lift:a.lift,height:a.height??null});await c.query(`INSERT INTO attachments(manufacturer_id,attachment_type,model_name,slug,lift_capacity_text,lift_height_text,configuration_text,data_status) VALUES(?,'front-loader',?,?,?,?,?,'verified') ON DUPLICATE KEY UPDATE model_name=VALUES(model_name),lift_capacity_text=VALUES(lift_capacity_text),lift_height_text=VALUES(lift_height_text),configuration_text=VALUES(configuration_text),data_status='verified'`,[mf,a.model,a.slug,a.lift,a.height??null,a.text]);const aid=await id(c,`SELECT id FROM attachments WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,a.slug]);const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,a.machine]);await c.query(`INSERT INTO machine_attachments(machine_id,attachment_id,compatibility_note,source_record_id,confidence) VALUES(?,?,?,?, 'official') ON DUPLICATE KEY UPDATE compatibility_note=VALUES(compatibility_note),source_record_id=VALUES(source_record_id),confidence='official'`,[mid,aid,`${a.model} current US fitment is explicitly listed by TYM for ${a.machine.toUpperCase()}.`,sr||csr]);}}};
