import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type PartSeed={number:string;name:string;category:string;url:string;externalId:string;note:string};
const VERSION_SLUG='united-states-current-2026-08';
const models=['9rx-710','9rx-770','9rx-830'] as const;
const parts:PartSeed[]=[
  {number:'DZ124765',name:'Primary Fuel Filter',category:'fuel-filters',url:'https://shop.deere.com/us/product/DZ124765%3A-Filter-Element/p/DZ124765',externalId:'john-deere-shop-dz124765-9rx-hhp-fitment',note:'John Deere Original primary fuel filter; Shop.Deere compatible-equipment list includes 9RX 710, 9RX 770 and 9RX 830.'},
  {number:'DZ124786',name:'Secondary Fuel Filter',category:'fuel-filters',url:'https://shop.deere.com/us/product/DZ124786%3A%2BSecondary%2BFuel%2BFilter/p/DZ124786',externalId:'john-deere-shop-dz124786-9rx-hhp-fitment',note:'John Deere Original secondary fuel filter; Shop.Deere compatible-equipment list includes 9RX 710, 9RX 770 and 9RX 830.'},
  {number:'TA27886',name:'Hydraulic Oil Filter Element',category:'hydraulic-filters',url:'https://shop.deere.com/us/product/TA27886%3A%2BHydraulic%2BOil%2BFilter%2BElement/p/TA27886',externalId:'john-deere-shop-ta27886-9rx-hhp-fitment',note:'John Deere Original hydraulic oil filter element; Shop.Deere compatible-equipment list includes 9RX 710, 9RX 770 and 9RX 830.'},
  {number:'TA17748',name:'Primary Air Filter Element',category:'air-filters',url:'https://shop.deere.com/us/product/TA17748%3A%2BPrimary%2BAir%2BFilter%2BElement/p/TA17748',externalId:'john-deere-shop-ta17748-9rx-hhp-fitment',note:'John Deere Original primary engine air filter element; Shop.Deere compatible-equipment list includes 9RX 710, 9RX 770 and 9RX 830.'},
  {number:'TA17749',name:'Secondary Air Filter Element',category:'air-filters',url:'https://shop.deere.com/us/product/TA17749%3A-Secondary-Air-Filter-Element/p/TA17749',externalId:'john-deere-shop-ta17749-9rx-hhp-fitment',note:'John Deere Original secondary engine air filter element; Shop.Deere compatible-equipment list includes 9RX 710, 9RX 770 and 9RX 830.'},
  {number:'TA32591',name:'Cab Fresh Air Filter',category:'cabin-air-filters',url:'https://shop.deere.com/us/product/TA32591%3A-Cab-Fresh-Air-Filter/p/TA32591',externalId:'john-deere-shop-ta32591-9rx-hhp-fitment',note:'John Deere Original cab fresh-air filter; Shop.Deere compatible-equipment list includes 9RX 710, 9RX 770 and 9RX 830.'},
  {number:'RE593819',name:'Cab Recirculation Air Filter',category:'cabin-air-filters',url:'https://shop.deere.com/us/product/RE593819%3A-Tractor-Cab-Air-Filter/p/RE593819',externalId:'john-deere-shop-re593819-9rx-hhp-fitment',note:'John Deere Original cab recirculation-air filter; Shop.Deere compatible-equipment list includes 9RX 710, 9RX 770 and 9RX 830.'},
];
async function selectId(connection:Parameters<DbMigration['apply']>[0],sql:string,params:unknown[]=[]){const [rows]=await connection.query<IdRow[]>(sql,params);if(!rows[0])throw new Error('Missing John Deere 9RX HHP service dependency.');return Number(rows[0].id);}
async function ensureCategory(connection:Parameters<DbMigration['apply']>[0],filtersId:number,name:string,slug:string){await connection.query(`INSERT INTO part_categories (parent_id,name,slug) VALUES (?,?,?) ON DUPLICATE KEY UPDATE parent_id=VALUES(parent_id),name=VALUES(name)`,[filtersId,name,slug]);return selectId(connection,`SELECT id FROM part_categories WHERE slug=? LIMIT 1`,[slug]);}
async function ensureSourceRecord(connection:Parameters<DbMigration['apply']>[0],sourceId:number,part:PartSeed){const [rows]=await connection.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[part.externalId]);if(rows[0])return Number(rows[0].id);const [result]=await connection.query<ResultSetHeader>(`INSERT INTO source_records (source_id,url,external_id,title) VALUES (?,?,?,?)`,[sourceId,part.url,part.externalId,`Shop.Deere ${part.number} - Original part compatible equipment for 9RX 710/770/830`]);return Number(result.insertId);}
async function upsertFitment(connection:Parameters<DbMigration['apply']>[0],machineId:number,versionId:number,partId:number,sourceRecordId:number,note:string){const [rows]=await connection.query<IdRow[]>(`SELECT id FROM machine_parts WHERE machine_id=? AND machine_version_id=? AND part_id=? AND serial_prefix IS NULL AND serial_from IS NULL AND serial_to IS NULL ORDER BY id DESC LIMIT 1`,[machineId,versionId,partId]);const configurationNote='Current US 9RX 710/770/830 JD18 service fitment confirmed by John Deere Shop.Deere compatible-equipment data; verify machine serial/options before ordering.';if(rows[0])await connection.query(`UPDATE machine_parts SET fitment_note=?,configuration_note=?,source_record_id=?,fitment_confidence='official' WHERE id=?`,[note,configurationNote,sourceRecordId,Number(rows[0].id)]);else await connection.query(`INSERT INTO machine_parts (machine_id,machine_version_id,part_id,fitment_note,configuration_note,source_record_id,fitment_confidence) VALUES (?,?,?,?,?,?,'official')`,[machineId,versionId,partId,note,configurationNote,sourceRecordId]);}

export const johnDeere9RXHHPServiceFiltersMigration:DbMigration={
  id:'20260828_220_john_deere_9rx_hhp_service_filters',
  description:'Add John Deere Original Shop.Deere service-filter fitments for current 9RX 710, 770 and 830 tractors',
  async apply(connection){
    const manufacturerId=await selectId(connection,`SELECT id FROM manufacturers WHERE slug='john-deere' LIMIT 1`);
    await connection.query(`INSERT INTO part_categories (name,slug) VALUES ('Filters','filters') ON DUPLICATE KEY UPDATE name=VALUES(name)`);const filtersId=await selectId(connection,`SELECT id FROM part_categories WHERE slug='filters' LIMIT 1`);
    const defs=[['Fuel Filters','fuel-filters'],['Hydraulic Filters','hydraulic-filters'],['Air Filters','air-filters'],['Cabin Air Filters','cabin-air-filters']] as const;const categoryIds=new Map<string,number>();for(const [name,slug] of defs)categoryIds.set(slug,await ensureCategory(connection,filtersId,name,slug));
    let [sourceRows]=await connection.query<IdRow[]>(`SELECT id FROM sources WHERE name='John Deere Parts' AND domain='shop.deere.com' ORDER BY id LIMIT 1`);let sourceId=sourceRows[0]?.id?Number(sourceRows[0].id):0;if(!sourceId){const [result]=await connection.query<ResultSetHeader>(`INSERT INTO sources (name,domain,source_type,authority_level) VALUES ('John Deere Parts','shop.deere.com','manufacturer','official')`);sourceId=Number(result.insertId);}
    const partData=new Map<string,{partId:number;sourceRecordId:number;note:string}>();
    for(const part of parts){const categoryId=categoryIds.get(part.category);if(!categoryId)throw new Error(`Missing 9RX HHP category ${part.category}`);const sourceRecordId=await ensureSourceRecord(connection,sourceId,part);await connection.query(`INSERT INTO parts (manufacturer_id,category_id,part_number,normalized_part_number,name,description,data_status) VALUES (?,?,?,?,?,?,'verified') ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),part_number=VALUES(part_number),name=VALUES(name),description=VALUES(description),data_status='verified'`,[manufacturerId,categoryId,part.number,part.number.toUpperCase(),part.name,part.note]);const partId=await selectId(connection,`SELECT id FROM parts WHERE manufacturer_id=? AND normalized_part_number=? LIMIT 1`,[manufacturerId,part.number.toUpperCase()]);partData.set(part.number,{partId,sourceRecordId,note:part.note});}
    for(const slug of models){const machineId=await selectId(connection,`SELECT m.id FROM machines m JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='john-deere' AND m.slug=? LIMIT 1`,[slug]);const versionId=await selectId(connection,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? AND is_current=1 LIMIT 1`,[machineId,VERSION_SLUG]);for(const part of parts){const data=partData.get(part.number);if(!data)throw new Error(`Missing 9RX HHP part ${part.number}`);await upsertFitment(connection,machineId,versionId,data.partId,data.sourceRecordId,data.note);}}
  }
};