import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';
type IdRow=RowDataPacket&{id:number};
const VERSION='united-states-current-2026-08';
async function id(c:Parameters<DbMigration['apply']>[0],q:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(q,p);if(!r[0])throw Error('Farmall 25SC dependency missing');return Number(r[0].id)}
async function source(c:Parameters<DbMigration['apply']>[0],sid:number,externalId:string,url:string,title:string,raw?:unknown){const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,url,externalId,title,raw?JSON.stringify(raw):null]);return Number(x.insertId)}
export const caseIHFarmall25SCCurrentMigration:DbMigration={id:'20260828_248_case_ih_farmall_25sc_current',description:'Add current US Case IH Farmall 25SC specs and L320S loader fitment',async apply(c){
 await c.query(`INSERT INTO equipment_types(name,slug) VALUES('Tractor','tractor') ON DUPLICATE KEY UPDATE name=VALUES(name)`);await c.query(`INSERT INTO manufacturers(name,slug) VALUES('Case IH','case-ih') ON DUPLICATE KEY UPDATE name=VALUES(name)`);const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='case-ih'`);const et=await id(c,`SELECT id FROM equipment_types WHERE slug='tractor'`);await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'Farmall Subcompact Series','farmall-subcompact-series') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND slug='farmall-subcompact-series'`,[mf]);let[s]=await c.query<IdRow[]>(`SELECT id FROM sources WHERE name='Case IH' AND domain='caseih.com' LIMIT 1`);let sid=s[0]?.id?Number(s[0].id):0;if(!sid){const[x]=await c.query<ResultSetHeader>(`INSERT INTO sources(name,domain,source_type,authority_level) VALUES('Case IH','caseih.com','manufacturer','official')`);sid=Number(x.insertId)}
 const familyUrl='https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-compact-series/farmall-subcompact-series';const modelUrl=familyUrl+'/farmall-25sc';const sr=await source(c,sid,'case-ih-farmall-25sc-current-us',modelUrl,'Case IH US Farmall 25SC official current specifications',{engineHp:24.7,ptoHp:17.2,displacementL:1.26,station:'Non-cab',traction:'MFD',hitchBallEndsLb:992,hitch24inLb:728});
 await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,'Farmall 25SC','farmall-25sc','Current US Case IH Farmall subcompact tractor','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes)`,[mf,et,series]);const mi=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug='farmall-25sc'`,[mf]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mi,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States','Current Farmall 25SC subcompact tractor',TRUE,?,'Official Case IH US current product data') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mi,VERSION,sr]);const vi=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=?`,[mi,VERSION]);
 const defs=[['Machine Configuration','configuration.station','Operator station','text',null,1],['Machine Configuration','configuration.drive','Drive configuration','text',null,2],['Engine','engine.displacement','Engine displacement','decimal','L',2],['Engine','engine.rated_power','Engine horsepower','decimal','hp',3],['PTO','pto.rated_power','PTO power','decimal','hp',10],['Hydraulics','hitch.rear_max_lift_capacity','Rear 3-point hitch lift capacity','decimal','lb',20]] as const;for(const d of defs)await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE label=VALUES(label)`,d);const vals:[string,string|number,string|null][]=[['configuration.station','Non-cab',null],['configuration.drive','MFD',null],['engine.displacement',1.26,'L'],['engine.rated_power',24.7,'hp'],['pto.rated_power',17.2,'hp'],['hitch.rear_max_lift_capacity',992,'lb']];for(const[v,val,u]of vals){const di=await id(c,`SELECT id FROM spec_definitions WHERE spec_key=?`,[v]);await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mi,vi,di,typeof val==='string'?val:null,typeof val==='number'?val:null,u,sr])}
 const lsr=await source(c,sid,'case-ih-farmall-25sc-l320s-current',familyUrl,'Case IH US L320S loader specifications for Farmall subcompact tractors',{liftLb:693,heightIn:72,breakoutLb:1426});await c.query(`INSERT INTO attachments(manufacturer_id,attachment_type,model_name,slug,lift_capacity_text,lift_height_text,configuration_text,data_status) VALUES(?,'front-loader','L320S','l320s-farmall-25sc','693 lb max lift capacity','72 in max height','Designed for Farmall subcompact tractors; 1,426 lb boom breakout force','verified') ON DUPLICATE KEY UPDATE data_status='verified',lift_capacity_text=VALUES(lift_capacity_text),lift_height_text=VALUES(lift_height_text),configuration_text=VALUES(configuration_text)`,[mf]);const ai=await id(c,`SELECT id FROM attachments WHERE manufacturer_id=? AND slug='l320s-farmall-25sc'`,[mf]);await c.query(`INSERT INTO machine_attachments(machine_id,attachment_id,compatibility_note,source_record_id,confidence) VALUES(?,?,'Official Case IH L320S compatibility for Farmall 25SC.',?,'official') ON DUPLICATE KEY UPDATE source_record_id=VALUES(source_record_id),confidence='official',compatibility_note=VALUES(compatibility_note)`,[mi,ai,lsr]);
}};