import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow = RowDataPacket & { id: number };
type Seed = {
  slug: string; name: string; baseModel: string; url: string; station: 'ROPS'|'Cab'; engineModel: string; hp: number; rpm: number; displacementL: number;
  transmission: string; speeds: string; hitchLb: number; fuelL: number; lengthIn: number; widthIn: number; wheelbaseIn: number; heightIn?: number; clearanceIn: number; weightLb: number; agTires: string;
};

const VERSION = 'united-states-current-2026-08';
const SERIES_URL = 'https://tym.world/en-us/products/tractors/series-3';

const models: Seed[] = [
  { slug:'2515r', name:'2515R', baseModel:'2515', url:'https://tym.world/en-us/products/tractors/series-3/2515', station:'ROPS', engineModel:'TYM T1700N6', hp:24, rpm:2100, displacementL:1.714, transmission:'Synchromesh', speeds:'F12 x R12', hitchLb:3306, fuelL:27, lengthIn:120.9, widthIn:56.3, wheelbaseIn:65.7, heightIn:97.3, clearanceIn:14.4, weightLb:2989, agTires:'8-16 / 12.4-24' },
  { slug:'2515h', name:'2515H', baseModel:'2515', url:'https://tym.world/en-us/products/tractors/series-3/2515', station:'ROPS', engineModel:'TYM T1700N6', hp:24, rpm:2100, displacementL:1.714, transmission:'HST', speeds:'3 ranges', hitchLb:3306, fuelL:27, lengthIn:120.9, widthIn:56.3, wheelbaseIn:65.7, heightIn:97.3, clearanceIn:14.4, weightLb:2969, agTires:'8-16 / 12.4-24' },
  { slug:'3015r', name:'3015R', baseModel:'3015', url:'https://tym.world/en-us/products/tractors/series-3/3015', station:'ROPS', engineModel:'TYM T1700N3', hp:30, rpm:2600, displacementL:1.714, transmission:'Synchromesh', speeds:'F12 x R12', hitchLb:3306, fuelL:27, lengthIn:120.9, widthIn:56.3, wheelbaseIn:65.7, heightIn:97.3, clearanceIn:14.4, weightLb:3183, agTires:'8-16 / 12.4-24' },
  { slug:'3015h', name:'3015H', baseModel:'3015', url:'https://tym.world/en-us/products/tractors/series-3/3015', station:'ROPS', engineModel:'TYM T1700N3', hp:30, rpm:2600, displacementL:1.714, transmission:'HST', speeds:'3 ranges', hitchLb:3306, fuelL:27, lengthIn:120.9, widthIn:56.3, wheelbaseIn:65.7, heightIn:97.3, clearanceIn:14.4, weightLb:3163, agTires:'8-16 / 12.4-24' },
  { slug:'3515r', name:'3515R', baseModel:'3515', url:'https://tym.world/en-us/products/tractors/series-3/3515', station:'ROPS', engineModel:'TYM T1700N2', hp:35, rpm:2600, displacementL:1.714, transmission:'Synchromesh', speeds:'F12 x R12', hitchLb:3306, fuelL:27, lengthIn:120.9, widthIn:56.3, wheelbaseIn:65.7, heightIn:97.3, clearanceIn:14.4, weightLb:3183, agTires:'8-16 / 12.4-24' },
  { slug:'3515h', name:'3515H', baseModel:'3515', url:'https://tym.world/en-us/products/tractors/series-3/3515', station:'ROPS', engineModel:'TYM T1700N2', hp:35, rpm:2600, displacementL:1.714, transmission:'HST', speeds:'3 ranges', hitchLb:3306, fuelL:27, lengthIn:120.9, widthIn:56.3, wheelbaseIn:65.7, heightIn:97.3, clearanceIn:14.4, weightLb:3163, agTires:'8-16 / 12.4-24' },
  { slug:'3515c', name:'3515C', baseModel:'3515C', url:'https://tym.world/en-us/products/tractors/series-3/3515c', station:'Cab', engineModel:'TYM T1700N2', hp:35, rpm:2600, displacementL:1.714, transmission:'HST', speeds:'3 ranges', hitchLb:3306, fuelL:27, lengthIn:120.9, widthIn:55.6, wheelbaseIn:65.7, clearanceIn:14.4, weightLb:3552, agTires:'7-16 / 11.2-24' },
  { slug:'4215r', name:'4215R', baseModel:'4215', url:'https://tym.world/en-us/products/tractors/series-3/4215', station:'ROPS', engineModel:'TYM T2000N2', hp:41, rpm:2600, displacementL:2.287, transmission:'Synchromesh', speeds:'F12 x R12', hitchLb:3306, fuelL:27, lengthIn:120.9, widthIn:56.3, wheelbaseIn:65.7, heightIn:97.3, clearanceIn:14.4, weightLb:3278, agTires:'8-16 / 12.4-24' },
  { slug:'4215h', name:'4215H', baseModel:'4215', url:'https://tym.world/en-us/products/tractors/series-3/4215', station:'ROPS', engineModel:'TYM T2000N2', hp:41, rpm:2600, displacementL:2.287, transmission:'HST', speeds:'3 ranges', hitchLb:3306, fuelL:27, lengthIn:120.9, widthIn:56.3, wheelbaseIn:65.7, heightIn:97.3, clearanceIn:14.4, weightLb:3258, agTires:'8-16 / 12.4-24' },
  { slug:'4215c', name:'4215C', baseModel:'4215C', url:'https://tym.world/en-us/products/tractors/series-3/4215c', station:'Cab', engineModel:'TYM T2000N2', hp:41, rpm:2600, displacementL:2.287, transmission:'HST', speeds:'3 ranges', hitchLb:3306, fuelL:27, lengthIn:120.9, widthIn:55.6, wheelbaseIn:65.7, clearanceIn:13.1, weightLb:3644, agTires:'7-16 / 11.2-24' },
  { slug:'4815r', name:'4815R', baseModel:'4815', url:'https://tym.world/en-us/products/tractors/series-3/4815', station:'ROPS', engineModel:'TYM T2300N2', hp:48, rpm:2600, displacementL:2.287, transmission:'Synchromesh', speeds:'F12 x R12', hitchLb:3306, fuelL:27, lengthIn:120.9, widthIn:56.3, wheelbaseIn:65.7, heightIn:97.3, clearanceIn:14.4, weightLb:3278, agTires:'8-16 / 12.4-24' },
  { slug:'4815h', name:'4815H', baseModel:'4815', url:'https://tym.world/en-us/products/tractors/series-3/4815', station:'ROPS', engineModel:'TYM T2300N2', hp:48, rpm:2600, displacementL:2.287, transmission:'HST', speeds:'3 ranges', hitchLb:3306, fuelL:27, lengthIn:120.9, widthIn:56.3, wheelbaseIn:65.7, heightIn:97.3, clearanceIn:14.4, weightLb:3278, agTires:'8-16 / 12.4-24' },
  { slug:'4815c', name:'4815C', baseModel:'4815C', url:'https://tym.world/en-us/products/tractors/series-3/4815c', station:'Cab', engineModel:'TYM T2300N2', hp:48, rpm:2600, displacementL:2.287, transmission:'HST', speeds:'3 ranges', hitchLb:3306, fuelL:27, lengthIn:120.9, widthIn:55.6, wheelbaseIn:65.7, clearanceIn:13.1, weightLb:3587, agTires:'7-16 / 11.2-24' },
];

const definitions: Array<[string,string,string,string,string|null,number]> = [
  ['Machine Configuration','configuration.station','Operator station','text',null,1], ['Engine','engine.make','Engine manufacturer','text',null,1], ['Engine','engine.model','Engine model','text',null,3], ['Engine','engine.displacement','Engine displacement','decimal','L',6], ['Engine','engine.gross_power','Gross engine power','decimal','hp',8], ['Engine','engine.rated_speed','Rated engine speed','integer','rpm',9],
  ['Transmission','transmission.standard','Transmission','text',null,10], ['Transmission','transmission.speeds','Transmission speeds / ranges','text',null,20], ['Transmission','steering.type','Steering','text',null,40], ['PTO','pto.rear_description','Rear PTO','text',null,20],
  ['Hydraulics','hitch.category','3-point hitch category','text',null,40], ['Hydraulics','hitch.lift_capacity','3-point hitch lift capacity','decimal','lb',50], ['Capacities','capacities.fuel_tank','Fuel tank capacity','decimal','L',10],
  ['Dimensions & Weight','dimensions.overall_length','Overall length with 3-point hitch','decimal','in',10], ['Dimensions & Weight','dimensions.overall_width','Overall width','decimal','in',20], ['Dimensions & Weight','dimensions.overall_height','Overall height','decimal','in',30], ['Dimensions & Weight','dimensions.wheelbase','Wheelbase','decimal','in',40], ['Dimensions & Weight','dimensions.ground_clearance','Minimum ground clearance','decimal','in',50], ['Dimensions & Weight','dimensions.unladen_weight','Published configuration weight','decimal','lb',70], ['Tires','tires.ag','R1 agricultural tires front / rear','text',null,10],
];

async function id(c: Parameters<DbMigration['apply']>[0], sql:string, params:unknown[]=[]){ const [rows]=await c.query<IdRow[]>(sql,params); if(!rows[0]) throw new Error('TYM Series 3 core migration dependency missing'); return Number(rows[0].id); }
async function ensureSource(c:Parameters<DbMigration['apply']>[0],sourceId:number,externalId:string,url:string,title:string,raw:unknown){ const [rows]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]); if(rows[0]) return Number(rows[0].id); const [r]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sourceId,url,externalId,title,JSON.stringify(raw)]); return Number(r.insertId); }
async function put(c:Parameters<DbMigration['apply']>[0],machineId:number,versionId:number,definitionId:number,sourceRecordId:number,value:string|number,unit:string|null){ await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[machineId,versionId,definitionId,typeof value==='string'?value:null,typeof value==='number'?value:null,unit,sourceRecordId]); }

export const tymSeries3CoreCurrentUsMigration: DbMigration = {
  id:'20260830_401_tym_series3_15_platform_current_us', description:'Add thirteen current US TYM Series 3 core ROPS/cab and R/H configurations from live US technical tables',
  async apply(c){
    const manufacturerId=await id(c,`SELECT id FROM manufacturers WHERE slug='tym' LIMIT 1`); const equipmentTypeId=await id(c,`SELECT id FROM equipment_types WHERE slug='tractor' LIMIT 1`); const sourceId=await id(c,`SELECT id FROM sources WHERE name='TYM' AND domain='tym.world' LIMIT 1`);
    await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'TYM Series 3','tym-series-3') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[manufacturerId,equipmentTypeId]); const seriesId=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND slug='tym-series-3' LIMIT 1`,[manufacturerId]);
    await ensureSource(c,sourceId,'tym-series3-core-current-us-2026-08',SERIES_URL,'TYM USA current Series 3 lineup and core variant structure',{market:'United States',captured:'2026-08-30',cards:['2515','3015','3515','3515C','4215','4215C','4815','4815C'],expandedConfigurations:models.map(m=>m.name),policy:'Base ROPS cards with separately published R/H technical rows are expanded into distinct machine records. Cab cards remain single HST records. Variant weights are preserved where TYM publishes them.'});
    const ids=new Map<string,number>(); for(const row of definitions){ await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,row); ids.set(row[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[row[1]])); }
    for(const m of models){ const sr=await ensureSource(c,sourceId,`tym-${m.slug}-current-us-2026-08`,m.url,`TYM ${m.name} current US specifications`,{market:'United States',captured:'2026-08-30',baseModel:m.baseModel,variantExpansion:true,sourcePolicy:'Live US technical table is primary; base-card R/H rows are stored separately.'}); await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current US TYM Series 3 compact tractor','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[manufacturerId,equipmentTypeId,seriesId,m.name,m.slug]); const machineId=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=? LIMIT 1`,[manufacturerId,m.slug]); await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[machineId,VERSION]); await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States',?,TRUE,?,'Current TYM USA Series 3 configuration expanded from the live model technical table.') ON DUPLICATE KEY UPDATE configuration=VALUES(configuration),is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[machineId,VERSION,`${m.station}; ${m.transmission}; ${m.speeds}`,sr]); const versionId=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[machineId,VERSION]); const vals:Array<[string,string|number,string|null]>=[['configuration.station',m.station,null],['engine.make','TYM',null],['engine.model',m.engineModel,null],['engine.displacement',m.displacementL,'L'],['engine.gross_power',m.hp,'hp'],['engine.rated_speed',m.rpm,'rpm'],['transmission.standard',m.transmission,null],['transmission.speeds',m.speeds,null],['steering.type','Hydrostatic',null],['pto.rear_description','540 rpm',null],['hitch.category','Category I',null],['hitch.lift_capacity',m.hitchLb,'lb'],['capacities.fuel_tank',m.fuelL,'L'],['dimensions.overall_length',m.lengthIn,'in'],['dimensions.overall_width',m.widthIn,'in'],['dimensions.wheelbase',m.wheelbaseIn,'in'],['dimensions.ground_clearance',m.clearanceIn,'in'],['dimensions.unladen_weight',m.weightLb,'lb'],['tires.ag',m.agTires,null]]; if(m.heightIn!==undefined) vals.push(['dimensions.overall_height',m.heightIn,'in']); for(const [key,value,unit] of vals){ const did=ids.get(key); if(!did) throw new Error(`Missing TYM Series 3 spec ${key}`); await put(c,machineId,versionId,did,sr,value,unit); }
    }
  }
};
