import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Seed={slug:string;name:string;hp:number;ptoHp:number;station:string;transmission:string;hitchLb:number;totalGpm:number;steeringGpm:number;remoteFlow:string;packages:string;pto:string};
const VERSION='united-states-current-2026-08';
const PRODUCTS='https://www.zetorna.com/products';
const SUB='https://www.zetorna.com/zetor-sub-compact';
const COMPACT='https://www.zetorna.com/zetor-compact';
const GUIDE='https://www.zetorna.com/file/1744/zetor-t4f-m-20210411.pdf';
const models:Seed[]=[
 {slug:'m22ht',name:'M22HT',hp:22,ptoHp:17.6,station:'ROPS',transmission:'2-range HST with Auto Throttle and forward/reverse foot pedals',hitchLb:1100,totalGpm:6.97,steeringGpm:2.11,remoteFlow:'Open-center compact hydraulic system',packages:'M22HTL / M22HTLM / M22HTLB / M22HTLBM package configurations documented; current web page prominently lists HTLM/HTLB/HTLBM',pto:'Independent 540 rear / 2500 mid'},
 {slug:'m25ht',name:'M25HT',hp:25.3,ptoHp:20.2,station:'ROPS',transmission:'2-range HST with cruise, Auto Throttle and dual pedals',hitchLb:1325,totalGpm:6.95,steeringGpm:2.3,remoteFlow:'Optional rear remote; factory loader valve options',packages:'M25HT / M25HTL / M25HTLM / M25HTLB / M25HTLBM appear across current compact/sub-compact product material; treated as package options around the same 25.3-hp base tractor',pto:'Independent 540 rear / 2500 mid'},
 {slug:'m40ss',name:'M40SS',hp:39.2,ptoHp:33.3,station:'ROPS',transmission:'12F x 12R Synchro-Shuttle with creeper',hitchLb:2650,totalGpm:12,steeringGpm:4.6,remoteFlow:'7.0 gpm to remotes/loader; 2 rear valves standard',packages:'ROPS compact tractor; QA loader and full-subframe backhoe available',pto:'Independent 540 rear'},
 {slug:'m40htc',name:'M40HTC',hp:39.2,ptoHp:31.3,station:'Cab',transmission:'3-range HST with dual pedals, Electronic Cruise and Auto Throttle',hitchLb:2650,totalGpm:12,steeringGpm:4.6,remoteFlow:'7.0 gpm to remotes/loader; 2 rear valves standard',packages:'Premium climate-control cab compact tractor; QA loader and full-subframe backhoe available',pto:'Independent 540 rear; optional 2000 mid'},
];
const defs:Array<[string,string,string,string,string|null,number]>=[
 ['Machine Configuration','configuration.station','Operator station','text',null,1],['Machine Configuration','configuration.packages','Current package/configuration options','text',null,2],
 ['Engine','engine.make','Engine manufacturer','text',null,1],['Engine','engine.type','Engine type','text',null,2],['Engine','engine.cylinders','Cylinders','integer',null,4],['Engine','emissions.standard','Emissions standard','text',null,5],['Engine','engine.gross_power','Engine power','decimal','hp',8],
 ['Transmission','transmission.standard','Transmission','text',null,10],['PTO','pto.rated_power','PTO power','decimal','hp',10],['PTO','pto.rear_description','PTO configuration','text',null,20],
 ['Hydraulics','hydraulics.system_type','Hydraulic system','text',null,5],['Hydraulics','hydraulics.total_flow','Total hydraulic flow','decimal','gpm',30],['Hydraulics','hydraulics.power_steering_pump_capacity','Power steering flow','decimal','gpm',25],['Hydraulics','hydraulics.remote_valves','Remote/loader flow and valves','text',null,60],['Hydraulics','hitch.category','3-point hitch category','text',null,40],['Hydraulics','hitch.lift_capacity','3-point hitch lift capacity','decimal','lb',50]
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('Zetor M-Series migration dependency missing');return Number(r[0].id)}
async function source(c:Parameters<DbMigration['apply']>[0],sid:number,eid:string,url:string,title:string,raw:unknown){const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[eid]);if(r[0])return Number(r[0].id);const[i]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,url,eid,title,JSON.stringify(raw)]);return Number(i.insertId)}
async function put(c:Parameters<DbMigration['apply']>[0],mid:number,vid:number,did:number,srid:number,v:string|number,u:string|null){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mid,vid,did,typeof v==='string'?v:null,typeof v==='number'?v:null,u,srid])}

export const zetorMSeriesSmallCurrentUsMigration:DbMigration={
 id:'20260831_446_zetor_m_series_small_current_us',description:'Introduce Zetor North America with current M22HT, M25HT, M40SS and M40HTC base tractors',
 async apply(c){
  await c.query(`INSERT INTO equipment_types(name,slug) VALUES('Tractor','tractor') ON DUPLICATE KEY UPDATE name=VALUES(name)`);await c.query(`INSERT INTO manufacturers(name,slug) VALUES('ZETOR','zetor') ON DUPLICATE KEY UPDATE name=VALUES(name)`);const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='zetor' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='tractor' LIMIT 1`);const[r]=await c.query<IdRow[]>(`SELECT id FROM sources WHERE name='Zetor North America' AND domain='zetorna.com' LIMIT 1`);let sid=r[0]?.id?Number(r[0].id):0;if(!sid){const[i]=await c.query<ResultSetHeader>(`INSERT INTO sources(name,domain,source_type,authority_level) VALUES('Zetor North America','zetorna.com','manufacturer','official')`);sid=Number(i.insertId)}
  await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'Zetor M-Series Small Tractors','zetor-m-series-small') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND slug='zetor-m-series-small' LIMIT 1`,[mf]);const seriesSr=await source(c,sid,'zetor-m-series-small-current-us-2026-08',PRODUCTS,'Zetor North America current sub-compact and compact lineup',{market:'United States',captured:'2026-08-31',productsPage:PRODUCTS,subCompactPage:SUB,compactPage:COMPACT,technicalGuide:GUIDE,currentClasses:{subCompact:'22 HP',compact:'25-40 HP'},normalizationPolicy:'Machine records represent base tractors. Factory combinations such as loader/mower/backhoe HTL/HTLM/HTLB/HTLBM are configuration packages and attachments, not duplicate tractor models.',currentModels:['M22HT base family','M25HT base family','M40SS','M40HTC'],sourceFreshness:'Current product pages remain active in 2026; technical guide provides detailed official model specs and is cross-checked against current pages.'});
  const d=new Map<string,number>();for(const row of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,row);d.set(row[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[row[1]]))}
  for(const m of models){const sr=await source(c,sid,`zetor-${m.slug}-current-us-2026-08`,GUIDE,`Zetor North America ${m.name} current specifications`,{market:'United States',captured:'2026-08-31',model:m.name,hp:m.hp,ptoHp:m.ptoHp,packages:m.packages,productPage:m.slug.startsWith('m40')?COMPACT:SUB});await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current US Zetor North America M-Series small tractor','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[mf,et,series,m.name,m.slug]);const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mid,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States',?,TRUE,?,'Current Zetor North America base tractor; loader/mower/backhoe package suffixes remain configuration metadata.') ON DUPLICATE KEY UPDATE configuration=VALUES(configuration),is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mid,VERSION,`${m.station}; ${m.transmission}; ${m.packages}`,sr||seriesSr]);const vid=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mid,VERSION]);const vals:Array<[string,string|number,string|null]>=[['configuration.station',m.station,null],['configuration.packages',m.packages,null],['engine.make','Yanmar',null],['engine.type','Tier 4 Final water-cooled diesel',null],['engine.cylinders',3,null],['emissions.standard','US EPA Tier 4 Final',null],['engine.gross_power',m.hp,'hp'],['transmission.standard',m.transmission,null],['pto.rated_power',m.ptoHp,'hp'],['pto.rear_description',m.pto,null],['hydraulics.system_type','Open center',null],['hydraulics.total_flow',m.totalGpm,'gpm'],['hydraulics.power_steering_pump_capacity',m.steeringGpm,'gpm'],['hydraulics.remote_valves',m.remoteFlow,null],['hitch.category','Category I',null],['hitch.lift_capacity',m.hitchLb,'lb']];for(const[k,v,u]of vals){const did=d.get(k);if(!did)throw new Error(`Missing Zetor M-Series spec ${k}`);await put(c,mid,vid,did,sr||seriesSr,v,u)}}
 }
};
