import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type ModelSeed={slug:string;model:string;ratedHp:number;maxHp:number;specUrl:string;specExternalId:string};
const CURRENT_URL='https://techpubs.deere.com/en-US/Search/Instruction?page=3919';
const CURRENT_EXTERNAL_ID='john-deere-9rt-490-540-590-current-techpub-2026-05';
const US_PRICEBOOK_URL='https://www.deere.com/assets/pdfs/region-4/industries/government-and-military-sales/contracts/price-pages/agricultural/Tractors_6000s-9000s_Less%20PUKS_01Nov2024.pdf';
const US_PRICEBOOK_EXTERNAL_ID='john-deere-us-9rt-490-540-590-pricebook-2024-11';
const VERSION_SLUG='united-states-current-2026-08';
const models:ModelSeed[]=[
  {slug:'9rt-490',model:'9RT 490',ratedHp:490,maxHp:539,specUrl:'https://www.deere.ca/en/tractors/4wd-track-tractors/9rt-490/',specExternalId:'john-deere-na-9rt-490-specs'},
  {slug:'9rt-540',model:'9RT 540',ratedHp:540,maxHp:594,specUrl:'https://www.deere.ca/en/tractors/4wd-track-tractors/9rt-540/',specExternalId:'john-deere-na-9rt-540-specs'},
  {slug:'9rt-590',model:'9RT 590',ratedHp:590,maxHp:649,specUrl:'https://www.deere.ca/en/tractors/4wd-track-tractors/9rt-590/',specExternalId:'john-deere-na-9rt-590-specs'},
];
const definitions=[
  ['Machine Configuration','configuration.station','Operator station','text',null,1],['Machine Configuration','configuration.track','Wheel or track configuration','text',null,2],['Machine Configuration','drivetrain.type','Drive type','text',null,3],
  ['Engine','engine.make','Engine manufacturer','text',null,1],['Engine','engine.model','Engine model','text',null,2],['Engine','engine.displacement','Engine displacement','decimal','L',3],['Engine','engine.cylinders','Cylinders','integer',null,4],['Engine','engine.rated_power','Rated engine power (ISO)','decimal','hp',5],['Engine','engine.maximum_power','Maximum engine power (ISO)','decimal','hp',6],['Engine','engine.rated_speed','Rated engine speed','integer','rpm',7],['Engine','engine.emissions','Emissions certification','text',null,8],
  ['PTO','pto.rated_power','Rated PTO power','decimal','hp',10],['Transmission','transmission.standard','Standard transmission','text',null,10],['Hydraulics','hydraulics.pump_rated_output','Standard hydraulic pump output','decimal','gpm',10],['Hydraulics','hydraulics.pump_optional_output','Optional hydraulic pump output','decimal','gpm',20],['Dimensions & Weight','weight.tractor','Base machine weight','decimal','lb',50],['Capacities','capacities.fuel_tank_variants','Fuel tank capacity','decimal','US gal',10],
] as const;
async function selectId(connection:Parameters<DbMigration['apply']>[0],sql:string,params:unknown[]=[]){const [rows]=await connection.query<IdRow[]>(sql,params);if(!rows[0])throw new Error('Missing John Deere 9RT current migration dependency.');return Number(rows[0].id);}
async function ensureSource(connection:Parameters<DbMigration['apply']>[0],sourceId:number,externalId:string,url:string,title:string,publishedDate:string|null=null){const [rows]=await connection.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(rows[0])return Number(rows[0].id);const [result]=await connection.query<ResultSetHeader>(`INSERT INTO source_records (source_id,url,external_id,title,published_date) VALUES (?,?,?,?,?)`,[sourceId,url,externalId,title,publishedDate]);return Number(result.insertId);}
async function upsertSpec(connection:Parameters<DbMigration['apply']>[0],machineId:number,versionId:number,definitionId:number,sourceRecordId:number,value:string|number,unit:string|null=null){await connection.query(`INSERT INTO machine_specs (machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES (?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[machineId,versionId,definitionId,typeof value==='string'?value:null,typeof value==='number'?value:null,unit,sourceRecordId]);}

export const johnDeere9RTCurrentSpecsMigration:DbMigration={
  id:'20260828_221_john_deere_9rt_current_specs',
  description:'Add current North American John Deere 9RT 490, 540 and 590 two-track tractor specifications, superseding the older 470/520/570 lineup for current catalog pages',
  async apply(connection){
    const manufacturerId=await selectId(connection,`SELECT id FROM manufacturers WHERE slug='john-deere' LIMIT 1`);const equipmentTypeId=await selectId(connection,`SELECT id FROM equipment_types WHERE slug='tractor' LIMIT 1`);
    await connection.query(`INSERT INTO machine_series (manufacturer_id,equipment_type_id,name,slug) VALUES (?,?,'9RT Series','9rt-series') ON DUPLICATE KEY UPDATE name='9RT Series'`,[manufacturerId,equipmentTypeId]);const seriesId=await selectId(connection,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='9rt-series' LIMIT 1`,[manufacturerId,equipmentTypeId]);
    let [sourceRows]=await connection.query<IdRow[]>(`SELECT id FROM sources WHERE name='John Deere' AND domain='deere.com' ORDER BY id LIMIT 1`);let sourceId=sourceRows[0]?.id?Number(sourceRows[0].id):0;if(!sourceId){const [result]=await connection.query<ResultSetHeader>(`INSERT INTO sources (name,domain,source_type,authority_level) VALUES ('John Deere','deere.com','manufacturer','official')`);sourceId=Number(result.insertId);}
    const currentSourceId=await ensureSource(connection,sourceId,CURRENT_EXTERNAL_ID,CURRENT_URL,'John Deere Technical Publications 2026 - 9RT 490/540/590 current supported model references','2026-05-29');
    const usPricebookId=await ensureSource(connection,sourceId,US_PRICEBOOK_EXTERNAL_ID,US_PRICEBOOK_URL,'John Deere US agricultural price book - 9RT 490/540/590 North American configuration','2024-11-01');
    const definitionIds=new Map<string,number>();for(const [section,key,label,valueType,canonicalUnit,displayOrder] of definitions){await connection.query(`INSERT INTO spec_definitions (section,spec_key,label,value_type,canonical_unit,display_order) VALUES (?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,[section,key,label,valueType,canonicalUnit,displayOrder]);definitionIds.set(key,await selectId(connection,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[key]));}const def=(key:string)=>{const id=definitionIds.get(key);if(!id)throw new Error(`Missing 9RT spec ${key}`);return id;};
    for(const model of models){const specSourceId=await ensureSource(connection,sourceId,model.specExternalId,model.specUrl,`John Deere North America ${model.model} official specifications`);await connection.query(`INSERT INTO machines (manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES (?,?,?,?,?,'Current North American John Deere 9RT two-track generation. Deere 2026 technical materials use 490/540/590 model designations.','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[manufacturerId,equipmentTypeId,seriesId,model.model,model.slug]);const machineId=await selectId(connection,`SELECT id FROM machines WHERE manufacturer_id=? AND equipment_type_id=? AND slug=? LIMIT 1`,[manufacturerId,equipmentTypeId,model.slug]);await connection.query(`INSERT INTO machine_versions (machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES (?,?,'US','United States','Current 9RT two-track agricultural tractor - cab',TRUE,?,?) ON DUPLICATE KEY UPDATE market_code='US',market_name='United States',configuration=VALUES(configuration),is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[machineId,VERSION_SLUG,currentSourceId,'Current model identity is supported by 2026 Deere Technical Publications and Deere US price-book history. Numerical specifications use official John Deere North American product pages; confirm build options for a specific serial number.']);const versionId=await selectId(connection,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[machineId,VERSION_SLUG]);const values:Array<[string,string|number,string|null,number]>=[['configuration.station','Cab',null,currentSourceId],['configuration.track','2-Track',null,currentSourceId],['drivetrain.type','4WD tracked',null,currentSourceId],['engine.make','John Deere',null,specSourceId],['engine.model','JD14',null,specSourceId],['engine.displacement',13.6,'L',specSourceId],['engine.cylinders',6,null,specSourceId],['engine.rated_power',model.ratedHp,'hp',specSourceId],['engine.maximum_power',model.maxHp,'hp',specSourceId],['engine.rated_speed',2100,'rpm',specSourceId],['engine.emissions','Final Tier 4',null,specSourceId],['pto.rated_power',335,'hp',specSourceId],['transmission.standard','John Deere e18 18-speed PowerShift with Efficiency Manager; 18F/6R, 25 mph',null,specSourceId],['hydraulics.pump_rated_output',55,'gpm',specSourceId],['hydraulics.pump_optional_output',110,'gpm',specSourceId],['weight.tractor',47326,'lb',specSourceId],['capacities.fuel_tank_variants',350,'US gal',usPricebookId]];for(const [key,value,unit,recordId] of values)await upsertSpec(connection,machineId,versionId,def(key),recordId,value,unit);}
  }
};