import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
const VERSION='north-america-current-2026-09';
const URL='https://construction.newholland.com/en-us/northamerica/products/light-construction-equipment/forklifts/f50c';
const defs:Array<[string,string,string,string,string|null,number]>=[
 ['Machine Configuration','configuration.type','Machine configuration','text',null,1],['Machine Configuration','configuration.market_scope','Official market scope','text',null,2],
 ['Engine','forklift.engine_power','Published horsepower','decimal','hp',10],
 ['Loader Performance','forklift.lift_capacity','Rated lift capacity','decimal','lb',10],['Loader Performance','forklift.mast_height','Standard mast / fork height','text',null,20],['Loader Performance','forklift.mast_side_shift','Mast side shift','text',null,30],['Loader Performance','forklift.fork_length','Fork length','decimal','in',40],
 ['Transmission','forklift.drivetrain','Drivetrain','text',null,10],['Transmission','forklift.transmission','Transmission','text',null,20],
 ['Travel','forklift.max_travel_speed','Maximum travel speed','decimal','mph',10],
 ['Dimensions & Weight','forklift.operating_weight','Operating weight','decimal','lb',10],['Dimensions & Weight','forklift.overall_operating_height','Overall operating height','decimal','in',20],['Dimensions & Weight','forklift.ground_clearance','Published ground clearance','text',null,30],
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('New Holland F50C migration dependency missing');return Number(r[0].id);}
async function source(c:Parameters<DbMigration['apply']>[0]){const[r]=await c.query<IdRow[]>(`SELECT id FROM sources WHERE name='New Holland Construction' AND domain='construction.newholland.com' ORDER BY id LIMIT 1`);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO sources(name,domain,source_type,authority_level) VALUES('New Holland Construction','construction.newholland.com','manufacturer','official')`);return Number(x.insertId);}
async function record(c:Parameters<DbMigration['apply']>[0],sid:number){const externalId='new-holland-f50c-rough-terrain-forklift-na-current-2026-09';const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(r[0])return Number(r[0].id);const raw={captured:'2026-09-01',market:'North America / United States site',equipmentType:'Rough Terrain Forklift',model:'F50C',grossHp:74,operatingWeightLb:12885,overallOperatingHeightIn:225,liftCapacityLb:5000,standardMast:'12 ft (3.7 m)',forkLengthIn:48,groundClearance:'over 10 in (260 mm)',mastSideShift:'3 in (76 mm) each side',maxTravelMph:24.1,drivetrain:'4WD',transmission:'Power shuttle synchromesh, 4 forward / 4 reverse'};const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,URL,externalId,'New Holland F50C current North America rough terrain forklift specifications',JSON.stringify(raw)]);return Number(x.insertId);}
async function put(c:Parameters<DbMigration['apply']>[0],mid:number,vid:number,did:number,rid:number,value:string|number,unit:string|null=null){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mid,vid,did,typeof value==='string'?value:null,typeof value==='number'?value:null,unit,rid]);}
export const newHollandF50cRoughTerrainForkliftCurrentMigration:DbMigration={id:'20260901_560_new_holland_f50c_rough_terrain_forklift_current',description:'Add current New Holland F50C rough terrain forklift',async apply(c){
 await c.query(`INSERT INTO equipment_types(name,slug) VALUES('Rough Terrain Forklift','rough-terrain-forklift') ON DUPLICATE KEY UPDATE name=VALUES(name)`);await c.query(`INSERT INTO manufacturers(name,slug) VALUES('New Holland','new-holland') ON DUPLICATE KEY UPDATE name=VALUES(name)`);const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='new-holland' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='rough-terrain-forklift' LIMIT 1`),sid=await source(c),rid=await record(c,sid);
 await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'New Holland Rough Terrain Forklifts','new-holland-rough-terrain-forklifts') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='new-holland-rough-terrain-forklifts' LIMIT 1`,[mf,et]);const ids=new Map<string,number>();for(const d of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,d);ids.set(d[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[d[1]]));}const def=(k:string)=>{const v=ids.get(k);if(!v)throw new Error(`Missing New Holland F50C definition ${k}`);return v;};
 await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,'F50C','f50c','Current New Holland Construction North America rough terrain forklift; product page specifically describes produce, citrus, bin and pallet handling','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[mf,et,series]);const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND equipment_type_id=? AND slug='f50c' LIMIT 1`,[mf,et]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mid,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'NA','North America','Current New Holland F50C product-page specification',TRUE,?,'Current North America direct product page captured 2026-09-01. Published greater-than ground-clearance wording is kept as text rather than converted to a false exact value.') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),configuration=VALUES(configuration),notes=VALUES(notes)`,[mid,VERSION,rid]);const vid=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mid,VERSION]);await put(c,mid,vid,def('configuration.type'),rid,'Rough terrain forklift');await put(c,mid,vid,def('configuration.market_scope'),rid,'North America / United States current catalog');await put(c,mid,vid,def('forklift.engine_power'),rid,74,'hp');await put(c,mid,vid,def('forklift.lift_capacity'),rid,5000,'lb');await put(c,mid,vid,def('forklift.mast_height'),rid,'12 ft (3.7 m) standard mast / 144 in fork height');await put(c,mid,vid,def('forklift.mast_side_shift'),rid,'3 in (76 mm) each side');await put(c,mid,vid,def('forklift.fork_length'),rid,48,'in');await put(c,mid,vid,def('forklift.drivetrain'),rid,'4WD');await put(c,mid,vid,def('forklift.transmission'),rid,'Power shuttle synchromesh, 4 forward / 4 reverse');await put(c,mid,vid,def('forklift.max_travel_speed'),rid,24.1,'mph');await put(c,mid,vid,def('forklift.operating_weight'),rid,12885,'lb');await put(c,mid,vid,def('forklift.overall_operating_height'),rid,225,'in');await put(c,mid,vid,def('forklift.ground_clearance'),rid,'over 10 in (260 mm)');
}};
