import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow = RowDataPacket & { id:number };
type Seed={slug:string;name:string;url:string;grossHp:number;ptoHp:number;station:'ROPS'|'Cab';transmission:string;heightIn:number;weightLb:number;dimensionSource:'live'|'generation'};
const VERSION='united-states-previous-mt4-generation';
const SERIES_URL='https://lstractorusa.com/series/previous-mt4/';
const BROCHURE_URL='https://lstractorusa.com/wp-content/themes/impactbase/brochures/LS-Tractor-Brochure_MT4.pdf';
const models:Seed[]=[
 {slug:'mt458',name:'MT458',url:'https://lstractorusa.com/tractor/mt458/',grossHp:58,ptoHp:51.2,station:'ROPS',transmission:'Synchro Shuttle',heightIn:103,weightLb:4674,dimensionSource:'generation'},
 {slug:'mt458c',name:'MT458C',url:'https://lstractorusa.com/tractor/mt458c/',grossHp:58,ptoHp:51.2,station:'Cab',transmission:'Synchro Shuttle',heightIn:103,weightLb:4674,dimensionSource:'live'},
 {slug:'mt468',name:'MT468',url:'https://lstractorusa.com/tractor/mt468/',grossHp:68,ptoHp:60,station:'ROPS',transmission:'Synchro Shuttle',heightIn:103,weightLb:4674,dimensionSource:'generation'},
 {slug:'mt468c',name:'MT468C',url:'https://lstractorusa.com/tractor/mt468c/',grossHp:68,ptoHp:60,station:'Cab',transmission:'Synchro Shuttle',heightIn:100.6,weightLb:5121,dimensionSource:'generation'},
 {slug:'mt468cps',name:'MT468CPS',url:'https://lstractorusa.com/tractor/mt468cps/',grossHp:68,ptoHp:60,station:'Cab',transmission:'Power Shuttle',heightIn:100.6,weightLb:5121,dimensionSource:'generation'},
];
const definitions:Array<[string,string,string,string,string|null,number]>=[
 ['Machine Configuration','configuration.station','Operator station','text',null,1],['Engine','engine.model','Engine model','text',null,3],['Engine','engine.type','Engine type','text',null,4],['Engine','emissions.standard','Emissions standard','text',null,5],['Engine','engine.displacement','Engine displacement','decimal','L',6],['Engine','engine.gross_power','Gross engine power','decimal','hp',8],['Engine','engine.rated_speed','Rated engine speed','integer','rpm',9],
 ['Transmission','transmission.standard','Transmission','text',null,10],['Transmission','transmission.speeds','Transmission speeds / ranges','text',null,20],['Transmission','brakes.type','Brakes','text',null,30],['Transmission','steering.type','Steering','text',null,40],
 ['PTO','pto.rated_power','PTO power','decimal','hp',10],['PTO','pto.type','PTO type','text',null,15],['PTO','pto.rear_description','Rear PTO','text',null,20],
 ['Hydraulics','hydraulics.control_system','Hydraulic control system','text',null,5],['Hydraulics','hydraulics.main_pump_capacity','Implement hydraulic pump capacity','decimal','gpm',10],['Hydraulics','hydraulics.power_steering_pump_capacity','Power-steering pump capacity','decimal','gpm',20],['Hydraulics','hydraulics.total_flow','Total hydraulic flow','decimal','gpm',30],['Hydraulics','hitch.category','3-point hitch category','text',null,40],['Hydraulics','hitch.lift_capacity','3-point hitch lift capacity','decimal','lb',50],['Hydraulics','hydraulics.remote_valves','Remote valves','text',null,60],
 ['Capacities','capacities.fuel_tank','Fuel tank capacity','decimal','L',10],['Electrical','electrical.alternator','Alternator','text',null,10],['Dimensions & Weight','dimensions.overall_length','Overall length','decimal','in',10],['Dimensions & Weight','dimensions.overall_width','Overall width','decimal','in',20],['Dimensions & Weight','dimensions.overall_height','Overall height','decimal','in',30],['Dimensions & Weight','dimensions.wheelbase','Wheelbase','decimal','in',40],['Dimensions & Weight','dimensions.unladen_weight','Tractor weight without ballast','decimal','lb',70],['Tires','tires.ag','Ag tires front / rear','text',null,10],['Tires','tires.industrial','Industrial tires front / rear','text',null,20],['Tires','tires.turf','Turf tires front / rear','text',null,30],
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,params:unknown[]=[]){const [rows]=await c.query<IdRow[]>(sql,params);if(!rows[0])throw new Error('LS Tractor Previous MT4 dependency missing');return Number(rows[0].id);}
async function ensureSource(c:Parameters<DbMigration['apply']>[0],sourceId:number,externalId:string,url:string,title:string,raw:unknown){const [rows]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(rows[0])return Number(rows[0].id);const [inserted]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sourceId,url,externalId,title,JSON.stringify(raw)]);return Number(inserted.insertId);}
async function put(c:Parameters<DbMigration['apply']>[0],machineId:number,versionId:number,definitionId:number,sourceRecordId:number,value:string|number,unit:string|null){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[machineId,versionId,definitionId,typeof value==='string'?value:null,typeof value==='number'?value:null,unit,sourceRecordId]);}

export const lsTractorPreviousMt4UsMigration:DbMigration={id:'20260830_395_ls_tractor_previous_mt4_us',description:'Archive the five models in the official Previous MT4 selector separately from New MT4',async apply(c){
 const manufacturerId=await id(c,`SELECT id FROM manufacturers WHERE slug='ls-tractor' LIMIT 1`);const equipmentTypeId=await id(c,`SELECT id FROM equipment_types WHERE slug='tractor' LIMIT 1`);const sourceId=await id(c,`SELECT id FROM sources WHERE name='LS Tractor' AND domain='lstractorusa.com' LIMIT 1`);
 await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'LS Previous MT4 Series','ls-previous-mt4-series') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[manufacturerId,equipmentTypeId]);const seriesId=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND slug='ls-previous-mt4-series' LIMIT 1`,[manufacturerId]);
 await ensureSource(c,sourceId,'ls-tractor-previous-mt4-lineup-2026-08',SERIES_URL,'LS Tractor USA Previous MT4 selector snapshot',{market:'United States',captured:'2026-08-30',generationStatus:'Previous',models:models.map(m=>m.name),replacement:'LS Tractor announced the enhanced New MT4 as the replacement for this line in 2024.',currentFlagPolicy:'All versions in this migration are is_current=false.'});
 const brochureSource=await ensureSource(c,sourceId,'ls-tractor-previous-mt4-generation-brochure',BROCHURE_URL,'LS Tractor MT4 previous-generation brochure',{generation:'Previous MT4',modelsPrinted:['MT458','MT458CPS','MT468','MT468C','MT468CPS'],shared:{engine:'L4C25-T',displacementCuIn:152.8,fuelGal:21.1,speeds:'F16 x R16',implementPumpGpm:9.9,steeringPumpGpm:4.6,totalFlowGpm:14.5,hitchCategory:'II',hitchLiftLb:4079,lengthIn:138.6,widthIn:70,wheelbaseIn:80.3},conflicts:[
  'The generation brochure labels the 58-hp cab column MT458CPS, while the current Previous MT4 selector contains MT458C and no MT458CPS. This migration does not silently map that brochure column onto MT458C.',
  'The current MT458C HTML page reports the same 103 in height and 4,674 lb weight as the ROPS MT458. Because the generation brochure has no unambiguous MT458C column, these live values are preserved for MT458C and the ambiguity is recorded rather than inferred.',
  'Current MT468C and MT468CPS HTML pages report 103 in / 4,674 lb, while the exact generation-brochure cab columns publish 100.6 in / 5,121 lb. Archive normalization follows the generation brochure for those exact model columns.',
  'Some live MT468 non-CPS pages render Transmission Type as Synchro Shuttle / Power Shuttle. The generation brochure states Power Shuttle applies to CPS models; non-CPS archive records are normalized as Synchro Shuttle.'
 ]});
 const definitionIds=new Map<string,number>();for(const row of definitions){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,row);definitionIds.set(row[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[row[1]]));}
 for(const m of models){const liveSource=await ensureSource(c,sourceId,`ls-tractor-${m.slug}-previous-mt4-html-2026-08`,m.url,`LS Tractor ${m.name} still-published US model page`,{market:'United States',captured:'2026-08-30',generation:'Previous MT4',role:'Current previous-generation selector/model-page cross-check',dimensionPolicy:m.dimensionSource});
  await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Previous-generation US LS Tractor MT4 utility tractor','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[manufacturerId,equipmentTypeId,seriesId,m.name,m.slug]);const machineId=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=? LIMIT 1`,[manufacturerId,m.slug]);
  await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States',?,FALSE,?,'Previous-generation LS Tractor MT4 configuration; archive-only and excluded from current New MT4 filters.') ON DUPLICATE KEY UPDATE configuration=VALUES(configuration),is_current=FALSE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[machineId,VERSION,`${m.station}; ${m.transmission}; F16 x R16`,liveSource]);const versionId=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[machineId,VERSION]);
  const dimSource=m.dimensionSource==='generation'?brochureSource:liveSource;const values:Array<[string,string|number,string|null,number?]>=[
   ['configuration.station',m.station,null],['engine.model','L4C25-T',null],['engine.type','4-cylinder inline vertical, liquid-cooled turbo CRDI diesel',null],['emissions.standard','Tier 4',null],['engine.displacement',2.504,'L'],['engine.gross_power',m.grossHp,'hp'],['engine.rated_speed',2500,'rpm'],['transmission.standard',m.transmission,null],['transmission.speeds','F16 x R16',null],['brakes.type','Wet, multi-disc',null],['steering.type','Hydrostatic power steering',null],['pto.rated_power',m.ptoHp,'hp'],['pto.type','Independent',null],['pto.rear_description','540 rpm',null],['hydraulics.control_system','Position / Draft',null],['hydraulics.main_pump_capacity',9.9,'gpm'],['hydraulics.power_steering_pump_capacity',4.6,'gpm'],['hydraulics.total_flow',14.5,'gpm'],['hitch.category','Category II',null],['hitch.lift_capacity',4079,'lb'],['hydraulics.remote_valves','2 pairs standard',null],['capacities.fuel_tank',79.9,'L'],['electrical.alternator','12 V / 70 A',null],['dimensions.overall_length',138.6,'in'],['dimensions.overall_width',70,'in'],['dimensions.wheelbase',80.3,'in'],['dimensions.overall_height',m.heightIn,'in',dimSource],['dimensions.unladen_weight',m.weightLb,'lb',dimSource],['tires.ag','9.5-20 / 16.9-24',null],['tires.industrial','10.5/80-18 / 19.5L-24',null],['tires.turf','36 x 13.5-15 / 16.9-24',null]
  ];
  for(const [key,value,unit,overrideSource] of values){const definitionId=definitionIds.get(key);if(!definitionId)throw new Error(`Missing Previous MT4 spec definition ${key}`);await put(c,machineId,versionId,definitionId,overrideSource??brochureSource,value,unit);}
 }
}};
