import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
const SOURCE_URL='https://www.kioti.com/us/es/products/attachments/front-end-loaders';
const machineSlugs=['nx4510','nx4510-cab','nx4510h','nx4510h-cab','nx5010','nx5010-cab','nx5010h','nx5010h-cab','nx5510','nx5510-cab','nx5510h','nx5510h-cab','nx6010h','nx6010h-cab'];
const loader={slug:'kl6010',model:'KL6010',liftCapacityLb:2761,liftHeightIn:108.3,breakoutLb:2990,bucketSizeIn:72,ratedFlowGpm:10,weightLb:1267};
async function id(c:Parameters<DbMigration['apply']>[0],q:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(q,p);if(!r[0])throw new Error('KIOTI NX loader migration dependency missing');return Number(r[0].id)}
export const kiotiNxLoaderMigration:DbMigration={id:'20260830_341_kioti_nx_loader',description:'Add verified KIOTI KL6010 front-end loader with official current NX Series fitment',async apply(c){
 const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='kioti' LIMIT 1`),sid=await id(c,`SELECT id FROM sources WHERE name='KIOTI' AND domain='kioti.com' LIMIT 1`);const externalId='kioti-kl6010-nx-current-us-2026-08';const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);let sr=r[0]?.id?Number(r[0].id):0;if(!sr){const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,SOURCE_URL,externalId,'KIOTI US KL6010 front-end loader specifications and NX Series compatibility',JSON.stringify({market:'United States',captured:'2026-08-30',loader,compatibility:'Fits the NX Series',fit:machineSlugs,note:'Official KIOTI US attachment catalog states KL6010 is specifically designed for and fits the NX Series. Performance values are taken from that same US catalog.'})]);sr=Number(x.insertId)}
 await c.query(`INSERT INTO attachments(manufacturer_id,attachment_type,model_name,slug,lift_capacity_text,lift_height_text,configuration_text,data_status) VALUES(?,'front-loader',?,?,?,?,?,'verified') ON DUPLICATE KEY UPDATE model_name=VALUES(model_name),lift_capacity_text=VALUES(lift_capacity_text),lift_height_text=VALUES(lift_height_text),configuration_text=VALUES(configuration_text),data_status='verified'`,[mf,loader.model,loader.slug,`${loader.liftCapacityLb.toLocaleString('en-US')} lb to full height`,`${loader.liftHeightIn} in maximum pivot-pin height`,`Fits the NX Series; ${loader.breakoutLb.toLocaleString('en-US')} lb breakout force at pivot pin; ${loader.bucketSizeIn} in bucket; ${loader.ratedFlowGpm} gpm rated flow; ${loader.weightLb.toLocaleString('en-US')} lb loader weight`]);const ai=await id(c,`SELECT id FROM attachments WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,loader.slug]);for(const slug of machineSlugs){const mi=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,slug]);await c.query(`INSERT INTO machine_attachments(machine_id,attachment_id,compatibility_note,source_record_id,confidence) VALUES(?,?,?,?, 'official') ON DUPLICATE KEY UPDATE compatibility_note=VALUES(compatibility_note),source_record_id=VALUES(source_record_id),confidence='official'`,[mi,ai,'Official KIOTI compatibility: KL6010 fits the current NX Series.',sr])}
}};
