import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Seed={slug:string;model:string;url?:string;width?:string;transport?:string;disks?:number;weightPerBlade?:number;powerHp?:number};
const VERSION='united-states-current-2026-08';
const FAMILY_URL='https://www.deere.com/en/tillage/field-cultivators/';
const models:Seed[]=[
 {slug:'hsd15',model:'HSD15',url:'https://www.deere.com/en-us/products-solutions/tillage/disks/hsd15-high-speed-disk-njcymvhg',width:'15 ft 3 in',transport:'12 ft',disks:37,weightPerBlade:370,powerHp:230},
 {slug:'hsd19',model:'HSD19'},
 {slug:'hsd22',model:'HSD22',url:'https://www.deere.com/en-us/products-solutions/tillage/disks/hsd22-high-speed-disk-njc0mvhg',width:'21 ft 11 in',transport:'12 ft',disks:53,weightPerBlade:364,powerHp:330},
 {slug:'hsd25-2s',model:'HSD25 2S'},
 {slug:'hsd25',model:'HSD25'},
 {slug:'hsd29',model:'HSD29',url:'https://www.deere.com/en-us/products-solutions/tillage/disks/hsd29-high-speed-disk-njgzmvhg'},
 {slug:'hsd32',model:'HSD32'},
 {slug:'hsd35',model:'HSD35'},
 {slug:'hsd39',model:'HSD39'},
 {slug:'hsd42',model:'HSD42'},
 {slug:'hsd45',model:'HSD45'},
];
const defs:Array<[string,string,string,string,string|null,number]>=[
 ['Machine Configuration','configuration.type','Machine configuration','text',null,1],['Machine Configuration','configuration.market_scope','Official market scope','text',null,2],
 ['Tillage System','high_speed_disk.working_depth','Working depth','text',null,10],['Tillage System','high_speed_disk.working_speed','Working speed','text',null,20],['Tillage System','high_speed_disk.disk_spacing','Disk spacing','text',null,30],['Tillage System','high_speed_disk.depth_control','Depth control','text',null,40],['Tillage System','high_speed_disk.residue_conditions','Residue conditions','text',null,50],['Tillage System','high_speed_disk.working_width','Working width','text',null,60],['Tillage System','high_speed_disk.disk_count','Number of disks','integer',null,70],['Tillage System','high_speed_disk.weight_per_blade_lb','Weight per blade','decimal','lb',80],
 ['Tractor Requirements','high_speed_disk.hp_per_ft','Required engine power per foot','text',null,10],['Tractor Requirements','high_speed_disk.recommended_engine_hp','Recommended engine power','decimal','hp',20],['Dimensions & Transport','high_speed_disk.transport_width','Transport width','text',null,10],['Precision Technology','high_speed_disk.autonomy_ready','Precision and autonomy preparation','text',null,10],
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('John Deere HSD migration dependency missing');return Number(r[0].id);}
async function src(c:Parameters<DbMigration['apply']>[0]){const[r]=await c.query<IdRow[]>(`SELECT id FROM sources WHERE name='John Deere' AND domain='deere.com' ORDER BY id LIMIT 1`);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO sources(name,domain,source_type,authority_level) VALUES('John Deere','deere.com','manufacturer','official')`);return Number(x.insertId);}
async function rec(c:Parameters<DbMigration['apply']>[0],sid:number,m:Seed){const externalId=`john-deere-${m.slug}-high-speed-disk-us-current-2026-08`;const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,m.url||FAMILY_URL,externalId,`John Deere ${m.model} current US high-speed disk specifications`,JSON.stringify({captured:'2026-08-31',market:'United States',equipmentType:'High-Speed Disk',familySource:FAMILY_URL,...m})]);return Number(x.insertId);}
async function putText(c:Parameters<DbMigration['apply']>[0],mid:number,vid:number,did:number,rid:number,v:string){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,NULL,NULL,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=NULL,unit=NULL,source_record_id=VALUES(source_record_id),confidence='official'`,[mid,vid,did,v,rid]);}
async function putNum(c:Parameters<DbMigration['apply']>[0],mid:number,vid:number,did:number,rid:number,v:number,u:string|null=null){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,NULL,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=NULL,value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mid,vid,did,v,u,rid]);}
export const johnDeereHsdHighSpeedDisksCurrentMigration:DbMigration={id:'20260831_520_john_deere_hsd_high_speed_disks_current',description:'Add current John Deere US HSD Series high-speed disks',async apply(c){
 await c.query(`INSERT INTO equipment_types(name,slug) VALUES('High-Speed Disk','high-speed-disk') ON DUPLICATE KEY UPDATE name=VALUES(name)`);await c.query(`INSERT INTO manufacturers(name,slug) VALUES('John Deere','john-deere') ON DUPLICATE KEY UPDATE name=VALUES(name)`);const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='john-deere' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='high-speed-disk' LIMIT 1`),sid=await src(c);await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'HSD Series','hsd-series') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='hsd-series' LIMIT 1`,[mf,et]);const ids=new Map<string,number>();for(const d of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,d);ids.set(d[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[d[1]]));}const def=(k:string)=>{const v=ids.get(k);if(!v)throw new Error(`Missing HSD definition ${k}`);return v;};
 for(const m of models){const rid=await rec(c,sid,m);await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current John Deere United States HSD Series high-speed disk lineup','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes)`,[mf,et,series,m.model,m.slug]);const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND equipment_type_id=? AND slug=? LIMIT 1`,[mf,et,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mid,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States','Current HSD Series specification',TRUE,?,'Current John Deere US tillage comparison and product-page data captured 2026-08-31.') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mid,VERSION,rid]);const vid=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mid,VERSION]);await putText(c,mid,vid,def('configuration.type'),rid,'High-speed disk');await putText(c,mid,vid,def('configuration.market_scope'),rid,'United States current catalog');await putText(c,mid,vid,def('high_speed_disk.working_depth'),rid,'2 - 6 in (5.1 - 15.2 cm)');await putText(c,mid,vid,def('high_speed_disk.working_speed'),rid,'10 - 14 mph (16 - 22.5 km/h)');await putText(c,mid,vid,def('high_speed_disk.disk_spacing'),rid,'10 in on current HSD individual specifications where published');await putText(c,mid,vid,def('high_speed_disk.depth_control'),rid,'TruSet Set-Point / Single-Point');await putText(c,mid,vid,def('high_speed_disk.residue_conditions'),rid,'Light / Medium / Heavy');await putText(c,mid,vid,def('high_speed_disk.hp_per_ft'),rid,'15+ engine hp/ft (36.7 kW/m)');await putText(c,mid,vid,def('high_speed_disk.autonomy_ready'),rid,'HSD Series is listed by John Deere as Autonomy Ready from the factory');if(m.width)await putText(c,mid,vid,def('high_speed_disk.working_width'),rid,m.width);if(m.transport)await putText(c,mid,vid,def('high_speed_disk.transport_width'),rid,m.transport);if(m.disks)await putNum(c,mid,vid,def('high_speed_disk.disk_count'),rid,m.disks);if(m.weightPerBlade)await putNum(c,mid,vid,def('high_speed_disk.weight_per_blade_lb'),rid,m.weightPerBlade,'lb');if(m.powerHp)await putNum(c,mid,vid,def('high_speed_disk.recommended_engine_hp'),rid,m.powerHp,'hp');}
 }};
