import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
const BROCHURE_URL='https://lstractorusa.com/wp-content/themes/impactbase/brochures/LS-Tractor-Brochure_MT4.pdf';
const LOADERS_URL='https://lstractorusa.com/front-end-loaders/';
const BACKHOES_URL='https://lstractorusa.com/backhoes/';
const machines=['mt458','mt458c','mt468','mt468c','mt468cps'];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,params:unknown[]=[]){const [rows]=await c.query<IdRow[]>(sql,params);if(!rows[0])throw new Error('LS Tractor Previous MT4 attachments dependency missing');return Number(rows[0].id);}
async function ensureSource(c:Parameters<DbMigration['apply']>[0],sourceId:number,externalId:string,url:string,title:string,raw:unknown){const [rows]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(rows[0])return Number(rows[0].id);const [inserted]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sourceId,url,externalId,title,JSON.stringify(raw)]);return Number(inserted.insertId);}
export const lsTractorPreviousMt4AttachmentsMigration:DbMigration={id:'20260830_396_ls_tractor_previous_mt4_attachments',description:'Add generation-correct LL5106 and LB3102 fitment for Previous MT4',async apply(c){
 const manufacturerId=await id(c,`SELECT id FROM manufacturers WHERE slug='ls-tractor' LIMIT 1`);const sourceId=await id(c,`SELECT id FROM sources WHERE name='LS Tractor' AND domain='lstractorusa.com' LIMIT 1`);
 const sourceRecordId=await ensureSource(c,sourceId,'ls-tractor-previous-mt4-generation-attachments',BROCHURE_URL,'LS Tractor Previous MT4 generation loader/backhoe matrix',{
  generation:'Previous MT4',applications:machines,loader:'LL5106',backhoe:'LB3102',
  generationLoader:{bucketIn:72,maxLiftHeightIn:116.3,clearanceDumpedIn:82.8,reachAtMaxHeightIn:6.6,maxDumpDeg:72,maxRollbackDeg:46,diggingDepthIn:4.2,carryHeightIn:68.9,liftAtPivotPinLb:2981,breakoutAtPivotPinLb:4767},
  currentLoaderCatalog:{url:LOADERS_URL,maxLiftHeightIn:116,clearanceDumpedIn:84.7,reachAtMaxHeightIn:6.6,maxDumpDeg:71,maxRollbackDeg:48,diggingDepthIn:4.1,carryHeightIn:67.6,liftAtPivotPin1_5mLb:3351,breakoutAtPivotPinLb:4556,compatible:['MT458','MT458C','MT468','MT468C','MT468CPS']},
  generationBackhoe:{diggingDepthIn:94.5,reachIn:136.2,loadingHeightIn:80.3,swingArcDeg:180,transportHeightIn:92.9,bucketRotationDeg:180,stabilizerDownIn:68.7,stabilizerUpIn:46.5,bucketDiggingForceLb:3740},
  currentBackhoeCatalog:{url:BACKHOES_URL,group:'LB3100, LB3102, LB3104',diggingDepthIn:94.4,reachIn:136.1,loadingHeightIn:80.3,swingArcDeg:180,transportHeightIn:92.9,bucketRotationDeg:180,stabilizerDownIn:68.7,stabilizerUpIn:46.4,bucketDiggingForceLb:3748,currentCompatibilityText:'MT342 MT347 MT352 MT357'},
  sourcePolicy:'Archive attachment geometry and performance follow the Previous MT4 generation brochure. The current central LL5106 catalog explicitly retains exact Previous MT4 model compatibility but publishes later/different performance values. The current central backhoe catalog no longer maps LB3102 to MT4, while the generation brochure and all still-published Previous MT4 model pages do; generation-correct fitment is therefore retained with the catalog change documented.'
 });
 await c.query(`INSERT INTO attachments(manufacturer_id,attachment_type,model_name,slug,lift_capacity_text,lift_height_text,configuration_text,data_status) VALUES(?,'front-loader','LL5106','ll5106',?,?,?,'verified') ON DUPLICATE KEY UPDATE model_name=VALUES(model_name),lift_capacity_text=VALUES(lift_capacity_text),lift_height_text=VALUES(lift_height_text),configuration_text=VALUES(configuration_text),data_status='verified'`,[manufacturerId,'2,981 lb at pivot pin in Previous MT4 generation brochure; current central catalog later publishes 3,351 lb at pivot pin / 1.5 m height','116.3 in generation brochure; current central catalog later publishes 116 in','Previous-generation MT4 LL5106 front loader. Generation brochure: 72 in bucket; 116.3 in max lift; 82.8 in dumped clearance; 6.6 in reach at max height; 72° dump; 46° rollback; 4.2 in digging depth; 68.9 in carry height; 2,981 lb lift at pivot pin; 4,767 lb breakout. Current central catalog retains exact MT458/MT458C/MT468/MT468C/MT468CPS compatibility but publishes a later measurement/specification set, preserved separately in provenance.']);
 const loaderId=await id(c,`SELECT id FROM attachments WHERE manufacturer_id=? AND slug='ll5106' LIMIT 1`,[manufacturerId]);
 await c.query(`INSERT INTO attachments(manufacturer_id,attachment_type,model_name,slug,lift_capacity_text,lift_height_text,configuration_text,data_status) VALUES(?,'backhoe','LB3102','lb3102',NULL,NULL,?,'verified') ON DUPLICATE KEY UPDATE model_name=VALUES(model_name),configuration_text=VALUES(configuration_text),data_status='verified'`,[manufacturerId,'Previous-generation MT4 LB3102 backhoe. Generation brochure: 94.5 in digging depth; 136.2 in reach from swing pivot; 80.3 in loading height; 180° swing; 92.9 in transport height; 180° bucket rotation; 68.7 in stabilizer spread down; 46.5 in up; 3,740 lb bucket digging force. Current centralized LB3100/LB3102/LB3104 listing has a slightly revised geometry/force set and no longer lists MT4 compatibility; historical MT4 fitment is preserved from the generation brochure and still-published MT4 model pages.']);
 const backhoeId=await id(c,`SELECT id FROM attachments WHERE manufacturer_id=? AND slug='lb3102' LIMIT 1`,[manufacturerId]);
 for(const machineSlug of machines){const machineId=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=? LIMIT 1`,[manufacturerId,machineSlug]);await c.query(`INSERT INTO machine_attachments(machine_id,attachment_id,compatibility_note,source_record_id,confidence) VALUES(?,?,?,?, 'official') ON DUPLICATE KEY UPDATE compatibility_note=VALUES(compatibility_note),source_record_id=VALUES(source_record_id),confidence='official'`,[machineId,loaderId,'LL5106 generation-correct fitment is confirmed by the Previous MT4 brochure, still-published model page and current central loader catalog.',sourceRecordId]);await c.query(`INSERT INTO machine_attachments(machine_id,attachment_id,compatibility_note,source_record_id,confidence) VALUES(?,?,?,?, 'official') ON DUPLICATE KEY UPDATE compatibility_note=VALUES(compatibility_note),source_record_id=VALUES(source_record_id),confidence='official'`,[machineId,backhoeId,'LB3102 generation-correct Previous MT4 fitment is confirmed by the generation brochure and still-published model page; the current central backhoe catalog has since remapped its compatibility list.',sourceRecordId]);}
}};
