import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Seed={slug:string;model:string;type:string;machines:string[];source:string;note:string};
const attachments:Seed[]=[
 {slug:'rk-l72',model:'L72',type:'front-loader',machines:['rk19h','rk21h'],source:'https://www.rktractors.com/products-tractors-rk21h-rk-tractors.php',note:'Quick-attach front-end loader with 48 in bucket'},
 {slug:'rk-l75',model:'L75',type:'front-loader',machines:['rk24h'],source:'https://www.rktractors.com/products-tractors-rk24-series-rk-tractors.php',note:'Quick-attach front-end loader with 50 in bucket'},
 {slug:'rk-l85',model:'L85',type:'front-loader',machines:['rk25h'],source:'https://www.rktractors.com/products-tractors-rk25-series-rk-tractors.php',note:'Quick-attach front-end loader with 50 in bucket'},
 {slug:'rk-l102',model:'L102',type:'front-loader',machines:['rk37s','rk37h','rk37sc','rk37hc'],source:'https://www.rktractors.com/products-tractors-rk37-series-rk-tractors.php',note:'Quick-attach front-end loader with 62 in bucket'},
 {slug:'rk-l110',model:'L110',type:'front-loader',machines:['rk55s','rk55h','rk55sc','rk55hc'],source:'https://www.rktractors.com/products-tractors-rk55-series-rk-tractors.php',note:'Quick-attach front-end loader with 72 in bucket'},
 {slug:'rk-l135sl',model:'L135SL',type:'front-loader',machines:['rk74psc'],source:'https://www.rktractors.com/products-tractors-rk74-series-rk-tractors.php',note:'Self-leveling skid-steer-compatible quick-attach front-end loader'},
 {slug:'rk-bh6-5',model:'BH6.5',type:'backhoe',machines:['rk24h'],source:'https://www.rktractors.com/products-tractors-rk24-series-rk-tractors.php',note:'6.5-ft backhoe with 12 in bucket and mechanical thumb'},
 {slug:'rk-bh6-7',model:'BH6.7',type:'backhoe',machines:['rk25h'],source:'https://www.rktractors.com/products-tractors-rk25-series-rk-tractors.php',note:'6.7-ft backhoe with 12 in bucket and mechanical thumb'},
 {slug:'rk-bh7-5',model:'BH7.5',type:'backhoe',machines:['rk37s','rk37h','rk37sc','rk37hc'],source:'https://www.rktractors.com/products-tractors-rk37-series-rk-tractors.php',note:'7.5-ft backhoe with 16 in bucket and mechanical thumb'},
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('RK attachments migration dependency missing');return Number(r[0].id)}
async function source(c:Parameters<DbMigration['apply']>[0],sid:number,a:Seed){const eid=`rk-${a.slug}-fitment-current-us-2026-08`;const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[eid]);if(r[0])return Number(r[0].id);const[i]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,a.source,eid,`RK Tractors ${a.model} current fitment`,JSON.stringify({market:'United States',captured:'2026-08-31',model:a.model,type:a.type,machines:a.machines,note:a.note,sourcePolicy:'Only attachment model codes explicitly named on current RK tractor pages are represented as verified attachment records. The unnamed RK55 8.5-ft backhoe is intentionally not assigned an invented model code.'})]);return Number(i.insertId)}
export const rkTractorsAttachmentsMigration:DbMigration={id:'20260831_470_rk_tractors_attachments',description:'Add verified current RK loader and explicitly named backhoe fitment',async apply(c){const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='rk-tractors' LIMIT 1`),sid=await id(c,`SELECT id FROM sources WHERE name='RK Tractors' AND domain='rktractors.com' LIMIT 1`);for(const a of attachments){const sr=await source(c,sid,a);await c.query(`INSERT INTO attachments(manufacturer_id,attachment_type,model_name,slug,configuration_text,data_status) VALUES(?,?,?,?,?,'verified') ON DUPLICATE KEY UPDATE attachment_type=VALUES(attachment_type),model_name=VALUES(model_name),configuration_text=VALUES(configuration_text),data_status='verified'`,[mf,a.type,a.model,a.slug,`${a.note}. Current official RK Tractors fitment.`]);const aid=await id(c,`SELECT id FROM attachments WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,a.slug]);for(const ms of a.machines){const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,ms]);await c.query(`INSERT INTO machine_attachments(machine_id,attachment_id,compatibility_note,source_record_id,confidence) VALUES(?,?,?,?, 'official') ON DUPLICATE KEY UPDATE compatibility_note=VALUES(compatibility_note),source_record_id=VALUES(source_record_id),confidence='official'`,[mid,aid,`${a.model}: ${a.note}; listed on the current RK Tractors model/series page.`,sr])}}}};
