import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';
type IdRow=RowDataPacket&{id:number};
const l625Fit=['farmall-90a','farmall-100a','farmall-110a','farmall-120a'];
const l575Fit=['farmall-95a','farmall-105a','farmall-115a'];
const loaders=[
 {model:'L625',slug:'l625-farmall-medium-utility-a',url:'https://www.caseih.com/en-us/unitedstates/products/loaders-attachments/l600-series-loaders/l625',externalId:'case-ih-farmall-medium-utility-a-l625-current',lift:null,height:null,config:'Designed for Farmall Medium Utility A 90A, 100A, 110A and 120A',fit:l625Fit},
 {model:'L575',slug:'l575-farmall-medium-utility-a',url:'https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-medium-utility-a-series/farmall-medium-utility-95a',externalId:'case-ih-farmall-medium-utility-a-l575-current',lift:'up to 3,174 lb',height:'up to 134.5 in',config:'Designed for Farmall Medium Utility A 95A, 105A and 115A; boom breakout up to 3,372 lb',fit:l575Fit},
] as const;
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw Error('Farmall Medium Utility loader dependency missing');return Number(r[0].id)}
export const caseIHFarmallMediumUtilityALoadersMigration:DbMigration={id:'20260828_242_case_ih_farmall_medium_utility_a_loaders',description:'Add official Case IH L625 and L575 fitments for Farmall Medium Utility A',async apply(c){const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='case-ih'`);let[s]=await c.query<IdRow[]>(`SELECT id FROM sources WHERE name='Case IH' AND domain='caseih.com' LIMIT 1`);const sid=s[0]?.id?Number(s[0].id):0;for(const loader of loaders){const[rows]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[loader.externalId]);let sr=rows[0]?.id?Number(rows[0].id):0;if(!sr){const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,loader.url,loader.externalId,`Case IH ${loader.model} official loader compatibility for Farmall Medium Utility A`,JSON.stringify(loader)]);sr=Number(x.insertId)}await c.query(`INSERT INTO attachments(manufacturer_id,attachment_type,model_name,slug,lift_capacity_text,lift_height_text,configuration_text,data_status) VALUES(?,'front-loader',?,?,?,?,?,'verified') ON DUPLICATE KEY UPDATE model_name=VALUES(model_name),lift_capacity_text=VALUES(lift_capacity_text),lift_height_text=VALUES(lift_height_text),configuration_text=VALUES(configuration_text),data_status='verified'`,[mf,loader.model,loader.slug,loader.lift,loader.height,loader.config]);const aid=await id(c,`SELECT id FROM attachments WHERE manufacturer_id=? AND slug=?`,[mf,loader.slug]);for(const slug of loader.fit){const mi=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=?`,[mf,slug]);await c.query(`INSERT INTO machine_attachments(machine_id,attachment_id,compatibility_note,source_record_id,confidence) VALUES(?,?,?,?,'official') ON DUPLICATE KEY UPDATE source_record_id=VALUES(source_record_id),confidence='official',compatibility_note=VALUES(compatibility_note)`,[mi,aid,`Official Case IH ${loader.model} compatibility for ${slug}.`,sr])}}}};
