import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
const SOURCE_URL='https://agriculture.newholland.com/en-us/nar/products/tractors-telehandlers/t6-180-methane-power';
const EXTERNAL_ID='new-holland-t6-180-methane-current-us-2026-08';
const VERSION='united-states-current-2026-08';
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('New Holland T6.180 Methane dependency missing');return Number(r[0].id)}
export const newHollandT6180MethaneCurrentSpecsMigration:DbMigration={id:'20260829_282_new_holland_t6_180_methane_current_specs',description:'Add current official US New Holland T6.180 Methane Power tractor',async apply(c){
 const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='new-holland' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='tractor' LIMIT 1`),sid=await id(c,`SELECT id FROM sources WHERE name='New Holland' AND domain='agriculture.newholland.com' LIMIT 1`);
 const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[EXTERNAL_ID]);let sr=r[0]?.id?Number(r[0].id):0;if(!sr){const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title) VALUES(?,?,?,'New Holland US T6.180 Methane Power current specifications')`,[sid,SOURCE_URL,EXTERNAL_ID]);sr=Number(x.insertId)}
 await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'T6 Methane Power','t6-methane-power') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='t6-methane-power' LIMIT 1`,[mf,et]);
 const defs:Array<[string,string,string,string,string|null,number]>=[['Machine Configuration','configuration.station','Operator station','text',null,1],['Machine Configuration','configuration.fuel','Fuel','text',null,3],['Engine','engine.displacement','Engine displacement','decimal','L',20],['Engine','engine.cylinders','Cylinders','integer',null,4],['Engine','engine.rated_power','Rated engine power','decimal','hp',10],['Engine','engine.max_power','Max boosted engine power','decimal','hp',11],['Transmission','transmission.options','Transmission options','text',null,20],['PTO','pto.rated_power','PTO power','decimal','hp',10]];for(const d of defs)await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,d);
 await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,'T6.180 Methane Power','t6-180-methane-power','Current US New Holland methane/CNG tractor','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes)`,[mf,et,series]);const mi=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug='t6-180-methane-power' LIMIT 1`,[mf]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mi,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States','T6.180 Methane Power',TRUE,?,'Official New Holland North America current data captured August 2026.') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mi,VERSION,sr]);const vi=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mi,VERSION]);const vals:Array<[string,string|number,string|null]>=[['configuration.station','Horizon cab',null],['configuration.fuel','Compressed natural gas (CNG) or biomethane',null],['engine.displacement',6.7,'L'],['engine.cylinders',6,null],['engine.rated_power',145,'hp'],['engine.max_power',175,'hp'],['transmission.options','Electro Command semi-powershift: 16x16, 17x16 Economy, 17x16 Fast Mover, or 32x32 Creeper',null],['pto.rated_power',126,'hp']];for(const[k,v,u]of vals){const di=await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[k]);await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mi,vi,di,typeof v==='string'?v:null,typeof v==='number'?v:null,u,sr])}
}};