import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow = RowDataPacket & { id: number };
type Seed = {
  slug:string; name:string; ratedHp:number; maxHp:number; torqueLbFt:number; speeds:string; hitchLb:number;
  hitchControl:string; pto:string; widthIn:number; heightIn:number; weightLb:number; maxWeightLb:number; frontTire:string; rearTire:string;
};

const VERSION='united-states-current-2026-08';
const SERIES_URL='https://deutz-fahramerica.com/tractors/5-series-home/';
const CURRENT_BROCHURE='https://deutz-fahramerica.com/wp-content/uploads/5-Series-Brochure.pdf';
const CURRENT_SPECS='https://deutz-fahramerica.com/wp-content/uploads/5-Series-Brochure-Specs.pdf';
const LEGACY_US_SPEC='https://deutz-fahramerica.com/wp-content/uploads/5-series-4pg-spec.pdf';

const models:Seed[]=[
  {slug:'5105',name:'5105',ratedHp:101,maxHp:106,torqueLbFt:313,speeds:'F40 x R40 with creeper and underdrive',hitchLb:7935,hitchControl:'Mechanical rear lift',pto:'540 / 540E rpm',widthIn:81.1,heightIn:105.6,weightLb:8820,maxWeightLb:14330,frontTire:'420/70 R24',rearTire:'480/70 R34'},
  {slug:'5125',name:'5125',ratedHp:120,maxHp:126,torqueLbFt:374,speeds:'F60 x R60 with creeper and 3-speed powershift',hitchLb:11900,hitchControl:'Electronic rear lift',pto:'540 / 540E / 1000 / 1000E rpm',widthIn:87,heightIn:107,weightLb:9590,maxWeightLb:16530,frontTire:'440/65 R28',rearTire:'540/65 R38'},
];

const defs:Array<[string,string,string,string,string|null,number]>=[
 ['Machine Configuration','configuration.station','Operator station','text',null,1],
 ['Engine','engine.make','Engine manufacturer','text',null,1],['Engine','engine.model','Engine model','text',null,3],['Engine','engine.cylinders','Cylinders','integer',null,4],['Engine','engine.displacement','Engine displacement','decimal','L',6],['Engine','engine.rated_power','Rated engine power','decimal','hp',7],['Engine','engine.gross_power','Maximum engine power','decimal','hp',8],['Engine','engine.rated_speed','Rated engine speed','integer','rpm',9],['Engine','engine.max_torque','Maximum torque','decimal','lb-ft',10],['Engine','engine.max_torque_speed','Maximum torque speed','integer','rpm',11],
 ['Transmission','transmission.standard','Transmission','text',null,10],['Transmission','transmission.speeds','Transmission speeds / ranges','text',null,20],['Transmission','drivetrain.type','Driveline','text',null,30],['Transmission','steering.type','Steering','text',null,40],
 ['PTO','pto.rear_description','Rear PTO','text',null,20],
 ['Hydraulics','hydraulics.system_type','Hydraulic system','text',null,5],['Hydraulics','hydraulics.main_pump_capacity','Implement hydraulic pump capacity','decimal','gpm',20],['Hydraulics','hitch.control','3-point hitch control','text',null,40],['Hydraulics','hitch.category','3-point hitch category','text',null,45],['Hydraulics','hitch.lift_capacity','3-point hitch lift capacity','decimal','lb',50],['Hydraulics','hydraulics.remote_valves','Remote valves','text',null,60],
 ['Capacities','capacities.fuel_tank','Fuel tank capacity','decimal','gal',10],['Capacities','capacities.def_tank','DEF tank capacity','decimal','gal',20],
 ['Dimensions & Weight','dimensions.overall_length','Maximum length','decimal','in',10],['Dimensions & Weight','dimensions.overall_width','Width','decimal','in',20],['Dimensions & Weight','dimensions.overall_height','Total height','decimal','in',30],['Dimensions & Weight','dimensions.wheelbase','Wheelbase','decimal','in',40],['Dimensions & Weight','dimensions.unladen_weight','Weight','decimal','lb',70],['Dimensions & Weight','dimensions.max_permissible_weight','Total admissible load','decimal','lb',80],
 ['Tires','tires.front','Published front tires','text',null,10],['Tires','tires.rear','Published rear tires','text',null,20],
];

async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('Deutz-Fahr 5 Series migration dependency missing');return Number(r[0].id)}
async function source(c:Parameters<DbMigration['apply']>[0],sid:number,eid:string,url:string,title:string,raw:unknown){const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[eid]);if(r[0])return Number(r[0].id);const[i]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,url,eid,title,JSON.stringify(raw)]);return Number(i.insertId)}
async function put(c:Parameters<DbMigration['apply']>[0],mid:number,vid:number,did:number,srid:number,v:string|number,u:string|null){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mid,vid,did,typeof v==='string'?v:null,typeof v==='number'?v:null,u,srid])}

export const deutzFahr5SeriesCurrentUsMigration:DbMigration={
 id:'20260830_415_deutz_fahr_5_series_current_us',
 description:'Add current US Deutz-Fahr America 5105 and 5125 5 Series tractors',
 async apply(c){
  const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='deutz-fahr' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='tractor' LIMIT 1`),sid=await id(c,`SELECT id FROM sources WHERE name='Deutz-Fahr America' AND domain='deutz-fahramerica.com' LIMIT 1`);
  await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'DEUTZ-FAHR 5 Series','deutz-fahr-5-series') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND slug='deutz-fahr-5-series' LIMIT 1`,[mf]);
  const seriesSr=await source(c,sid,'deutz-fahr-america-5-series-current-us-2026-08',SERIES_URL,'Deutz-Fahr America current 5 Series lineup',{market:'United States',captured:'2026-08-30',models:['5105','5125'],currentBrochure:CURRENT_BROCHURE,currentSpecSheet:CURRENT_SPECS,legacyUsSpec:LEGACY_US_SPEC,sourcePolicy:'Current America HTML and current brochure/spec sheet are primary. The current PDF extraction collapses repeated transmission cells for 5125; exact 60x60 configuration is carried from the prior official US model spec sheet and remains consistent with the current series statement that configurations run up to 60 forward/reverse speeds.',hitchNote:'Current HTML rounds series maximum to 11,925 lb while the current model table publishes 11,900 lb for 5125; the model-table value is retained.'});
  const d=new Map<string,number>();for(const row of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,row);d.set(row[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[row[1]]))}
  for(const m of models){const sr=await source(c,sid,`deutz-fahr-america-${m.slug}-current-us-2026-08`,CURRENT_BROCHURE,`Deutz-Fahr America ${m.name} current US specifications`,{market:'United States',captured:'2026-08-30',model:m.name,currentSeriesPage:SERIES_URL,currentSpecSheet:CURRENT_SPECS});await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current US Deutz-Fahr America 5 Series utility tractor','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[mf,et,series,m.name,m.slug]);const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mid,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States',?,TRUE,?,'Current Deutz-Fahr America 5 Series cab utility tractor.') ON DUPLICATE KEY UPDATE configuration=VALUES(configuration),is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mid,VERSION,`Cab; electro-hydraulic PowerShuttle with Stop&Go; ${m.speeds}`,sr||seriesSr]);const vid=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mid,VERSION]);const vals:Array<[string,string|number,string|null]>=[['configuration.station','Cab',null],['engine.make','FARMotion',null],['engine.model','FARMotion 45',null],['engine.cylinders',4,null],['engine.displacement',3.849,'L'],['engine.rated_power',m.ratedHp,'hp'],['engine.gross_power',m.maxHp,'hp'],['engine.rated_speed',2200,'rpm'],['engine.max_torque',m.torqueLbFt,'lb-ft'],['engine.max_torque_speed',1400,'rpm'],['transmission.standard','Electro-hydraulic PowerShuttle with Stop&Go',null],['transmission.speeds',m.speeds,null],['drivetrain.type','4WD',null],['steering.type','Hydrostatic steering with independent pump',null],['pto.rear_description',m.pto,null],['hydraulics.system_type','Open center',null],['hydraulics.main_pump_capacity',14.5,'gpm'],['hitch.control',m.hitchControl,null],['hitch.category','Category II Automatic',null],['hitch.lift_capacity',m.hitchLb,'lb'],['hydraulics.remote_valves','3 rear spool valves',null],['capacities.fuel_tank',38.3,'gal'],['capacities.def_tank',2.6,'gal'],['dimensions.overall_length',168,'in'],['dimensions.overall_width',m.widthIn,'in'],['dimensions.overall_height',m.heightIn,'in'],['dimensions.wheelbase',94.5,'in'],['dimensions.unladen_weight',m.weightLb,'lb'],['dimensions.max_permissible_weight',m.maxWeightLb,'lb'],['tires.front',m.frontTire,null],['tires.rear',m.rearTire,null]];for(const[k,v,u]of vals){const did=d.get(k);if(!did)throw new Error(`Missing Deutz-Fahr 5 Series spec ${k}`);await put(c,mid,vid,did,sr||seriesSr,v,u)}}
 }
};
