import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow = RowDataPacket & { id: number };
type Seed = { slug:string; name:string; maxHp:number; boostHp:number; torqueLbFt:number };
const VERSION = 'united-states-current-2026-08';
const SERIES_URL = 'https://mccormick-tractors.com/us/en/products/x6-6.html';
const TECH_URL = 'https://mccormick-tractors.com/content/dam/mccormick/as/MC_RP78_X6.6_Brochure_2p_6725807A1_HR_EN.pdf.inline.pdf';
const models: Seed[] = [
  { slug:'x6-616-xtrashift', name:'X6.616 XtraShift', maxHp:155, boostHp:165, torqueLbFt:498.6 },
  { slug:'x6-618-xtrashift', name:'X6.618 XtraShift', maxHp:166, boostHp:175, torqueLbFt:516.3 },
];
const defs:Array<[string,string,string,string,string|null,number]> = [
 ['Machine Configuration','configuration.station','Operator station','text',null,1],
 ['Engine','engine.make','Engine manufacturer','text',null,1],['Engine','engine.model','Engine model','text',null,3],['Engine','engine.cylinders','Cylinders','integer',null,4],['Engine','emissions.standard','Emissions standard','text',null,5],['Engine','engine.displacement','Engine displacement','decimal','L',6],['Engine','engine.gross_power','Maximum engine power','decimal','hp',8],['Engine','engine.boost_power','Maximum power with EPM','decimal','hp',9],['Engine','engine.max_torque','Maximum torque with EPM','decimal','lb-ft',10],['Engine','engine.oil_change_interval','Engine service interval','integer','h',20],
 ['Transmission','transmission.standard','Transmission','text',null,10],['Transmission','transmission.speeds','Transmission speeds','text',null,20],['Transmission','transmission.minimum_speed','Minimum transmission speed','decimal','mph',25],
 ['Hydraulics','hydraulics.system_type','Hydraulic system','text',null,5],['Hydraulics','hydraulics.main_pump_capacity','Hydraulic pump capacity','decimal','gpm',20],['Hydraulics','hydraulics.power_steering_pump_capacity','Steering pump capacity','decimal','gpm',25],['Hydraulics','hydraulics.remote_valves','Remote valves','text',null,60],['Hydraulics','hitch.category','Rear hitch category','text',null,40],['Hydraulics','hitch.lift_capacity','Rear hitch lift capacity','decimal','lb',50],
 ['PTO','pto.rear_description','Rear PTO','text',null,20],
 ['Capacities','capacities.fuel_tank','Fuel tank capacity','decimal','gal',10],['Capacities','capacities.def_tank','DEF tank capacity','decimal','gal',20],
 ['Dimensions & Weight','dimensions.wheelbase','Wheelbase','decimal','in',40],['Dimensions & Weight','dimensions.unladen_weight','Shipping weight','decimal','lb',70],['Dimensions & Weight','dimensions.max_permissible_weight','Gross vehicle weight','decimal','lb',80],
 ['Cab','cab.suspension','Cab suspension','text',null,10]
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('McCormick X6.6 migration dependency missing');return Number(r[0].id)}
async function source(c:Parameters<DbMigration['apply']>[0],sid:number,eid:string,url:string,title:string,raw:unknown){const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[eid]);if(r[0])return Number(r[0].id);const[i]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,url,eid,title,JSON.stringify(raw)]);return Number(i.insertId)}
async function put(c:Parameters<DbMigration['apply']>[0],mid:number,vid:number,did:number,srid:number,v:string|number,u:string|null){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mid,vid,did,typeof v==='string'?v:null,typeof v==='number'?v:null,u,srid])}
export const mccormickX66CurrentUsMigration:DbMigration={
 id:'20260830_439_mccormick_x6_6_current_us',description:'Add current McCormick North America X6.616 and X6.618 XtraShift tractors',
 async apply(c){
  const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='mccormick' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='tractor' LIMIT 1`),sid=await id(c,`SELECT id FROM sources WHERE name='McCormick North America' AND domain='mccormick-tractors.com' LIMIT 1`);
  await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'McCormick X6.6','mccormick-x6-6') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);
  const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND slug='mccormick-x6-6' LIMIT 1`,[mf]);
  const seriesSr=await source(c,sid,'mccormick-x6-6-current-us-2026-08',SERIES_URL,'McCormick North America current X6.6 lineup',{market:'United States',captured:'2026-08-30',currentModels:models.map(m=>m.name),currentUsPage:SERIES_URL,currentTechnicalTable:TECH_URL,currentUsCard:{powerHp:'165 / 175',transmission:'XtraShift'},powerPolicy:'The current US product card markets 165/175 hp. The official X6.6 technical table identifies these as maximum power WITH EPM; base maximum power is 155/166 hp. Both are normalized into separate fields rather than treating EPM output as unqualified engine power.',shared:{engine:'FPT NEF 67, 6-cylinder, 6.7 L, turbo intercooler, Stage V / Tier 4 Final HI-eSCR2',maintenanceHours:500,fuelL:280,defL:38,transmission:'XtraShift, 6 speeds (HML) and 3 ranges',gears:'54F + 18R without creeper; 108F + 36R with creeper',minimumSpeedKmh:'1.6 without creeper; 0.3 with creeper',rearPto:'540 / 1000',hydraulics:'CCLS piston pump 110 L/min; steering 38 L/min',remotes:'3 mechanical standard; 5 mechanical optional, 80 L/min',rearHitch:'Category III; 8,400 kg',wheelbaseMm:2880,shippingWeightKg:6700,grossVehicleWeightKg:11300},unitNormalization:{fuel:'280 L -> 74.0 gal',def:'38 L -> 10.0 gal',mainHydraulics:'110 L/min -> 29.1 gpm',steering:'38 L/min -> 10.0 gpm',rearHitch:'8,400 kg -> 18,519 lb',wheelbase:'2,880 mm -> 113.4 in',shippingWeight:'6,700 kg -> 14,771 lb',grossVehicleWeight:'11,300 kg -> 24,912 lb',minimumCreeperSpeed:'0.3 km/h -> 0.19 mph',torque:'676/700 Nm EPM torque -> 498.6/516.3 lb-ft'}});
  const d=new Map<string,number>();for(const row of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,row);d.set(row[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[row[1]]))}
  for(const m of models){const sr=await source(c,sid,`mccormick-${m.slug}-current-us-2026-08`,TECH_URL,`McCormick ${m.name} current North America specifications`,{market:'United States',captured:'2026-08-30',model:m.name,maximumHp:m.maxHp,maximumWithEpmHp:m.boostHp,maximumTorqueWithEpmLbFt:m.torqueLbFt});await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current US McCormick X6.6 open-field tractor','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[mf,et,series,m.name,m.slug]);const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mid,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States','Cab; XtraShift 54F x 18R, optional creeper 108F x 36R',TRUE,?,'Current McCormick North America X6.6 configuration.') ON DUPLICATE KEY UPDATE configuration=VALUES(configuration),is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mid,VERSION,sr||seriesSr]);const vid=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mid,VERSION]);const vals:Array<[string,string|number,string|null]>=[['configuration.station','Cab',null],['engine.make','FPT',null],['engine.model','NEF 67',null],['engine.cylinders',6,null],['emissions.standard','Stage V / Tier 4 Final; HI-eSCR2',null],['engine.displacement',6.7,'L'],['engine.gross_power',m.maxHp,'hp'],['engine.boost_power',m.boostHp,'hp'],['engine.max_torque',m.torqueLbFt,'lb-ft'],['engine.oil_change_interval',500,'h'],['transmission.standard','XtraShift; 6 speeds (HML) x 3 ranges',null],['transmission.speeds','54F x 18R standard; 108F x 36R with creeper',null],['transmission.minimum_speed',0.19,'mph'],['hydraulics.system_type','Closed-center load sensing (CCLS)',null],['hydraulics.main_pump_capacity',29.1,'gpm'],['hydraulics.power_steering_pump_capacity',10.0,'gpm'],['hydraulics.remote_valves','3 mechanical standard; 5 mechanical optional (80 L/min)',null],['hitch.category','Category III',null],['hitch.lift_capacity',18519,'lb'],['pto.rear_description','540 / 1000 rpm',null],['capacities.fuel_tank',74.0,'gal'],['capacities.def_tank',10.0,'gal'],['dimensions.wheelbase',113.4,'in'],['dimensions.unladen_weight',14771,'lb'],['dimensions.max_permissible_weight',24912,'lb'],['cab.suspension','McCormick mechanical cab suspension',null]];for(const[k,v,u]of vals){const did=d.get(k);if(!did)throw new Error(`Missing McCormick X6.6 spec ${k}`);await put(c,mid,vid,did,sr||seriesSr,v,u)}}
 }
};
