import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type ModelSeed={slug:string;model:string;ratedHp:number;maxHp:number;ptoHp:number;url:string;externalId:string};
const FAMILY_URL='https://www.caseih.com/en-us/unitedstates/products/tractors/puma-super-series/afs-connect-puma-series';
const FAMILY_EXTERNAL_ID='case-ih-afs-connect-puma-current-my2025-2026';
const VERSION_SLUG='united-states-current-2026-08';
const models:ModelSeed[]=[
  {slug:'afs-connect-puma-185',model:'AFS Connect Puma 185',ratedHp:180,maxHp:225,ptoHp:150,url:'https://www.caseih.com/en-us/unitedstates/products/tractors/puma-super-series/afs-connect-puma-series/afs-connect-puma-185',externalId:'case-ih-afs-connect-puma-185-current-us'},
  {slug:'afs-connect-puma-200',model:'AFS Connect Puma 200',ratedHp:200,maxHp:245,ptoHp:170,url:'https://www.caseih.com/en-us/unitedstates/products/tractors/puma-super-series/afs-connect-puma-series/afs-connect-puma-200',externalId:'case-ih-afs-connect-puma-200-current-us'},
  {slug:'afs-connect-puma-220',model:'AFS Connect Puma 220',ratedHp:220,maxHp:260,ptoHp:190,url:'https://www.caseih.com/en-us/unitedstates/products/tractors/puma-super-series/afs-connect-puma-series/afs-connect-puma-220',externalId:'case-ih-afs-connect-puma-220-current-us'},
  {slug:'afs-connect-puma-240',model:'AFS Connect Puma 240',ratedHp:240,maxHp:270,ptoHp:210,url:'https://www.caseih.com/en-us/unitedstates/products/tractors/puma-super-series/afs-connect-puma-series/afs-connect-puma-240',externalId:'case-ih-afs-connect-puma-240-current-us'},
  {slug:'afs-connect-puma-260',model:'AFS Connect Puma 260',ratedHp:260,maxHp:302,ptoHp:230,url:'https://www.caseih.com/en-us/unitedstates/products/tractors/puma-super-series/afs-connect-puma-series/afs-connect-puma-260',externalId:'case-ih-afs-connect-puma-260-current-us'},
];
const definitions=[
  ['Machine Configuration','configuration.station','Operator station','text',null,1],['Machine Configuration','configuration.drive','Drive configuration','text',null,2],
  ['Engine','engine.make','Engine manufacturer','text',null,1],['Engine','engine.displacement','Engine displacement','decimal','L',2],['Engine','engine.rated_power','Rated engine power','decimal','hp',3],['Engine','engine.maximum_power','Maximum boosted engine power','decimal','hp',4],['Engine','engine.rated_speed','Rated engine speed','integer','rpm',5],
  ['PTO','pto.rated_power','PTO power','decimal','hp',10],['Transmission','transmission.options','Transmission options','text',null,10],['Hydraulics','hitch.rear_max_lift_capacity','Maximum rear hitch lift capacity','decimal','lb',20],['Capacities','capacities.fuel_tank_variants','Fuel tank capacity','decimal','US gal',10],['Maintenance','maintenance.engine_oil_interval','Engine oil service interval','integer','hours',10],
] as const;
async function selectId(connection:Parameters<DbMigration['apply']>[0],sql:string,params:unknown[]=[]){const [rows]=await connection.query<IdRow[]>(sql,params);if(!rows[0])throw new Error('Missing Case IH AFS Connect Puma migration dependency.');return Number(rows[0].id);}
async function ensureSource(connection:Parameters<DbMigration['apply']>[0],sourceId:number,externalId:string,url:string,title:string){const [rows]=await connection.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(rows[0])return Number(rows[0].id);const [result]=await connection.query<ResultSetHeader>(`INSERT INTO source_records (source_id,url,external_id,title) VALUES (?,?,?,?)`,[sourceId,url,externalId,title]);return Number(result.insertId);}
async function upsertSpec(connection:Parameters<DbMigration['apply']>[0],machineId:number,versionId:number,definitionId:number,sourceRecordId:number,value:string|number,unit:string|null=null){await connection.query(`INSERT INTO machine_specs (machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES (?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[machineId,versionId,definitionId,typeof value==='string'?value:null,typeof value==='number'?value:null,unit,sourceRecordId]);}

export const caseIHAfsConnectPumaCurrentSpecsMigration:DbMigration={
  id:'20260828_227_case_ih_afs_connect_puma_current_specs',
  description:'Add current US MY2025+ Case IH AFS Connect Puma 185/200/220/240/260 specifications from official Case IH product pages',
  async apply(connection){
    await connection.query(`INSERT INTO equipment_types (name,slug) VALUES ('Tractor','tractor') ON DUPLICATE KEY UPDATE name=VALUES(name)`);
    await connection.query(`INSERT INTO manufacturers (name,slug) VALUES ('Case IH','case-ih') ON DUPLICATE KEY UPDATE name=VALUES(name)`);
    const manufacturerId=await selectId(connection,`SELECT id FROM manufacturers WHERE slug='case-ih' LIMIT 1`);const equipmentTypeId=await selectId(connection,`SELECT id FROM equipment_types WHERE slug='tractor' LIMIT 1`);
    await connection.query(`INSERT INTO machine_series (manufacturer_id,equipment_type_id,name,slug) VALUES (?,?,'AFS Connect Puma Series','afs-connect-puma-series') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[manufacturerId,equipmentTypeId]);const seriesId=await selectId(connection,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='afs-connect-puma-series' LIMIT 1`,[manufacturerId,equipmentTypeId]);
    let [sourceRows]=await connection.query<IdRow[]>(`SELECT id FROM sources WHERE name='Case IH' AND domain='caseih.com' ORDER BY id LIMIT 1`);let sourceId=sourceRows[0]?.id?Number(sourceRows[0].id):0;if(!sourceId){const [result]=await connection.query<ResultSetHeader>(`INSERT INTO sources (name,domain,source_type,authority_level) VALUES ('Case IH','caseih.com','manufacturer','official')`);sourceId=Number(result.insertId);}
    const familyId=await ensureSource(connection,sourceId,FAMILY_EXTERNAL_ID,FAMILY_URL,'Case IH US AFS Connect Puma Series - MY2025 updates and current lineup');
    const definitionIds=new Map<string,number>();for(const [section,key,label,valueType,canonicalUnit,displayOrder] of definitions){await connection.query(`INSERT INTO spec_definitions (section,spec_key,label,value_type,canonical_unit,display_order) VALUES (?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,[section,key,label,valueType,canonicalUnit,displayOrder]);definitionIds.set(key,await selectId(connection,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[key]));}const def=(key:string)=>{const id=definitionIds.get(key);if(!id)throw new Error(`Missing Case IH Puma spec ${key}`);return id;};
    for(const model of models){const modelSourceId=await ensureSource(connection,sourceId,model.externalId,model.url,`Case IH US ${model.model} official product specifications`);await connection.query(`INSERT INTO machines (manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES (?,?,?,?,?,'Current US MY2025+ AFS Connect Puma model','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[manufacturerId,equipmentTypeId,seriesId,model.model,model.slug]);const machineId=await selectId(connection,`SELECT id FROM machines WHERE manufacturer_id=? AND equipment_type_id=? AND slug=? LIMIT 1`,[manufacturerId,equipmentTypeId,model.slug]);await connection.query(`INSERT INTO machine_versions (machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES (?,?,'US','United States','MY2025+ AFS Connect Puma - wheeled cab tractor',TRUE,?,?) ON DUPLICATE KEY UPDATE market_code='US',market_name='United States',configuration=VALUES(configuration),is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[machineId,VERSION_SLUG,familyId,'Current Case IH US AFS Connect Puma family. Numerical engine/PTO values use the individual current product page; family-level fuel, hitch, transmission and maintenance values use the MY2025+ series page.']);const versionId=await selectId(connection,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[machineId,VERSION_SLUG]);const values:Array<[string,string|number,string|null,number]>=[['configuration.station','Cab',null,familyId],['configuration.drive','Wheeled tractor',null,familyId],['engine.make','FPT / Case IH',null,familyId],['engine.displacement',6.7,'L',modelSourceId],['engine.rated_power',model.ratedHp,'hp',modelSourceId],['engine.maximum_power',model.maxHp,'hp',modelSourceId],['engine.rated_speed',2200,'rpm',modelSourceId],['pto.rated_power',model.ptoHp,'hp',modelSourceId],['transmission.options','PowerDrive full powershift or CVXDrive continuously variable transmission; availability/configuration varies by model',null,familyId],['hitch.rear_max_lift_capacity',23000,'lb',familyId],['capacities.fuel_tank_variants',124,'US gal',familyId],['maintenance.engine_oil_interval',750,'hours',familyId]];for(const [key,value,unit,recordId] of values)await upsertSpec(connection,machineId,versionId,def(key),recordId,value,unit);}
  }
};