import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow = RowDataPacket & { id: number };
type Seed = { slug:string; model:string; sourceUrl:string; wheelOptions:string; maxWidth:string; operation:string };
const VERSION='united-states-current-2026-08';
const FAMILY_URL='https://www.caseih.com/en-us/unitedstates/products/wheel-rakes-mergers/wheel-rakes';
const models:Seed[]=[
  {slug:'wr102',model:'WR102',sourceUrl:`${FAMILY_URL}/wr102`,wheelOptions:'8, 10, or 12 wheels',maxWidth:'24 ft 6 in (7.5 m)',operation:'Carted wheel rake; one-side raking is available for tight spaces or finishing a field'},
  {slug:'wr201',model:'WR201',sourceUrl:`${FAMILY_URL}/wr201`,wheelOptions:'8 or 10 wheels',maxWidth:'20 ft 4 in (6.2 m)',operation:'Wheel rake with optional single-side opening kit for independent operation of each side'},
  {slug:'wr302',model:'WR302',sourceUrl:`${FAMILY_URL}/wr302`,wheelOptions:'12, 14, or 16 wheels',maxWidth:'31 ft (9.45 m)',operation:'High-capacity wheel rake with optional hydraulic windrow-width adjustment and optional single-side opening kit'},
];
const defs:Array<[string,string,string,string,string|null,number]>=[
  ['Machine Configuration','configuration.type','Machine configuration','text',null,1],
  ['Machine Configuration','configuration.market_scope','Official market scope','text',null,2],
  ['Raking System','rake.wheel_options','Rake wheel options','text',null,10],
  ['Raking System','rake.maximum_working_width','Maximum raking width','text',null,20],
  ['Raking System','rake.operation','Raking operation and adjustment','text',null,30],
  ['Raking System','rake.frame','Frame and flotation','text',null,40],
  ['Dimensions & Transport','rake.transport','Transport configuration','text',null,10],
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,params:unknown[]=[]){const [r]=await c.query<IdRow[]>(sql,params);if(!r[0])throw new Error('Case IH WR migration dependency missing');return Number(r[0].id);}
async function source(c:Parameters<DbMigration['apply']>[0]){const [r]=await c.query<IdRow[]>(`SELECT id FROM sources WHERE name='Case IH' AND domain='caseih.com' ORDER BY id LIMIT 1`);if(r[0])return Number(r[0].id);const [x]=await c.query<ResultSetHeader>(`INSERT INTO sources(name,domain,source_type,authority_level) VALUES('Case IH','caseih.com','manufacturer','official')`);return Number(x.insertId);}
async function record(c:Parameters<DbMigration['apply']>[0],sourceId:number,m:Seed){const externalId=`case-ih-${m.slug}-wheel-rake-us-current-2026-08`;const [r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(r[0])return Number(r[0].id);const [x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sourceId,m.sourceUrl,externalId,`Case IH ${m.model} current US wheel rake specifications`,JSON.stringify({captured:'2026-08-31',market:'United States',equipmentType:'Wheel Rake',familySource:FAMILY_URL,...m})]);return Number(x.insertId);}
async function put(c:Parameters<DbMigration['apply']>[0],machineId:number,versionId:number,definitionId:number,recordId:number,value:string|number,unit:string|null=null){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[machineId,versionId,definitionId,typeof value==='string'?value:null,typeof value==='number'?value:null,unit,recordId]);}
export const caseIhWrWheelRakesCurrentMigration:DbMigration={
  id:'20260831_504_case_ih_wr_wheel_rakes_current',description:'Add current Case IH US WR102, WR201 and WR302 wheel rakes',async apply(c){
    await c.query(`INSERT INTO equipment_types(name,slug) VALUES('Wheel Rake','wheel-rake') ON DUPLICATE KEY UPDATE name=VALUES(name)`);await c.query(`INSERT INTO manufacturers(name,slug) VALUES('Case IH','case-ih') ON DUPLICATE KEY UPDATE name=VALUES(name)`);const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='case-ih' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='wheel-rake' LIMIT 1`),sid=await source(c);await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'WR Series','wr-series') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='wr-series' LIMIT 1`,[mf,et]);
    const ids=new Map<string,number>();for(const d of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,d);ids.set(d[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[d[1]]));}const def=(k:string)=>{const v=ids.get(k);if(!v)throw new Error(`Missing rake definition ${k}`);return v;};
    for(const m of models){const rid=await record(c,sid,m);await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current Case IH United States WR wheel rake lineup','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes)`,[mf,et,series,m.model,m.slug]);const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND equipment_type_id=? AND slug=? LIMIT 1`,[mf,et,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mid,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States','Current WR wheel rake specification',TRUE,?,'Current Case IH US product-page data captured 2026-08-31.') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mid,VERSION,rid]);const vid=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mid,VERSION]);await put(c,mid,vid,def('configuration.type'),rid,'Carted wheel rake');await put(c,mid,vid,def('configuration.market_scope'),rid,'United States current catalog');await put(c,mid,vid,def('rake.wheel_options'),rid,m.wheelOptions);await put(c,mid,vid,def('rake.maximum_working_width'),rid,m.maxWidth);await put(c,mid,vid,def('rake.operation'),rid,m.operation);await put(c,mid,vid,def('rake.frame'),rid,'Heavy-duty frame with rake sections designed to float over uneven terrain');await put(c,mid,vid,def('rake.transport'),rid,'Rake wheels fold on top of the cart for transport');}
  }
};
