import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';
type IdRow=RowDataPacket&{id:number};
type Seed={slug:string;model:string;hp:number;pto:number;station:string;drive:string;transmission:string;url:string;externalId:string};
const VERSION='united-states-current-2026-08';
const FAMILY='https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-utility-series/farmall-small-utility-c-series';
const models:Seed[]=[
 {slug:'farmall-65c',model:'Farmall Utility 65C',hp:64,pto:50,station:'Cab',drive:'MFD',transmission:'12x12 Power Shuttle',url:FAMILY+'/farmall-65c',externalId:'case-ih-farmall-65c-current-us'},
 {slug:'farmall-75c',model:'Farmall Utility 75C',hp:74,pto:65,station:'Cab or Non-cab',drive:'2WD or MFD',transmission:'8x8 or 12x12 Mechanical or Power Shuttle',url:'https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-small-utility-c-series/farmall-75c',externalId:'case-ih-farmall-75c-current-us'}];
async function id(c:Parameters<DbMigration['apply']>[0],q:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(q,p);if(!r[0])throw Error('Farmall Small Utility C dependency missing');return Number(r[0].id)}
async function src(c:Parameters<DbMigration['apply']>[0],sid:number,m:Seed){const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[m.externalId]);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,m.url,m.externalId,`Case IH US ${m.model} official current specifications`,JSON.stringify(m)]);return Number(x.insertId)}
export const caseIHFarmallSmallUtilityCCurrentSpecsMigration:DbMigration={id:'20260828_251_case_ih_farmall_small_utility_c_current_specs',description:'Add current US Case IH Farmall Small Utility C 65C/75C specs',async apply(c){
 await c.query(`INSERT INTO equipment_types(name,slug) VALUES('Tractor','tractor') ON DUPLICATE KEY UPDATE name=VALUES(name)`);await c.query(`INSERT INTO manufacturers(name,slug) VALUES('Case IH','case-ih') ON DUPLICATE KEY UPDATE name=VALUES(name)`);const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='case-ih'`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='tractor'`);await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'Farmall Small Utility C Series','farmall-small-utility-c-series') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND slug='farmall-small-utility-c-series'`,[mf]);let[s]=await c.query<IdRow[]>(`SELECT id FROM sources WHERE name='Case IH' AND domain='caseih.com' LIMIT 1`);let sid=s[0]?.id?Number(s[0].id):0;if(!sid){const[x]=await c.query<ResultSetHeader>(`INSERT INTO sources(name,domain,source_type,authority_level) VALUES('Case IH','caseih.com','manufacturer','official')`);sid=Number(x.insertId)}
 const defs:(string|number|null)[][]=[['Machine Configuration','configuration.station','Operator station','text',null,1],['Machine Configuration','configuration.drive','Drive configuration','text',null,2],['Engine','engine.rated_power','Engine horsepower','decimal','hp',3],['PTO','pto.rated_power','PTO power','decimal','hp',10],['Transmission','transmission.options','Transmission options','text',null,10]];for(const d of defs)await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit)`,d);
 for(const m of models){const sr=await src(c,sid,m);await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current US Case IH Farmall Small Utility C tractor','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes)`,[mf,et,series,m.model,m.slug]);const mi=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=?`,[mf,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mi,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States','Current Farmall Small Utility C tractor',TRUE,?,'Official Case IH US current product data') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mi,VERSION,sr]);const vi=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=?`,[mi,VERSION]);const vals:[string,string|number,string|null][]=[['configuration.station',m.station,null],['configuration.drive',m.drive,null],['engine.rated_power',m.hp,'hp'],['pto.rated_power',m.pto,'hp'],['transmission.options',m.transmission,null]];for(const[k,v,u]of vals){const di=await id(c,`SELECT id FROM spec_definitions WHERE spec_key=?`,[k]);await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mi,vi,di,typeof v==='string'?v:null,typeof v==='number'?v:null,u,sr])}}
}};