import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Seed={slug:string;model:string;configurations:string;spacing:string;fertilizer:string};
const VERSION='united-states-current-2026-08';
const URL='https://www.deere.com/en/tillage/field-cultivators/';
const models:Seed[]=[
 {slug:'st12-strip-till',model:'ST12',configurations:'Integral or Drawn',spacing:'30 in (76.2 cm)',fertilizer:'Integral: N/A; Drawn: 10 tons'},
 {slug:'st16-strip-till',model:'ST16',configurations:'Integral or Drawn',spacing:'30 in (76.2 cm)',fertilizer:'Integral: N/A; Drawn: 10 tons'},
 {slug:'st18-strip-till',model:'ST18',configurations:'Drawn',spacing:'20 in (50.8 cm) or 22 in (55.9 cm)',fertilizer:'Drawn: 10 tons'},
];
const defs:Array<[string,string,string,string,string|null,number]>=[
 ['Machine Configuration','configuration.type','Machine configuration','text',null,1],['Machine Configuration','configuration.market_scope','Official market scope','text',null,2],
 ['Strip-Till System','strip_till.configurations','Configurations','text',null,10],['Strip-Till System','strip_till.row_spacing','Row spacing','text',null,20],['Strip-Till System','strip_till.working_speed','Working speed','text',null,30],['Strip-Till System','strip_till.working_depth','Working depth','text',null,40],['Strip-Till System','strip_till.row_unit_options','Row-unit tillage options','text',null,50],
 ['Application System','strip_till.fertilizer_capacity','Fertilizer capacity','text',null,10],['Precision Technology','strip_till.precision_system','Precision system','text',null,10],
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('John Deere ST migration dependency missing');return Number(r[0].id);}
async function src(c:Parameters<DbMigration['apply']>[0]){const[r]=await c.query<IdRow[]>(`SELECT id FROM sources WHERE name='John Deere' AND domain='deere.com' ORDER BY id LIMIT 1`);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO sources(name,domain,source_type,authority_level) VALUES('John Deere','deere.com','manufacturer','official')`);return Number(x.insertId);}
async function rec(c:Parameters<DbMigration['apply']>[0],sid:number,m:Seed){const externalId=`john-deere-${m.slug}-us-current-2026-08`;const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,URL,externalId,`John Deere ${m.model} current US strip-till comparison specifications`,JSON.stringify({captured:'2026-08-31',market:'United States',equipmentType:'Strip-Till',source:URL,...m})]);return Number(x.insertId);}
async function put(c:Parameters<DbMigration['apply']>[0],mid:number,vid:number,did:number,rid:number,v:string){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,NULL,NULL,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=NULL,unit=NULL,source_record_id=VALUES(source_record_id),confidence='official'`,[mid,vid,did,v,rid]);}
export const johnDeereStStripTillCurrentMigration:DbMigration={id:'20260831_528_john_deere_st_strip_till_current',description:'Add current John Deere US ST12, ST16 and ST18 strip-till models',async apply(c){
 await c.query(`INSERT INTO equipment_types(name,slug) VALUES('Strip-Till','strip-till') ON DUPLICATE KEY UPDATE name=VALUES(name)`);await c.query(`INSERT INTO manufacturers(name,slug) VALUES('John Deere','john-deere') ON DUPLICATE KEY UPDATE name=VALUES(name)`);const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='john-deere' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='strip-till' LIMIT 1`),sid=await src(c);await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'ST Series Strip-Till','st-series-strip-till') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='st-series-strip-till' LIMIT 1`,[mf,et]);const ids=new Map<string,number>();for(const d of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,d);ids.set(d[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[d[1]]));}const def=(k:string)=>{const v=ids.get(k);if(!v)throw new Error(`Missing ST definition ${k}`);return v;};
 for(const m of models){const rid=await rec(c,sid,m);await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current John Deere United States ST Series strip-till lineup','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes)`,[mf,et,series,m.model,m.slug]);const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND equipment_type_id=? AND slug=? LIMIT 1`,[mf,et,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mid,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States','Current ST Series comparison specification',TRUE,?,'Current John Deere US tillage comparison data captured 2026-08-31. Older price-book weights, dimensions and configuration details are intentionally not promoted into this current record.') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mid,VERSION,rid]);const vid=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mid,VERSION]);await put(c,mid,vid,def('configuration.type'),rid,'Strip-till solution');await put(c,mid,vid,def('configuration.market_scope'),rid,'United States current catalog');await put(c,mid,vid,def('strip_till.configurations'),rid,m.configurations);await put(c,mid,vid,def('strip_till.row_spacing'),rid,m.spacing);await put(c,mid,vid,def('strip_till.working_speed'),rid,'Coulters: 7 - 10 mph; Shanks: 5 - 8 mph');await put(c,mid,vid,def('strip_till.working_depth'),rid,'Coulters: up to 6 in (15.24 cm); Shanks: up to 11 in (27.9 cm)');await put(c,mid,vid,def('strip_till.row_unit_options'),rid,'Dual coulter or shank tillage');await put(c,mid,vid,def('strip_till.fertilizer_capacity'),rid,m.fertilizer);await put(c,mid,vid,def('strip_till.precision_system'),rid,'John Deere guidance and implement-control options are offered for ST Series; current comparison data retained at family level');}
 }};
