import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type PartSeed={number:string;name:string;category:string;note:string};
const GUIDE_URL='https://www.deere.com/assets/pdfs/common/qrg/rpg-8rx-tractors-final-tier-4-ft4-801001-8rx310-8rx340-8rx370-8rx410.pdf';
const GUIDE_EXTERNAL_ID='john-deere-rx560545-8rx-ft4-801001-service-guide';
const VERSION_SLUG='united-states-current-2026-08';
const models=['8rx-310','8rx-340','8rx-370','8rx-410'] as const;
const currentParts:PartSeed[]=[
  {number:'RE596317',name:'Primary Engine Air Filter',category:'air-filters',note:'Primary air filter; replace every 1000 hours, annually or as indicated.'},
  {number:'RE596318',name:'Secondary Engine Air Filter',category:'air-filters',note:'Secondary air filter; replace every 1000 hours, annually or as indicated.'},
  {number:'RE539465',name:'Primary Fuel Filter Element',category:'fuel-filters',note:'Primary fuel filter; replace every 500 hours or as indicated.'},
  {number:'DZ110558',name:'Secondary Fuel Filter Element - Current Serial',category:'fuel-filters',note:'Secondary fuel filter with water drain valve for serial 804001 and later.'},
  {number:'RE509672',name:'Engine Oil Filter',category:'engine-oil-filters',note:'Engine oil filter; extended 500-hour service requires Deere guide oil/fuel conditions.'},
  {number:'AT365869',name:'Fuel Water Separator Filter',category:'fuel-water-separators',note:'Fuel-water separator filter, if equipped; replace every 500 hours.'},
  {number:'RE596661',name:'Hydraulic Oil Filter Element',category:'hydraulic-filters',note:'Hydraulic oil filter element, quantity 2; replace every 1500 hours.'},
  {number:'TA21586',name:'SCV Oil Filter - Current Serial',category:'hydraulic-filters',note:'SCV oil filter for serial 808001 and later; replace every 1500 hours.'},
  {number:'RE284091',name:'Cab Fresh Air Filter',category:'cabin-air-filters',note:'Cab fresh-air filter; normal service 1000 hours or annually.'},
  {number:'RE593819',name:'Cab Recirculation Air Filter',category:'cabin-air-filters',note:'Cab recirculation-air filter; normal service 1000 hours or annually.'},
  {number:'H216169',name:'Fuel / DEF Tank Vent Filter',category:'vent-filters',note:'Fuel/DEF vent filter; replace every 1500 hours.'},
  {number:'DZ124403',name:'DEF Inline Filter',category:'def-filters',note:'DEF inline filter; replace every 3000 hours or 3 years.'},
  {number:'DZ114640',name:'DEF Supply Module Filter',category:'def-filters',note:'DEF supply-module filter; replace every 3000 hours or 3 years.'},
  {number:'HXE135862',name:'Air Dryer Filter Element',category:'air-dryer-filters',note:'Air-dryer filter, if equipped; replace at least every 2 years.'},
];
const legacyParts:PartSeed[]=[
  {number:'DZ112918',name:'Secondary Fuel Filter Element - Early Serial',category:'fuel-filters',note:'Secondary fuel filter without water drain valve for serial through 804000.'},
  {number:'RE269061',name:'SCV Oil Filter Kit - Early Serial',category:'hydraulic-filters',note:'SCV oil filter for serial through 807999.'},
];
async function selectId(connection:Parameters<DbMigration['apply']>[0],sql:string,params:unknown[]=[]){const [rows]=await connection.query<IdRow[]>(sql,params);if(!rows[0])throw new Error('Missing John Deere 8RX service dependency.');return Number(rows[0].id);}
async function ensureCategory(connection:Parameters<DbMigration['apply']>[0],filtersId:number,name:string,slug:string){await connection.query(`INSERT INTO part_categories (parent_id,name,slug) VALUES (?,?,?) ON DUPLICATE KEY UPDATE parent_id=VALUES(parent_id),name=VALUES(name)`,[filtersId,name,slug]);return selectId(connection,`SELECT id FROM part_categories WHERE slug=? LIMIT 1`,[slug]);}
async function link(connection:Parameters<DbMigration['apply']>[0],machineId:number,versionId:number|null,partId:number,sourceRecordId:number,note:string,serialFrom:string|null=null,serialTo:string|null=null){const [rows]=await connection.query<IdRow[]>(`SELECT id FROM machine_parts WHERE machine_id=? AND ((machine_version_id=?) OR (machine_version_id IS NULL AND ? IS NULL)) AND part_id=? AND serial_prefix IS NULL AND ((serial_from=?) OR (serial_from IS NULL AND ? IS NULL)) AND ((serial_to=?) OR (serial_to IS NULL AND ? IS NULL)) ORDER BY id DESC LIMIT 1`,[machineId,versionId,versionId,partId,serialFrom,serialFrom,serialTo,serialTo]);const configurationNote=versionId?'Current US 8RX four-track service reference; confirm serial/options before ordering.':'Historical 8RX FT4 801001+ serial-specific service reference; confirm exact serial before ordering.';if(rows[0])await connection.query(`UPDATE machine_parts SET fitment_note=?,configuration_note=?,source_record_id=?,fitment_confidence='official',serial_from=?,serial_to=? WHERE id=?`,[note,configurationNote,sourceRecordId,serialFrom,serialTo,Number(rows[0].id)]);else await connection.query(`INSERT INTO machine_parts (machine_id,machine_version_id,part_id,serial_from,serial_to,fitment_note,configuration_note,source_record_id,fitment_confidence) VALUES (?,?,?,?,?,?,?,?,'official')`,[machineId,versionId,partId,serialFrom,serialTo,note,configurationNote,sourceRecordId]);}

export const johnDeere8RXServiceFiltersMigration:DbMigration={id:'20260828_218_john_deere_8rx_service_filters',description:'Add official current and serial-specific John Deere 8RX FT4 801001+ service-filter fitments',async apply(connection){
  const manufacturerId=await selectId(connection,`SELECT id FROM manufacturers WHERE slug='john-deere' LIMIT 1`);await connection.query(`INSERT INTO part_categories (name,slug) VALUES ('Filters','filters') ON DUPLICATE KEY UPDATE name=VALUES(name)`);const filtersId=await selectId(connection,`SELECT id FROM part_categories WHERE slug='filters' LIMIT 1`);const defs=[['Engine Oil Filters','engine-oil-filters'],['Fuel Filters','fuel-filters'],['Air Filters','air-filters'],['Hydraulic Filters','hydraulic-filters'],['Cabin Air Filters','cabin-air-filters'],['Fuel / Water Separators','fuel-water-separators'],['DEF Filters','def-filters'],['Vent Filters','vent-filters'],['Air Dryer Filters','air-dryer-filters']] as const;const categoryIds=new Map<string,number>();for(const [name,slug] of defs)categoryIds.set(slug,await ensureCategory(connection,filtersId,name,slug));
  let [sourceRows]=await connection.query<IdRow[]>(`SELECT id FROM sources WHERE name='John Deere' AND domain='deere.com' ORDER BY id LIMIT 1`);let sourceId=sourceRows[0]?.id?Number(sourceRows[0].id):0;if(!sourceId){const [result]=await connection.query<ResultSetHeader>(`INSERT INTO sources (name,domain,source_type,authority_level) VALUES ('John Deere','deere.com','manufacturer','official')`);sourceId=Number(result.insertId);}const [existingSource]=await connection.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[GUIDE_EXTERNAL_ID]);let sourceRecordId=existingSource[0]?.id?Number(existingSource[0].id):0;if(!sourceRecordId){const [result]=await connection.query<ResultSetHeader>(`INSERT INTO source_records (source_id,url,external_id,title,published_date) VALUES (?,?,?,?,?)`,[sourceId,GUIDE_URL,GUIDE_EXTERNAL_ID,'John Deere 8RX FT4 801001+ Replacement Parts Guide - filter overview','2024-04-01']);sourceRecordId=Number(result.insertId);}
  const partIds=new Map<string,number>();for(const part of [...currentParts,...legacyParts]){const categoryId=categoryIds.get(part.category);if(!categoryId)throw new Error(`Missing 8RX category ${part.category}`);await connection.query(`INSERT INTO parts (manufacturer_id,category_id,part_number,normalized_part_number,name,description,data_status) VALUES (?,?,?,?,?,?,'verified') ON DUPLICATE KEY UPDATE category_id=VALUES(category_id),part_number=VALUES(part_number),name=VALUES(name),description=VALUES(description),data_status='verified'`,[manufacturerId,categoryId,part.number,part.number.toUpperCase(),part.name,`John Deere official 8RX FT4 801001+ service reference. ${part.note}`]);partIds.set(part.number,await selectId(connection,`SELECT id FROM parts WHERE manufacturer_id=? AND normalized_part_number=? LIMIT 1`,[manufacturerId,part.number.toUpperCase()]));}
  for(const slug of models){const machineId=await selectId(connection,`SELECT m.id FROM machines m JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='john-deere' AND m.slug=? LIMIT 1`,[slug]);const versionId=await selectId(connection,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? AND is_current=1 LIMIT 1`,[machineId,VERSION_SLUG]);for(const part of currentParts){const serialFrom=part.number==='DZ110558'?'804001':part.number==='TA21586'?'808001':null;await link(connection,machineId,versionId,partIds.get(part.number)!,sourceRecordId,part.note,serialFrom,null);}await link(connection,machineId,null,partIds.get('DZ112918')!,sourceRecordId,legacyParts[0].note,null,'804000');await link(connection,machineId,null,partIds.get('RE269061')!,sourceRecordId,legacyParts[1].note,null,'807999');}
}};