import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Seed={slug:string;model:string;hp?:number;batteryKwh?:number;weightLb:number;powertrain:'Diesel'|'Electric'};
const VERSION='north-america-current-2026-08';
const URL='https://www.casece.com/en-us/northamerica/products/wheel-loaders/compact-wheel-loaders';
const models:Seed[]=[
 {slug:'cl36ev',model:'CL36EV',batteryKwh:23,weightLb:8911,powertrain:'Electric'},
 {slug:'21f',model:'21F',hp:58,weightLb:10518,powertrain:'Diesel'},
 {slug:'121f',model:'121F',hp:64,weightLb:11826,powertrain:'Diesel'},
 {slug:'221f',model:'221F',hp:74,weightLb:12547,powertrain:'Diesel'},
 {slug:'221g',model:'221G',hp:74,weightLb:12549,powertrain:'Diesel'},
 {slug:'321f',model:'321F',hp:74,weightLb:13633,powertrain:'Diesel'},
 {slug:'321g',model:'321G',hp:74,weightLb:13691,powertrain:'Diesel'},
];
const defs:Array<[string,string,string,string,string|null,number]>=[
 ['Machine Configuration','configuration.type','Machine configuration','text',null,1],['Machine Configuration','configuration.market_scope','Official market scope','text',null,2],['Machine Configuration','case.brand_context','Brand context','text',null,3],
 ['Engine','compact_wheel_loader.engine_power','Published horsepower','decimal','hp',10],['Electrical','compact_wheel_loader.battery_capacity','Battery capacity','decimal','kWh',10],
 ['Loader Performance','compact_wheel_loader.powertrain','Powertrain','text',null,10],['Dimensions & Weight','compact_wheel_loader.operating_weight','Operating weight','decimal','lb',10],
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('CASE compact wheel loader migration dependency missing');return Number(r[0].id);}
async function source(c:Parameters<DbMigration['apply']>[0]){const[r]=await c.query<IdRow[]>(`SELECT id FROM sources WHERE name='CASE Construction Equipment' AND domain='casece.com' ORDER BY id LIMIT 1`);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO sources(name,domain,source_type,authority_level) VALUES('CASE Construction Equipment','casece.com','manufacturer','official')`);return Number(x.insertId);}
async function record(c:Parameters<DbMigration['apply']>[0],sid:number){const externalId='case-compact-wheel-loaders-na-current-2026-08';const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,URL,externalId,'CASE compact wheel loaders current North America model table',JSON.stringify({captured:'2026-08-31',market:'North America',equipmentType:'Compact Wheel Loader',models})]);return Number(x.insertId);}
async function put(c:Parameters<DbMigration['apply']>[0],mid:number,vid:number,did:number,rid:number,value:string|number,unit:string|null=null){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mid,vid,did,typeof value==='string'?value:null,typeof value==='number'?value:null,unit,rid]);}
export const caseCompactWheelLoadersCurrentMigration:DbMigration={id:'20260831_539_case_compact_wheel_loaders_current',description:'Add current CASE North America compact wheel loaders',async apply(c){
 await c.query(`INSERT INTO equipment_types(name,slug) VALUES('Compact Wheel Loader','compact-wheel-loader') ON DUPLICATE KEY UPDATE name=VALUES(name)`);await c.query(`INSERT INTO manufacturers(name,slug) VALUES('CASE','case') ON DUPLICATE KEY UPDATE name=VALUES(name)`);const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='case' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='compact-wheel-loader' LIMIT 1`),sid=await source(c),rid=await record(c,sid);
 await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'CASE Compact Wheel Loaders','case-compact-wheel-loaders') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='case-compact-wheel-loaders' LIMIT 1`,[mf,et]);const ids=new Map<string,number>();for(const d of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,d);ids.set(d[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[d[1]]));}const def=(k:string)=>{const v=ids.get(k);if(!v)throw new Error(`Missing CASE CWL definition ${k}`);return v;};
 for(const m of models){await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current CASE North America compact wheel loader lineup; CASE agriculture page identifies compact wheel loaders as farm-relevant equipment','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[mf,et,series,m.model,m.slug]);const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND equipment_type_id=? AND slug=? LIMIT 1`,[mf,et,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mid,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'NA','North America','Current CASE compact wheel loader family-table specification',TRUE,?,'Current CASE North America product table captured 2026-08-31. Electric CL36EV uses published battery capacity instead of inventing a horsepower equivalent.') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mid,VERSION,rid]);const vid=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mid,VERSION]);await put(c,mid,vid,def('configuration.type'),rid,'Compact wheel loader');await put(c,mid,vid,def('configuration.market_scope'),rid,'North America current catalog');await put(c,mid,vid,def('case.brand_context'),rid,'CASE Construction Equipment');await put(c,mid,vid,def('compact_wheel_loader.powertrain'),rid,m.powertrain);await put(c,mid,vid,def('compact_wheel_loader.operating_weight'),rid,m.weightLb,'lb');if(m.hp)await put(c,mid,vid,def('compact_wheel_loader.engine_power'),rid,m.hp,'hp');if(m.batteryKwh)await put(c,mid,vid,def('compact_wheel_loader.battery_capacity'),rid,m.batteryKwh,'kWh');}
}};
