import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
const SOURCE_URL='https://www.kioti.com/us/es/products/attachments/front-end-loaders';
const machineSlugs=['ns4710','ns4710h','ns4710-cab','ns4710h-cab','ns5310h','ns6010','ns6010h','ns6010-cab','ns6010h-cab'];
const loader={slug:'kl5810',model:'KL5810',liftCapacityLb:2621,liftHeightIn:106.3,breakoutLb:3896,bucketSizeIn:72,ratedFlowGpm:9.6,weightLb:1188};
async function id(c:Parameters<DbMigration['apply']>[0],q:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(q,p);if(!r[0])throw new Error('KIOTI NS loader migration dependency missing');return Number(r[0].id)}
export const kiotiNsLoaderMigration:DbMigration={id:'20260830_339_kioti_ns_loader',description:'Add verified KIOTI KL5810 front-end loader with official current NS Series fitment',async apply(c){
 const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='kioti' LIMIT 1`),sid=await id(c,`SELECT id FROM sources WHERE name='KIOTI' AND domain='kioti.com' LIMIT 1`);const externalId='kioti-kl5810-ns-current-us-2026-08';const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);let sr=r[0]?.id?Number(r[0].id):0;if(!sr){const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,SOURCE_URL,externalId,'KIOTI US KL5810 front-end loader specifications and NS Series compatibility',JSON.stringify({market:'United States',captured:'2026-08-30',loader,compatibility:'Fits the NS Series',fit:machineSlugs,note:'Official KIOTI US attachment catalog states KL5810 is specifically designed for and fits the NS Series. Current US Build & Price pages additionally list KL5810 for NS tractors.'})]);sr=Number(x.insertId)}
 await c.query(`INSERT INTO attachments(manufacturer_id,attachment_type,model_name,slug,lift_capacity_text,lift_height_text,configuration_text,data_status) VALUES(?,'front-loader',?,?,?,?,?,'verified') ON DUPLICATE KEY UPDATE model_name=VALUES(model_name),lift_capacity_text=VALUES(lift_capacity_text),lift_height_text=VALUES(lift_height_text),configuration_text=VALUES(configuration_text),data_status='verified'`,[mf,loader.model,loader.slug,`${loader.liftCapacityLb.toLocaleString('en-US')} lb to full height`,`${loader.liftHeightIn} in maximum pivot-pin height`,`Fits the NS Series; ${loader.breakoutLb.toLocaleString('en-US')} lb breakout force at pivot pin; ${loader.bucketSizeIn} in bucket; ${loader.ratedFlowGpm} gpm rated flow; ${loader.weightLb.toLocaleString('en-US')} lb loader weight`]);const ai=await id(c,`SELECT id FROM attachments WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,loader.slug]);for(const slug of machineSlugs){const mi=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,slug]);await c.query(`INSERT INTO machine_attachments(machine_id,attachment_id,compatibility_note,source_record_id,confidence) VALUES(?,?,?,?, 'official') ON DUPLICATE KEY UPDATE compatibility_note=VALUES(compatibility_note),source_record_id=VALUES(source_record_id),confidence='official'`,[mi,ai,'Official KIOTI compatibility: KL5810 fits the current NS Series.',sr])}
}};
