import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow = RowDataPacket & { id: number };
type Seed = { slug:string; model:string; url:string; hp:number; weightLb:number; rocBucketStraight:number; rocBucketArticulated:number; rocForksStraight:number; rocForksArticulated:number; lowMph:number; highMph:number; auxStdGpm:number; auxHighGpm?:number; fuelGal:number; hingeIn:number; widthTiresIn:number; lengthNoAttachmentIn:number; drive:string };
const VERSION='united-states-current-2026-08';
const FAMILY_URL='https://www.bobcat.com/na/en/equipment/loaders/wheel-loaders/compact-wheel-loaders';
const models:Seed[]=[
 {slug:'l65',model:'L65',url:`${FAMILY_URL}/l65`,hp:55,weightLb:9944,rocBucketStraight:3133,rocBucketArticulated:2618,rocForksStraight:3759,rocForksArticulated:3172,lowMph:4.9,highMph:15.1,auxStdGpm:19.9,fuelGal:20.8,hingeIn:127,widthTiresIn:69.7,lengthNoAttachmentIn:193.9,drive:'Two-speed hydrostatic with Advanced Attachment Control'},
 {slug:'l95',model:'L95',url:`${FAMILY_URL}/l95`,hp:74,weightLb:11993,rocBucketStraight:3981,rocBucketArticulated:3335,rocForksStraight:4860,rocForksArticulated:4127,lowMph:5.3,highMph:24.3,auxStdGpm:19.9,auxHighGpm:27.3,fuelGal:20.8,hingeIn:128.9,widthTiresIn:70.9,lengthNoAttachmentIn:192.4,drive:'Four-speed hydrostatic with Advanced Attachment Control'},
];
const defs:Array<[string,string,string,string,string|null,number]>=[
 ['Machine Configuration','configuration.type','Machine configuration','text',null,1],['Machine Configuration','configuration.market_scope','Official market scope','text',null,2],
 ['Engine','compact_wheel_loader.engine_power','Published horsepower','decimal','hp',10],
 ['Loader Performance','compact_wheel_loader.roc_bucket_straight','ROC with bucket, straight','decimal','lb',10],['Loader Performance','compact_wheel_loader.roc_bucket_articulated','ROC with bucket, articulated','decimal','lb',20],['Loader Performance','compact_wheel_loader.roc_forks_straight','ROC with forks, straight','decimal','lb',30],['Loader Performance','compact_wheel_loader.roc_forks_articulated','ROC with forks, articulated','decimal','lb',40],['Loader Performance','compact_wheel_loader.drive_type','Drive type','text',null,50],
 ['Travel','compact_wheel_loader.travel_low','Low travel speed','decimal','mph',10],['Travel','compact_wheel_loader.travel_high','High travel speed','decimal','mph',20],
 ['Hydraulics','compact_wheel_loader.aux_standard_flow','Auxiliary standard flow','decimal','gpm',10],['Hydraulics','compact_wheel_loader.aux_high_flow','Auxiliary high flow','decimal','gpm',20],
 ['Capacities','compact_wheel_loader.fuel_tank','Fuel tank','decimal','gal',10],
 ['Dimensions & Weight','compact_wheel_loader.operating_weight','Operating weight','decimal','lb',10],['Dimensions & Weight','compact_wheel_loader.hinge_pin_height','Height to hinge pin, fully raised','decimal','in',20],['Dimensions & Weight','compact_wheel_loader.width_over_tires','Width over tires','decimal','in',30],['Dimensions & Weight','compact_wheel_loader.length_no_attachment','Length without attachment','decimal','in',40],
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('Bobcat compact wheel loader migration dependency missing');return Number(r[0].id);}
async function source(c:Parameters<DbMigration['apply']>[0]){const[r]=await c.query<IdRow[]>(`SELECT id FROM sources WHERE name='Bobcat' AND domain='bobcat.com' ORDER BY id LIMIT 1`);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO sources(name,domain,source_type,authority_level) VALUES('Bobcat','bobcat.com','manufacturer','official')`);return Number(x.insertId);}
async function record(c:Parameters<DbMigration['apply']>[0],sid:number,m:Seed){const externalId=`bobcat-${m.slug}-compact-wheel-loader-us-current-2026-08`;const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,m.url,externalId,`Bobcat ${m.model} current US compact wheel loader specifications`,JSON.stringify({captured:'2026-08-31',market:'United States / North America',equipmentType:'Compact Wheel Loader',model:m})]);return Number(x.insertId);}
async function put(c:Parameters<DbMigration['apply']>[0],mid:number,vid:number,did:number,rid:number,value:string|number,unit:string|null=null){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mid,vid,did,typeof value==='string'?value:null,typeof value==='number'?value:null,unit,rid]);}
export const bobcatCompactWheelLoadersCurrentMigration:DbMigration={id:'20260831_549_bobcat_compact_wheel_loaders_current',description:'Add current Bobcat US L65 and L95 compact wheel loaders',async apply(c){
 await c.query(`INSERT INTO equipment_types(name,slug) VALUES('Compact Wheel Loader','compact-wheel-loader') ON DUPLICATE KEY UPDATE name=VALUES(name)`);await c.query(`INSERT INTO manufacturers(name,slug) VALUES('Bobcat','bobcat') ON DUPLICATE KEY UPDATE name=VALUES(name)`);const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='bobcat' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='compact-wheel-loader' LIMIT 1`),sid=await source(c);
 await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'Bobcat Current Compact Wheel Loaders','bobcat-current-compact-wheel-loaders') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='bobcat-current-compact-wheel-loaders' LIMIT 1`,[mf,et]);const ids=new Map<string,number>();for(const d of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,d);ids.set(d[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[d[1]]));}const def=(k:string)=>{const v=ids.get(k);if(!v)throw new Error(`Missing Bobcat CWL definition ${k}`);return v;};
 for(const m of models){const rid=await record(c,sid,m);await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current Bobcat North America compact wheel loader with direct model-page specification set','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[mf,et,series,m.model,m.slug]);const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND equipment_type_id=? AND slug=? LIMIT 1`,[mf,et,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mid,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States','Current Bobcat North America compact wheel loader model-page specification',TRUE,?,'Current direct Bobcat model page captured 2026-08-31. L65 and L95 are the two models exposed in the current North America Models result set; L85 is not promoted into current data because the family page text and current result count conflict.') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mid,VERSION,rid]);const vid=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mid,VERSION]);await put(c,mid,vid,def('configuration.type'),rid,'Compact wheel loader');await put(c,mid,vid,def('configuration.market_scope'),rid,'United States / North America current catalog');await put(c,mid,vid,def('compact_wheel_loader.engine_power'),rid,m.hp,'hp');await put(c,mid,vid,def('compact_wheel_loader.roc_bucket_straight'),rid,m.rocBucketStraight,'lb');await put(c,mid,vid,def('compact_wheel_loader.roc_bucket_articulated'),rid,m.rocBucketArticulated,'lb');await put(c,mid,vid,def('compact_wheel_loader.roc_forks_straight'),rid,m.rocForksStraight,'lb');await put(c,mid,vid,def('compact_wheel_loader.roc_forks_articulated'),rid,m.rocForksArticulated,'lb');await put(c,mid,vid,def('compact_wheel_loader.drive_type'),rid,m.drive);await put(c,mid,vid,def('compact_wheel_loader.travel_low'),rid,m.lowMph,'mph');await put(c,mid,vid,def('compact_wheel_loader.travel_high'),rid,m.highMph,'mph');await put(c,mid,vid,def('compact_wheel_loader.aux_standard_flow'),rid,m.auxStdGpm,'gpm');if(m.auxHighGpm)await put(c,mid,vid,def('compact_wheel_loader.aux_high_flow'),rid,m.auxHighGpm,'gpm');await put(c,mid,vid,def('compact_wheel_loader.fuel_tank'),rid,m.fuelGal,'gal');await put(c,mid,vid,def('compact_wheel_loader.operating_weight'),rid,m.weightLb,'lb');await put(c,mid,vid,def('compact_wheel_loader.hinge_pin_height'),rid,m.hingeIn,'in');await put(c,mid,vid,def('compact_wheel_loader.width_over_tires'),rid,m.widthTiresIn,'in');await put(c,mid,vid,def('compact_wheel_loader.length_no_attachment'),rid,m.lengthNoAttachmentIn,'in');}
}};
