import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type ModelSeed={slug:string;model:string;hp:number;ptoHp:number;station:string;transmission:string;url:string;externalId:string};
const FAMILY_URL='https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-compact-series/compact-farmall-c-series';
const FAMILY_EXTERNAL_ID='case-ih-farmall-compact-c-current-us-35-55-2026-08';
const VERSION_SLUG='united-states-current-2026-08';
const models:ModelSeed[]=[
  {slug:'farmall-compact-35c',model:'Farmall Compact 35C',hp:35,ptoHp:29.7,station:'Non-cab',transmission:'12x12 Mechanical Shuttle or 3-range Hydrostatic',url:'https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-compact-series/compact-farmall-c-series/farmall-35c',externalId:'case-ih-farmall-compact-35c-current-us'},
  {slug:'farmall-compact-40c',model:'Farmall Compact 40C',hp:40,ptoHp:34,station:'Cab',transmission:'12x12 Mechanical Shuttle or 3-range Hydrostatic',url:'https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-compact-series/compact-farmall-c-series/farmall-40c',externalId:'case-ih-farmall-compact-40c-current-us'},
  {slug:'farmall-compact-45c',model:'Farmall Compact 45C',hp:45,ptoHp:38.2,station:'Cab or Non-cab',transmission:'16x16 Mechanical Shuttle or 3-range Hydrostatic',url:'https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-compact-series/compact-farmall-c-series/farmall-45c',externalId:'case-ih-farmall-compact-45c-current-us'},
  {slug:'farmall-compact-50c',model:'Farmall Compact 50C',hp:50,ptoHp:42.5,station:'Cab or Non-cab',transmission:'16x16 Mechanical Shuttle or 3-range Hydrostatic',url:'https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-compact-series/compact-farmall-c-series/farmall-50c',externalId:'case-ih-farmall-compact-50c-current-us'},
  {slug:'farmall-compact-55c',model:'Farmall Compact 55C',hp:55,ptoHp:46.7,station:'Cab or Non-cab',transmission:'16x16 Mechanical Shuttle or 3-range Hydrostatic',url:'https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-compact-series/compact-farmall-c-series/farmall-55c',externalId:'case-ih-farmall-compact-55c-current-us'},
];
const definitions=[
  ['Machine Configuration','configuration.station','Operator station','text',null,1],['Machine Configuration','configuration.drive','Drive configuration','text',null,2],
  ['Engine','engine.displacement','Engine displacement','decimal','L',2],['Engine','engine.rated_power','Engine horsepower','decimal','hp',3],
  ['PTO','pto.rated_power','PTO power','decimal','hp',10],['Transmission','transmission.options','Transmission options','text',null,10],
] as const;
async function selectId(connection:Parameters<DbMigration['apply']>[0],sql:string,params:unknown[]=[]){const [rows]=await connection.query<IdRow[]>(sql,params);if(!rows[0])throw new Error('Missing Case IH Farmall Compact C migration dependency.');return Number(rows[0].id);}
async function ensureSource(connection:Parameters<DbMigration['apply']>[0],sourceId:number,externalId:string,url:string,title:string){const [rows]=await connection.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(rows[0])return Number(rows[0].id);const [result]=await connection.query<ResultSetHeader>(`INSERT INTO source_records (source_id,url,external_id,title) VALUES (?,?,?,?)`,[sourceId,url,externalId,title]);return Number(result.insertId);}
async function upsertSpec(connection:Parameters<DbMigration['apply']>[0],machineId:number,versionId:number,definitionId:number,sourceRecordId:number,value:string|number,unit:string|null=null){await connection.query(`INSERT INTO machine_specs (machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES (?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[machineId,versionId,definitionId,typeof value==='string'?value:null,typeof value==='number'?value:null,unit,sourceRecordId]);}

export const caseIHFarmallCompactCCurrentSpecsMigration:DbMigration={
  id:'20260828_246_case_ih_farmall_compact_c_current_specs',
  description:'Add current US Case IH Farmall Compact C 35C/40C/45C/50C/55C official horsepower, PTO, operator station, MFD and transmission data',
  async apply(connection){
    await connection.query(`INSERT INTO equipment_types (name,slug) VALUES ('Tractor','tractor') ON DUPLICATE KEY UPDATE name=VALUES(name)`);
    await connection.query(`INSERT INTO manufacturers (name,slug) VALUES ('Case IH','case-ih') ON DUPLICATE KEY UPDATE name=VALUES(name)`);
    const manufacturerId=await selectId(connection,`SELECT id FROM manufacturers WHERE slug='case-ih' LIMIT 1`);const equipmentTypeId=await selectId(connection,`SELECT id FROM equipment_types WHERE slug='tractor' LIMIT 1`);
    await connection.query(`INSERT INTO machine_series (manufacturer_id,equipment_type_id,name,slug) VALUES (?,?,'Farmall Compact C Series','farmall-compact-c-series') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[manufacturerId,equipmentTypeId]);const seriesId=await selectId(connection,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='farmall-compact-c-series' LIMIT 1`,[manufacturerId,equipmentTypeId]);
    let [sourceRows]=await connection.query<IdRow[]>(`SELECT id FROM sources WHERE name='Case IH' AND domain='caseih.com' ORDER BY id LIMIT 1`);let sourceId=sourceRows[0]?.id?Number(sourceRows[0].id):0;if(!sourceId){const [result]=await connection.query<ResultSetHeader>(`INSERT INTO sources (name,domain,source_type,authority_level) VALUES ('Case IH','caseih.com','manufacturer','official')`);sourceId=Number(result.insertId);}
    await ensureSource(connection,sourceId,FAMILY_EXTERNAL_ID,FAMILY_URL,'Case IH US current Farmall Compact C Series 35C-55C lineup');
    const definitionIds=new Map<string,number>();for(const [section,key,label,valueType,canonicalUnit,displayOrder] of definitions){await connection.query(`INSERT INTO spec_definitions (section,spec_key,label,value_type,canonical_unit,display_order) VALUES (?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,[section,key,label,valueType,canonicalUnit,displayOrder]);definitionIds.set(key,await selectId(connection,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[key]));}const def=(key:string)=>{const id=definitionIds.get(key);if(!id)throw new Error(`Missing Farmall Compact C spec ${key}`);return id;};
    for(const model of models){const modelSourceId=await ensureSource(connection,sourceId,model.externalId,model.url,`Case IH US ${model.model} official current product specifications`);await connection.query(`INSERT INTO machines (manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES (?,?,?,?,?,'Current US Case IH Farmall Compact C tractor','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[manufacturerId,equipmentTypeId,seriesId,model.model,model.slug]);const machineId=await selectId(connection,`SELECT id FROM machines WHERE manufacturer_id=? AND equipment_type_id=? AND slug=? LIMIT 1`,[manufacturerId,equipmentTypeId,model.slug]);await connection.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[machineId,VERSION_SLUG]);await connection.query(`INSERT INTO machine_versions (machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES (?,?,'US','United States','Current Farmall Compact C - compact tractor',TRUE,?,'Current Case IH US product page data. PTO value uses the published gear-transmission maximum where gear/hydro values are listed.') ON DUPLICATE KEY UPDATE market_code='US',market_name='United States',configuration=VALUES(configuration),is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[machineId,VERSION_SLUG,modelSourceId]);const versionId=await selectId(connection,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[machineId,VERSION_SLUG]);const values:Array<[string,string|number,string|null]>=[['configuration.station',model.station,null],['configuration.drive','MFD',null],['engine.displacement',1.9,'L'],['engine.rated_power',model.hp,'hp'],['pto.rated_power',model.ptoHp,'hp'],['transmission.options',model.transmission,null]];for(const [key,value,unit] of values)await upsertSpec(connection,machineId,versionId,def(key),modelSourceId,value,unit);}
  }
};
