import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Seed={slug:string;name:string;url:string;hp:number;engine:string;transmission:string;configuration:string;weight:string;lift:string};
const VERSION='north-america-current-2026-08';
const models:Seed[]=[
 {slug:'trx-5800',name:'TRX 5800',url:'https://www.antoniocarraro.it/na/catalogue/TRX_5800',hp:52,engine:'Yanmar direct-injection common-rail turbo diesel; 4 cylinders, 16 valves; 2,091 cc; Tier 4 Final; 2,600 rpm',transmission:'S90 synchronized gearbox; 16 FWD + 16 REV with synchronized shuttle',configuration:'Tora steering reversible tractor with RGS Rev-Guide System',weight:'1,800-2,015 kg with roll bar; 1,950-2,165 kg with RedCab',lift:'2,190 kg'},
 {slug:'tc-6800-f',name:'TC 6800 F',url:'https://www.antoniocarraro.it/na/catalogue/TC_6800_F',hp:66,engine:'Yanmar common-rail direct-injection turbo/intercooled diesel; 4 cylinders, 16 valves; Stage 5; 2,091 cc',transmission:'S90 synchronized gearbox; 16 FWD + 16 REV with synchronized shuttle',configuration:'Tora unidirectional steering tractor',weight:'1,870-2,075 kg with roll bar',lift:'2,190 kg'},
 {slug:'tn-5800',name:'TN 5800',url:'https://www.antoniocarraro.it/na/catalogue/TN_5800_6800',hp:51.5,engine:'Yanmar supercharged common-rail direct-injection diesel; 4 cylinders, 16 valves; Stage 5',transmission:'S90 synchronized gearbox; 16 FWD + 16 REV with synchronized shuttle',configuration:'Tora unidirectional steering tractor',weight:'1,810-1,960 kg with roll bar; 1,960-2,110 kg with RedCab',lift:'2,190 kg'},
 {slug:'tn-6800',name:'TN 6800',url:'https://www.antoniocarraro.it/na/catalogue/TN_5800_6800',hp:66,engine:'Yanmar common-rail direct-injection turbo/intercooled diesel; 4 cylinders, 16 valves; Stage 5',transmission:'S90 synchronized gearbox; 16 FWD + 16 REV with synchronized shuttle',configuration:'Tora unidirectional steering tractor',weight:'1,810-1,960 kg with roll bar; 1,960-2,110 kg with RedCab',lift:'2,190 kg'},
 {slug:'sn-6800-v',name:'SN 6800 V',url:'https://www.antoniocarraro.it/na/catalogue/SN_6800V',hp:66,engine:'Yanmar common-rail direct-injection turbo/intercooled diesel; 4 cylinders, 16 valves; Stage 5',transmission:'S90 synchronized gearbox; 16 FWD + 16 REV with synchronized shuttle',configuration:'Tora articulated unidirectional tractor',weight:'1,775-1,965 kg with roll bar; 1,925-2,115 kg with RedCab',lift:'2,190 kg'},
 {slug:'srx-5800',name:'SRX 5800',url:'https://www.antoniocarraro.it/na/catalogue/SRX_5800_Tora',hp:51.5,engine:'Supercharged common-rail direct-injection diesel; 4 cylinders, 16 valves; Stage 5',transmission:'S90 synchronized gearbox; 16 FWD + 16 REV with synchronized shuttle',configuration:'Tora articulated reversible tractor with RGS Rev-Guide System',weight:'1,775-1,965 kg with roll bar; 1,925-2,115 kg with RedCab',lift:'2,190 kg'},
 {slug:'srx-6800',name:'SRX 6800',url:'https://www.antoniocarraro.it/na/catalogue/SRX_5800_Tora',hp:66,engine:'Yanmar common-rail direct-injection turbo/intercooled diesel; 4 cylinders, 16 valves; Stage 5',transmission:'S90 synchronized gearbox; 16 FWD + 16 REV with synchronized shuttle',configuration:'Tora articulated reversible tractor with RGS Rev-Guide System',weight:'1,775-1,965 kg with roll bar; 1,925-2,115 kg with RedCab',lift:'2,190 kg'},
];
const defs:Array<[string,string,string,string,string|null,number]>=[['Machine Configuration','configuration.type','Machine configuration','text',null,1],['Machine Configuration','configuration.market_scope','Official market scope','text',null,2],['Engine','engine.description','Engine description','text',null,2],['Engine','engine.gross_power','Engine power','decimal','hp',8],['Transmission','transmission.standard','Transmission','text',null,10],['Hydraulics','hitch.lift_capacity_published','Published lift capacity','text',null,50],['Dimensions & Weight','dimensions.published_weight','Published weight','text',null,70]];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('Antonio Carraro Tora migration dependency missing');return Number(r[0].id)}
async function source(c:Parameters<DbMigration['apply']>[0],sid:number,m:Seed){const eid=`antonio-carraro-${m.slug}-na-current-2026-08`;const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[eid]);if(r[0])return Number(r[0].id);const[i]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,m.url,eid,`Antonio Carraro ${m.name} current North America specifications`,JSON.stringify({market:'North America',captured:'2026-08-31',model:m.name,hp:m.hp,engine:m.engine,transmission:m.transmission,configuration:m.configuration,publishedWeight:m.weight,publishedLift:m.lift})]);return Number(i.insertId)}
async function put(c:Parameters<DbMigration['apply']>[0],mid:number,vid:number,did:number,srid:number,v:string|number,u:string|null){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mid,vid,did,typeof v==='string'?v:null,typeof v==='number'?v:null,u,srid])}
export const antonioCarraroToraNaCurrentMigration:DbMigration={id:'20260831_473_antonio_carraro_tora_na_current',description:'Add current Antonio Carraro North America Tora models TRX 5800, TC 6800 F, TN 5800/6800, SN 6800 V and SRX 5800/6800',async apply(c){const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='antonio-carraro' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='tractor' LIMIT 1`),sid=await id(c,`SELECT id FROM sources WHERE name='Antonio Carraro' AND domain='antoniocarraro.it' LIMIT 1`);await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'Tora Series','tora-series') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND slug='tora-series' LIMIT 1`,[mf]);const d=new Map<string,number>();for(const row of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,row);d.set(row[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[row[1]]))}for(const m of models){const sr=await source(c,sid,m);await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current Antonio Carraro North America Tora product','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[mf,et,series,m.name,m.slug]);const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mid,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'NA','North America',?,TRUE,?,'Current Antonio Carraro North America Tora listing captured 2026-08-31.') ON DUPLICATE KEY UPDATE configuration=VALUES(configuration),is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mid,VERSION,m.configuration,sr]);const vid=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mid,VERSION]);const vals:Array<[string,string|number,string|null]>=[['configuration.type',m.configuration,null],['configuration.market_scope','North America',null],['engine.description',m.engine,null],['engine.gross_power',m.hp,'hp'],['transmission.standard',m.transmission,null],['hitch.lift_capacity_published',m.lift,null],['dimensions.published_weight',m.weight,null]];for(const[k,v,u]of vals){const did=d.get(k);if(!did)throw new Error(`Missing Antonio Carraro Tora spec ${k}`);await put(c,mid,vid,did,sr,v,u)}}}};
