import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Seed={
  slug:string; model:string; series:string; url:string; powerBasis:string; hp:number; engineType:string;
  displacementText:string; cargoBedLoad:string; towingCapacity:string; lengthText:string; widthIn:number; heightIn:number;
  driveSystem:string; transmission:string; differentialLock:string; fuelGal:number; maxSpeedMph:number; notes:string;
};
const VERSION='united-states-current-2026-09';
const models:Seed[]=[
  {
    slug:'rtv520',model:'RTV520',series:'RTV520',url:'https://www.kubotausa.com/series/utility-vehicles/mid-size-utility-vehicles/rtv520',
    powerBasis:'Kubota live page published horsepower',hp:17.4,engineType:'2-cylinder, gas, OHC, water-cooled, EFI',displacementText:'31.4 cu in (514 cc)',
    cargoBedLoad:'440 lb (200 kg) on current Kubota USA live specifications',towingCapacity:'1,168 lb (530 kg)',lengthText:'105.1 in (2670 mm)',widthIn:54.7,heightIn:74,
    driveSystem:'4WD standard',transmission:'VHT PLUS',differentialLock:'Standard',fuelGal:5.1,maxSpeedMph:24.9,
    notes:'Current Kubota USA RTV520 product page captured 2026-09-01. The live comparison table publishes 440 lb as Cargo Bed Load, while Kubota full-line/accessory literature has also published 935 lb as Cargo Bed Capacity. The live value is retained in this version and the discrepancy is not silently reconciled.',
  },
  {
    slug:'rtv-xg850-sidekick',model:'RTV-XG850 Sidekick',series:'Sidekick',url:'https://www.kubotausa.com/products/utility-vehicles/full-size-utility-vehicles/rtv-xg850-sidekick',
    powerBasis:'2026 Kubota live product page',hp:54,engineType:'2-cylinder, 4-cycle, gas, DOHC',displacementText:'851 cc',
    cargoBedLoad:'1,000 lb (454 kg); 600 lb (272 kg) California model',towingCapacity:'2,000 lb flat / 1,550 lb slope',lengthText:'117 in without bumper; 119.6 in including bumper',widthIn:63.2,heightIn:79.5,
    driveSystem:'4WD standard',transmission:'CVT PLUS with centrifugal clutch',differentialLock:'Standard',fuelGal:8.4,maxSpeedMph:40,
    notes:'Current Kubota USA page explicitly identifies this as the 2026 Sidekick and publishes the model-specific work-capacity and travel values. California cargo-bed limit remains separate text rather than being averaged.',
  },
  {
    slug:'rtv-x',model:'RTV-X',series:'RTV-X',url:'https://www.kubotausa.com/equipment-series/rtv-x-series',
    powerBasis:'Kubota live RTV-X series specification table',hp:23.3,engineType:'3-cylinder, 4-cycle, diesel, OHV',displacementText:'68.5 cu in (1123 cc)',
    cargoBedLoad:'1,102 lb (500 kg)',towingCapacity:'1,300 lb (590 kg)',lengthText:'120.3–122.9 in (3055–3121 mm)',widthIn:63.2,heightIn:79.5,
    driveSystem:'4WD standard',transmission:'Variable Hydro Transmission (VHT-X)',differentialLock:'Foot operated',fuelGal:7.9,maxSpeedMph:25,
    notes:'Current Kubota USA RTV-X live series table captured 2026-09-01. A newer Kubota RTV-X brochure has published a different horsepower figure for some 2026 RTV-X configurations; this record intentionally keeps the live series-page 23.3 hp value and does not merge unlike configuration literature.',
  },
];
const defs:Array<[string,string,string,string,string|null,number]>=[
 ['Machine Configuration','configuration.type','Machine configuration','text',null,1],['Machine Configuration','configuration.market_scope','Official market scope','text',null,2],['Machine Configuration','kubota.utility_vehicle.series','Kubota utility vehicle family','text',null,3],
 ['Engine','kubota.utility_vehicle.engine_type','Engine type','text',null,10],['Engine','kubota.utility_vehicle.published_power','Published horsepower','decimal','hp',20],['Engine','kubota.utility_vehicle.power_basis','Power source basis','text',null,30],['Engine','kubota.utility_vehicle.displacement','Engine displacement','text',null,40],
 ['Utility Vehicle Performance','kubota.utility_vehicle.cargo_bed_load','Cargo bed load','text',null,10],['Utility Vehicle Performance','kubota.utility_vehicle.towing_capacity','Towing capacity','text',null,20],['Utility Vehicle Performance','kubota.utility_vehicle.drive_system','Drive system','text',null,30],['Utility Vehicle Performance','kubota.utility_vehicle.differential_lock','Differential lock','text',null,40],
 ['Travel','kubota.utility_vehicle.transmission','Transmission','text',null,10],['Travel','kubota.utility_vehicle.maximum_speed','Maximum travel speed','decimal','mph',20],
 ['Capacities','kubota.utility_vehicle.fuel_tank','Fuel tank','decimal','gal',10],
 ['Dimensions & Weight','kubota.utility_vehicle.length','Overall length','text',null,10],['Dimensions & Weight','kubota.utility_vehicle.width','Overall width','decimal','in',20],['Dimensions & Weight','kubota.utility_vehicle.height','Overall height','decimal','in',30],
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('Kubota utility vehicle migration dependency missing');return Number(r[0].id);}
async function source(c:Parameters<DbMigration['apply']>[0]){const[r]=await c.query<IdRow[]>(`SELECT id FROM sources WHERE name='Kubota' AND domain='kubotausa.com' ORDER BY id LIMIT 1`);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO sources(name,domain,source_type,authority_level) VALUES('Kubota','kubotausa.com','manufacturer','official')`);return Number(x.insertId);}
async function record(c:Parameters<DbMigration['apply']>[0],sid:number,m:Seed){const externalId=`kubota-${m.slug}-utility-vehicle-us-current-2026-09`;const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,m.url,externalId,`Kubota ${m.model} current U.S. utility vehicle specifications`,JSON.stringify({captured:'2026-09-01',market:'United States',equipmentType:'Utility Vehicle',model:m})]);return Number(x.insertId);}
async function put(c:Parameters<DbMigration['apply']>[0],mid:number,vid:number,did:number,rid:number,value:string|number,unit:string|null=null){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mid,vid,did,typeof value==='string'?value:null,typeof value==='number'?value:null,unit,rid]);}

export const kubotaCurrentUtilityVehiclesMigration:DbMigration={id:'20260901_568_kubota_current_utility_vehicles',description:'Add current Kubota USA RTV520 Sidekick and RTV-X utility vehicles from live manufacturer pages',async apply(c){
 await c.query(`INSERT INTO equipment_types(name,slug) VALUES('Utility Vehicle','utility-vehicle') ON DUPLICATE KEY UPDATE name=VALUES(name)`);await c.query(`INSERT INTO manufacturers(name,slug) VALUES('Kubota','kubota') ON DUPLICATE KEY UPDATE name=VALUES(name)`);const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='kubota' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='utility-vehicle' LIMIT 1`),sid=await source(c);
 const seriesIds=new Map<string,number>();for(const family of ['RTV520','Sidekick','RTV-X']){const slug=family.toLowerCase().replace(/[^a-z0-9]+/g,'-');await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et,`Kubota ${family}`,`kubota-${slug}`]);seriesIds.set(family,await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug=? LIMIT 1`,[mf,et,`kubota-${slug}`]));}
 const ids=new Map<string,number>();for(const d of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,d);ids.set(d[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[d[1]]));}const def=(k:string)=>{const v=ids.get(k);if(!v)throw new Error(`Missing Kubota utility vehicle definition ${k}`);return v;};
 for(const m of models){const rid=await record(c,sid,m),series=seriesIds.get(m.series);if(!series)throw new Error(`Missing Kubota utility vehicle series ${m.series}`);await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current Kubota USA utility vehicle from live manufacturer product pages','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[mf,et,series,m.model,m.slug]);const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND equipment_type_id=? AND slug=? LIMIT 1`,[mf,et,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mid,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States','Current Kubota USA live product-page specification',TRUE,?,?) ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),configuration=VALUES(configuration),notes=VALUES(notes)`,[mid,VERSION,rid,m.notes]);const vid=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mid,VERSION]);
 await put(c,mid,vid,def('configuration.type'),rid,'Utility vehicle');await put(c,mid,vid,def('configuration.market_scope'),rid,'United States current catalog');await put(c,mid,vid,def('kubota.utility_vehicle.series'),rid,m.series);await put(c,mid,vid,def('kubota.utility_vehicle.engine_type'),rid,m.engineType);await put(c,mid,vid,def('kubota.utility_vehicle.published_power'),rid,m.hp,'hp');await put(c,mid,vid,def('kubota.utility_vehicle.power_basis'),rid,m.powerBasis);await put(c,mid,vid,def('kubota.utility_vehicle.displacement'),rid,m.displacementText);await put(c,mid,vid,def('kubota.utility_vehicle.cargo_bed_load'),rid,m.cargoBedLoad);await put(c,mid,vid,def('kubota.utility_vehicle.towing_capacity'),rid,m.towingCapacity);await put(c,mid,vid,def('kubota.utility_vehicle.drive_system'),rid,m.driveSystem);await put(c,mid,vid,def('kubota.utility_vehicle.differential_lock'),rid,m.differentialLock);await put(c,mid,vid,def('kubota.utility_vehicle.transmission'),rid,m.transmission);await put(c,mid,vid,def('kubota.utility_vehicle.maximum_speed'),rid,m.maxSpeedMph,'mph');await put(c,mid,vid,def('kubota.utility_vehicle.fuel_tank'),rid,m.fuelGal,'gal');await put(c,mid,vid,def('kubota.utility_vehicle.length'),rid,m.lengthText);await put(c,mid,vid,def('kubota.utility_vehicle.width'),rid,m.widthIn,'in');await put(c,mid,vid,def('kubota.utility_vehicle.height'),rid,m.heightIn,'in');}
}};
