import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';
type IdRow=RowDataPacket&{id:number};
const VERSION='united-states-current-2026-08';
const family={url:'https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-medium-utility-a-series',externalId:'case-ih-farmall-medium-utility-a-current-us-90-120-2026-08'};
const models=[
 ['farmall-90a','Farmall Utility 90A',90,75,'Cab','4WD','electronic power shuttle','https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-medium-utility-a-series/farmall-medium-utility-90a'],
 ['farmall-95a','Farmall Utility 95A',97,78,'Cab or Non-cab','2WD or MFD','12x12 power shuttle and creeper ready','https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-utility-series/farmall-medium-utility-a-series/farmall-medium-utility-95a'],
 ['farmall-100a','Farmall Utility 100A',101,85,'Cab','4WD','electronic power shuttle','https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-medium-utility-a-series/farmall-medium-utility-100a'],
 ['farmall-105a','Farmall Utility 105A',112,92,'Cab or Non-cab','2WD or MFD','12x12 power shuttle and creeper ready','https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-utility-series/farmall-medium-utility-a-series/farmall-medium-utility-105a'],
 ['farmall-110a','Farmall Utility 110A',110,93,'Cab','4WD','electronic power shuttle','https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-medium-utility-a-series/farmall-medium-utility-110a'],
 ['farmall-115a','Farmall Utility 115A',120,100,'Cab or Non-cab','2WD or MFD','12x12 power shuttle and creeper ready','https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-utility-series/farmall-medium-utility-a-series/farmall-medium-utility-115a'],
 ['farmall-120a','Farmall Utility 120A',117,99,'Cab','4WD','electronic power shuttle','https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-medium-utility-a-series/farmall-medium-utility-120a']
] as const;
const defs=[['Machine Configuration','configuration.station','Operator area','text',null,1],['Machine Configuration','configuration.drive','Traction','text',null,2],['Engine','engine.rated_power','Engine horsepower','decimal','hp',3],['PTO','pto.rated_power','PTO horsepower','decimal','hp',10],['Transmission','transmission.options','Transmission','text',null,10]] as const;
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw Error('Farmall Medium Utility A dependency missing');return Number(r[0].id)}
async function source(c:Parameters<DbMigration['apply']>[0],sid:number,e:string,url:string,title:string){const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[e]);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title) VALUES(?,?,?,?)`,[sid,url,e,title]);return Number(x.insertId)}
export const caseIHFarmallMediumUtilityACurrentSpecsMigration:DbMigration={id:'20260828_241_case_ih_farmall_medium_utility_a_current_specs',description:'Add current US Case IH Farmall Medium Utility A 90A-120A specifications',async apply(c){
 await c.query(`INSERT INTO equipment_types(name,slug) VALUES('Tractor','tractor') ON DUPLICATE KEY UPDATE name=VALUES(name)`);await c.query(`INSERT INTO manufacturers(name,slug) VALUES('Case IH','case-ih') ON DUPLICATE KEY UPDATE name=VALUES(name)`);const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='case-ih'`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='tractor'`);await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'Farmall Medium Utility A Series','farmall-medium-utility-a-series') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='farmall-medium-utility-a-series'`,[mf,et]);let[sr]=await c.query<IdRow[]>(`SELECT id FROM sources WHERE name='Case IH' AND domain='caseih.com' LIMIT 1`);let sid=sr[0]?.id?Number(sr[0].id):0;if(!sid){const[x]=await c.query<ResultSetHeader>(`INSERT INTO sources(name,domain,source_type,authority_level) VALUES('Case IH','caseih.com','manufacturer','official')`);sid=Number(x.insertId)}await source(c,sid,family.externalId,family.url,'Case IH US Farmall Medium Utility A current lineup');
 for(const [slug,name,hp,pto,station,drive,trans,url] of models){const ext=`case-ih-${slug}-current-us`;const rs=await source(c,sid,ext,url,`Case IH US ${name} official current specifications`);await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current US Case IH Farmall Medium Utility A tractor','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes)`,[mf,et,series,name,slug]);const mi=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=?`,[mf,slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mi,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States','Current Farmall Medium Utility A',TRUE,?,'Current Case IH US product page data.') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mi,VERSION,rs]);const vi=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=?`,[mi,VERSION]);for(const[d,val,u] of [['configuration.station',station,null],['configuration.drive',drive,null],['engine.rated_power',hp,'hp'],['pto.rated_power',pto,'hp'],['transmission.options',trans,null]] as const){const [section,key,label,type,unit,ord]=defs.find(x=>x[1]===d)!;await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,[section,key,label,type,unit,ord]);const di=await id(c,`SELECT id FROM spec_definitions WHERE spec_key=?`,[key]);await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mi,vi,di,typeof val==='string'?val:null,typeof val==='number'?val:null,u,rs])}}
}};
