import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Seed={slug:string;model:string;hp:number;maxHp:number;ptoHp:number;url:string;externalId:string};
const VERSION='united-states-current-2026-08';
const FAMILY='https://www.caseih.com/en-us/unitedstates/products/tractors/puma-series';
const models:Seed[]=[
 {slug:'puma-150',model:'Puma 150',hp:150,maxHp:175,ptoHp:125,url:FAMILY+'/puma-150',externalId:'case-ih-puma-150-current-us'},
 {slug:'puma-165',model:'Puma 165',hp:165,maxHp:189.9,ptoHp:140,url:FAMILY+'/puma-165',externalId:'case-ih-puma-165-current-us'},
 {slug:'puma-175',model:'Puma 175',hp:180,maxHp:224,ptoHp:150,url:FAMILY+'/puma-175',externalId:'case-ih-puma-175-current-us'},
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw Error('Puma 150-175 dependency missing');return Number(r[0].id)}
async function source(c:Parameters<DbMigration['apply']>[0],sid:number,externalId:string,url:string,title:string,raw?:unknown){const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(r[0])return Number(r[0].id);const[x]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,url,externalId,title,raw?JSON.stringify(raw):null]);return Number(x.insertId)}
export const caseIHPuma150175CurrentMigration:DbMigration={id:'20260828_257_case_ih_puma_150_175_current',description:'Add current US Case IH Puma 150/165/175 specs and L116 loader fitments',async apply(c){
 await c.query(`INSERT INTO equipment_types(name,slug) VALUES('Tractor','tractor') ON DUPLICATE KEY UPDATE name=VALUES(name)`);await c.query(`INSERT INTO manufacturers(name,slug) VALUES('Case IH','case-ih') ON DUPLICATE KEY UPDATE name=VALUES(name)`);const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='case-ih'`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='tractor'`);await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,'Puma Series','puma-series') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND slug='puma-series'`,[mf]);let[s]=await c.query<IdRow[]>(`SELECT id FROM sources WHERE name='Case IH' AND domain='caseih.com' LIMIT 1`);let sid=s[0]?.id?Number(s[0].id):0;if(!sid){const[x]=await c.query<ResultSetHeader>(`INSERT INTO sources(name,domain,source_type,authority_level) VALUES('Case IH','caseih.com','manufacturer','official')`);sid=Number(x.insertId)}
 const defs:Array<[string,string,string,string,string|null,number]>=[['Machine Configuration','configuration.station','Operator station','text',null,1],['Machine Configuration','configuration.drive','Drive configuration','text',null,2],['Engine','engine.displacement','Engine displacement','decimal','L',2],['Engine','engine.rated_power','Rated engine power','decimal','hp',3],['Engine','engine.maximum_power','Maximum engine power','decimal','hp',4],['PTO','pto.rated_power','PTO power','decimal','hp',10],['Transmission','transmission.options','Transmission options','text',null,10]];for(const d of defs)await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit)`,d);
 for(const m of models){const sr=await source(c,sid,m.externalId,m.url,`Case IH US ${m.model} official current specifications`,m);await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Current US Case IH Puma tractor','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes)`,[mf,et,series,m.model,m.slug]);const mi=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=?`,[mf,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mi,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'US','United States','Current Puma wheeled cab tractor',TRUE,?,'Official Case IH US current product data') ON DUPLICATE KEY UPDATE is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mi,VERSION,sr]);const vi=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=?`,[mi,VERSION]);const vals:Array<[string,string|number,string|null]>=[['configuration.station','Cab',null],['configuration.drive','4WD',null],['engine.displacement',6.7,'L'],['engine.rated_power',m.hp,'hp'],['engine.maximum_power',m.maxHp,'hp'],['pto.rated_power',m.ptoHp,'hp'],['transmission.options','PowerDrive powershift or CVXDrive continuously variable transmission',null]];for(const[k,v,u]of vals){const di=await id(c,`SELECT id FROM spec_definitions WHERE spec_key=?`,[k]);await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mi,vi,di,typeof v==='string'?v:null,typeof v==='number'?v:null,u,sr])}}
 const lsr=await source(c,sid,'case-ih-puma-l116-current','https://www.caseih.com/en-us/unitedstates/products/loaders-attachments/l11-series-loaders','Case IH US L116 loader specifications and Puma compatibility',{maxLiftLb:5732,maxHeightIn:156,boomBreakoutLb:7385,compatible:['Puma 150','Puma 165','Puma 175','Puma 185']});await c.query(`INSERT INTO attachments(manufacturer_id,attachment_type,model_name,slug,lift_capacity_text,lift_height_text,configuration_text,data_status) VALUES(?,'front-loader','L116','l116-puma','5,732 lb max lift capacity','156 in max height','7,385 lb boom breakout force; for Puma 150-185','verified') ON DUPLICATE KEY UPDATE lift_capacity_text=VALUES(lift_capacity_text),lift_height_text=VALUES(lift_height_text),configuration_text=VALUES(configuration_text),data_status='verified'`,[mf]);const ai=await id(c,`SELECT id FROM attachments WHERE manufacturer_id=? AND slug='l116-puma'`,[mf]);for(const slug of ['puma-150','puma-165','puma-175','afs-connect-puma-185']){const mi=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=?`,[mf,slug]);await c.query(`INSERT INTO machine_attachments(machine_id,attachment_id,compatibility_note,source_record_id,confidence) VALUES(?,?,'Official Case IH L116 compatibility for Puma 150-185.',?,'official') ON DUPLICATE KEY UPDATE source_record_id=VALUES(source_record_id),confidence='official',compatibility_note=VALUES(compatibility_note)`,[mi,ai,lsr])}
}};