import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type Seed={slug:string;name:string;url:string;series:string;seriesSlug:string;hp:number;engine:string;cylinders:number;displacementCc:number|null;transmission:string;configuration:string;lift:string|null;weight:string|null;sourceScope:'na'|'global-supplement'};
const VERSION='north-america-current-2026-08';
const NA_HOME='https://www.antoniocarraro.it/na';
const models:Seed[]=[
 {slug:'mach-4-tony',name:'MACH 4 TONY',url:'https://www.antoniocarraro.it/na/catalogue/Mach4_Tony',series:'MACH / Tony',seriesSlug:'mach-tony',hp:74.2,engine:'Kubota 4-cylinder 16-valve turbo common-rail diesel',cylinders:4,displacementCc:3769,transmission:'Electronically controlled constant-variable hybrid mechanical-hydrostatic transmission; 4 speed ranges',configuration:'Articulated ACTIO quadtrack; reversible Rev-Guide System',lift:null,weight:'3,300 kg with Air cab (official global technical page; NA page confirms current product but omits numeric technical table)',sourceScope:'global-supplement'},
 {slug:'tgf-8900-r',name:'TGF 8900 R',url:'https://www.antoniocarraro.it/na/catalogue/tgf-ergit-r',series:'Ergit R',seriesSlug:'ergit-r',hp:74.2,engine:'Kubota 4-cylinder 16-valve turbo common-rail diesel',cylinders:4,displacementCc:3769,transmission:'32-speed synchronized gearbox; 16 forward + 16 reverse with synchronized shuttle',configuration:'Super-low-profile mono-directional steering tractor; unequal-size wheels',lift:'2,400 kg',weight:'2,230-2,555 kg with roll bar; 2,360-2,585 kg with Protector cab',sourceScope:'na'},
 {slug:'ttr-4800-hst',name:'TTR 4800 HST',url:'https://www.antoniocarraro.it/na/catalogue/TTR_4800_HST',series:'30 Series',seriesSlug:'30-series',hp:38.7,engine:'Yanmar 3-cylinder turbo direct-injection common-rail diesel',cylinders:3,displacementCc:1568,transmission:'Hydrostatic transmission with hydraulic control',configuration:'Isodiametric ACTIO tractor; reversible drive; low center of gravity',lift:'910 kg',weight:'1,150-1,200 kg with roll bar',sourceScope:'na'},
 {slug:'sp-4800',name:'SP 4800',url:'https://www.antoniocarraro.it/na/catalogue/SP_4800',series:'32 Series',seriesSlug:'32-series',hp:38.7,engine:'Yanmar 3-cylinder Stage 5 diesel',cylinders:3,displacementCc:null,transmission:'Hydrostatic transmission',configuration:'Isodiametric mono-directional tractor; articulated ACTIO chassis; full-option cab',lift:null,weight:null,sourceScope:'na'},
];
const defs:Array<[string,string,string,string,string|null,number]>=[
 ['Machine Configuration','configuration.type','Machine configuration','text',null,1],['Machine Configuration','configuration.market_scope','Official market scope','text',null,2],
 ['Engine','engine.make','Engine manufacturer','text',null,1],['Engine','engine.cylinders','Cylinders','integer',null,4],['Engine','engine.displacement','Engine displacement','decimal','cc',6],['Engine','engine.gross_power','Engine power','decimal','hp',8],
 ['Transmission','transmission.standard','Transmission','text',null,10],['Hydraulics','hitch.lift_capacity_published','Published lift capacity','text',null,50],['Dimensions & Weight','dimensions.published_weight','Published weight','text',null,70]
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('Antonio Carraro migration dependency missing');return Number(r[0].id)}
async function source(c:Parameters<DbMigration['apply']>[0],sid:number,eid:string,url:string,title:string,raw:unknown){const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[eid]);if(r[0])return Number(r[0].id);const[i]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,url,eid,title,JSON.stringify(raw)]);return Number(i.insertId)}
async function put(c:Parameters<DbMigration['apply']>[0],mid:number,vid:number,did:number,srid:number,v:string|number,u:string|null){await c.query(`INSERT INTO machine_specs(machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES(?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[mid,vid,did,typeof v==='string'?v:null,typeof v==='number'?v:null,u,srid])}
export const antonioCarraroNaFeaturedCurrentMigration:DbMigration={id:'20260831_471_antonio_carraro_na_featured_current',description:'Introduce Antonio Carraro North America featured current tractors: MACH 4 TONY, TGF 8900 R, TTR 4800 HST and SP 4800',async apply(c){
 await c.query(`INSERT INTO equipment_types(name,slug) VALUES('Tractor','tractor') ON DUPLICATE KEY UPDATE name=VALUES(name)`);
 await c.query(`INSERT INTO manufacturers(name,slug) VALUES('Antonio Carraro','antonio-carraro') ON DUPLICATE KEY UPDATE name=VALUES(name)`);
 const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='antonio-carraro' LIMIT 1`),et=await id(c,`SELECT id FROM equipment_types WHERE slug='tractor' LIMIT 1`);
 const[r]=await c.query<IdRow[]>(`SELECT id FROM sources WHERE name='Antonio Carraro' AND domain='antoniocarraro.it' LIMIT 1`);let sid=r[0]?.id?Number(r[0].id):0;
 if(!sid){const[i]=await c.query<ResultSetHeader>(`INSERT INTO sources(name,domain,source_type,authority_level) VALUES('Antonio Carraro','antoniocarraro.it','manufacturer','official')`);sid=Number(i.insertId)}
 const homeSr=await source(c,sid,'antonio-carraro-na-featured-current-2026-08',NA_HOME,'Antonio Carraro North America current featured tractor lineup',{market:'North America',captured:'2026-08-31',featuredModels:['MACH 4 TONY','TGF Ergit R / TGF 8900 R','TTR 4800 HST II / TTR 4800 HST','SP 4800'],scopePolicy:'The manufacturer North America homepage is used to establish current NA presence. The broader /na/catalogue contains additional product entries and will be expanded in later migrations.'});
 const d=new Map<string,number>();for(const row of defs){await c.query(`INSERT INTO spec_definitions(section,spec_key,label,value_type,canonical_unit,display_order) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,row);d.set(row[1],await id(c,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[row[1]]))}
 for(const m of models){await c.query(`INSERT INTO machine_series(manufacturer_id,equipment_type_id,name,slug) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE name=VALUES(name)`,[mf,et,m.series,m.seriesSlug]);const series=await id(c,`SELECT id FROM machine_series WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,m.seriesSlug]);
   let sr=await source(c,sid,`antonio-carraro-${m.slug}-na-2026-08`,m.url,`Antonio Carraro ${m.name} North America product page`,{market:'North America',captured:'2026-08-31',model:m.name,hp:m.hp,engine:m.engine,transmission:m.transmission,configuration:m.configuration,sourceScope:m.sourceScope});
   if(m.slug==='mach-4-tony'){const supplemental=await source(c,sid,'antonio-carraro-mach-4-tony-global-spec-2026-08','https://www.antoniocarraro.it/en/catalogue/Mach4_Tony','Antonio Carraro MACH 4 TONY official technical specifications',{captured:'2026-08-31',scope:'Official global technical product page used only for numeric engine/power/weight fields because the North America page currently omits its numeric technical table.',hp:74.2,displacementCc:3769,weightKgAirCab:3300});sr=supplemental||sr}
   await c.query(`INSERT INTO machines(manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES(?,?,?,?,?,'Listed in Antonio Carraro North America current catalogue / featured lineup','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[mf,et,series,m.name,m.slug]);
   const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,m.slug]);await c.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[mid,VERSION]);await c.query(`INSERT INTO machine_versions(machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES(?,?,'NA','North America',?,TRUE,?,'Current Antonio Carraro North America product listing captured 2026-08-31.') ON DUPLICATE KEY UPDATE configuration=VALUES(configuration),is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[mid,VERSION,m.configuration,sr||homeSr]);const vid=await id(c,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[mid,VERSION]);
   const make=m.engine.startsWith('Kubota')?'Kubota':'Yanmar';const vals:Array<[string,string|number,string|null]>=[['configuration.type',m.configuration,null],['configuration.market_scope','North America',null],['engine.make',make,null],['engine.cylinders',m.cylinders,null],['engine.gross_power',m.hp,'hp'],['transmission.standard',m.transmission,null]];if(m.displacementCc!==null)vals.push(['engine.displacement',m.displacementCc,'cc']);if(m.lift)vals.push(['hitch.lift_capacity_published',m.lift,null]);if(m.weight)vals.push(['dimensions.published_weight',m.weight,null]);for(const[k,v,u]of vals){const did=d.get(k);if(!did)throw new Error(`Missing Antonio Carraro spec ${k}`);await put(c,mid,vid,did,sr||homeSr,v,u)}
 }
}};
