import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type AttachmentSeed={slug:string;name:string;type:'front-loader'|'backhoe';capacity:string|null;height:string|null;config:string;fitment:string[];url:string};
const attachments:AttachmentSeed[]=[
 {slug:'bbl100',name:'BBL100',type:'front-loader',capacity:'617 lb lift capacity to full height at pivot pin',height:'72.7 in maximum lift height',config:'48 in bucket; 4.0 in digging depth; 1,253 lb breakout force; 438 lb shipping weight.',fitment:['1022'],url:'https://badboycountry.com/tractors/1022-tractor'},
 {slug:'bbh100',name:'BBH100',type:'backhoe',capacity:null,height:null,config:'12 in bucket; subframe-mounted quick attach; 66 in maximum digging depth; 1,975 lb bucket digging force; 747 lb shipping weight.',fitment:['1022'],url:'https://badboycountry.com/tractors/1022-tractor'},
 {slug:'bbl105',name:'BBL105',type:'front-loader',capacity:'992 lb lift capacity to full height at pivot pin',height:'75.5 in maximum lift height',config:'50 in bucket; 4.6 in digging depth; 1,531 lb breakout force; 573 lb shipping weight.',fitment:['1025'],url:'https://badboycountry.com/tractors/1025-tractor'},
 {slug:'bbh105',name:'BBH105',type:'backhoe',capacity:null,height:null,config:'12 in bucket; subframe-mounted quick attach; 76 in maximum digging depth; 2,020 lb bucket digging force; 816 lb shipping weight.',fitment:['1025'],url:'https://badboycountry.com/tractors/1025-tractor'},
 {slug:'bbl300',name:'BBL300',type:'front-loader',capacity:'1,314 lb lift capacity to full height at pivot pin',height:'86 in maximum lift height',config:'54 in bucket; 4.2 in digging depth; 1,960 lb breakout force; 654 lb shipping weight.',fitment:['3026'],url:'https://badboycountry.com/tractors/3026-tractor'},
 {slug:'bbh200',name:'BBH200',type:'backhoe',capacity:null,height:null,config:'12 in bucket; subframe-mounted quick attach; 76 in maximum digging depth; 2,050 lb bucket digging force; 827 lb shipping weight.',fitment:['3026'],url:'https://badboycountry.com/tractors/3026-tractor'},
 {slug:'bbl400',name:'BBL400',type:'front-loader',capacity:'2,200 lb lift capacity to full height at pivot pin',height:'104 in maximum lift height',config:'62 in bucket; 1.8 in digging depth; 3,660 lb breakout force; 1,007 lb shipping weight.',fitment:['4025','4035','4035-cab'],url:'https://badboycountry.com/tractors/4035-tractor'},
 {slug:'bbh400',name:'BBH400',type:'backhoe',capacity:null,height:null,config:'16 in bucket; subframe-mounted quick attach; 92.2 in maximum digging depth; 4,380 lb bucket digging force; 1,270 lb shipping weight.',fitment:['4025','4035','4035-cab'],url:'https://badboycountry.com/tractors/4035-tractor'},
];
async function id(c:Parameters<DbMigration['apply']>[0],sql:string,p:unknown[]=[]){const[r]=await c.query<IdRow[]>(sql,p);if(!r[0])throw new Error('Bad Boy attachment migration dependency missing');return Number(r[0].id)}
async function source(c:Parameters<DbMigration['apply']>[0],sid:number,a:AttachmentSeed){const eid=`bad-boy-${a.slug}-current-us-2026-08`;const raw={market:'United States',captured:'2026-08-31',model:a.name,type:a.type,fitment:a.fitment,sourcePage:a.url,configuration:a.config};const[r]=await c.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[eid]);if(r[0])return Number(r[0].id);const[i]=await c.query<ResultSetHeader>(`INSERT INTO source_records(source_id,url,external_id,title,raw_reference) VALUES(?,?,?,?,?)`,[sid,a.url,eid,`Bad Boy ${a.name} current specifications and fitment`,JSON.stringify(raw)]);return Number(i.insertId)}
export const badBoy103040AttachmentsMigration:DbMigration={id:'20260831_461_bad_boy_10_30_40_attachments',description:'Add verified current loaders and backhoes for Bad Boy 10, 30 and 40 Series tractors',async apply(c){const mf=await id(c,`SELECT id FROM manufacturers WHERE slug='bad-boy' LIMIT 1`),sid=await id(c,`SELECT id FROM sources WHERE name='Bad Boy Tractors' AND domain='badboycountry.com' LIMIT 1`);for(const a of attachments){const sr=await source(c,sid,a);await c.query(`INSERT INTO attachments(manufacturer_id,attachment_type,model_name,slug,lift_capacity_text,lift_height_text,configuration_text,data_status) VALUES(?,?,?,?,?,?,?,'verified') ON DUPLICATE KEY UPDATE attachment_type=VALUES(attachment_type),model_name=VALUES(model_name),lift_capacity_text=VALUES(lift_capacity_text),lift_height_text=VALUES(lift_height_text),configuration_text=VALUES(configuration_text),data_status='verified'`,[mf,a.type,a.name,a.slug,a.capacity,a.height,a.config]);const aid=await id(c,`SELECT id FROM attachments WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,a.slug]);for(const machineSlug of a.fitment){const mid=await id(c,`SELECT id FROM machines WHERE manufacturer_id=? AND slug=? LIMIT 1`,[mf,machineSlug]);await c.query(`INSERT INTO machine_attachments(machine_id,attachment_id,compatibility_note,source_record_id,confidence) VALUES(?,?,?,?, 'official') ON DUPLICATE KEY UPDATE compatibility_note=VALUES(compatibility_note),source_record_id=VALUES(source_record_id),confidence='official'`,[mid,aid,`${a.name} is explicitly listed in the current Bad Boy Tractor Specs table for this model.`,sr])}}}};
