import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import type { DbMigration } from '@/lib/db-migration-types';

type IdRow=RowDataPacket&{id:number};
type ModelSeed={slug:string;model:string;hp:number;ptoHp:number;station:string;drive:string;transmission:string;url:string;externalId:string};
const FAMILY_URL='https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-small-utility-a-series';
const FAMILY_EXTERNAL_ID='case-ih-farmall-small-utility-a-current-us-50-75-2026-08';
const VERSION_SLUG='united-states-current-2026-08';
const models:ModelSeed[]=[
  {slug:'farmall-50a',model:'Farmall Utility 50A',hp:53,ptoHp:45,station:'Non-cab',drive:'2WD or MFD',transmission:'8x8 Mechanical Shuttle',url:'https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-small-utility-a-series/farmall-50a',externalId:'case-ih-farmall-50a-current-us'},
  {slug:'farmall-55a',model:'Farmall Utility 55A',hp:54,ptoHp:40,station:'Cab',drive:'2WD or MFD',transmission:'8x8 mechanical, 12x12 power or 12x12 with creeper',url:'https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-small-utility-a-series/farmall-55a',externalId:'case-ih-farmall-55a-current-us'},
  {slug:'farmall-60a',model:'Farmall Utility 60A',hp:60,ptoHp:51,station:'Non-cab',drive:'2WD or MFD',transmission:'8x8 Mechanical Shuttle',url:'https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-small-utility-a-series/farmall-60a',externalId:'case-ih-farmall-60a-current-us'},
  {slug:'farmall-65a',model:'Farmall Utility 65A',hp:64,ptoHp:50,station:'Cab',drive:'2WD or MFD',transmission:'8x8 mechanical, 12x12 power or 12x12 with creeper',url:'https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-small-utility-a-series/farmall-65a',externalId:'case-ih-farmall-65a-current-us'},
  {slug:'farmall-70a',model:'Farmall Utility 70A',hp:70,ptoHp:62,station:'Non-cab',drive:'2WD or MFD',transmission:'8x8 Mechanical Shuttle',url:'https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-small-utility-a-series/farmall-70a',externalId:'case-ih-farmall-70a-current-us'},
  {slug:'farmall-75a',model:'Farmall Utility 75A',hp:74,ptoHp:60,station:'Cab or Non-cab',drive:'2WD or MFD',transmission:'8x8 mechanical, 12x12 power or 12x12 with creeper',url:'https://www.caseih.com/en-us/unitedstates/products/tractors/farmall-small-utility-a-series/farmall-75a',externalId:'case-ih-farmall-75a-current-us'},
];
const definitions=[
  ['Machine Configuration','configuration.station','Operator station','text',null,1],
  ['Machine Configuration','configuration.drive','Drive configuration','text',null,2],
  ['Engine','engine.rated_power','Engine horsepower','decimal','hp',3],
  ['PTO','pto.rated_power','PTO power','decimal','hp',10],
  ['Transmission','transmission.options','Transmission options','text',null,10],
] as const;
async function selectId(connection:Parameters<DbMigration['apply']>[0],sql:string,params:unknown[]=[]){const [rows]=await connection.query<IdRow[]>(sql,params);if(!rows[0])throw new Error('Missing Case IH Farmall Small Utility A migration dependency.');return Number(rows[0].id);}
async function ensureSource(connection:Parameters<DbMigration['apply']>[0],sourceId:number,externalId:string,url:string,title:string){const [rows]=await connection.query<IdRow[]>(`SELECT id FROM source_records WHERE external_id=? LIMIT 1`,[externalId]);if(rows[0])return Number(rows[0].id);const [result]=await connection.query<ResultSetHeader>(`INSERT INTO source_records (source_id,url,external_id,title) VALUES (?,?,?,?)`,[sourceId,url,externalId,title]);return Number(result.insertId);}
async function upsertSpec(connection:Parameters<DbMigration['apply']>[0],machineId:number,versionId:number,definitionId:number,sourceRecordId:number,value:string|number,unit:string|null=null){await connection.query(`INSERT INTO machine_specs (machine_id,machine_version_id,spec_definition_id,value_text,value_number,unit,source_record_id,confidence) VALUES (?,?,?,?,?,?,?,'official') ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),value_number=VALUES(value_number),unit=VALUES(unit),source_record_id=VALUES(source_record_id),confidence='official'`,[machineId,versionId,definitionId,typeof value==='string'?value:null,typeof value==='number'?value:null,unit,sourceRecordId]);}

export const caseIHFarmallSmallUtilityACurrentSpecsMigration:DbMigration={
  id:'20260828_239_case_ih_farmall_small_utility_a_current_specs',
  description:'Add current US Case IH Farmall Small Utility A 50A/55A/60A/65A/70A/75A official horsepower, PTO, operator station, drive and transmission data',
  async apply(connection){
    await connection.query(`INSERT INTO equipment_types (name,slug) VALUES ('Tractor','tractor') ON DUPLICATE KEY UPDATE name=VALUES(name)`);
    await connection.query(`INSERT INTO manufacturers (name,slug) VALUES ('Case IH','case-ih') ON DUPLICATE KEY UPDATE name=VALUES(name)`);
    const manufacturerId=await selectId(connection,`SELECT id FROM manufacturers WHERE slug='case-ih' LIMIT 1`);const equipmentTypeId=await selectId(connection,`SELECT id FROM equipment_types WHERE slug='tractor' LIMIT 1`);
    await connection.query(`INSERT INTO machine_series (manufacturer_id,equipment_type_id,name,slug) VALUES (?,?,'Farmall Small Utility A Series','farmall-small-utility-a-series') ON DUPLICATE KEY UPDATE name=VALUES(name)`,[manufacturerId,equipmentTypeId]);const seriesId=await selectId(connection,`SELECT id FROM machine_series WHERE manufacturer_id=? AND equipment_type_id=? AND slug='farmall-small-utility-a-series' LIMIT 1`,[manufacturerId,equipmentTypeId]);
    let [sourceRows]=await connection.query<IdRow[]>(`SELECT id FROM sources WHERE name='Case IH' AND domain='caseih.com' ORDER BY id LIMIT 1`);let sourceId=sourceRows[0]?.id?Number(sourceRows[0].id):0;if(!sourceId){const [result]=await connection.query<ResultSetHeader>(`INSERT INTO sources (name,domain,source_type,authority_level) VALUES ('Case IH','caseih.com','manufacturer','official')`);sourceId=Number(result.insertId);}
    const familySourceId=await ensureSource(connection,sourceId,FAMILY_EXTERNAL_ID,FAMILY_URL,'Case IH US current Farmall Small Utility A Series 50A-75A lineup');
    const definitionIds=new Map<string,number>();for(const [section,key,label,valueType,canonicalUnit,displayOrder] of definitions){await connection.query(`INSERT INTO spec_definitions (section,spec_key,label,value_type,canonical_unit,display_order) VALUES (?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section=VALUES(section),label=VALUES(label),value_type=VALUES(value_type),canonical_unit=VALUES(canonical_unit),display_order=VALUES(display_order)`,[section,key,label,valueType,canonicalUnit,displayOrder]);definitionIds.set(key,await selectId(connection,`SELECT id FROM spec_definitions WHERE spec_key=? LIMIT 1`,[key]));}const def=(key:string)=>{const id=definitionIds.get(key);if(!id)throw new Error(`Missing Farmall Small Utility A spec ${key}`);return id;};
    for(const model of models){const modelSourceId=await ensureSource(connection,sourceId,model.externalId,model.url,`Case IH US ${model.model} official current product specifications`);await connection.query(`INSERT INTO machines (manufacturer_id,equipment_type_id,series_id,model_name,slug,market_notes,data_status) VALUES (?,?,?,?,?,'Current US Case IH Farmall Small Utility A tractor','partial') ON DUPLICATE KEY UPDATE series_id=VALUES(series_id),model_name=VALUES(model_name),market_notes=VALUES(market_notes),data_status=IF(data_status='verified','verified','partial')`,[manufacturerId,equipmentTypeId,seriesId,model.model,model.slug]);const machineId=await selectId(connection,`SELECT id FROM machines WHERE manufacturer_id=? AND equipment_type_id=? AND slug=? LIMIT 1`,[manufacturerId,equipmentTypeId,model.slug]);await connection.query(`UPDATE machine_versions SET is_current=FALSE WHERE machine_id=? AND slug<>?`,[machineId,VERSION_SLUG]);await connection.query(`INSERT INTO machine_versions (machine_id,slug,market_code,market_name,configuration,is_current,source_record_id,notes) VALUES (?,?,'US','United States','Current Farmall Small Utility A - utility tractor',TRUE,?,'Current Case IH US product page data. Published horsepower, PTO horsepower, operator area, traction and transmission are sourced from each official model page.') ON DUPLICATE KEY UPDATE market_code='US',market_name='United States',configuration=VALUES(configuration),is_current=TRUE,source_record_id=VALUES(source_record_id),notes=VALUES(notes)`,[machineId,VERSION_SLUG,modelSourceId]);const versionId=await selectId(connection,`SELECT id FROM machine_versions WHERE machine_id=? AND slug=? LIMIT 1`,[machineId,VERSION_SLUG]);const values:Array<[string,string|number,string|null,number]>=[['configuration.station',model.station,null,modelSourceId],['configuration.drive',model.drive,null,modelSourceId],['engine.rated_power',model.hp,'hp',modelSourceId],['pto.rated_power',model.ptoHp,'hp',modelSourceId],['transmission.options',model.transmission,null,modelSourceId]];for(const [key,value,unit,recordId] of values)await upsertSpec(connection,machineId,versionId,def(key),recordId,value,unit);await upsertSpec(connection,machineId,versionId,def('configuration.drive'),modelSourceId,model.drive);}
  }
};
