import { NextResponse } from 'next/server';
import type { RowDataPacket } from 'mysql2';
import { getDbReady } from '@/lib/db-migrations';
export const dynamic='force-dynamic';export const revalidate=0;
type CountRow=RowDataPacket&{count:number};
async function count(sql:string){const db=await getDbReady();const [rows]=await db.query<CountRow[]>(sql);return Number(rows[0]?.count||0);}
export async function GET(){try{
  const [migrationApplied,machineRows,currentVersions,specificationRows,trackRows,ratedPowerRows,ptoRows,serviceParts,currentServiceFitments,historicalSerialFitments,currentFuelCutover,legacyFuelCutover,currentPilotCutover,legacyPilotCutover,officialSourceRows]=await Promise.all([
    count(`SELECT COUNT(*) count FROM schema_migrations WHERE id='20260828_216_john_deere_8rt_service_filters'`),
    count(`SELECT COUNT(*) count FROM machines m JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='john-deere' AND m.slug IN ('8rt-310','8rt-340','8rt-370','8rt-410') AND m.data_status IN ('partial','verified')`),
    count(`SELECT COUNT(*) count FROM machine_versions mv JOIN machines m ON m.id=mv.machine_id JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='john-deere' AND m.slug IN ('8rt-310','8rt-340','8rt-370','8rt-410') AND mv.slug='united-states-current-2026-08' AND mv.is_current=1`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN manufacturers mf ON mf.id=m.manufacturer_id JOIN machine_versions mv ON mv.id=ms.machine_version_id WHERE mf.slug='john-deere' AND m.slug IN ('8rt-310','8rt-340','8rt-370','8rt-410') AND mv.slug='united-states-current-2026-08'`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN manufacturers mf ON mf.id=m.manufacturer_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE mf.slug='john-deere' AND m.slug IN ('8rt-310','8rt-340','8rt-370','8rt-410') AND mv.slug='united-states-current-2026-08' AND sd.spec_key='configuration.track' AND ms.value_text='2-Track'`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN manufacturers mf ON mf.id=m.manufacturer_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE mf.slug='john-deere' AND mv.slug='united-states-current-2026-08' AND sd.spec_key='engine.rated_power' AND ((m.slug='8rt-310' AND ms.value_number=310) OR (m.slug='8rt-340' AND ms.value_number=340) OR (m.slug='8rt-370' AND ms.value_number=370) OR (m.slug='8rt-410' AND ms.value_number=410))`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN manufacturers mf ON mf.id=m.manufacturer_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE mf.slug='john-deere' AND mv.slug='united-states-current-2026-08' AND sd.spec_key='pto.rated_power' AND ((m.slug='8rt-310' AND ms.value_number=246) OR (m.slug='8rt-340' AND ms.value_number=273) OR (m.slug IN ('8rt-370','8rt-410') AND ms.value_number=300))`),
    count(`SELECT COUNT(*) count FROM parts p JOIN manufacturers mf ON mf.id=p.manufacturer_id WHERE mf.slug='john-deere' AND p.normalized_part_number IN ('RE596317','RE596318','RE539465','DZ110558','RE509672','AT365869','RE577250','RE210857','TA21586','RE284091','RE593819','H216169','DZ124403','DZ114640','R556122','DZ112918','RE269061') AND p.data_status='verified'`),
    count(`SELECT COUNT(*) count FROM machine_parts mp JOIN machines m ON m.id=mp.machine_id JOIN manufacturers mf ON mf.id=m.manufacturer_id JOIN machine_versions mv ON mv.id=mp.machine_version_id WHERE mf.slug='john-deere' AND m.slug IN ('8rt-310','8rt-340','8rt-370','8rt-410') AND mv.slug='united-states-current-2026-08' AND mp.fitment_confidence='official'`),
    count(`SELECT COUNT(*) count FROM machine_parts mp JOIN machines m ON m.id=mp.machine_id JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='john-deere' AND m.slug IN ('8rt-310','8rt-340','8rt-370','8rt-410') AND mp.machine_version_id IS NULL AND mp.fitment_confidence='official'`),
    count(`SELECT COUNT(*) count FROM machine_parts mp JOIN machines m ON m.id=mp.machine_id JOIN parts p ON p.id=mp.part_id WHERE m.slug IN ('8rt-310','8rt-340','8rt-370','8rt-410') AND p.normalized_part_number='DZ110558' AND mp.serial_from='927001'`),
    count(`SELECT COUNT(*) count FROM machine_parts mp JOIN machines m ON m.id=mp.machine_id JOIN parts p ON p.id=mp.part_id WHERE m.slug IN ('8rt-310','8rt-340','8rt-370','8rt-410') AND p.normalized_part_number='DZ112918' AND mp.serial_to='927000'`),
    count(`SELECT COUNT(*) count FROM machine_parts mp JOIN machines m ON m.id=mp.machine_id JOIN parts p ON p.id=mp.part_id WHERE m.slug IN ('8rt-310','8rt-340','8rt-370','8rt-410') AND p.normalized_part_number='TA21586' AND mp.serial_from='931001'`),
    count(`SELECT COUNT(*) count FROM machine_parts mp JOIN machines m ON m.id=mp.machine_id JOIN parts p ON p.id=mp.part_id WHERE m.slug IN ('8rt-310','8rt-340','8rt-370','8rt-410') AND p.normalized_part_number='RE269061' AND mp.serial_to='930999'`),
    count(`SELECT COUNT(*) count FROM source_records WHERE external_id IN ('john-deere-8-series-current-family-2026-08','john-deere-8-series-official-specifications','john-deere-rx525360-8rt-ft4-924001-service-guide')`),
  ]);
  const checks={migrationApplied:migrationApplied===1,machineRows:machineRows===4,currentVersions:currentVersions===4,specificationRows:specificationRows===56,trackRows:trackRows===4,ratedPowerRows:ratedPowerRows===4,ptoRows:ptoRows===4,serviceParts:serviceParts===17,currentServiceFitments:currentServiceFitments===60,historicalSerialFitments:historicalSerialFitments===8,currentFuelCutover:currentFuelCutover===4,legacyFuelCutover:legacyFuelCutover===4,currentPilotCutover:currentPilotCutover===4,legacyPilotCutover:legacyPilotCutover===4,officialSourceRows:officialSourceRows===3};const ok=Object.values(checks).every(Boolean);
  return NextResponse.json({ok,expectedLatest8RTMigration:'20260828_216_john_deere_8rt_service_filters',checks,values:{machineRows,currentVersions,specificationRows,trackRows,ratedPowerRows,ptoRows,serviceParts,currentServiceFitments,historicalSerialFitments,currentFuelCutover,legacyFuelCutover,currentPilotCutover,legacyPilotCutover,officialSourceRows}},{status:ok?200:503,headers:{'Cache-Control':'no-store, max-age=0','X-Robots-Tag':'noindex, nofollow'}});
}catch(error){console.error('John Deere 8RT health check failed:',error);return NextResponse.json({ok:false,error:'John Deere 8RT health check failed'},{status:500,headers:{'Cache-Control':'no-store, max-age=0','X-Robots-Tag':'noindex, nofollow'}});}}
