import { NextResponse } from 'next/server';
import type { RowDataPacket } from 'mysql2';
import { getDbReady } from '@/lib/db-migrations';
export const dynamic='force-dynamic';export const revalidate=0;
type CountRow=RowDataPacket&{count:number};
async function count(sql:string){const db=await getDbReady();const [rows]=await db.query<CountRow[]>(sql);return Number(rows[0]?.count||0);}
export async function GET(){try{
  const [migrationApplied,machineRows,currentVersions,legacy230Current,specificationRows,ratedPowerRows,maxPowerRows,ptoPowerRows,singleTurboRows,dualTurboRows,serviceParts,currentServiceFitments,historicalSerialFitments,currentSecondaryFuelFitments,legacySecondaryFuelFitments,currentScvFitments,legacyScvFitments,officialSourceRows]=await Promise.all([
    count(`SELECT COUNT(*) count FROM schema_migrations WHERE id='20260828_214_john_deere_8r_service_filters'`),
    count(`SELECT COUNT(*) count FROM machines m JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='john-deere' AND m.slug IN ('8r-250','8r-280','8r-310','8r-340','8r-370','8r-410') AND m.data_status IN ('partial','verified')`),
    count(`SELECT COUNT(*) count FROM machine_versions mv JOIN machines m ON m.id=mv.machine_id JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='john-deere' AND m.slug IN ('8r-250','8r-280','8r-310','8r-340','8r-370','8r-410') AND mv.slug='united-states-current-2026-08' AND mv.is_current=1`),
    count(`SELECT COUNT(*) count FROM machine_versions mv JOIN machines m ON m.id=mv.machine_id JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='john-deere' AND m.slug='8r-230' AND mv.is_current=1`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN manufacturers mf ON mf.id=m.manufacturer_id JOIN machine_versions mv ON mv.id=ms.machine_version_id WHERE mf.slug='john-deere' AND m.slug IN ('8r-250','8r-280','8r-310','8r-340','8r-370','8r-410') AND mv.slug='united-states-current-2026-08'`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN manufacturers mf ON mf.id=m.manufacturer_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE mf.slug='john-deere' AND mv.slug='united-states-current-2026-08' AND sd.spec_key='engine.rated_power' AND ((m.slug='8r-250' AND ms.value_number=250) OR (m.slug='8r-280' AND ms.value_number=280) OR (m.slug='8r-310' AND ms.value_number=310) OR (m.slug='8r-340' AND ms.value_number=340) OR (m.slug='8r-370' AND ms.value_number=370) OR (m.slug='8r-410' AND ms.value_number=410))`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN manufacturers mf ON mf.id=m.manufacturer_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE mf.slug='john-deere' AND mv.slug='united-states-current-2026-08' AND sd.spec_key='engine.maximum_power' AND ((m.slug='8r-250' AND ms.value_number=275) OR (m.slug='8r-280' AND ms.value_number=308) OR (m.slug='8r-310' AND ms.value_number=341) OR (m.slug='8r-340' AND ms.value_number=374) OR (m.slug='8r-370' AND ms.value_number=407) OR (m.slug='8r-410' AND ms.value_number=443))`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN manufacturers mf ON mf.id=m.manufacturer_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE mf.slug='john-deere' AND mv.slug='united-states-current-2026-08' AND sd.spec_key='pto.rated_power' AND ((m.slug='8r-250' AND ms.value_number=200) OR (m.slug='8r-280' AND ms.value_number=228) OR (m.slug='8r-310' AND ms.value_number=257) OR (m.slug='8r-340' AND ms.value_number=284) OR (m.slug IN ('8r-370','8r-410') AND ms.value_number=310))`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN manufacturers mf ON mf.id=m.manufacturer_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE mf.slug='john-deere' AND m.slug IN ('8r-250','8r-280','8r-310') AND mv.slug='united-states-current-2026-08' AND sd.spec_key='engine.aspiration' AND ms.value_text LIKE 'Single%'`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN manufacturers mf ON mf.id=m.manufacturer_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE mf.slug='john-deere' AND m.slug IN ('8r-340','8r-370','8r-410') AND mv.slug='united-states-current-2026-08' AND sd.spec_key='engine.aspiration' AND ms.value_text LIKE 'Dual%'`),
    count(`SELECT COUNT(*) count FROM parts p JOIN manufacturers mf ON mf.id=p.manufacturer_id WHERE mf.slug='john-deere' AND p.normalized_part_number IN ('RE596317','RE596318','RE539465','DZ110558','RE509672','AT365869','DZ114640','RE596661','RE284091','RE593819','TA21586','H216169','HXE135862','RE597838','DZ124403','DZ112918','RE269061') AND p.data_status='verified'`),
    count(`SELECT COUNT(*) count FROM machine_parts mp JOIN machines m ON m.id=mp.machine_id JOIN manufacturers mf ON mf.id=m.manufacturer_id JOIN machine_versions mv ON mv.id=mp.machine_version_id WHERE mf.slug='john-deere' AND m.slug IN ('8r-250','8r-280','8r-310','8r-340','8r-370','8r-410') AND mv.slug='united-states-current-2026-08' AND mp.fitment_confidence='official'`),
    count(`SELECT COUNT(*) count FROM machine_parts mp JOIN machines m ON m.id=mp.machine_id JOIN manufacturers mf ON mf.id=m.manufacturer_id JOIN parts p ON p.id=mp.part_id WHERE mf.slug='john-deere' AND m.slug IN ('8r-250','8r-280','8r-310','8r-340','8r-370','8r-410') AND mp.machine_version_id IS NULL AND p.normalized_part_number IN ('DZ112918','RE269061') AND mp.fitment_confidence='official'`),
    count(`SELECT COUNT(*) count FROM machine_parts mp JOIN machines m ON m.id=mp.machine_id JOIN manufacturers mf ON mf.id=m.manufacturer_id JOIN machine_versions mv ON mv.id=mp.machine_version_id JOIN parts p ON p.id=mp.part_id WHERE mf.slug='john-deere' AND m.slug IN ('8r-250','8r-280','8r-310','8r-340','8r-370','8r-410') AND mv.slug='united-states-current-2026-08' AND p.normalized_part_number='DZ110558' AND mp.serial_from='200001'`),
    count(`SELECT COUNT(*) count FROM machine_parts mp JOIN machines m ON m.id=mp.machine_id JOIN manufacturers mf ON mf.id=m.manufacturer_id JOIN parts p ON p.id=mp.part_id WHERE mf.slug='john-deere' AND m.slug IN ('8r-250','8r-280','8r-310','8r-340','8r-370','8r-410') AND mp.machine_version_id IS NULL AND p.normalized_part_number='DZ112918' AND mp.serial_to='200000'`),
    count(`SELECT COUNT(*) count FROM machine_parts mp JOIN machines m ON m.id=mp.machine_id JOIN manufacturers mf ON mf.id=m.manufacturer_id JOIN machine_versions mv ON mv.id=mp.machine_version_id JOIN parts p ON p.id=mp.part_id WHERE mf.slug='john-deere' AND m.slug IN ('8r-250','8r-280','8r-310','8r-340','8r-370','8r-410') AND mv.slug='united-states-current-2026-08' AND p.normalized_part_number='TA21586' AND mp.serial_from='240001'`),
    count(`SELECT COUNT(*) count FROM machine_parts mp JOIN machines m ON m.id=mp.machine_id JOIN manufacturers mf ON mf.id=m.manufacturer_id JOIN parts p ON p.id=mp.part_id WHERE mf.slug='john-deere' AND m.slug IN ('8r-250','8r-280','8r-310','8r-340','8r-370','8r-410') AND mp.machine_version_id IS NULL AND p.normalized_part_number='RE269061' AND mp.serial_to='239999'`),
    count(`SELECT COUNT(*) count FROM source_records WHERE external_id IN ('john-deere-8-series-current-family-2026-08','john-deere-8-series-official-specifications','john-deere-rx525359-8r-ft4-170001-service-guide')`),
  ]);
  const checks={migrationApplied:migrationApplied===1,machineRows:machineRows===6,currentVersions:currentVersions===6,legacy230Current:legacy230Current===0,specificationRows:specificationRows===120,ratedPowerRows:ratedPowerRows===6,maxPowerRows:maxPowerRows===6,ptoPowerRows:ptoPowerRows===6,singleTurboRows:singleTurboRows===3,dualTurboRows:dualTurboRows===3,serviceParts:serviceParts===17,currentServiceFitments:currentServiceFitments===90,historicalSerialFitments:historicalSerialFitments===12,currentSecondaryFuelFitments:currentSecondaryFuelFitments===6,legacySecondaryFuelFitments:legacySecondaryFuelFitments===6,currentScvFitments:currentScvFitments===6,legacyScvFitments:legacyScvFitments===6,officialSourceRows:officialSourceRows===3};const ok=Object.values(checks).every(Boolean);
  return NextResponse.json({ok,expectedLatest8RMigration:'20260828_214_john_deere_8r_service_filters',checks,values:{machineRows,currentVersions,legacy230Current,specificationRows,ratedPowerRows,maxPowerRows,ptoPowerRows,singleTurboRows,dualTurboRows,serviceParts,currentServiceFitments,historicalSerialFitments,currentSecondaryFuelFitments,legacySecondaryFuelFitments,currentScvFitments,legacyScvFitments,officialSourceRows}},{status:ok?200:503,headers:{'Cache-Control':'no-store, max-age=0','X-Robots-Tag':'noindex, nofollow'}});
}catch(error){console.error('John Deere 8R health check failed:',error);return NextResponse.json({ok:false,error:'John Deere 8R health check failed'},{status:500,headers:{'Cache-Control':'no-store, max-age=0','X-Robots-Tag':'noindex, nofollow'}});}}
