import { NextResponse } from 'next/server';
import type { RowDataPacket } from 'mysql2';
import { getDbReady } from '@/lib/db-migrations';
export const dynamic='force-dynamic';export const revalidate=0;
type CountRow=RowDataPacket&{count:number};
async function count(sql:string){const db=await getDbReady();const [rows]=await db.query<CountRow[]>(sql);return Number(rows[0]?.count||0);}
export async function GET(){try{
  const [migrationApplied,machineRows,currentVersions,specificationRows,trackRows,jd18Rows,ratedPowerRows,maxPowerRows,ptoRows,noDefRows,serviceParts,currentServiceFitments,defFitments,shopSourceRows,officialSourceRows]=await Promise.all([
    count(`SELECT COUNT(*) count FROM schema_migrations WHERE id='20260828_220_john_deere_9rx_hhp_service_filters'`),
    count(`SELECT COUNT(*) count FROM machines m JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='john-deere' AND m.slug IN ('9rx-710','9rx-770','9rx-830') AND m.data_status IN ('partial','verified')`),
    count(`SELECT COUNT(*) count FROM machine_versions mv JOIN machines m ON m.id=mv.machine_id JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='john-deere' AND m.slug IN ('9rx-710','9rx-770','9rx-830') AND mv.slug='united-states-current-2026-08' AND mv.is_current=1`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN manufacturers mf ON mf.id=m.manufacturer_id JOIN machine_versions mv ON mv.id=ms.machine_version_id WHERE mf.slug='john-deere' AND m.slug IN ('9rx-710','9rx-770','9rx-830') AND mv.slug='united-states-current-2026-08'`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN ('9rx-710','9rx-770','9rx-830') AND mv.slug='united-states-current-2026-08' AND sd.spec_key='configuration.track' AND ms.value_text='4-Track'`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN ('9rx-710','9rx-770','9rx-830') AND mv.slug='united-states-current-2026-08' AND sd.spec_key='engine.model' AND ms.value_text='JD18'`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE mv.slug='united-states-current-2026-08' AND sd.spec_key='engine.rated_power' AND ((m.slug='9rx-710' AND ms.value_number=710) OR (m.slug='9rx-770' AND ms.value_number=770) OR (m.slug='9rx-830' AND ms.value_number=830))`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE mv.slug='united-states-current-2026-08' AND sd.spec_key='engine.maximum_power' AND ((m.slug='9rx-710' AND ms.value_number=781) OR (m.slug='9rx-770' AND ms.value_number=847) OR (m.slug='9rx-830' AND ms.value_number=913))`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN ('9rx-710','9rx-770','9rx-830') AND mv.slug='united-states-current-2026-08' AND sd.spec_key='pto.rated_power' AND ms.value_number=335`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN ('9rx-710','9rx-770','9rx-830') AND mv.slug='united-states-current-2026-08' AND sd.spec_key='engine.emissions' AND ms.value_text LIKE '%no DEF%'`),
    count(`SELECT COUNT(*) count FROM parts p JOIN manufacturers mf ON mf.id=p.manufacturer_id WHERE mf.slug='john-deere' AND p.normalized_part_number IN ('DZ124765','DZ124786','TA27886','TA17748','TA17749','TA32591','RE593819') AND p.data_status='verified'`),
    count(`SELECT COUNT(*) count FROM machine_parts mp JOIN machines m ON m.id=mp.machine_id JOIN manufacturers mf ON mf.id=m.manufacturer_id JOIN machine_versions mv ON mv.id=mp.machine_version_id JOIN parts p ON p.id=mp.part_id WHERE mf.slug='john-deere' AND m.slug IN ('9rx-710','9rx-770','9rx-830') AND mv.slug='united-states-current-2026-08' AND p.normalized_part_number IN ('DZ124765','DZ124786','TA27886','TA17748','TA17749','TA32591','RE593819') AND mp.fitment_confidence='official'`),
    count(`SELECT COUNT(*) count FROM machine_parts mp JOIN machines m ON m.id=mp.machine_id JOIN machine_versions mv ON mv.id=mp.machine_version_id JOIN parts p ON p.id=mp.part_id JOIN part_categories pc ON pc.id=p.category_id WHERE m.slug IN ('9rx-710','9rx-770','9rx-830') AND mv.slug='united-states-current-2026-08' AND pc.slug='def-filters'`),
    count(`SELECT COUNT(*) count FROM source_records WHERE external_id IN ('john-deere-shop-dz124765-9rx-hhp-fitment','john-deere-shop-dz124786-9rx-hhp-fitment','john-deere-shop-ta27886-9rx-hhp-fitment','john-deere-shop-ta17748-9rx-hhp-fitment','john-deere-shop-ta17749-9rx-hhp-fitment','john-deere-shop-ta32591-9rx-hhp-fitment','john-deere-shop-re593819-9rx-hhp-fitment')`),
    count(`SELECT COUNT(*) count FROM source_records WHERE external_id IN ('john-deere-9rx-hhp-current-2026-08','john-deere-9rx-710-770-830-official-specifications')`),
  ]);
  const checks={migrationApplied:migrationApplied===1,machineRows:machineRows===3,currentVersions:currentVersions===3,specificationRows:specificationRows===51,trackRows:trackRows===3,jd18Rows:jd18Rows===3,ratedPowerRows:ratedPowerRows===3,maxPowerRows:maxPowerRows===3,ptoRows:ptoRows===3,noDefRows:noDefRows===3,serviceParts:serviceParts===7,currentServiceFitments:currentServiceFitments===21,defFitments:defFitments===0,shopSourceRows:shopSourceRows===7,officialSourceRows:officialSourceRows===2};const ok=Object.values(checks).every(Boolean);
  return NextResponse.json({ok,expectedLatest9RXHHPMigration:'20260828_220_john_deere_9rx_hhp_service_filters',checks,values:{machineRows,currentVersions,specificationRows,trackRows,jd18Rows,ratedPowerRows,maxPowerRows,ptoRows,noDefRows,serviceParts,currentServiceFitments,defFitments,shopSourceRows,officialSourceRows}},{status:ok?200:503,headers:{'Cache-Control':'no-store, max-age=0','X-Robots-Tag':'noindex, nofollow'}});
}catch(error){console.error('John Deere 9RX HHP health check failed:',error);return NextResponse.json({ok:false,error:'John Deere 9RX HHP health check failed'},{status:500,headers:{'Cache-Control':'no-store, max-age=0','X-Robots-Tag':'noindex, nofollow'}});}}
