import { NextResponse } from 'next/server';
import type { RowDataPacket } from 'mysql2';
import { getDbReady } from '@/lib/db-migrations';
export const dynamic='force-dynamic';export const revalidate=0;
type CountRow=RowDataPacket&{count:number};async function count(sql:string){const db=await getDbReady();const [rows]=await db.query<CountRow[]>(sql);return Number(rows[0]?.count||0);}
const slugs="'farmall-compact-35c','farmall-compact-40c','farmall-compact-45c','farmall-compact-50c','farmall-compact-55c'";
export async function GET(){try{const [migrations,machines,versions,specs,pto,loaderRows,fitments,sources]=await Promise.all([
 count(`SELECT COUNT(*) count FROM schema_migrations WHERE id IN ('20260828_246_case_ih_farmall_compact_c_current_specs','20260828_247_case_ih_farmall_compact_c_loaders')`),
 count(`SELECT COUNT(*) count FROM machines m JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='case-ih' AND m.slug IN (${slugs})`),
 count(`SELECT COUNT(*) count FROM machine_versions mv JOIN machines m ON m.id=mv.machine_id WHERE m.slug IN (${slugs}) AND mv.slug='united-states-current-2026-08' AND mv.is_current=1`),
 count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id WHERE m.slug IN (${slugs}) AND mv.slug='united-states-current-2026-08'`),
 count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE sd.spec_key='pto.rated_power' AND ((m.slug='farmall-compact-35c' AND ms.value_number=29.7) OR (m.slug='farmall-compact-40c' AND ms.value_number=34) OR (m.slug='farmall-compact-45c' AND ms.value_number=38.2) OR (m.slug='farmall-compact-50c' AND ms.value_number=42.5) OR (m.slug='farmall-compact-55c' AND ms.value_number=46.7))`),
 count(`SELECT COUNT(*) count FROM attachments a JOIN manufacturers mf ON mf.id=a.manufacturer_id WHERE mf.slug='case-ih' AND a.slug IN ('l350a-farmall-compact-c','l360a-farmall-compact-c') AND a.data_status='verified'`),
 count(`SELECT COUNT(*) count FROM machine_attachments ma JOIN machines m ON m.id=ma.machine_id JOIN attachments a ON a.id=ma.attachment_id WHERE m.slug IN (${slugs}) AND a.slug IN ('l350a-farmall-compact-c','l360a-farmall-compact-c') AND ma.confidence='official'`),
 count(`SELECT COUNT(*) count FROM source_records WHERE external_id IN ('case-ih-farmall-compact-c-current-us-35-55-2026-08','case-ih-farmall-compact-35c-current-us','case-ih-farmall-compact-40c-current-us','case-ih-farmall-compact-45c-current-us','case-ih-farmall-compact-50c-current-us','case-ih-farmall-compact-55c-current-us','case-ih-farmall-compact-c-l350a-current','case-ih-farmall-compact-c-l360a-current')`)
]);const checks={migrations:migrations===2,machines:machines===5,versions:versions===5,specs:specs===30,pto:pto===5,loaderRows:loaderRows===2,fitments:fitments===5,sources:sources===8};const ok=Object.values(checks).every(Boolean);return NextResponse.json({ok,expectedLatest:'20260828_247_case_ih_farmall_compact_c_loaders',checks,values:{migrations,machines,versions,specs,pto,loaderRows,fitments,sources}},{status:ok?200:503,headers:{'Cache-Control':'no-store, max-age=0','X-Robots-Tag':'noindex, nofollow'}});}catch(error){console.error(error);return NextResponse.json({ok:false,error:'Farmall Compact C health check failed'},{status:500});}}
