import { NextResponse } from 'next/server';
import type { RowDataPacket } from 'mysql2';
import { getDbReady } from '@/lib/db-migrations';

export const dynamic='force-dynamic';
export const revalidate=0;

type CountRow=RowDataPacket&{count:number};
async function count(sql:string){const db=await getDbReady();const [rows]=await db.query<CountRow[]>(sql);return Number(rows[0]?.count||0);}
const slugs="'optum-270','optum-300','optum-340','optum-360','optum-390','optum-440'";

export async function GET(){try{
  const [migrationApplied,machines,currentVersions,specRows,sixSevenRows,eightSevenRows,ratedRows,optum340RatedRows,maxRows,ptoRows,newPtoRows,oldHitchRows,newHitchRows,maintenanceRows,sourceRows]=await Promise.all([
    count(`SELECT COUNT(*) count FROM schema_migrations WHERE id='20260828_232_case_ih_optum_current_specs'`),
    count(`SELECT COUNT(*) count FROM machines m JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='case-ih' AND m.slug IN (${slugs})`),
    count(`SELECT COUNT(*) count FROM machine_versions mv JOIN machines m ON m.id=mv.machine_id JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='case-ih' AND m.slug IN (${slugs}) AND mv.slug='united-states-current-2026-08' AND mv.is_current=1`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='case-ih' AND m.slug IN (${slugs}) AND mv.slug='united-states-current-2026-08'`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN ('optum-270','optum-300','optum-340') AND mv.slug='united-states-current-2026-08' AND sd.spec_key='engine.displacement' AND ms.value_number=6.7`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN ('optum-360','optum-390','optum-440') AND mv.slug='united-states-current-2026-08' AND sd.spec_key='engine.displacement' AND ms.value_number=8.7`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE mv.slug='united-states-current-2026-08' AND sd.spec_key='engine.rated_power' AND ((m.slug='optum-270' AND ms.value_number=271) OR (m.slug='optum-300' AND ms.value_number=300) OR (m.slug='optum-360' AND ms.value_number=360) OR (m.slug='optum-390' AND ms.value_number=390) OR (m.slug='optum-440' AND ms.value_number=435))`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug='optum-340' AND mv.slug='united-states-current-2026-08' AND sd.spec_key='engine.rated_power'`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE mv.slug='united-states-current-2026-08' AND sd.spec_key='engine.maximum_power' AND ((m.slug='optum-270' AND ms.value_number=290) OR (m.slug='optum-300' AND ms.value_number=313) OR (m.slug='optum-340' AND ms.value_number=340) OR (m.slug='optum-360' AND ms.value_number=360) OR (m.slug='optum-390' AND ms.value_number=390) OR (m.slug='optum-440' AND ms.value_number=435))`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE mv.slug='united-states-current-2026-08' AND sd.spec_key='pto.rated_power' AND ((m.slug='optum-270' AND ms.value_number=240) OR (m.slug='optum-300' AND ms.value_number=267) OR (m.slug='optum-340' AND ms.value_number=282))`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN ('optum-360','optum-390','optum-440') AND mv.slug='united-states-current-2026-08' AND sd.spec_key='pto.rated_power'`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN ('optum-270','optum-300','optum-340') AND mv.slug='united-states-current-2026-08' AND sd.spec_key='hitch.rear_max_lift_capacity' AND ms.value_number=22705`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN ('optum-360','optum-390','optum-440') AND mv.slug='united-states-current-2026-08' AND sd.spec_key='hitch.rear_max_lift_capacity' AND ms.value_number=25926`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN (${slugs}) AND mv.slug='united-states-current-2026-08' AND sd.spec_key='maintenance.engine_oil_interval' AND ms.value_number=750`),
    count(`SELECT COUNT(*) count FROM source_records WHERE external_id IN ('case-ih-optum-current-us-270-440-2026-08','case-ih-optum-270-current-us','case-ih-optum-300-current-us','case-ih-optum-340-current-us','case-ih-optum-360-current-us','case-ih-optum-390-current-us','case-ih-optum-440-current-us')`),
  ]);
  const checks={migrationApplied:migrationApplied===1,machines:machines===6,currentVersions:currentVersions===6,specRows:specRows===56,sixSevenRows:sixSevenRows===3,eightSevenRows:eightSevenRows===3,ratedRows:ratedRows===5,optum340RatedRows:optum340RatedRows===0,maxRows:maxRows===6,ptoRows:ptoRows===3,newPtoRows:newPtoRows===0,oldHitchRows:oldHitchRows===3,newHitchRows:newHitchRows===3,maintenanceRows:maintenanceRows===6,sourceRows:sourceRows===7};
  const ok=Object.values(checks).every(Boolean);
  return NextResponse.json({ok,expectedLatestCaseIHOptumMigration:'20260828_232_case_ih_optum_current_specs',checks,values:{migrationApplied,machines,currentVersions,specRows,sixSevenRows,eightSevenRows,ratedRows,optum340RatedRows,maxRows,ptoRows,newPtoRows,oldHitchRows,newHitchRows,maintenanceRows,sourceRows}},{status:ok?200:503,headers:{'Cache-Control':'no-store, max-age=0','X-Robots-Tag':'noindex, nofollow'}});
}catch(error){console.error('Case IH Optum health check failed:',error);return NextResponse.json({ok:false,error:'Case IH Optum health check failed'},{status:500,headers:{'Cache-Control':'no-store, max-age=0','X-Robots-Tag':'noindex, nofollow'}});}}
