import { NextResponse } from 'next/server';
import type { RowDataPacket } from 'mysql2';
import { getDbReady } from '@/lib/db-migrations';
export const dynamic='force-dynamic';export const revalidate=0;
type CountRow=RowDataPacket&{count:number};
async function count(sql:string){const db=await getDbReady();const [rows]=await db.query<CountRow[]>(sql);return Number(rows[0]?.count||0);}
export async function GET(){try{
  const [migrationApplied,machineRows,currentVersions,legacyCurrentVersions,specificationRows,trackRows,jd14Rows,ratedPowerRows,maxPowerRows,ptoRows,serviceParts,currentServiceFitments,shopSourceRows,currentSourceRows]=await Promise.all([
    count(`SELECT COUNT(*) count FROM schema_migrations WHERE id='20260828_222_john_deere_9rt_service_filters'`),
    count(`SELECT COUNT(*) count FROM machines m JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='john-deere' AND m.slug IN ('9rt-490','9rt-540','9rt-590') AND m.data_status IN ('partial','verified')`),
    count(`SELECT COUNT(*) count FROM machine_versions mv JOIN machines m ON m.id=mv.machine_id JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='john-deere' AND m.slug IN ('9rt-490','9rt-540','9rt-590') AND mv.slug='united-states-current-2026-08' AND mv.is_current=1`),
    count(`SELECT COUNT(*) count FROM machine_versions mv JOIN machines m ON m.id=mv.machine_id JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='john-deere' AND m.slug IN ('9rt-470','9rt-520','9rt-570') AND mv.is_current=1`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id WHERE m.slug IN ('9rt-490','9rt-540','9rt-590') AND mv.slug='united-states-current-2026-08'`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN ('9rt-490','9rt-540','9rt-590') AND mv.slug='united-states-current-2026-08' AND sd.spec_key='configuration.track' AND ms.value_text='2-Track'`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN ('9rt-490','9rt-540','9rt-590') AND mv.slug='united-states-current-2026-08' AND sd.spec_key='engine.model' AND ms.value_text='JD14'`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE mv.slug='united-states-current-2026-08' AND sd.spec_key='engine.rated_power' AND ((m.slug='9rt-490' AND ms.value_number=490) OR (m.slug='9rt-540' AND ms.value_number=540) OR (m.slug='9rt-590' AND ms.value_number=590))`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE mv.slug='united-states-current-2026-08' AND sd.spec_key='engine.maximum_power' AND ((m.slug='9rt-490' AND ms.value_number=539) OR (m.slug='9rt-540' AND ms.value_number=594) OR (m.slug='9rt-590' AND ms.value_number=649))`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN ('9rt-490','9rt-540','9rt-590') AND mv.slug='united-states-current-2026-08' AND sd.spec_key='pto.rated_power' AND ms.value_number=335`),
    count(`SELECT COUNT(*) count FROM parts p JOIN manufacturers mf ON mf.id=p.manufacturer_id WHERE mf.slug='john-deere' AND p.normalized_part_number IN ('TA17973','RE230985','RE572785','DZ124761','DZ124786','RE577612','RE577250','RE593819') AND p.data_status='verified'`),
    count(`SELECT COUNT(*) count FROM machine_parts mp JOIN machines m ON m.id=mp.machine_id JOIN machine_versions mv ON mv.id=mp.machine_version_id JOIN parts p ON p.id=mp.part_id WHERE m.slug IN ('9rt-490','9rt-540','9rt-590') AND mv.slug='united-states-current-2026-08' AND p.normalized_part_number IN ('TA17973','RE230985','RE572785','DZ124761','DZ124786','RE577612','RE577250','RE593819') AND mp.fitment_confidence='official'`),
    count(`SELECT COUNT(*) count FROM source_records WHERE external_id IN ('john-deere-shop-ta17973-9rt-current-fitment','john-deere-shop-re230985-9rt-current-fitment','john-deere-shop-re572785-9rt-current-fitment','john-deere-shop-dz124761-9rt-current-fitment','john-deere-shop-dz124786-9rt-current-fitment','john-deere-shop-re577612-9rt-current-fitment','john-deere-shop-re577250-9rt-current-fitment','john-deere-shop-re593819-9rt-current-fitment')`),
    count(`SELECT COUNT(*) count FROM source_records WHERE external_id IN ('john-deere-9rt-490-540-590-current-techpub-2026-05','john-deere-us-9rt-490-540-590-pricebook-2024-11','john-deere-na-9rt-490-specs','john-deere-na-9rt-540-specs','john-deere-na-9rt-590-specs')`),
  ]);
  const checks={migrationApplied:migrationApplied===1,machineRows:machineRows===3,currentVersions:currentVersions===3,legacyCurrentVersions:legacyCurrentVersions===0,specificationRows:specificationRows===51,trackRows:trackRows===3,jd14Rows:jd14Rows===3,ratedPowerRows:ratedPowerRows===3,maxPowerRows:maxPowerRows===3,ptoRows:ptoRows===3,serviceParts:serviceParts===8,currentServiceFitments:currentServiceFitments===24,shopSourceRows:shopSourceRows===8,currentSourceRows:currentSourceRows===5};const ok=Object.values(checks).every(Boolean);
  return NextResponse.json({ok,expectedLatest9RTMigration:'20260828_222_john_deere_9rt_service_filters',checks,values:{machineRows,currentVersions,legacyCurrentVersions,specificationRows,trackRows,jd14Rows,ratedPowerRows,maxPowerRows,ptoRows,serviceParts,currentServiceFitments,shopSourceRows,currentSourceRows}},{status:ok?200:503,headers:{'Cache-Control':'no-store, max-age=0','X-Robots-Tag':'noindex, nofollow'}});
}catch(error){console.error('John Deere 9RT health check failed:',error);return NextResponse.json({ok:false,error:'John Deere 9RT health check failed'},{status:500,headers:{'Cache-Control':'no-store, max-age=0','X-Robots-Tag':'noindex, nofollow'}});}}
