import { NextResponse } from 'next/server';
import type { RowDataPacket } from 'mysql2';
import { getDbReady } from '@/lib/db-migrations';
export const dynamic='force-dynamic';export const revalidate=0;
type CountRow=RowDataPacket&{count:number};
async function count(sql:string){const db=await getDbReady();const [rows]=await db.query<CountRow[]>(sql);return Number(rows[0]?.count||0);}
const slugs="'afs-connect-puma-185','afs-connect-puma-200','afs-connect-puma-220','afs-connect-puma-240','afs-connect-puma-260'";
export async function GET(){try{
  const [migrationApplied,machines,currentVersions,specRows,displacementRows,ratedRows,maxRows,ptoRows,fuelRows,hitchRows,maintenanceRows,loaderRows,loaderFitments,sourceRows]=await Promise.all([
    count(`SELECT COUNT(*) count FROM schema_migrations WHERE id='20260828_228_case_ih_afs_connect_puma_l117_loader'`),
    count(`SELECT COUNT(*) count FROM machines m JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='case-ih' AND m.slug IN (${slugs})`),
    count(`SELECT COUNT(*) count FROM machine_versions mv JOIN machines m ON m.id=mv.machine_id JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='case-ih' AND m.slug IN (${slugs}) AND mv.slug='united-states-current-2026-08' AND mv.is_current=1`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='case-ih' AND m.slug IN (${slugs}) AND mv.slug='united-states-current-2026-08'`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN (${slugs}) AND mv.slug='united-states-current-2026-08' AND sd.spec_key='engine.displacement' AND ms.value_number=6.7`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN (${slugs}) AND mv.slug='united-states-current-2026-08' AND sd.spec_key='engine.rated_power' AND ((m.slug='afs-connect-puma-185' AND ms.value_number=180) OR (m.slug='afs-connect-puma-200' AND ms.value_number=200) OR (m.slug='afs-connect-puma-220' AND ms.value_number=220) OR (m.slug='afs-connect-puma-240' AND ms.value_number=240) OR (m.slug='afs-connect-puma-260' AND ms.value_number=260))`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN (${slugs}) AND mv.slug='united-states-current-2026-08' AND sd.spec_key='engine.maximum_power' AND ((m.slug='afs-connect-puma-185' AND ms.value_number=225) OR (m.slug='afs-connect-puma-200' AND ms.value_number=245) OR (m.slug='afs-connect-puma-220' AND ms.value_number=260) OR (m.slug='afs-connect-puma-240' AND ms.value_number=270) OR (m.slug='afs-connect-puma-260' AND ms.value_number=302))`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN (${slugs}) AND mv.slug='united-states-current-2026-08' AND sd.spec_key='pto.rated_power' AND ((m.slug='afs-connect-puma-185' AND ms.value_number=150) OR (m.slug='afs-connect-puma-200' AND ms.value_number=170) OR (m.slug='afs-connect-puma-220' AND ms.value_number=190) OR (m.slug='afs-connect-puma-240' AND ms.value_number=210) OR (m.slug='afs-connect-puma-260' AND ms.value_number=230))`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN (${slugs}) AND mv.slug='united-states-current-2026-08' AND sd.spec_key='capacities.fuel_tank_variants' AND ms.value_number=124`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN (${slugs}) AND mv.slug='united-states-current-2026-08' AND sd.spec_key='hitch.rear_max_lift_capacity' AND ms.value_number=23000`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN (${slugs}) AND mv.slug='united-states-current-2026-08' AND sd.spec_key='maintenance.engine_oil_interval' AND ms.value_number=750`),
    count(`SELECT COUNT(*) count FROM attachments a JOIN manufacturers mf ON mf.id=a.manufacturer_id WHERE mf.slug='case-ih' AND a.slug='l117' AND a.attachment_type='front-loader' AND a.data_status='verified'`),
    count(`SELECT COUNT(*) count FROM machine_attachments ma JOIN machines m ON m.id=ma.machine_id JOIN attachments a ON a.id=ma.attachment_id JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='case-ih' AND m.slug IN (${slugs}) AND a.slug='l117' AND ma.confidence='official'`),
    count(`SELECT COUNT(*) count FROM source_records WHERE external_id IN ('case-ih-afs-connect-puma-current-my2025-2026','case-ih-afs-connect-puma-185-current-us','case-ih-afs-connect-puma-200-current-us','case-ih-afs-connect-puma-220-current-us','case-ih-afs-connect-puma-240-current-us','case-ih-afs-connect-puma-260-current-us','case-ih-afs-connect-puma-l117-loader-current')`),
  ]);
  const checks={migrationApplied:migrationApplied===1,machines:machines===5,currentVersions:currentVersions===5,specRows:specRows===60,displacementRows:displacementRows===5,ratedRows:ratedRows===5,maxRows:maxRows===5,ptoRows:ptoRows===5,fuelRows:fuelRows===5,hitchRows:hitchRows===5,maintenanceRows:maintenanceRows===5,loaderRows:loaderRows===1,loaderFitments:loaderFitments===5,sourceRows:sourceRows===7};const ok=Object.values(checks).every(Boolean);
  return NextResponse.json({ok,expectedLatestCaseIHPumaMigration:'20260828_228_case_ih_afs_connect_puma_l117_loader',checks,values:{migrationApplied,machines,currentVersions,specRows,displacementRows,ratedRows,maxRows,ptoRows,fuelRows,hitchRows,maintenanceRows,loaderRows,loaderFitments,sourceRows}},{status:ok?200:503,headers:{'Cache-Control':'no-store, max-age=0','X-Robots-Tag':'noindex, nofollow'}});
}catch(error){console.error('Case IH Puma health check failed:',error);return NextResponse.json({ok:false,error:'Case IH Puma health check failed'},{status:500,headers:{'Cache-Control':'no-store, max-age=0','X-Robots-Tag':'noindex, nofollow'}});}}
