import { NextResponse } from 'next/server';
import type { RowDataPacket } from 'mysql2';
import { getDbReady } from '@/lib/db-migrations';
export const dynamic='force-dynamic';export const revalidate=0;
type CountRow=RowDataPacket&{count:number};
async function count(sql:string){const db=await getDbReady();const [rows]=await db.query<CountRow[]>(sql);return Number(rows[0]?.count||0);}
const currentSlugs="'magnum-200','magnum-220','magnum-240','magnum-265','magnum-295','magnum-325','magnum-355','magnum-385','magnum-405'";
export async function GET(){try{
  const [migrationApplied,machines,currentVersions,legacyCurrent,specRows,ratedRows,ptoRows,maxRows,magnum240MaxRows,boosted355Rows,sixSevenRows,eightSevenRows,rowtracRows,transmissionRows,loaderRows,loaderFitments,wrongLoaderFitments,sourceRows]=await Promise.all([
    count(`SELECT COUNT(*) count FROM schema_migrations WHERE id='20260828_230_case_ih_magnum_l118_loader'`),
    count(`SELECT COUNT(*) count FROM machines m JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='case-ih' AND m.slug IN (${currentSlugs})`),
    count(`SELECT COUNT(*) count FROM machine_versions mv JOIN machines m ON m.id=mv.machine_id JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='case-ih' AND m.slug IN (${currentSlugs}) AND mv.slug='united-states-current-2026-08' AND mv.is_current=1`),
    count(`SELECT COUNT(*) count FROM machine_versions mv JOIN machines m ON m.id=mv.machine_id JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='case-ih' AND m.slug IN ('magnum-180','magnum-250','magnum-280','magnum-380') AND mv.is_current=1`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id WHERE m.slug IN (${currentSlugs}) AND mv.slug='united-states-current-2026-08'`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN (${currentSlugs}) AND mv.slug='united-states-current-2026-08' AND sd.spec_key='engine.rated_power' AND ((m.slug='magnum-200' AND ms.value_number=200) OR (m.slug='magnum-220' AND ms.value_number=220) OR (m.slug='magnum-240' AND ms.value_number=240) OR (m.slug='magnum-265' AND ms.value_number=265) OR (m.slug='magnum-295' AND ms.value_number=295) OR (m.slug='magnum-325' AND ms.value_number=325) OR (m.slug='magnum-355' AND ms.value_number=355) OR (m.slug='magnum-385' AND ms.value_number=385) OR (m.slug='magnum-405' AND ms.value_number=405))`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN (${currentSlugs}) AND mv.slug='united-states-current-2026-08' AND sd.spec_key='pto.rated_power' AND ((m.slug='magnum-200' AND ms.value_number=170) OR (m.slug='magnum-220' AND ms.value_number=185) OR (m.slug='magnum-240' AND ms.value_number=205) OR (m.slug='magnum-265' AND ms.value_number=218) OR (m.slug='magnum-295' AND ms.value_number=248) OR (m.slug='magnum-325' AND ms.value_number=277) OR (m.slug='magnum-355' AND ms.value_number=303) OR (m.slug='magnum-385' AND ms.value_number=320) OR (m.slug='magnum-405' AND ms.value_number=352))`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN (${currentSlugs}) AND mv.slug='united-states-current-2026-08' AND sd.spec_key='engine.maximum_power'`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug='magnum-240' AND mv.slug='united-states-current-2026-08' AND sd.spec_key='engine.maximum_power'`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug='magnum-355' AND mv.slug='united-states-current-2026-08' AND sd.spec_key='engine.maximum_boosted_power' AND ms.value_number=410`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN (${currentSlugs}) AND mv.slug='united-states-current-2026-08' AND sd.spec_key='engine.displacement' AND ms.value_number=6.7`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN (${currentSlugs}) AND mv.slug='united-states-current-2026-08' AND sd.spec_key='engine.displacement' AND ms.value_number=8.7`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN ('magnum-355','magnum-385','magnum-405') AND mv.slug='united-states-current-2026-08' AND sd.spec_key='configuration.drive' AND ms.value_text='Wheeled or Rowtrac'`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN (${currentSlugs}) AND mv.slug='united-states-current-2026-08' AND sd.spec_key='transmission.standard'`),
    count(`SELECT COUNT(*) count FROM attachments a JOIN manufacturers mf ON mf.id=a.manufacturer_id WHERE mf.slug='case-ih' AND a.slug='l118' AND a.attachment_type='front-loader' AND a.data_status='verified'`),
    count(`SELECT COUNT(*) count FROM machine_attachments ma JOIN machines m ON m.id=ma.machine_id JOIN attachments a ON a.id=ma.attachment_id WHERE m.slug IN ('magnum-200','magnum-220','magnum-240') AND a.slug='l118' AND ma.confidence='official'`),
    count(`SELECT COUNT(*) count FROM machine_attachments ma JOIN machines m ON m.id=ma.machine_id JOIN attachments a ON a.id=ma.attachment_id WHERE m.slug IN ('magnum-265','magnum-295','magnum-325','magnum-355','magnum-385','magnum-405') AND a.slug='l118'`),
    count(`SELECT COUNT(*) count FROM source_records WHERE external_id IN ('case-ih-magnum-current-us-200-405-2026-08','case-ih-magnum-200-current-us','case-ih-magnum-220-current-us','case-ih-magnum-240-current-us','case-ih-magnum-265-current-us','case-ih-magnum-295-current-us','case-ih-magnum-325-current-us','case-ih-magnum-355-current-us','case-ih-magnum-385-current-us','case-ih-magnum-405-current-us','case-ih-magnum-l118-loader-current')`),
  ]);
  const checks={migrationApplied:migrationApplied===1,machines:machines===9,currentVersions:currentVersions===9,legacyCurrent:legacyCurrent===0,specRows:specRows===71,ratedRows:ratedRows===9,ptoRows:ptoRows===9,maxRows:maxRows===8,magnum240MaxRows:magnum240MaxRows===0,boosted355Rows:boosted355Rows===1,sixSevenRows:sixSevenRows===3,eightSevenRows:eightSevenRows===6,rowtracRows:rowtracRows===3,transmissionRows:transmissionRows===8,loaderRows:loaderRows===1,loaderFitments:loaderFitments===3,wrongLoaderFitments:wrongLoaderFitments===0,sourceRows:sourceRows===11};const ok=Object.values(checks).every(Boolean);
  return NextResponse.json({ok,expectedLatestCaseIHMagnumMigration:'20260828_230_case_ih_magnum_l118_loader',checks,values:{migrationApplied,machines,currentVersions,legacyCurrent,specRows,ratedRows,ptoRows,maxRows,magnum240MaxRows,boosted355Rows,sixSevenRows,eightSevenRows,rowtracRows,transmissionRows,loaderRows,loaderFitments,wrongLoaderFitments,sourceRows}},{status:ok?200:503,headers:{'Cache-Control':'no-store, max-age=0','X-Robots-Tag':'noindex, nofollow'}});
}catch(error){console.error('Case IH Magnum health check failed:',error);return NextResponse.json({ok:false,error:'Case IH Magnum health check failed'},{status:500,headers:{'Cache-Control':'no-store, max-age=0','X-Robots-Tag':'noindex, nofollow'}});}}
