import { NextResponse } from 'next/server';
import type { RowDataPacket } from 'mysql2';
import { getDbReady } from '@/lib/db-migrations';
export const dynamic='force-dynamic';export const revalidate=0;
type CountRow=RowDataPacket&{count:number};
async function count(sql:string){const db=await getDbReady();const [rows]=await db.query<CountRow[]>(sql);return Number(rows[0]?.count||0);}
const slugs="'9rx-490','9rx-540','9rx-590','9rx-640'";
export async function GET(){try{
  const [migrationApplied,machines,currentVersions,specRows,trackRows,jd14Rows,current136Rows,current15Rows,ratedRows,maxRows,ptoRows,serviceParts,currentFitments,historicalScv,currentScv,sourceRows]=await Promise.all([
    count(`SELECT COUNT(*) count FROM schema_migrations WHERE id='20260828_226_john_deere_9rx_490_640_service_filters'`),
    count(`SELECT COUNT(*) count FROM machines m JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='john-deere' AND m.slug IN (${slugs})`),
    count(`SELECT COUNT(*) count FROM machine_versions mv JOIN machines m ON m.id=mv.machine_id JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='john-deere' AND m.slug IN (${slugs}) AND mv.slug='united-states-current-2026-08' AND mv.is_current=1`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='john-deere' AND m.slug IN (${slugs}) AND mv.slug='united-states-current-2026-08'`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN (${slugs}) AND mv.slug='united-states-current-2026-08' AND sd.spec_key='configuration.track' AND ms.value_text='4-Track'`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN (${slugs}) AND mv.slug='united-states-current-2026-08' AND sd.spec_key='engine.model' AND ms.value_text='JD14'`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN (${slugs}) AND mv.slug='united-states-current-2026-08' AND sd.spec_key='engine.displacement' AND ms.value_number=13.6`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN (${slugs}) AND mv.slug='united-states-current-2026-08' AND sd.spec_key='engine.displacement' AND ms.value_number=15`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN (${slugs}) AND mv.slug='united-states-current-2026-08' AND sd.spec_key='engine.rated_power' AND ((m.slug='9rx-490' AND ms.value_number=490) OR (m.slug='9rx-540' AND ms.value_number=540) OR (m.slug='9rx-590' AND ms.value_number=590) OR (m.slug='9rx-640' AND ms.value_number=640))`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN (${slugs}) AND mv.slug='united-states-current-2026-08' AND sd.spec_key='engine.maximum_power' AND ((m.slug='9rx-490' AND ms.value_number=539) OR (m.slug='9rx-540' AND ms.value_number=594) OR (m.slug='9rx-590' AND ms.value_number=649) OR (m.slug='9rx-640' AND ms.value_number=691))`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN (${slugs}) AND mv.slug='united-states-current-2026-08' AND sd.spec_key='pto.rated_power' AND ms.value_number=335`),
    count(`SELECT COUNT(*) count FROM parts p JOIN manufacturers mf ON mf.id=p.manufacturer_id WHERE mf.slug='john-deere' AND p.normalized_part_number IN ('AT365869','DZ124403','DZ114640','H216169','TA17973','RE230985','RE597019','DZ124761','DZ124786','RE572785','RE577250','RE577612','RE284091','RE593819','TA21586','RE269061') AND p.data_status='verified'`),
    count(`SELECT COUNT(*) count FROM machine_parts mp JOIN machines m ON m.id=mp.machine_id JOIN machine_versions mv ON mv.id=mp.machine_version_id WHERE m.slug IN (${slugs}) AND mv.slug='united-states-current-2026-08' AND mp.fitment_confidence='official'`),
    count(`SELECT COUNT(*) count FROM machine_parts mp JOIN machines m ON m.id=mp.machine_id JOIN parts p ON p.id=mp.part_id WHERE m.slug IN (${slugs}) AND mp.machine_version_id IS NULL AND p.normalized_part_number='RE269061' AND mp.serial_to='824999' AND mp.fitment_confidence='official'`),
    count(`SELECT COUNT(*) count FROM machine_parts mp JOIN machines m ON m.id=mp.machine_id JOIN machine_versions mv ON mv.id=mp.machine_version_id JOIN parts p ON p.id=mp.part_id WHERE m.slug IN (${slugs}) AND mv.slug='united-states-current-2026-08' AND p.normalized_part_number='TA21586' AND mp.serial_from='825001' AND mp.fitment_confidence='official'`),
    count(`SELECT COUNT(*) count FROM source_records WHERE external_id IN ('john-deere-9rx-490-640-current-related-products-2026-08','john-deere-9rx-490-640-jd14-official-specifications','john-deere-shop-sz10293-13-6l-9rx-490-640-fitment','john-deere-rx564272-9rx-490-640-ft4-service-guide')`),
  ]);
  const checks={migrationApplied:migrationApplied===1,machines:machines===4,currentVersions:currentVersions===4,specRows:specRows===64,trackRows:trackRows===4,jd14Rows:jd14Rows===4,current136Rows:current136Rows===4,current15Rows:current15Rows===0,ratedRows:ratedRows===4,maxRows:maxRows===4,ptoRows:ptoRows===4,serviceParts:serviceParts===16,currentFitments:currentFitments===60,historicalScv:historicalScv===4,currentScv:currentScv===4,sourceRows:sourceRows===4};const ok=Object.values(checks).every(Boolean);
  return NextResponse.json({ok,expectedLatest9RXJD14Migration:'20260828_226_john_deere_9rx_490_640_service_filters',checks,values:{migrationApplied,machines,currentVersions,specRows,trackRows,jd14Rows,current136Rows,current15Rows,ratedRows,maxRows,ptoRows,serviceParts,currentFitments,historicalScv,currentScv,sourceRows}},{status:ok?200:503,headers:{'Cache-Control':'no-store, max-age=0','X-Robots-Tag':'noindex, nofollow'}});
}catch(error){console.error('John Deere 9RX JD14 health check failed:',error);return NextResponse.json({ok:false,error:'John Deere 9RX JD14 health check failed'},{status:500,headers:{'Cache-Control':'no-store, max-age=0','X-Robots-Tag':'noindex, nofollow'}});}}
