import { NextResponse } from 'next/server';
import type { RowDataPacket } from 'mysql2';
import { getDbReady } from '@/lib/db-migrations';

export const dynamic='force-dynamic';
export const revalidate=0;

type CountRow=RowDataPacket&{count:number};
async function count(sql:string){const db=await getDbReady();const [rows]=await db.query<CountRow[]>(sql);return Number(rows[0]?.count||0);}
const slugs="'farmall-110a-pro','farmall-120a-pro','farmall-130a-pro','farmall-140a-pro'";
const loaderSlugs="'l113-farmall-100a-pro','l114-farmall-100a-pro'";

export async function GET(){try{
  const [migrationsApplied,machines,currentVersions,specRows,engineMakeRows,displacementRows,ratedRows,ptoRows,stationRows,driveRows,transmissionRows,hydraulicRows,hitchRows,loaderRows,loaderFitments,sourceRows]=await Promise.all([
    count(`SELECT COUNT(*) count FROM schema_migrations WHERE id IN ('20260828_237_case_ih_farmall_100a_pro_current_specs','20260828_238_case_ih_farmall_100a_pro_loaders')`),
    count(`SELECT COUNT(*) count FROM machines m JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='case-ih' AND m.slug IN (${slugs})`),
    count(`SELECT COUNT(*) count FROM machine_versions mv JOIN machines m ON m.id=mv.machine_id JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='case-ih' AND m.slug IN (${slugs}) AND mv.slug='united-states-current-2026-08' AND mv.is_current=1`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='case-ih' AND m.slug IN (${slugs}) AND mv.slug='united-states-current-2026-08'`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN (${slugs}) AND mv.slug='united-states-current-2026-08' AND sd.spec_key='engine.make' AND ms.value_text='FPT Industrial'`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN (${slugs}) AND mv.slug='united-states-current-2026-08' AND sd.spec_key='engine.displacement' AND ms.value_number=4.5`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE mv.slug='united-states-current-2026-08' AND sd.spec_key='engine.rated_power' AND ((m.slug='farmall-110a-pro' AND ms.value_number=110) OR (m.slug='farmall-120a-pro' AND ms.value_number=120) OR (m.slug='farmall-130a-pro' AND ms.value_number=130) OR (m.slug='farmall-140a-pro' AND ms.value_number=140))`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE mv.slug='united-states-current-2026-08' AND sd.spec_key='pto.rated_power' AND ((m.slug='farmall-110a-pro' AND ms.value_number=92) OR (m.slug='farmall-120a-pro' AND ms.value_number=102) OR (m.slug='farmall-130a-pro' AND ms.value_number=112) OR (m.slug='farmall-140a-pro' AND ms.value_number=118))`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE mv.slug='united-states-current-2026-08' AND sd.spec_key='configuration.station' AND ((m.slug='farmall-110a-pro' AND ms.value_text='Cab') OR (m.slug='farmall-120a-pro' AND ms.value_text='Non-cab or Cab') OR (m.slug='farmall-130a-pro' AND ms.value_text='Cab') OR (m.slug='farmall-140a-pro' AND ms.value_text='Cab or Non-cab'))`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE mv.slug='united-states-current-2026-08' AND sd.spec_key='configuration.drive' AND ((m.slug='farmall-110a-pro' AND ms.value_text='MFD') OR (m.slug='farmall-120a-pro' AND ms.value_text='MFD') OR (m.slug='farmall-130a-pro' AND ms.value_text='2WD or MFD') OR (m.slug='farmall-140a-pro' AND ms.value_text='2WD (Cab Only) or MFD'))`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN (${slugs}) AND mv.slug='united-states-current-2026-08' AND sd.spec_key='transmission.options' AND ms.value_text='8x8 or 16x8 Power Shuttle'`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN (${slugs}) AND mv.slug='united-states-current-2026-08' AND sd.spec_key='hydraulics.main_pump_max_flow' AND ms.value_number=22`),
    count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE m.slug IN (${slugs}) AND mv.slug='united-states-current-2026-08' AND sd.spec_key='hitch.rear_max_lift_capacity' AND ms.value_number=7200`),
    count(`SELECT COUNT(*) count FROM attachments a JOIN manufacturers mf ON mf.id=a.manufacturer_id WHERE mf.slug='case-ih' AND a.slug IN (${loaderSlugs}) AND a.attachment_type='front-loader' AND a.data_status='verified'`),
    count(`SELECT COUNT(*) count FROM machine_attachments ma JOIN machines m ON m.id=ma.machine_id JOIN attachments a ON a.id=ma.attachment_id WHERE m.slug IN (${slugs}) AND a.slug IN (${loaderSlugs}) AND ma.confidence='official'`),
    count(`SELECT COUNT(*) count FROM source_records WHERE external_id IN ('case-ih-farmall-large-utility-100a-pro-current-us-110-140-2026-08','case-ih-farmall-110a-pro-current-us','case-ih-farmall-120a-pro-current-us','case-ih-farmall-130a-pro-current-us','case-ih-farmall-140a-pro-current-us','case-ih-farmall-100a-pro-l113-loader-current','case-ih-farmall-100a-pro-l114-loader-current')`),
  ]);
  const checks={migrationsApplied:migrationsApplied===2,machines:machines===4,currentVersions:currentVersions===4,specRows:specRows===36,engineMakeRows:engineMakeRows===4,displacementRows:displacementRows===4,ratedRows:ratedRows===4,ptoRows:ptoRows===4,stationRows:stationRows===4,driveRows:driveRows===4,transmissionRows:transmissionRows===4,hydraulicRows:hydraulicRows===4,hitchRows:hitchRows===4,loaderRows:loaderRows===2,loaderFitments:loaderFitments===8,sourceRows:sourceRows===7};
  const ok=Object.values(checks).every(Boolean);
  return NextResponse.json({ok,expectedLatestCaseIHFarmall100AMigration:'20260828_238_case_ih_farmall_100a_pro_loaders',checks,values:{migrationsApplied,machines,currentVersions,specRows,engineMakeRows,displacementRows,ratedRows,ptoRows,stationRows,driveRows,transmissionRows,hydraulicRows,hitchRows,loaderRows,loaderFitments,sourceRows}},{status:ok?200:503,headers:{'Cache-Control':'no-store, max-age=0','X-Robots-Tag':'noindex, nofollow'}});
}catch(error){console.error('Case IH Farmall 100A Pro health check failed:',error);return NextResponse.json({ok:false,error:'Case IH Farmall 100A Pro health check failed'},{status:500,headers:{'Cache-Control':'no-store, max-age=0','X-Robots-Tag':'noindex, nofollow'}});}}
