import { NextResponse } from 'next/server';
import type { RowDataPacket } from 'mysql2';
import { getDbReady } from '@/lib/db-migrations';

export const dynamic='force-dynamic';
export const revalidate=0;
type CountRow=RowDataPacket&{count:number};
async function count(sql:string){const db=await getDbReady();const [rows]=await db.query<CountRow[]>(sql);return Number(rows[0]?.count||0);}
const slugs="'farmall-50a','farmall-55a','farmall-60a','farmall-65a','farmall-70a','farmall-75a'";

export async function GET(){try{
 const [migrationsApplied,machines,currentVersions,specRows,ratedRows,ptoRows,stationRows,driveRows,transmissionRows,loaderRows,loaderFitments,sourceRows]=await Promise.all([
  count(`SELECT COUNT(*) count FROM schema_migrations WHERE id IN ('20260828_239_case_ih_farmall_small_utility_a_current_specs','20260828_240_case_ih_farmall_small_utility_a_loaders')`),
  count(`SELECT COUNT(*) count FROM machines m JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='case-ih' AND m.slug IN (${slugs})`),
  count(`SELECT COUNT(*) count FROM machine_versions mv JOIN machines m ON m.id=mv.machine_id JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='case-ih' AND m.slug IN (${slugs}) AND mv.slug='united-states-current-2026-08' AND mv.is_current=1`),
  count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN manufacturers mf ON mf.id=m.manufacturer_id WHERE mf.slug='case-ih' AND m.slug IN (${slugs}) AND mv.slug='united-states-current-2026-08'`),
  count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE mv.slug='united-states-current-2026-08' AND sd.spec_key='engine.rated_power' AND ((m.slug='farmall-50a' AND ms.value_number=53) OR (m.slug='farmall-55a' AND ms.value_number=54) OR (m.slug='farmall-60a' AND ms.value_number=60) OR (m.slug='farmall-65a' AND ms.value_number=64) OR (m.slug='farmall-70a' AND ms.value_number=70) OR (m.slug='farmall-75a' AND ms.value_number=74))`),
  count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE mv.slug='united-states-current-2026-08' AND sd.spec_key='pto.rated_power' AND ((m.slug='farmall-50a' AND ms.value_number=45) OR (m.slug='farmall-55a' AND ms.value_number=40) OR (m.slug='farmall-60a' AND ms.value_number=51) OR (m.slug='farmall-65a' AND ms.value_number=50) OR (m.slug='farmall-70a' AND ms.value_number=62) OR (m.slug='farmall-75a' AND ms.value_number=60))`),
  count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE mv.slug='united-states-current-2026-08' AND sd.spec_key='configuration.station' AND ((m.slug='farmall-50a' AND ms.value_text='Non-cab') OR (m.slug='farmall-55a' AND ms.value_text='Cab') OR (m.slug='farmall-60a' AND ms.value_text='Non-cab') OR (m.slug='farmall-65a' AND ms.value_text='Cab') OR (m.slug='farmall-70a' AND ms.value_text='Non-cab') OR (m.slug='farmall-75a' AND ms.value_text='Cab or Non-cab'))`),
  count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE mv.slug='united-states-current-2026-08' AND sd.spec_key='configuration.drive' AND ms.value_text='2WD or MFD' AND m.slug IN (${slugs})`),
  count(`SELECT COUNT(*) count FROM machine_specs ms JOIN machines m ON m.id=ms.machine_id JOIN machine_versions mv ON mv.id=ms.machine_version_id JOIN spec_definitions sd ON sd.id=ms.spec_definition_id WHERE mv.slug='united-states-current-2026-08' AND sd.spec_key='transmission.options' AND m.slug IN (${slugs})`),
  count(`SELECT COUNT(*) count FROM attachments a JOIN manufacturers mf ON mf.id=a.manufacturer_id WHERE mf.slug='case-ih' AND a.slug IN ('l545-farmall-small-utility-a','l555-farmall-small-utility-a','l610-farmall-small-utility-a') AND a.attachment_type='front-loader' AND a.data_status='verified'`),
  count(`SELECT COUNT(*) count FROM machine_attachments ma JOIN machines m ON m.id=ma.machine_id JOIN attachments a ON a.id=ma.attachment_id WHERE m.slug IN (${slugs}) AND a.slug IN ('l545-farmall-small-utility-a','l555-farmall-small-utility-a','l610-farmall-small-utility-a') AND ma.confidence='official'`),
  count(`SELECT COUNT(*) count FROM source_records WHERE external_id IN ('case-ih-farmall-small-utility-a-current-us-50-75-2026-08','case-ih-farmall-50a-current-us','case-ih-farmall-55a-current-us','case-ih-farmall-60a-current-us','case-ih-farmall-65a-current-us','case-ih-farmall-70a-current-us','case-ih-farmall-75a-current-us','case-ih-farmall-small-utility-a-l545-current','case-ih-farmall-small-utility-a-l555-current','case-ih-farmall-small-utility-a-l610-current')`),
 ]);
 const checks={migrationsApplied:migrationsApplied===2,machines:machines===6,currentVersions:currentVersions===6,specRows:specRows===30,ratedRows:ratedRows===6,ptoRows:ptoRows===6,stationRows:stationRows===6,driveRows:driveRows===6,transmissionRows:transmissionRows===6,loaderRows:loaderRows===3,loaderFitments:loaderFitments===9,sourceRows:sourceRows===10};
 const ok=Object.values(checks).every(Boolean);
 return NextResponse.json({ok,expectedLatestCaseIHFarmallSmallUtilityAMigration:'20260828_240_case_ih_farmall_small_utility_a_loaders',checks,values:{migrationsApplied,machines,currentVersions,specRows,ratedRows,ptoRows,stationRows,driveRows,transmissionRows,loaderRows,loaderFitments,sourceRows}},{status:ok?200:503,headers:{'Cache-Control':'no-store, max-age=0','X-Robots-Tag':'noindex, nofollow'}});
 }catch(error){console.error('Case IH Farmall Small Utility A health check failed:',error);return NextResponse.json({ok:false,error:'Case IH Farmall Small Utility A health check failed'},{status:500,headers:{'Cache-Control':'no-store, max-age=0','X-Robots-Tag':'noindex, nofollow'}});}}
